# imports

In [1]:
import os
os.chdir('/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl')

In [67]:
from importlib import reload
import interpretable_ssl.evaluation.metric_helpers.embedding_metrics
import interpretable_ssl.evaluation.metric_helpers.embedding_tables
reload(interpretable_ssl.evaluation.metric_helpers.embedding_metrics)
reload(interpretable_ssl.evaluation.metric_helpers.embedding_tables)

In [68]:
from interpretable_ssl.evaluation.metric_helpers.embedding_metrics import *
from interpretable_ssl.evaluation.metric_helpers.embedding_tables import *
from interpretable_ssl.datasets.dataset_configs import *

In [51]:
def save_baseline_metrics(ds_id, pt_epochs=50, ft_epochs=1):
    ds_conf = DATASETS[ds_id]
    adata = sc.read_h5ad(ds_conf["path"])
    if adata.X.max() > 50:
        print('adata x is not normalized')
    bk, lk = ds_conf["batch_key"], ds_conf["label_key"]
    add_pca_harmoney(adata, ds_conf["batch_key"], "X_pca")
    add_scvi_emb(adata, ds_conf["test_studies"], bk, pt_epochs, ft_epochs)
    scg, scb = get_metrics(adata, ['X_pca', 'X_pca_harmoney', 'X_scvi'], bk, lk)
    home = '/ictstr01/home/icb/fatemehs.hashemig/'
    os.makedirs(home + f'/models/{ds_id}/baselines/', exist_ok=True)
    scg.to_csv(home + f'/models/{ds_id}/baselines/scgraph.csv')
    scb.to_csv(home + f'/models/{ds_id}/baselines/scib.csv')
    mc_ad = load_seacell(ds_id)
    add_pca_harmoney(mc_ad, bk, 'seacell_pca')
    scg, scb = get_metacell_metrics(mc_ad, ['seacell_pca', 'seacell_pca_harmoney'], bk, lk)
    os.makedirs(home + f'/models/{ds_id}/seacell/', exist_ok=True)
    scg.to_csv(home + f'/models/{ds_id}/seacell/scgraph.csv')
    scb.to_csv(home + f'/models/{ds_id}/seacell/scib.csv')

# pancreas

In [69]:
df, dfs = load_tb('pancreas')

/home/icb/fatemehs.hashemig/models/pancreas/seacell_sc.h5ad/scib.csv
/home/icb/fatemehs.hashemig/models/pancreas/seacell_agg.h5ad/scib.csv
/home/icb/fatemehs.hashemig/models/pancreas/scpoli_ds_panc_finetune_20_cvae_pre_100/scib.csv
/home/icb/fatemehs.hashemig/models/pancreas/seacell_sc.h5ad/scgraph.csv
/home/icb/fatemehs.hashemig/models/pancreas/seacell_agg.h5ad/scgraph.csv
/home/icb/fatemehs.hashemig/models/pancreas/scpoli_ds_panc_finetune_20_cvae_pre_100/scgraph.csv

In [76]:
def is_mc(idx):
    return ('mc' in idx) or ('seacell' in idx)
mask = np.array([is_mc(idx) for idx in df.index])
df[mask]

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total,Rank-PCA,Corr-PCA,Corr-Weighted
swav_ds_panc_NP_220_bs_256_mc_pca,0.528825,0.660357,0.519134,0.611786,0.964370,0.804386,0.245743,0.815068,0.980038,0.000000e+00,0.569047,0.656894,0.621756,0.984694,0.989955,0.971395
swav_ds_panc_NP_220_bs_256_knn_diff_mc_pca,0.500000,0.654802,0.473306,0.612784,0.964310,0.758983,0.308999,0.960140,0.921589,0.000000e+00,0.589942,0.641040,0.620601,0.877551,0.976667,0.903867
seacell_pca,0.500000,0.553293,0.273967,0.589719,0.936285,0.692187,0.162420,0.640394,0.827775,3.260648e-07,0.464555,0.570653,0.528214,0.910714,0.991154,0.961740
seacell_pca_harmoney,0.500000,0.698510,0.474634,0.639701,0.967154,0.829590,0.343208,0.757881,0.820925,4.966550e-01,0.649652,0.656000,0.653461,0.880952,0.988750,0.961405
swav_ds_panc_NP_220_cvae_pre_100_bs_256_mc_pca,0.556721,0.715544,0.464228,0.672920,0.993561,0.795286,0.142232,0.980684,0.981720,0.000000e+00,0.579985,0.680595,0.640351,0.903061,0.979793,0.874967
swav_ds_panc_NP_220_finetune_20_cvae_pre_100_bs_256_mc_pca,0.500000,0.813209,0.665789,0.711648,0.998059,0.780039,0.185321,0.934862,0.907967,0.000000e+00,0.561638,0.737741,0.667300,0.954082,0.986896,0.947962
swav_ds_panc_NP_220_cvae_pre_100_bs_256_knn_diff_mc_pca,0.404299,0.770174,0.630192,0.671274,0.994051,0.749374,0.216408,0.945122,0.929058,0.000000e+00,0.567992,0.693998,0.643596,0.933673,0.968435,0.870570

In [78]:
show_tb(df[mask])

In [79]:
show_tb(df[~mask])

In [74]:
show_tb(df[~mask])

TypeError: bad operand type for unary ~: 'list'

# immune

In [52]:
save_baseline_metrics('pbmc-immune')

2025-09-15 08:31:20,305 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO:harmonypy:Computing initial centroids with sklearn.KMeans...
2025-09-15 08:31:35,267 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO:harmonypy:sklearn.KMeans initialization complete.
2025-09-15 08:31:35,497 - harmonypy - INFO - Iteration 1 of 10
INFO:harmonypy:Iteration 1 of 10
2025-09-15 08:31:50,389 - harmonypy - INFO - Iteration 2 of 10
INFO:harmonypy:Iteration 2 of 10
2025-09-15 08:32:08,539 - harmonypy - INFO - Iteration 3 of 10
INFO:harmonypy:Iteration 3 of 10
2025-09-15 08:32:27,321 - harmonypy - INFO - Iteration 4 of 10
INFO:harmonypy:Iteration 4 of 10
2025-09-15 08:32:47,373 - harmonypy - INFO - Converged after 4 iterations
INFO:harmonypy:Converged after 4 iterations
Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 50/50: 100%|██████████| 50/50 [02:12<00:00,  2.72s/it, loss=647, v_num=1]

`Trainer.fit` stopped: `max_epochs=50` reached.

Epoch 50/50: 100%|██████████| 50/50 [02:12<00:00,  2.66s/it, loss=647, v_num=1]

Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 1/1: 100%|██████████| 1/1 [00:03<00:00,  3.07s/it, loss=756, v_num=1]

`Trainer.fit` stopped: `max_epochs=1` reached.

Epoch 1/1: 100%|██████████| 1/1 [00:03<00:00,  3.08s/it, loss=756, v_num=1]
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_1aa5bda8.h5ad

Computing neighbors: 100%|██████████| 3/3 [01:09<00:00, 23.15s/it]
Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:53<08:00, 53.33s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:53<08:00, 53.33s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [01:02<03:38, 27.36s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [01:02<03:38, 27.36s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [01:55<04:32, 38.87s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [01:55<04:32, 38.87s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [01:56<02:23, 23.95s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [01:56<02:23, 23.95s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [02:12<01:46, 21.32s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [02:12<01:46, 21.32s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [02:13<00:56, 14.19s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [02:13<00:56, 14.19s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [02:38<00:53, 17.99s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [02:38<00:53, 17.99s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [02:39<00:35, 17.99s/it, Batch correction: pcr_comparison]
Embeddings:  33%|███▎      | 1/3 [02:39<05:19, 159.73s/it]tch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:53<07:59, 53.32s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:53<07:59, 53.32s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [01:03<03:43, 27.97s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [01:03<03:43, 27.97s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [01:59<04:43, 40.53s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [01:59<04:43, 40.53s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [01:59<02:28, 24.68s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [01:59<02:28, 24.68s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [02:09<01:36, 19.37s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [02:09<01:36, 19.37s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [02:09<00:51, 12.91s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [02:09<00:51, 12.91s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [02:36<00:52, 17.51s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [02:36<00:52, 17.51s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [02:36<00:35, 17.51s/it, Batch correction: pcr_comparison]
Embeddings:  67%|██████▋   | 2/3 [05:16<02:38, 158.13s/it]tch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:04<00:37,  4.17s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:04<00:37,  4.17s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:08<00:35,  4.39s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:08<00:35,  4.39s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.27s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.27s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:13<00:16,  2.68s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:13<00:16,  2.68s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:14<00:11,  2.21s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:14<00:11,  2.21s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:14<00:06,  1.56s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:14<00:06,  1.56s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:37<00:25,  8.55s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:37<00:25,  8.55s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:37<00:17,  8.55s/it, Batch correction: pcr_comparison]
Embeddings: 100%|██████████| 3/3 [05:54<00:00, 118.30s/it]tch correction: pcr_comparison]

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/icb/fatemehs.hashemig//models/pbmc-immune/seacell_agg.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [56]:
dfs = load_tb('pbmc-immune')
show_tb(dfs)

/home/icb/fatemehs.hashemig/models/pbmc-immune/scpoli_finetune_20_cvae_pre_100/scib.csv
/home/icb/fatemehs.hashemig/models/pbmc-immune/scpoli_cvae_pre_100/scib.csv
/home/icb/fatemehs.hashemig/models/pbmc-immune/scpoli_finetune_20_cvae_pre_100/scgraph.csv
/home/icb/fatemehs.hashemig/models/pbmc-immune/scpoli_cvae_pre_100/scgraph.csv

# add seacell metrics

## pancreas

In [12]:
home = '/home/icb/fatemehs.hashemig/'
SEACell_ad = sc.read_h5ad(f'{home}/pancreas_seacells.h5ad')

In [13]:
bk, lk = 'tech', 'celltype'

ds = 'pancreas'
save_pca_harmoney_metrics(SEACell_ad, bk, lk, ds, "seacell_pca")

2025-09-08 14:39:55,202 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO:harmonypy:Computing initial centroids with sklearn.KMeans...
2025-09-08 14:39:55,915 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO:harmonypy:sklearn.KMeans initialization complete.
2025-09-08 14:39:55,962 - harmonypy - INFO - Iteration 1 of 10
INFO:harmonypy:Iteration 1 of 10
2025-09-08 14:39:56,023 - harmonypy - INFO - Iteration 2 of 10
INFO:harmonypy:Iteration 2 of 10
2025-09-08 14:39:56,047 - harmonypy - INFO - Iteration 3 of 10
INFO:harmonypy:Iteration 3 of 10
2025-09-08 14:39:56,079 - harmonypy - INFO - Iteration 4 of 10
INFO:harmonypy:Iteration 4 of 10
2025-09-08 14:39:56,112 - harmonypy - INFO - Iteration 5 of 10
INFO:harmonypy:Iteration 5 of 10
2025-09-08 14:39:56,138 - harmonypy - INFO - Iteration 6 of 10
INFO:harmonypy:Iteration 6 of 10
2025-09-08 14:39:56,164 - harmonypy - INFO - Iteration 7 of 10
INFO:harmonypy:Iteration 7 of 10
2025-09-08 14:39:56,190 - harmonypy - INFO - Iteration 8 of 10
INFO:harmonypy:Iteration 8 of 10
2025-09-08 14:39:56,207 - harmonypy - INFO - Iteration 9 of 10
INFO:harmonypy:Iteration 9 of 10
2025-09-08 14:39:56,224 - harmonypy - INFO - Iteration 10 of 10
INFO:harmonypy:Iteration 10 of 10
2025-09-08 14:39:56,241 - harmonypy - INFO - Converged after 10 iterations
INFO:harmonypy:Converged after 10 iterations

Skipped cell type schwann, due to < 10 cells
Skipped cell type endothelial, due to < 10 cells
Skipped cell type macrophage, due to < 10 cells
Skipped cell type quiescent_stellate, due to < 10 cells
Skipped cell type mast, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Skipped batch celseq2, due to < 100 cells
Skipped batch fluidigmc1, due to < 100 cells
Skipped batch smartseq2, due to < 100 cells
Skipped batch inDrop2, due to < 100 cells
Skipped batch celseq, due to < 100 cells
Skipped batch inDrop1, due to < 100 cells
Skipped batch inDrop4, due to < 100 cells
Skipped batch inDrop3, due to < 100 cells
Skipped batch smarter, due to < 100 cells

ValueError: No objects to concatenate

## immune

In [15]:
seacell_agg = sc.read_h5ad(f'{home}/models/pbmc-immune/seacell_agg.h5ad')
seacell_sc = sc.read_h5ad(f'{home}/models/pbmc-immune/seacell_sc.h5ad')

In [16]:
get_seacell_metrics(seacell_agg, seacell_sc, 'study', 'final_annotation', 'pbmc-immune')

2025-09-08 14:40:32,805 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO:harmonypy:Computing initial centroids with sklearn.KMeans...
2025-09-08 14:40:33,559 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO:harmonypy:sklearn.KMeans initialization complete.
2025-09-08 14:40:33,561 - harmonypy - INFO - Iteration 1 of 10
INFO:harmonypy:Iteration 1 of 10
2025-09-08 14:40:33,598 - harmonypy - INFO - Iteration 2 of 10
INFO:harmonypy:Iteration 2 of 10
2025-09-08 14:40:33,617 - harmonypy - INFO - Iteration 3 of 10
INFO:harmonypy:Iteration 3 of 10
2025-09-08 14:40:33,634 - harmonypy - INFO - Iteration 4 of 10
INFO:harmonypy:Iteration 4 of 10
2025-09-08 14:40:33,648 - harmonypy - INFO - Converged after 4 iterations
INFO:harmonypy:Converged after 4 iterations

Skipped cell type CD10+ B cells, due to < 10 cells
Skipped cell type CD8+ T cells, due to < 10 cells
Skipped cell type Plasma cells, due to < 10 cells
Skipped cell type Megakaryocyte progenitors, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Skipped batch 10X, due to < 100 cells
Skipped batch Sun, due to < 100 cells
Skipped batch Freytag, due to < 100 cells
Skipped batch Villani, due to < 100 cells

Computing neighbors: 100%|██████████| 2/2 [00:19<00:00,  9.74s/it]
Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

Metrics:  10%|█         | 1/10 [00:08<01:20,  8.93s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:08<01:20,  8.93s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:10<00:35,  4.47s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:10<00:35,  4.47s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:10<00:31,  4.47s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:11<00:11,  1.96s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:11<00:11,  1.96s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:15<00:14,  2.81s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:15<00:14,  2.81s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:16<00:11,  2.81s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD8+ T cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:23<00:09,  3.30s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:23<00:09,  3.30s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:23<00:06,  3.30s/it, Batch correction: pcr_comparison]
Embeddings:  50%|█████     | 1/2 [00:25<00:25, 25.05s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:00<00:00, 47.07it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.18it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.18it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:00<00:03,  2.18it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:00<00:02,  2.18it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:00<00:02,  2.18it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:00<00:01,  2.18it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD8+ T cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:01<00:00,  6.96it/s, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:01<00:00,  6.96it/s, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 2/2 [00:26<00:00, 13.14s/it]atch correction: pcr_comparison]

(                     Isolated labels KMeans NMI KMeans ARI Silhouette label  \
 Embedding
 seacell_pca                 0.701739    0.77803   0.588735         0.582683
 seacell_pca_harmoney        0.625824    0.80267   0.738461         0.607853
 scpoli                      0.586442   0.546949   0.304108         0.525358
 t2_cvae_0.01_prop_1         0.589887   0.657145   0.402389         0.567761
 X_pca                       0.599962   0.587749   0.387142         0.536031
 X_pca_harmoney              0.575475   0.688179   0.535855         0.568512
 X_scvi                      0.623681   0.661308   0.441094         0.569204

                          cLISI Silhouette batch     iLISI      KBET  \
 Embedding
 seacell_pca           0.940706         0.663277  0.144948  0.576221
 seacell_pca_harmoney   0.95677         0.759837  0.460046  0.850063
 scpoli                0.977944         0.873515   0.37772  0.443718
 t2_cvae_0.01_prop_1   0.990002          0.81488   0.17507  0.196576
 X_pca                 0.996537         0.728243       0.0  0.216919
 X_pca_harmoney        0.995547         0.825176  0.198216  0.266702
 X_scvi                0.997236         0.814463  0.243136  0.260096

                      Graph connectivity PCR comparison Batch correction  \
 Embedding
 seacell_pca                    0.866986            0.0         0.450286
 seacell_pca_harmoney           0.852931       0.596644         0.703904
 scpoli                          0.87979       0.951589         0.705266
 t2_cvae_0.01_prop_1            0.854275       0.932882         0.594737
 X_pca                          0.640025            0.0         0.317037
 X_pca_harmoney                 0.630204       0.879787         0.560017
 X_scvi                         0.893512       0.817861         0.605814

                      Bio conservation     Total
 Embedding
 seacell_pca                  0.718378  0.611142
 seacell_pca_harmoney         0.746316  0.729351
 scpoli                        0.58816  0.635003
 t2_cvae_0.01_prop_1          0.641437  0.622757
 X_pca                        0.621484  0.499706
 X_pca_harmoney               0.672713  0.627635
 X_scvi                       0.658505  0.637428  ,
                       Rank-PCA  Corr-PCA  Corr-Weighted
 seacell_pca           0.929487  0.977643       0.936127
 seacell_pca_harmoney  0.848485  0.962185       0.902033
 scpoli                0.492463  0.673433       0.449950
 t2_cvae_0.01_prop_1   0.520404  0.693673       0.478531
 X_pca                 0.664706  0.498572       0.356963
 X_pca_harmoney        0.489522  0.652790       0.442862
 X_scvi                0.545588  0.674347       0.486010)

# show tables

In [17]:
generate_table('~/models/pbmc-immune/')

In [18]:
generate_table('~/models/pancreas/')

In [31]:
df = pd.read_csv('~/models/pbmc-immune/scgraph.csv', index_col=0)
df.style.apply(highlight_max_second, axis=0)

In [32]:
df.drop([col for col in df.index if 'seacell' in col], axis=0).style.apply(highlight_max_second, axis=0)

# compute metrics for scProto metacells - Immune ds

In [45]:
scproto_params = {
    "cvae_loss_scaler": 0.01,
    "propagation_reg": 1,
    "experiment_name": "t2",
    "debug": 1
}

In [47]:
from interpretable_ssl.trainers.scproto import *


t = SCProtoTrainer(**scproto_params)

dataset is None, loading pbmc-immune
loading pbmc-immune data
done
✅ Already subsetted to HVGs (4000 genes).

In [49]:
model = t.load_model()

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

In [51]:
protos = model.get_prototypes()

In [76]:
batch = np.zeros((protos.shape[0],1))
batch = torch.as_tensor(batch, dtype=torch.long, device='cuda')
batch.shape

torch.Size([300, 1])

In [83]:
sizefactor = np.ones((protos.shape[0],))
sizefactor = torch.as_tensor(sizefactor, dtype=torch.long, device='cuda')
sizefactor.shape

torch.Size([300])

In [84]:
metacells = model.decode(protos, batch, sizefactor)

In [106]:
sample_proto_sim = t.encode_adata(adata, model, return_mapped = True)
sample_proto_sim.shape

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [5]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

100%|██████████| 33/33 [00:07<00:00,  4.54it/s]

torch.Size([33506, 300])

In [149]:
from interpretable_ssl.scproto_metacells import *

In [150]:
proto_labels = extract_proto_labels(adata, sample_proto_sim.detach().cpu().numpy(), ['final_annotation', 'study'])

In [136]:
metacells_adata = generate_metacell_adata(metacells, proto_labels)

In [ ]:
sc.tl.pca(metacells_adata)
# rename

In [142]:
save_metrics(metacells_adata, ['scproto_metacells_pca'], 'pbmc-immune', 'study', 'final_annotation')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

2025-09-09 06:23:44,750 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO - 09/09/25 06:23:44 - 11:02:54 - Computing initial centroids with sklearn.KMeans...
2025-09-09 06:23:46,073 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO - 09/09/25 06:23:46 - 11:02:55 - sklearn.KMeans initialization complete.
2025-09-09 06:23:46,090 - harmonypy - INFO - Iteration 1 of 10
INFO - 09/09/25 06:23:46 - 11:02:55 - Iteration 1 of 10
2025-09-09 06:23:46,124 - harmonypy - INFO - Iteration 2 of 10
INFO - 09/09/25 06:23:46 - 11:02:55 - Iteration 2 of 10
2025-09-09 06:23:46,167 - harmonypy - INFO - Iteration 3 of 10
INFO - 09/09/25 06:23:46 - 11:02:56 - Iteration 3 of 10
2025-09-09 06:23:46,195 - harmonypy - INFO - Iteration 4 of 10
INFO - 09/09/25 06:23:46 - 11:02:56 - Iteration 4 of 10
2025-09-09 06:23:46,223 - harmonypy - INFO - Converged after 4 iterations
INFO - 09/09/25 06:23:46 - 11:02:56 - Converged after 4 iterations

Skipped cell type Megakaryocyte progenitors, due to < 10 cells
Skipped cell type Monocyte-derived dendritic cells, due to < 10 cells
Skipped cell type CD10+ B cells, due to < 10 cells
Skipped cell type Erythroid progenitors, due to < 10 cells
Skipped cell type HSPCs, due to < 10 cells
Skipped cell type CD16+ Monocytes, due to < 10 cells
Skipped cell type Plasmacytoid dendritic cells, due to < 10 cells
Skipped cell type Plasma cells, due to < 10 cells
Skipped cell type Monocyte progenitors, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Skipped batch 10X, due to < 100 cells
Skipped batch Sun, due to < 100 cells
Skipped batch Freytag, due to < 100 cells
Skipped batch Villani, due to < 100 cells

Computing neighbors: 100%|██████████| 2/2 [00:00<00:00,  2.24it/s]
Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/09/25 06:23:55 - 11:03:04 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:06,  1.30it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:00<00:06,  1.30it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:19<01:29, 11.22s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:19<01:29, 11.22s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:19<01:18, 11.22s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:19<01:07, 11.22s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:22<00:19,  3.86s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:22<00:19,  3.86s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:22<00:15,  3.86s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD16+ Monocytes consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     HSPCs consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte-derived dendritic cells consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.
INFO     Plasmacytoid dendritic cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:24<00:08,  2.82s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:24<00:08,  2.82s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:24<00:05,  2.82s/it, Batch correction: pcr_comparison]
Embeddings:  50%|█████     | 1/2 [00:24<00:24, 24.92s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/09/25 06:24:20 - 11:03:29 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:00, 38.33it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.17it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.17it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:00<00:03,  2.17it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:00<00:02,  2.17it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:01<00:02,  2.17it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:01<00:00,  7.24it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:01<00:00,  7.24it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD16+ Monocytes consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     HSPCs consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte-derived dendritic cells consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.
INFO     Plasmacytoid dendritic cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:01<00:00,  7.24it/s, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:01<00:00,  7.24it/s, Batch correction: pcr_comparison]
Embeddings: 100%|██████████| 2/2 [00:26<00:00, 13.06s/it]atch correction: pcr_comparison]

(                               Isolated labels KMeans NMI KMeans ARI  \
 Embedding
 scProto_metacells_pca                 0.590772   0.616662   0.289849
 scProto_metacells_pca_harmoney        0.593523   0.623641   0.253203
 seacell_pca                           0.701739    0.77803   0.588735
 seacell_pca_harmoney                  0.625824    0.80267   0.738461
 scpoli                                0.586442   0.546949   0.304108
 t2_cvae_0.01_prop_1                   0.589887   0.657145   0.402389
 X_pca                                 0.599962   0.587749   0.387142
 X_pca_harmoney                        0.575475   0.688179   0.535855
 X_scvi                                0.623681   0.661308   0.441094

                                Silhouette label     cLISI Silhouette batch  \
 Embedding
 scProto_metacells_pca                  0.521681  0.957613          0.75682
 scProto_metacells_pca_harmoney         0.522546   0.95688         0.766133
 seacell_pca                            0.582683  0.940706         0.663277
 seacell_pca_harmoney                   0.607853   0.95677         0.759837
 scpoli                                 0.525358  0.977944         0.873515
 t2_cvae_0.01_prop_1                    0.567761  0.990002          0.81488
 X_pca                                  0.536031  0.996537         0.728243
 X_pca_harmoney                         0.568512  0.995547         0.825176
 X_scvi                                 0.569204  0.997236         0.814463

                                    iLISI      KBET Graph connectivity  \
 Embedding
 scProto_metacells_pca           0.131427  0.847283           0.980336
 scProto_metacells_pca_harmoney  0.189404  0.977876           0.905315
 seacell_pca                     0.144948  0.576221           0.866986
 seacell_pca_harmoney            0.460046  0.850063           0.852931
 scpoli                           0.37772  0.443718            0.87979
 t2_cvae_0.01_prop_1              0.17507  0.196576           0.854275
 X_pca                                0.0  0.216919           0.640025
 X_pca_harmoney                  0.198216  0.266702           0.630204
 X_scvi                          0.243136  0.260096           0.893512

                                PCR comparison Batch correction  \
 Embedding
 scProto_metacells_pca                       0         0.543173
 scProto_metacells_pca_harmoney       0.100055         0.587757
 seacell_pca                               0.0         0.450286
 seacell_pca_harmoney                 0.596644         0.703904
 scpoli                               0.951589         0.705266
 t2_cvae_0.01_prop_1                  0.932882         0.594737
 X_pca                                     0.0         0.317037
 X_pca_harmoney                       0.879787         0.560017
 X_scvi                               0.817861         0.605814

                                Bio conservation     Total
 Embedding
 scProto_metacells_pca                  0.595316  0.574459
 scProto_metacells_pca_harmoney         0.589958  0.589078
 seacell_pca                            0.718378  0.611142
 seacell_pca_harmoney                   0.746316  0.729351
 scpoli                                  0.58816  0.635003
 t2_cvae_0.01_prop_1                    0.641437  0.622757
 X_pca                                  0.621484  0.499706
 X_pca_harmoney                         0.672713  0.627635
 X_scvi                                 0.658505  0.637428  ,
                                 Rank-PCA  Corr-PCA  Corr-Weighted
 scProto_metacells_pca           0.831633  0.960864       0.845142
 scProto_metacells_pca_harmoney  0.862245  0.968959       0.864371
 seacell_pca                     0.929487  0.977643       0.936127
 seacell_pca_harmoney            0.848485  0.962185       0.902033
 scpoli                          0.492463  0.673433       0.449950
 t2_cvae_0.01_prop_1             0.520404  0.693673       0.478531
 X_pca                           0.664706  0.498572       0.356963
 X_pca_harmoney                  0.489522  0.652790       0.442862
 X_scvi                          0.545588  0.674347       0.486010)

In [148]:
generate_table('~/models/pbmc-immune/')

# re-calc ref metrics

In [250]:
# pca. harmoney, scvi, scpoli, scproto, seacell, seacell_harmoney, scproto_mc_pca

In [255]:
ref = adata[~adata.obs.study.isin(DATASETS['pbmc-immune']['test_studies'])]
ref = ref.copy()
bk, lk = 'study', 'final_annotation'

In [265]:
ds = 'pbmc-immune'
scgraph_kwargs = {
    "thres_batch": 10,
    "thres_celltype": 10,
}

In [266]:
get_scproto_metacell_metrics(t, ref, ds, bk, lk, name_postfix = 'ref_v2', **scgraph_kwargs)

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

100%|██████████| 29/29 [00:03<00:00,  7.53it/s]

Skipped cell type Megakaryocyte progenitors, due to < 10 cells
Skipped cell type Monocyte-derived dendritic cells, due to < 10 cells
Skipped cell type CD10+ B cells, due to < 10 cells
Skipped cell type HSPCs, due to < 10 cells
Skipped cell type CD16+ Monocytes, due to < 10 cells
Skipped cell type Plasmacytoid dendritic cells, due to < 10 cells
Skipped cell type Plasma cells, due to < 10 cells
Skipped cell type Monocyte progenitors, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scgraph_ref_v2.csv

Computing neighbors: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:24:21 - 2 days, 12:03:31 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:01<00:12,  1.39s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:01<00:12,  1.39s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:12<00:56,  7.06s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:12<00:56,  7.06s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:49,  7.06s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:12<00:42,  7.06s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:11,  2.36s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:11,  2.36s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:13<00:09,  2.36s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD16+ Monocytes consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     HSPCs consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte-derived dendritic cells consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.
INFO     Plasmacytoid dendritic cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:16<00:05,  1.87s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:16<00:05,  1.87s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:16<00:03,  1.87s/it, Batch correction: pcr_comparison]
Embeddings: 100%|██████████| 1/1 [00:16<00:00, 16.50s/it]atch correction: pcr_comparison]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scib_ref_v2.csv

(               Isolated labels KMeans NMI KMeans ARI Silhouette label  \
 Embedding
 scProto_mc_pca        0.597917   0.632531   0.283255         0.534265

                    cLISI Silhouette batch     iLISI      KBET  \
 Embedding
 scProto_mc_pca  0.957261           0.7509  0.266704  0.776951

                Graph connectivity PCR comparison Batch correction  \
 Embedding
 scProto_mc_pca           0.958872            0.0         0.550685

                Bio conservation     Total
 Embedding
 scProto_mc_pca         0.601046  0.580902  ,
                 Rank-PCA  Corr-PCA  Corr-Weighted
 scProto_mc_pca     0.875  0.972581       0.924775)

In [270]:
p = f'{home}/models/pbmc-immune/ref_seacell'
ad, SEACell_ad = sc.read_h5ad(p + '_sc.h5ad'), sc.read_h5ad(p + '_agg.h5ad')

get_seacell_metrics(SEACell_ad, ad, 'study', 'final_annotation', 'pbmc-immune', 'ref_v2', **scgraph_kwargs)

2025-09-11 07:27:19,749 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO - 09/11/25 07:27:19 - 2 days, 12:06:29 - Computing initial centroids with sklearn.KMeans...
2025-09-11 07:27:20,557 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - sklearn.KMeans initialization complete.
2025-09-11 07:27:20,564 - harmonypy - INFO - Iteration 1 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 1 of 10
2025-09-11 07:27:20,621 - harmonypy - INFO - Iteration 2 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 2 of 10
2025-09-11 07:27:20,652 - harmonypy - INFO - Iteration 3 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 3 of 10
2025-09-11 07:27:20,671 - harmonypy - INFO - Iteration 4 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 4 of 10
2025-09-11 07:27:20,686 - harmonypy - INFO - Iteration 5 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 5 of 10
2025-09-11 07:27:20,701 - harmonypy - INFO - Iteration 6 of 10
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Iteration 6 of 10
2025-09-11 07:27:20,716 - harmonypy - INFO - Converged after 6 iterations
INFO - 09/11/25 07:27:20 - 2 days, 12:06:30 - Converged after 6 iterations
... storing 'study' as categorical
... storing 'final_annotation' as categorical

Skipped cell type CD10+ B cells, due to < 10 cells
Skipped cell type CD8+ T cells, due to < 10 cells
Skipped cell type Plasma cells, due to < 10 cells
Skipped cell type Megakaryocyte progenitors, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scgraph_ref_v2.csv

Computing neighbors: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:27:23 - 2 days, 12:06:32 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:00, 59.01it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:01<00:04,  1.72it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:01<00:04,  1.72it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:01<00:04,  1.72it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:01<00:03,  1.72it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:01<00:02,  1.72it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:01<00:02,  1.72it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD8+ T cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:01<00:00,  5.64it/s, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:01<00:00,  5.64it/s, Batch correction: graph_connectivity]
Embeddings:  50%|█████     | 1/2 [00:01<00:01,  1.51s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:27:24 - 2 days, 12:06:34 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:00, 45.67it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.04it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:03,  2.04it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:00<00:03,  2.04it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:01<00:02,  2.04it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:01<00:02,  2.04it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:01<00:01,  2.04it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     CD8+ T cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Megakaryocyte progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.
INFO     Plasma cells consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:01<00:00,  6.79it/s, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:01<00:00,  6.79it/s, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 2/2 [00:02<00:00,  1.39s/it]atch correction: pcr_comparison]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scib_ref_v2.csv

(                     Isolated labels KMeans NMI KMeans ARI Silhouette label  \
 Embedding
 seacell_pca                 0.690193     0.7612    0.48162          0.59916
 seacell_pca_harmoney        0.653794   0.797615    0.62345         0.624343
 scProto_mc_pca              0.597917   0.632531   0.283255         0.534265

                          cLISI Silhouette batch     iLISI      KBET  \
 Embedding
 seacell_pca            0.95729          0.66175  0.201272  0.555556
 seacell_pca_harmoney  0.977364         0.771486  0.617611   0.84946
 scProto_mc_pca        0.957261           0.7509  0.266704  0.776951

                      Graph connectivity PCR comparison Batch correction  \
 Embedding
 seacell_pca                    0.935342            0.0         0.470784
 seacell_pca_harmoney           0.910392       0.699572         0.769704
 scProto_mc_pca                 0.958872            0.0         0.550685

                      Bio conservation     Total
 Embedding
 seacell_pca                  0.697893  0.607049
 seacell_pca_harmoney         0.735313   0.74907
 scProto_mc_pca               0.601046  0.580902  ,
                       Rank-PCA  Corr-PCA  Corr-Weighted
 seacell_pca           0.942890  0.988028       0.968619
 seacell_pca_harmoney  0.931235  0.988803       0.974476
 scProto_mc_pca        0.875000  0.972581       0.924775)

In [ ]:
scproto_params = {
    "cvae_loss_scaler": 0.01,
    "propagation_reg": 1,
    "experiment_name": "t2",
    "debug": 1
}
t = SCProtoTrainer(**scproto_params)
add_trainer_emb(t, ref)
scpoli_params = {
    "model": "scpoli"
}
t2 = OriginalTrainer(**scpoli_params)
add_trainer_emb(t2, ref)

In [271]:
ref = add_pca_harmoney(ref, bk, 'X_pca')
ref = add_scvi_emb(ref, [], bk)

2025-09-11 07:28:46,069 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO - 09/11/25 07:28:46 - 2 days, 12:07:55 - Computing initial centroids with sklearn.KMeans...
2025-09-11 07:28:50,845 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO - 09/11/25 07:28:50 - 2 days, 12:08:00 - sklearn.KMeans initialization complete.
2025-09-11 07:28:50,957 - harmonypy - INFO - Iteration 1 of 10
INFO - 09/11/25 07:28:50 - 2 days, 12:08:00 - Iteration 1 of 10
2025-09-11 07:28:55,099 - harmonypy - INFO - Iteration 2 of 10
INFO - 09/11/25 07:28:55 - 2 days, 12:08:04 - Iteration 2 of 10
2025-09-11 07:28:59,252 - harmonypy - INFO - Iteration 3 of 10
INFO - 09/11/25 07:28:59 - 2 days, 12:08:09 - Iteration 3 of 10
2025-09-11 07:29:02,455 - harmonypy - INFO - Converged after 3 iterations
INFO - 09/11/25 07:29:02 - 2 days, 12:08:12 - Converged after 3 iterations
Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-6f66a4db-c267-549f-945a-69946ecc988e]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 100/100: 100%|██████████| 100/100 [02:39<00:00,  1.59s/it, loss=647, v_num=1]

`Trainer.fit` stopped: `max_epochs=100` reached.

Epoch 100/100: 100%|██████████| 100/100 [02:39<00:00,  1.60s/it, loss=647, v_num=1]

Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-6f66a4db-c267-549f-945a-69946ecc988e]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 1/1: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, loss=643, v_num=1]

`Trainer.fit` stopped: `max_epochs=1` reached.

Epoch 1/1: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, loss=643, v_num=1]

In [274]:
emb_keys = [
    "X_pca",
    "t2_cvae_0.01_prop_1",
    "scpoli",
    "X_pca_harmoney",
    "X_scvi",
]

In [275]:
save_metrics(ref, emb_keys, ds, bk, lk, name_postfix='ref_v2', **scgraph_kwargs)

... storing 'conditions_combined' as categorical

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scgraph_ref_v2.csv

Computing neighbors: 100%|██████████| 5/5 [01:11<00:00, 14.27s/it]
Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:43:39 - 2 days, 12:22:49 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:16<02:24, 16.10s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:16<02:24, 16.10s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:24<01:30, 11.34s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:24<01:30, 11.34s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:39<01:32, 13.20s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:39<01:32, 13.20s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:39<00:48,  8.04s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:39<00:48,  8.04s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:42<00:31,  6.22s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:42<00:31,  6.22s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:42<00:16,  4.16s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:42<00:16,  4.16s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:56<00:21,  7.17s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:56<00:21,  7.17s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:56<00:14,  7.17s/it, Batch correction: pcr_comparison]
Embeddings:  20%|██        | 1/5 [00:56<03:45, 56.47s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:44:36 - 2 days, 12:23:45 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:01<00:17,  1.92s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:01<00:17,  1.92s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:18,  2.36s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:18,  2.36s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:06<00:13,  1.98s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:06<00:13,  1.98s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:06<00:07,  1.31s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:06<00:07,  1.31s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:06<00:04,  1.01it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:06<00:04,  1.01it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:07<00:02,  1.36it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:07<00:02,  1.36it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:29<00:23,  7.92s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:29<00:23,  7.92s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:29<00:15,  7.92s/it, Batch correction: pcr_comparison]
Embeddings:  40%|████      | 2/5 [01:26<02:02, 40.85s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:45:05 - 2 days, 12:24:15 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:01<00:12,  1.35s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:01<00:12,  1.35s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:17,  2.16s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:17,  2.16s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:05<00:11,  1.61s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:05<00:11,  1.61s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:05<00:06,  1.06s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:05<00:06,  1.06s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:05<00:04,  1.22it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:05<00:04,  1.22it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:05<00:02,  1.65it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:05<00:02,  1.65it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:22<00:17,  5.78s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:22<00:17,  5.78s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:22<00:11,  5.78s/it, Batch correction: pcr_comparison]
Embeddings:  60%|██████    | 3/5 [01:48<01:04, 32.42s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:45:28 - 2 days, 12:24:38 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:15<02:22, 15.80s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:15<02:22, 15.80s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:21<01:19,  9.90s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:21<01:19,  9.90s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:36<01:26, 12.33s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:36<01:26, 12.33s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:36<00:45,  7.51s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:36<00:45,  7.51s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:39<00:29,  5.85s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:39<00:29,  5.85s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:39<00:15,  3.90s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:39<00:15,  3.90s/it, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:52<00:20,  6.75s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:52<00:20,  6.75s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:52<00:13,  6.75s/it, Batch correction: pcr_comparison]
Embeddings:  80%|████████  | 4/5 [02:41<00:40, 40.45s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/11/25 07:46:21 - 2 days, 12:25:30 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:01<00:14,  1.63s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:01<00:14,  1.63s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:17,  2.13s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:04<00:17,  2.13s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:05<00:11,  1.68s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:05<00:11,  1.68s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:05<00:06,  1.11s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:05<00:06,  1.11s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:05<00:04,  1.16it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:05<00:04,  1.16it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:06<00:02,  1.58it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:06<00:02,  1.58it/s, Batch correction: kbet_per_label]

INFO     CD10+ B cells consists of a single batch or is too small. Skip.
INFO     Erythrocytes consists of a single batch or is too small. Skip.
INFO     Erythroid progenitors consists of a single batch or is too small. Skip.
INFO     Monocyte progenitors consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:19<00:14,  4.89s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:19<00:14,  4.89s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:19<00:09,  4.89s/it, Batch correction: pcr_comparison]
Embeddings: 100%|██████████| 5/5 [03:01<00:00, 36.29s/it]atch correction: pcr_comparison]

ref_v2 /home/icb/fatemehs.hashemig/models//pbmc-immune//scib_ref_v2.csv

(                     Isolated labels KMeans NMI KMeans ARI Silhouette label  \
 Embedding
 X_pca                        0.59233   0.652593   0.414049         0.565817
 t2_cvae_0.01_prop_1         0.577204   0.661628   0.383094         0.572264
 scpoli                       0.58403   0.542031    0.28758         0.526546
 X_pca_harmoney              0.546008   0.700868   0.474959         0.568079
 X_scvi                      0.621211   0.709064   0.533177         0.578135
 seacell_pca                 0.690193     0.7612    0.48162          0.59916
 seacell_pca_harmoney        0.653794   0.797615    0.62345         0.624343
 scProto_mc_pca              0.597917   0.632531   0.283255         0.534265

                          cLISI Silhouette batch     iLISI      KBET  \
 Embedding
 X_pca                 0.997075         0.723055       0.0  0.222168
 t2_cvae_0.01_prop_1   0.991557         0.813762  0.231996  0.276684
 scpoli                 0.97946         0.881873  0.582541  0.552637
 X_pca_harmoney        0.997636         0.889055  0.132653  0.451438
 X_scvi                0.997028         0.841072  0.379604  0.332569
 seacell_pca            0.95729          0.66175  0.201272  0.555556
 seacell_pca_harmoney  0.977364         0.771486  0.617611   0.84946
 scProto_mc_pca        0.957261           0.7509  0.266704  0.776951

                      Graph connectivity PCR comparison Batch correction  \
 Embedding
 X_pca                           0.67558            0.0         0.324161
 t2_cvae_0.01_prop_1            0.879831       0.942095         0.628874
 scpoli                         0.878579       0.971824         0.773491
 X_pca_harmoney                 0.714306       0.847013         0.606893
 X_scvi                         0.924349       0.899802         0.675479
 seacell_pca                    0.935342            0.0         0.470784
 seacell_pca_harmoney           0.910392       0.699572         0.769704
 scProto_mc_pca                 0.958872            0.0         0.550685

                      Bio conservation     Total
 Embedding
 X_pca                        0.644373  0.516288
 t2_cvae_0.01_prop_1          0.637149  0.633839
 scpoli                       0.583929  0.659754
 X_pca_harmoney                0.65751  0.637263
 X_scvi                       0.687723  0.682825
 seacell_pca                  0.697893  0.607049
 seacell_pca_harmoney         0.735313   0.74907
 scProto_mc_pca               0.601046  0.580902  ,
                       Rank-PCA  Corr-PCA  Corr-Weighted
 X_pca                 0.841360  0.913529       0.847457
 t2_cvae_0.01_prop_1   0.546507  0.723536       0.514437
 scpoli                0.481434  0.685367       0.441909
 X_pca_harmoney        0.787684  0.890070       0.794661
 X_scvi                0.555515  0.732990       0.545128
 seacell_pca           0.942890  0.988028       0.968619
 seacell_pca_harmoney  0.931235  0.988803       0.974476
 scProto_mc_pca        0.875000  0.972581       0.924775)

In [276]:
generate_table(f'{home}/models/pbmc-immune/', 'ref_v2')

# compare seacell - scproto on scgraph metrics in 1 batch

In [32]:
pwd

'/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl'

In [33]:
home = '/ictstr01/home/icb/fatemehs.hashemig/'
p = f'{home}/models/cd34/ref_seacell'
ad, SEACell_ad = sc.read_h5ad(p + '_sc.h5ad'), sc.read_h5ad(p + '_agg.h5ad')

In [326]:
    sc.pp.normalize_per_cell(SEACell_ad)
    sc.pp.log1p(SEACell_ad)

In [329]:
SEACell_ad = agg_obs(SEACell_ad, ad, 'celltype')

In [342]:
SEACell_ad

AnnData object with n_obs × n_vars = 95 × 12464
    obs: 'n_counts', 'celltype', 'batch'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'hvg', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'
    layers: 'raw'

In [336]:
sc.pp.highly_variable_genes(
        SEACell_ad,
        n_top_genes=1000,
    )

In [337]:
sc.tl.pca(SEACell_ad, use_highly_variable=True)

In [339]:
SEACell_ad.obs['batch'] = ['b0']*95

In [350]:
SEACell_ad.obs['batch'].nunique()

1

In [347]:
SEACell_ad.obs.batch.value_counts()

b0    95
Name: batch, dtype: int64

In [348]:
SEACell_ad.write("tmp.h5ad")
scgraph = scGraph(
    adata_path="tmp.h5ad", label_key='celltype', batch_key = 'batch', thres_celltype = 3, thres_batch=10
)
scgr_res = scgraph.main(_obsm_list=['X_pca'])

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/1 [00:00<?, ?it/s]

In [349]:
scgr_res

       Rank-PCA  Corr-PCA  Corr-Weighted
X_pca       1.0  0.999865       0.999818

# add scproto + scproto mc scgraph metrics

In [1]:
# load scproto model trained on cd34
# generate scproto metacells
# hvg + pca -> scgraph with same params

In [9]:
p = {
    'cvae_epochs': 100,
    'dataset_id': 'cd34',
    'num_prototypes': 95,
    'batch_size': 128
}
t = SCProtoTrainer(debug=1, **p)

dataset is None, loading cd34
loading cd34 data
done
ℹ️ Found 1000 HVGs out of 12464 total genes.
1 batch dataset

In [13]:
metacells_adata = get_scproto_mc_adata(t, t.dataset.adata, 'batch', 'celltype')

Embedding dictionary:
 	Num conditions: [1]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 1000 32 10
	Mean/Var Layer in/out: 32 8
Decoder Architecture:
	First Layer in, out and cond:  8 32 10
	Output Layer in/out:  32 1000

100%|██████████| 54/54 [00:05<00:00,  9.12it/s]

In [14]:
sc.pp.highly_variable_genes(
        metacells_adata,
        n_top_genes=1000,
    )

In [22]:
sc.tl.pca(metacells_adata, use_highly_variable=True)

In [28]:
metacells_adata.write("tmp.h5ad")
scgraph = scGraph(
    adata_path="tmp.h5ad", label_key='celltype', batch_key = 'batch', thres_celltype = 3, thres_batch=10
)
scgr_res = scgraph.main(_obsm_list=['X_pca'])

Skipped cell type CLP, due to < 3 cells
Skipped cell type pDC, due to < 3 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
scgr_res

       Rank-PCA  Corr-PCA  Corr-Weighted
X_pca       1.0  0.999986       0.999968

In [35]:
SEACell_ad.X.max()

1178.4344482421875

In [38]:
model = t.load_model()
protos = model.get_prototypes()
batch = np.zeros((protos.shape[0], 1))
batch = torch.as_tensor(batch, dtype=torch.long, device="cuda")
sizefactor = np.ones((protos.shape[0],))
sizefactor = torch.as_tensor(sizefactor, dtype=torch.long, device="cuda")
metacells = model.decode(protos, batch, sizefactor)

Embedding dictionary:
 	Num conditions: [1]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 1000 32 10
	Mean/Var Layer in/out: 32 8
Decoder Architecture:
	First Layer in, out and cond:  8 32 10
	Output Layer in/out:  32 1000

In [42]:
# reproduce all results

torch.Size([95, 1000])

In [41]:
add save_metrics to trainer

save_scib
save_scgraph
save_metacell

AnnData object with n_obs × n_vars = 6881 × 1000
    obs: 'leiden', 'celltype', 'n_counts', 'batch', 'conditions_combined'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'celltype_colors', 'hvg', 'log1p', 'pca'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'counts'

In [45]:
model = t.get_model()

Embedding dictionary:
 	Num conditions: [1]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 1000 32 10
	Mean/Var Layer in/out: 32 8
Decoder Architecture:
	First Layer in, out and cond:  8 32 10
	Output Layer in/out:  32 1000

In [46]:
model

scProtoGMVAE(
  (scpoli_cvae): scpoli(
    (embeddings): ModuleList(
      (0): Embedding(1, 10, max_norm=1.0)
    )
    (encoder): Encoder(
      (FC): Sequential(
        (L0): CondLayers(
          (expr_L): Linear(in_features=1000, out_features=32, bias=True)
          (cond_L): Linear(in_features=10, out_features=32, bias=False)
        )
        (N0): LayerNorm((32,), eps=1e-05, elementwise_affine=False)
        (A0): ReLU()
        (D0): Dropout(p=0.05, inplace=False)
      )
      (mean_encoder): Linear(in_features=32, out_features=8, bias=True)
      (log_var_encoder): Linear(in_features=32, out_features=8, bias=True)
    )
    (decoder): Decoder(
      (FirstL): Sequential(
        (L0): CondLayers(
          (expr_L): Linear(in_features=8, out_features=32, bias=False)
          (cond_L): Linear(in_features=10, out_features=32, bias=False)
        )
        (N0): LayerNorm((32,), eps=1e-05, elementwise_affine=False)
        (A0): ReLU()
        (D0): Dropout(p=0.05, inplace=False)
      )
      (HiddenL): Sequential()
      (mean_decoder): Sequential(
        (0): Linear(in_features=32, out_features=1000, bias=True)
        (1): Softmax(dim=-1)
      )
    )
  )
  (prototypes): Linear(in_features=8, out_features=95, bias=False)
)

In [138]:
t = SCProtoTrainer(proto_init = 'random', ft_epochs=5)

dataset is None, loading pbmc-immune
loading pbmc-immune data
done
✅ Already subsetted to HVGs (4000 genes).

In [139]:
t.model = t.load_model()

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [5]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

In [92]:
t.log_wandb_loss = lambda a, b: None
t.train(5)

In [141]:
import os
os.environ["JAX_ENABLE_X64"] = "0"   # force 32-bit JAX
# optional, extra belt:
os.environ["JAX_DEFAULT_DTYPE_BITS"] = "32"

In [143]:
t.dataset.adata

AnnData object with n_obs × n_vars = 33506 × 4000
    obs: 'batch', 'chemistry', 'data_type', 'dpt_pseudotime', 'final_annotation', 'mt_frac', 'n_counts', 'n_genes', 'sample_ID', 'size_factors', 'species', 'study', 'tissue', 'conditions_combined'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg', 'pca'
    obsm: 'swav', 'X_pca'
    varm: 'PCs'
    layers: 'counts'

In [144]:
get_scib(t.dataset.adata, ['X_pca'], 'study', 'final_annotation')

Computing neighbors: 100%|██████████| 1/1 [00:21<00:00, 21.20s/it]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/12/25 09:28:57 - 11:47:22 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:36<05:30, 36.75s/it, Bio conservation: isolated_labels]
Embeddings:   0%|          | 0/1 [00:37<?, ?it/s]5s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]

TypeError: body_fun output and input must have identical types, got
('ShapedArray(float32[16,50])', 'ShapedArray(float32[])', 'DIFFERENT ShapedArray(float32[]) vs. ShapedArray(float64[], weak_type=True)', 'ShapedArray(float64[1])').

In [1]:
from scib_metrics.benchmark import Benchmarker

In [2]:
import jax
print("enable_x64:", jax.config.read("jax_enable_x64"))
print("default dtype:", jax.numpy.array(0.0).dtype)

enable_x64: False

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

default dtype: float32

In [3]:
import SEACells

In [4]:
print("default dtype:", jax.numpy.array(0.0).dtype)

default dtype: float64

In [6]:
pwd

'/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl/notebooks'

In [8]:
import scanpy as sc
h = '/ictstr01/home/icb/fatemehs.hashemig/'
ad = sc.read_h5ad(f'{h}/data/pancreas_hvg.h5ad')

In [12]:
sc.tl.pca(ad)

In [13]:
bm = Benchmarker(
    adata=ad,
    batch_key='tech',
    label_key='celltype',
    embedding_obsm_keys=['X_pca'],  # evaluate the PCA space
)
bm.benchmark()  # runs neighbors, clustering, and metrics
results = bm.get_results(min_max_scale=False)

Computing neighbors: 100%|██████████| 1/1 [00:39<00:00, 39.03s/it]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:12<01:53, 12.56s/it, Bio conservation: isolated_labels]
Embeddings:   0%|          | 0/1 [00:13<?, ?it/s]6s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]

TypeError: body_fun output and input must have identical types, got
('ShapedArray(float32[14,50])', 'ShapedArray(float32[])', 'DIFFERENT ShapedArray(float32[]) vs. ShapedArray(float64[], weak_type=True)', 'ShapedArray(float64[1])').