# imports

In [ ]:
import os
os.chdir('/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl')

In [52]:
import importlib
import interpretable_ssl.evaluation.metric_helpers.embedding_metrics
importlib.reload(interpretable_ssl.evaluation.metric_helpers.embedding_metrics)

In [54]:
from interpretable_ssl.evaluation.metric_helpers.embedding_metrics import *

In [23]:
import jax.numpy as jnp
print(jnp.array(0.0).dtype)  # should say float32

float32

# pca, harmoney scib pancreas

In [3]:
import scanpy as sc

In [92]:
def load_pancreas():
    home = '/ictstr01/home/icb/fatemehs.hashemig/'
    adata = sc.read_h5ad(f'{home}/data/pancreas_hvg.h5ad')
    sc.tl.pca(adata)
    return adata

adata = load_pancreas()

In [93]:
save_pca_harmoney_metrics(adata, 'tech', 'celltype', 'pancreas')

2025-09-05 13:58:06,014 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO - 09/05/25 13:58:06 - 3:56:46 - Computing initial centroids with sklearn.KMeans...
2025-09-05 13:58:09,742 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO - 09/05/25 13:58:09 - 3:56:50 - sklearn.KMeans initialization complete.
2025-09-05 13:58:11,407 - harmonypy - INFO - Iteration 1 of 10
INFO - 09/05/25 13:58:11 - 3:56:51 - Iteration 1 of 10
2025-09-05 13:58:13,756 - harmonypy - INFO - Iteration 2 of 10
INFO - 09/05/25 13:58:13 - 3:56:54 - Iteration 2 of 10
2025-09-05 13:58:15,981 - harmonypy - INFO - Iteration 3 of 10
INFO - 09/05/25 13:58:15 - 3:56:56 - Iteration 3 of 10
2025-09-05 13:58:18,205 - harmonypy - INFO - Iteration 4 of 10
INFO - 09/05/25 13:58:18 - 3:56:58 - Iteration 4 of 10
2025-09-05 13:58:20,439 - harmonypy - INFO - Iteration 5 of 10
INFO - 09/05/25 13:58:20 - 3:57:00 - Iteration 5 of 10
2025-09-05 13:58:22,670 - harmonypy - INFO - Iteration 6 of 10
INFO - 09/05/25 13:58:22 - 3:57:03 - Iteration 6 of 10
2025-09-05 13:58:24,899 - harmonypy - INFO - Iteration 7 of 10
INFO - 09/05/25 13:58:24 - 3:57:05 - Iteration 7 of 10
2025-09-05 13:58:27,112 - harmonypy - INFO - Iteration 8 of 10
INFO - 09/05/25 13:58:27 - 3:57:07 - Iteration 8 of 10
2025-09-05 13:58:28,828 - harmonypy - INFO - Iteration 9 of 10
INFO - 09/05/25 13:58:28 - 3:57:09 - Iteration 9 of 10
2025-09-05 13:58:29,575 - harmonypy - INFO - Iteration 10 of 10
INFO - 09/05/25 13:58:29 - 3:57:10 - Iteration 10 of 10
2025-09-05 13:58:30,322 - harmonypy - INFO - Converged after 10 iterations
INFO - 09/05/25 13:58:30 - 3:57:10 - Converged after 10 iterations

Skipped cell type t_cell, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Computing neighbors: 100%|██████████| 2/2 [00:19<00:00,  9.81s/it]
Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 13:58:57 - 3:57:38 - isolated labels: no more than 4 batches per label

Metrics:  10%|█         | 1/10 [00:04<00:44,  4.97s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:04<00:44,  4.97s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:07<00:29,  3.69s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:07<00:29,  3.69s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.27s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.27s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:12<00:25,  4.27s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:10,  2.17s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:10,  2.17s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:13<00:08,  2.17s/it, Batch correction: kbet_per_label]

INFO     t_cell consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:20<00:07,  2.62s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:20<00:07,  2.62s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:20<00:05,  2.62s/it, Batch correction: pcr_comparison]
Embeddings:  50%|█████     | 1/2 [00:20<00:20, 20.34s/it]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 13:59:17 - 3:57:58 - isolated labels: no more than 4 batches per label

Metrics:  10%|█         | 1/10 [00:05<00:45,  5.01s/it, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:05<00:45,  5.01s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:07<00:28,  3.62s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:07<00:28,  3.62s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.23s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:12<00:29,  4.23s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:12<00:25,  4.23s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:10,  2.15s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:13<00:10,  2.15s/it, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:13<00:08,  2.15s/it, Batch correction: kbet_per_label]

INFO     t_cell consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:20<00:08,  2.73s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:20<00:08,  2.73s/it, Batch correction: graph_connectivity]
Metrics:  80%|████████  | 8/10 [00:20<00:05,  2.73s/it, Batch correction: pcr_comparison]
Embeddings: 100%|██████████| 2/2 [00:41<00:00, 20.55s/it]atch correction: pcr_comparison]

(               Isolated labels KMeans NMI KMeans ARI Silhouette label cLISI  \
 Embedding
 X_pca                 0.662941    0.68413   0.473834          0.54067   1.0
 X_pca_harmoney        0.607937   0.831354   0.831072         0.608349   1.0

                Silhouette batch     iLISI      KBET Graph connectivity  \
 Embedding
 X_pca                  0.831701   0.00043  0.160427           0.719823
 X_pca_harmoney          0.90136  0.233896   0.52573           0.882766

                PCR comparison Batch correction Bio conservation     Total
 Embedding
 X_pca                     0.0         0.342476         0.672315   0.54038
 X_pca_harmoney       0.859589         0.680668         0.775742  0.737713  ,
                 Rank-PCA  Corr-PCA  Corr-Weighted
 X_pca           0.915046  0.961659       0.920961
 X_pca_harmoney  0.916314  0.970931       0.932270)

In [15]:
ad, SEACell_ad, model = compute_seacells(adata, 220)

Welcome to SEACells!
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
Building kernel on X_pca
Computing diffusion components from X_pca for waypoint initialization ...
Done.
Sampling waypoints ...
Done.
Selecting 207 cells from waypoint initialization.
Initializing residual matrix using greedy column selection
Initializing f and g...

100%|██████████| 23/23 [00:00<00:00, 48.94it/s]

Selecting 13 cells from greedy initialization.
Randomly initialized A matrix.
Setting convergence threshold at 0.00230
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Starting iteration 20.
Completed iteration 20.
Starting iteration 30.
Completed iteration 30.
Converged after 34 iterations.

100%|██████████| 220/220 [00:01<00:00, 155.75it/s]

In [17]:
SEACell_ad.X.max()

7.325793195956563

In [16]:
bk, lk, ds = 'tech', 'celltype', 'pancreas'
get_seacell_metrics(SEACell_ad, adata, bk, lk, ds)

2025-09-04 16:07:57,736 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
INFO:harmonypy:Computing initial centroids with sklearn.KMeans...
2025-09-04 16:07:58,706 - harmonypy - INFO - sklearn.KMeans initialization complete.
INFO:harmonypy:sklearn.KMeans initialization complete.
2025-09-04 16:07:58,780 - harmonypy - INFO - Iteration 1 of 10
INFO:harmonypy:Iteration 1 of 10
2025-09-04 16:07:58,951 - harmonypy - INFO - Iteration 2 of 10
INFO:harmonypy:Iteration 2 of 10
2025-09-04 16:07:58,978 - harmonypy - INFO - Iteration 3 of 10
INFO:harmonypy:Iteration 3 of 10
2025-09-04 16:07:59,011 - harmonypy - INFO - Iteration 4 of 10
INFO:harmonypy:Iteration 4 of 10
2025-09-04 16:07:59,039 - harmonypy - INFO - Iteration 5 of 10
INFO:harmonypy:Iteration 5 of 10
2025-09-04 16:07:59,063 - harmonypy - INFO - Iteration 6 of 10
INFO:harmonypy:Iteration 6 of 10
2025-09-04 16:07:59,086 - harmonypy - INFO - Iteration 7 of 10
INFO:harmonypy:Iteration 7 of 10
2025-09-04 16:07:59,110 - harmonypy - INFO - Iteration 8 of 10
INFO:harmonypy:Iteration 8 of 10
2025-09-04 16:07:59,133 - harmonypy - INFO - Iteration 9 of 10
INFO:harmonypy:Iteration 9 of 10
2025-09-04 16:07:59,156 - harmonypy - INFO - Iteration 10 of 10
INFO:harmonypy:Iteration 10 of 10
2025-09-04 16:07:59,178 - harmonypy - INFO - Converged after 10 iterations
INFO:harmonypy:Converged after 10 iterations

Skipped cell type schwann, due to < 10 cells
Skipped cell type endothelial, due to < 10 cells
Skipped cell type macrophage, due to < 10 cells
Skipped cell type quiescent_stellate, due to < 10 cells
Skipped cell type mast, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Skipped batch celseq2, due to < 100 cells
Skipped batch fluidigmc1, due to < 100 cells
Skipped batch smartseq2, due to < 100 cells
Skipped batch inDrop2, due to < 100 cells
Skipped batch celseq, due to < 100 cells
Skipped batch inDrop1, due to < 100 cells
Skipped batch inDrop4, due to < 100 cells
Skipped batch inDrop3, due to < 100 cells
Skipped batch smarter, due to < 100 cells

ValueError: No objects to concatenate

In [6]:
home = '/ictstr01/home/icb/fatemehs.hashemig/'

In [23]:
SEACell_ad.write(f'{home}/pancreas_seacells.h5ad')

# load pancreas seacell, save scib and scgraph

In [94]:
SEACell_ad = sc.read_h5ad(f'{home}/pancreas_seacells.h5ad')
SEACell_ad

AnnData object with n_obs × n_vars = 220 × 4000
    obs: 'n_counts', 'tech', 'celltype'
    uns: 'log1p', 'pca'
    obsm: 'X_pca', 'seacell_pca', 'seacell_pca_harmoney'
    varm: 'PCs'
    layers: 'raw'

In [95]:
bk, lk = 'tech', 'celltype'

ds = 'pancreas'
metrics = get_scib(SEACell_ad, ['seacell_pca', 'seacell_pca_harmoney'], ds, bk, lk)
metrics

Computing neighbors: 100%|██████████| 2/2 [00:00<00:00,  6.22it/s]
Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 13:59:39 - 3:58:20 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:00, 125.42it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:02,  3.50it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:02,  3.50it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:00<00:01,  3.50it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:00<00:01,  3.50it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:00<00:01,  3.50it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:00<00:01,  3.50it/s, Batch correction: kbet_per_label]

INFO     endothelial consists of a single batch or is too small. Skip.
INFO     macrophage consists of a single batch or is too small. Skip.
INFO     mast consists of a single batch or is too small. Skip.
INFO     quiescent_stellate consists of a single batch or is too small. Skip.
INFO     schwann consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:00<00:00, 11.24it/s, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:00<00:00, 11.24it/s, Batch correction: graph_connectivity]
Embeddings:  50%|█████     | 1/2 [00:00<00:00,  1.33it/s]atch correction: pcr_comparison]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 13:59:40 - 3:58:20 - isolated labels: no more than 1 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:00, 95.51it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:02,  3.62it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:00<00:02,  3.62it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:00<00:01,  3.62it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:00<00:01,  3.62it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:00<00:01,  3.62it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:00<00:01,  3.62it/s, Batch correction: kbet_per_label]

INFO     endothelial consists of a single batch or is too small. Skip.
INFO     macrophage consists of a single batch or is too small. Skip.
INFO     mast consists of a single batch or is too small. Skip.
INFO     quiescent_stellate consists of a single batch or is too small. Skip.
INFO     schwann consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:00<00:00, 11.52it/s, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:00<00:00, 11.52it/s, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.34it/s]atch correction: pcr_comparison]

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
seacell_pca,0.5,0.625279,0.383839,0.5833,0.933285,0.701281,0.17771,0.575758,0.77553,0.0,0.446056,0.605141,0.541507
seacell_pca_harmoney,0.5,0.749384,0.569488,0.630511,0.96952,0.818407,0.376212,0.852755,0.827615,0.537683,0.682534,0.68378,0.683282
X_pca,0.662941,0.68413,0.473834,0.54067,1.0,0.831701,0.00043,0.160427,0.719823,0.0,0.342476,0.672315,0.54038
X_pca_harmoney,0.607937,0.831354,0.831072,0.608349,1.0,0.90136,0.233896,0.52573,0.882766,0.859589,0.680668,0.775742,0.737713

In [96]:
get_scgraph(SEACell_ad, ['seacell_pca', 'seacell_pca_harmoney'], ds, bk, lk, thres_batch = 10)

Skipped cell type schwann, due to < 10 cells
Skipped cell type endothelial, due to < 10 cells
Skipped cell type macrophage, due to < 10 cells
Skipped cell type quiescent_stellate, due to < 10 cells
Skipped cell type mast, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

                      Rank-PCA  Corr-PCA  Corr-Weighted
seacell_pca           0.943878  0.989190       0.959352
seacell_pca_harmoney  0.913265  0.987165       0.959283
X_pca                 0.915046  0.961659       0.920961
X_pca_harmoney        0.916314  0.970931       0.932270

# scvi

In [97]:
get_scvi_metrics(adata, ["celseq", "celseq2"], bk, lk, ds)

Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 100/100: 100%|██████████| 100/100 [01:09<00:00,  1.53it/s, loss=1.54e+03, v_num=1]

`Trainer.fit` stopped: `max_epochs=100` reached.

Epoch 100/100: 100%|██████████| 100/100 [01:09<00:00,  1.44it/s, loss=1.54e+03, v_num=1]

Multiprocessing is handled by SLURM.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.

Epoch 1/1: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s, loss=1.65e+03, v_num=1]

`Trainer.fit` stopped: `max_epochs=1` reached.

Epoch 1/1: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, loss=1.65e+03, v_num=1]
Skipped cell type t_cell, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Computing neighbors: 100%|██████████| 1/1 [00:07<00:00,  7.17s/it]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 14:01:18 - 3:59:59 - isolated labels: no more than 4 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:04,  1.81it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:00<00:04,  1.81it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:11,  1.42s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:11,  1.42s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:03<00:07,  1.02s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:03<00:07,  1.02s/it, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:03<00:06,  1.02s/it, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:03<00:02,  2.02it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:03<00:02,  2.02it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:03<00:01,  2.02it/s, Batch correction: kbet_per_label]

INFO     t_cell consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:10<00:05,  1.96s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:10<00:05,  1.96s/it, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 1/1 [00:10<00:00, 10.93s/it]atch correction: pcr_comparison]

(                     Isolated labels KMeans NMI KMeans ARI Silhouette label  \
 Embedding
 X_scvi                      0.747434   0.755029   0.495347         0.629888
 seacell_pca                      0.5   0.625279   0.383839           0.5833
 seacell_pca_harmoney             0.5   0.749384   0.569488         0.630511
 X_pca                       0.662941    0.68413   0.473834          0.54067
 X_pca_harmoney              0.607937   0.831354   0.831072         0.608349

                          cLISI Silhouette batch     iLISI      KBET  \
 Embedding
 X_scvi                     1.0         0.859884   0.17507  0.318916
 seacell_pca           0.933285         0.701281   0.17771  0.575758
 seacell_pca_harmoney   0.96952         0.818407  0.376212  0.852755
 X_pca                      1.0         0.831701   0.00043  0.160427
 X_pca_harmoney             1.0          0.90136  0.233896   0.52573

                      Graph connectivity PCR comparison Batch correction  \
 Embedding
 X_scvi                         0.931973       0.670423         0.591253
 seacell_pca                     0.77553            0.0         0.446056
 seacell_pca_harmoney           0.827615       0.537683         0.682534
 X_pca                          0.719823            0.0         0.342476
 X_pca_harmoney                 0.882766       0.859589         0.680668

                      Bio conservation     Total
 Embedding
 X_scvi                        0.72554  0.671825
 seacell_pca                  0.605141  0.541507
 seacell_pca_harmoney          0.68378  0.683282
 X_pca                        0.672315   0.54038
 X_pca_harmoney               0.775742  0.737713  ,
                       Rank-PCA  Corr-PCA  Corr-Weighted
 X_scvi                0.532967  0.743138       0.469317
 seacell_pca           0.943878  0.989190       0.959352
 seacell_pca_harmoney  0.913265  0.987165       0.959283
 X_pca                 0.915046  0.961659       0.920961
 X_pca_harmoney        0.916314  0.970931       0.932270)

# scproto

In [98]:
from interpretable_ssl.trainers.swav import *

In [99]:
params = {
    "cvae_loss_scaler": 0.01,
    "propagation_reg": 1,
    "experiment_name": "corrected-ds",
    "dataset_id": "pancreas",
    "num_prototypes": 220,
    "batch_size": 128,
}
t = SwAV(**params)
t.setup()

dataset is None, loading pancreas
loading pancreas data

INFO - 09/05/25 14:01:29 - 4:00:10 - Starting '__init__' of class 'get train test'
INFO - 09/05/25 14:01:29 - 4:00:10 - Finished '__init__' of class 'get train test' in 0.0056 seconds

done
tech

INFO - 09/05/25 14:01:31 - 0:00:00 - ============ Initialized logger ============
INFO - 09/05/25 14:01:31 - 0:00:00 - all_latent: None
                                     assignment_metric: dotp
                                     augmentation_type: knn
                                     base_lr: 4.8
                                     batch_removal_ratio: 0.0
                                     batch_sinkhorn: 1
                                     batch_size: 128
                                     cell_type_key: cell_type
                                     checkpoint_freq: 30
                                     condition_key: tech
                                     cvae_epochs: 0
                                     cvae_loss_scaler: 0.01
                                     cvae_reg: 0
                                     dataset: pancreas
                                     dataset_cnt: 0
                                     dataset_id: pancreas
                                     debug: False
                                     decodable_prototypes: 0
                                     default_dispersion: 0.1
                                     default_values: {'dataset_id': 'pbmc-immune', 'model_name_version': 7, 'num_prototypes': 300, 'hidden_dim': 64, 'latent_dims': 8, 'experiment_name': '', 'condition_key': 'study', 'cell_type_key': 'cell_type', 'linear_eval': False, 'only_eval': False, 'use_early_stopping': False, 'training_type': 'pretrain_encoder', 'pretrain_dataset_id': 'hlca', 'finetune_dataset_id': 'pbmc-immune', 'dump_name_version': 4, 'nmb_crops': [4], 'augmentation_type': 'knn', 'size_crops': [224], 'min_scale_crops': [0.14], 'max_scale_crops': [1], 'views_for_assign': [0, 1], 'sinkhorn_iterations': 3, 'feat_dim': 8, 'cvae_reg': 0, 'dist_url': 'env://', 'world_size': 1, 'rank': 0, 'local_rank': 0, 'checkpoint_freq': 30, 'umap_checkpoint_freq': 10, 'scib_freq': 10, 'save_scib': 1, 'use_fp16': False, 'sync_bn': 'pytorch', 'syncbn_process_group_size': 8, 'seed': 31, 'model': '', 'optimizer': '', 'lr_schedule': '', 'queue': None, 'train_loader': '', 'training_stats': '', 'device': 'cuda', 'prot_decoding_loss_scaler': 0.0, 'hidden_mlp': 1024, 'swav_dim': 64, 'use_projector': False, 'model_version': 1, 'train_decoder': False, 'longest_path': 1, 'dimensionality_reduction': 'pca', 'k_neighbors': 50, 'job_name': '', 'no_data': 'False', 'freezable_prototypes': 0, 'prot_init': 'kmeans', 'prot_emb_sim_reg': 0.0, 'loss_type': 'cross_entropy', 'decodable_prototypes': 0, 'save_temp_res': 1, 'temp_res_path': 'temp-res', 'n_components': 50, 'supervised_ratio': 0.1, 'multi_layer_protos': 0, 'batch_removal_ratio': 0.0, 'use_bknn': 0, 'freeze_batch_embedding': 0, 'batch_sinkhorn': 1, 'weighted_batch': 0, 'knn_similarity': 'cosine', 'recon_loss': 'mse', 'no_sinkhorn': 0, 'wandb_sweep': 0, 'sweep_id': -1, 'mask_probability': 0.2, 'default_dispersion': 0.1, 'fold': 0, 'spatial': 0, 'use_the_queue': 0, 'entropy_reg': 0.0, 'dataset_cnt': 0, 'study_id': '', 'l2norm': 1, 'use_rbf': 1, 'assignment_metric': 'dotp', 'pretraining_epochs': 100, 'fine_tuning_epochs': 0, 'cvae_epochs': 0, 'cvae_loss_scaler': 0.0, 'propagation_reg': 0, 'model_type': 'gm', 'workers': 1, 'wd': 1e-06, 'final_lr': 0, 'warmup_epochs': 10, 'start_warmup': 0, 'batch_size': 1024, 'base_lr': 4.8, 'freeze_prototypes_nepochs': 20, 'hard_clustering': 0, 'temperature': 0.1, 'epsilon': 0.05, 'epoch_queue_starts': 0, 'queue_length': 0}
                                     device: cuda
                                     dimensionality_reduction: pca
                                     dist_url: env://
                                     ds_ids: range(0, 7)
                                     dump_checkpoints: /home/icb/fatemehs.hashemig/models//pancreas/corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs_128/checkpoints
                                     dump_name_version: 4
                                     dump_path: /home/icb/fatemehs.hashemig/models//pancreas/corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs_128
                                     entropy_reg: 0.0
                                     epoch_queue_starts: 0
                                     epsilon: 0.05
                                     experiment_name: corrected-ds
                                     feat_dim: 8
                                     final_lr: 0
                                     fine_tuning_epochs: 0
                                     finetune_dataset_id: pbmc-immune
                                     finetune_ds: None
                                     finetuning: False
                                     fold: 0
                                     freezable_prototypes: 0
                                     freeze_batch_embedding: 0
                                     freeze_prototypes_nepochs: 20
                                     hard_clustering: 0
                                     hidden_dim: 64
                                     hidden_mlp: 1024
                                     input_dim: 4000
                                     is_swav: 1
                                     job_name: corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs_128/pancreas
                                     k_neighbors: 50
                                     knn_similarity: cosine
                                     l2norm: 1
                                     latent_dims: 8
                                     linear_eval: False
                                     local_rank: 0
                                     longest_path: 1
                                     loss_type: cross_entropy
                                     lr_schedule:
                                     mask_probability: 0.2
                                     max_scale_crops: [1]
                                     min_scale_crops: [0.14]
                                     model:
                                     model_name_version: 7
                                     model_type: gm
                                     model_version: 1
                                     multi_layer_protos: 0
                                     n_components: 50
                                     nmb_crops: [4]
                                     nmb_prototypes: 220
                                     no_data: False
                                     no_sinkhorn: 0
                                     num_prototypes: 220
                                     only_eval: False
                                     optimizer:
                                     original_ref: pancreas
                                     params: {'is_swav': 1, 'default_values': {'dataset_id': 'pbmc-immune', 'model_name_version': 7, 'num_prototypes': 300, 'hidden_dim': 64, 'latent_dims': 8, 'experiment_name': '', 'condition_key': 'study', 'cell_type_key': 'cell_type', 'linear_eval': False, 'only_eval': False, 'use_early_stopping': False, 'training_type': 'pretrain_encoder', 'pretrain_dataset_id': 'hlca', 'finetune_dataset_id': 'pbmc-immune', 'dump_name_version': 4, 'nmb_crops': [4], 'augmentation_type': 'knn', 'size_crops': [224], 'min_scale_crops': [0.14], 'max_scale_crops': [1], 'views_for_assign': [0, 1], 'sinkhorn_iterations': 3, 'feat_dim': 8, 'cvae_reg': 0, 'dist_url': 'env://', 'world_size': 1, 'rank': 0, 'local_rank': 0, 'checkpoint_freq': 30, 'umap_checkpoint_freq': 10, 'scib_freq': 10, 'save_scib': 1, 'use_fp16': False, 'sync_bn': 'pytorch', 'syncbn_process_group_size': 8, 'seed': 31, 'model': '', 'optimizer': '', 'lr_schedule': '', 'queue': None, 'train_loader': '', 'training_stats': '', 'device': 'cuda', 'prot_decoding_loss_scaler': 0.0, 'hidden_mlp': 1024, 'swav_dim': 64, 'use_projector': False, 'model_version': 1, 'train_decoder': False, 'longest_path': 1, 'dimensionality_reduction': 'pca', 'k_neighbors': 50, 'job_name': '', 'no_data': 'False', 'freezable_prototypes': 0, 'prot_init': 'kmeans', 'prot_emb_sim_reg': 0.0, 'loss_type': 'cross_entropy', 'decodable_prototypes': 0, 'save_temp_res': 1, 'temp_res_path': 'temp-res', 'n_components': 50, 'supervised_ratio': 0.1, 'multi_layer_protos': 0, 'batch_removal_ratio': 0.0, 'use_bknn': 0, 'freeze_batch_embedding': 0, 'batch_sinkhorn': 1, 'weighted_batch': 0, 'knn_similarity': 'cosine', 'recon_loss': 'mse', 'no_sinkhorn': 0, 'wandb_sweep': 0, 'sweep_id': -1, 'mask_probability': 0.2, 'default_dispersion': 0.1, 'fold': 0, 'spatial': 0, 'use_the_queue': 0, 'entropy_reg': 0.0, 'dataset_cnt': 0, 'study_id': '', 'l2norm': 1, 'use_rbf': 1, 'assignment_metric': 'dotp', 'pretraining_epochs': 100, 'fine_tuning_epochs': 0, 'cvae_epochs': 0, 'cvae_loss_scaler': 0.0, 'propagation_reg': 0, 'model_type': 'gm', 'workers': 1, 'wd': 1e-06, 'final_lr': 0, 'warmup_epochs': 10, 'start_warmup': 0, 'batch_size': 1024, 'base_lr': 4.8, 'freeze_prototypes_nepochs': 20, 'hard_clustering': 0, 'temperature': 0.1, 'epsilon': 0.05, 'epoch_queue_starts': 0, 'queue_length': 0}, 'dataset_id': 'pancreas', 'model_name_version': 7, 'num_prototypes': 220, 'hidden_dim': 64, 'latent_dims': 8, 'experiment_name': 'corrected-ds', 'condition_key': 'study', 'cell_type_key': 'cell_type', 'linear_eval': False, 'only_eval': False, 'use_early_stopping': False, 'training_type': 'pretrain_encoder', 'pretrain_dataset_id': 'hlca', 'finetune_dataset_id': 'pbmc-immune', 'dump_name_version': 4, 'nmb_crops': [4], 'augmentation_type': 'knn', 'size_crops': [224], 'min_scale_crops': [0.14], 'max_scale_crops': [1], 'views_for_assign': [0, 1], 'sinkhorn_iterations': 3, 'feat_dim': 8, 'cvae_reg': 0, 'dist_url': 'env://', 'world_size': 1, 'rank': 0, 'local_rank': 0, 'checkpoint_freq': 30, 'umap_checkpoint_freq': 10, 'scib_freq': 10, 'save_scib': 1, 'use_fp16': False, 'sync_bn': 'pytorch', 'syncbn_process_group_size': 8, 'seed': 31, 'model': '', 'optimizer': '', 'lr_schedule': '', 'queue': None, 'train_loader': '', 'training_stats': '', 'device': 'cuda', 'prot_decoding_loss_scaler': 0.0, 'hidden_mlp': 1024, 'swav_dim': 64, 'use_projector': False, 'model_version': 1, 'train_decoder': False, 'longest_path': 1, 'dimensionality_reduction': 'pca', 'k_neighbors': 50, 'job_name': '', 'no_data': 'False', 'freezable_prototypes': 0, 'prot_init': 'kmeans', 'prot_emb_sim_reg': 0.0, 'loss_type': 'cross_entropy', 'decodable_prototypes': 0, 'save_temp_res': 1, 'temp_res_path': 'temp-res', 'n_components': 50, 'supervised_ratio': 0.1, 'multi_layer_protos': 0, 'batch_removal_ratio': 0.0, 'use_bknn': 0, 'freeze_batch_embedding': 0, 'batch_sinkhorn': 1, 'weighted_batch': 0, 'knn_similarity': 'cosine', 'recon_loss': 'mse', 'no_sinkhorn': 0, 'wandb_sweep': 0, 'sweep_id': -1, 'mask_probability': 0.2, 'default_dispersion': 0.1, 'fold': 0, 'spatial': 0, 'use_the_queue': 0, 'entropy_reg': 0.0, 'dataset_cnt': 0, 'study_id': '', 'l2norm': 1, 'use_rbf': 1, 'assignment_metric': 'dotp', 'pretraining_epochs': 100, 'fine_tuning_epochs': 0, 'cvae_epochs': 0, 'cvae_loss_scaler': 0.01, 'propagation_reg': 1, 'model_type': 'gm', 'workers': 1, 'wd': 1e-06, 'final_lr': 0, 'warmup_epochs': 10, 'start_warmup': 0, 'batch_size': 128, 'base_lr': 4.8, 'freeze_prototypes_nepochs': 20, 'hard_clustering': 0, 'temperature': 0.1, 'epsilon': 0.05, 'epoch_queue_starts': 0, 'queue_length': 0}
                                     partial_ref: None
                                     pretrain_dataset_id: hlca
                                     pretraining_epochs: 100
                                     propagation_reg: 1
                                     prot_decoding_loss_scaler: 0.0
                                     prot_emb_sim_reg: 0.0
                                     prot_init: kmeans
                                     query: pancreas
                                     query_latent: None
                                     queue: {}
                                     queue_length: 0
                                     rank: 0
                                     recon_loss: mse
                                     ref: pancreas
                                     ref_latent: None
                                     save_scib: 1
                                     save_temp_res: 1
                                     scib_freq: 10
                                     seed: 31
                                     sinkhorn_iterations: 3
                                     size_crops: [224]
                                     spatial: 0
                                     start_warmup: 0
                                     study_id:
                                     supervised_ratio: 0.1
                                     swav_dim: 64
                                     sweep_id: -1
                                     sync_bn: pytorch
                                     syncbn_process_group_size: 8
                                     temp_res_path: temp-res
                                     temperature: 0.1
                                     train_augmentation: knn
                                     train_decoder: False
                                     train_loader:
                                     training_stats:
                                     training_type: pretrain_encoder
                                     transfer_learning_mode: False
                                     umap_checkpoint_freq: 10
                                     use_bknn: 0
                                     use_early_stopping: False
                                     use_fp16: False
                                     use_projector: False
                                     use_projector_out: False
                                     use_rbf: 1
                                     use_the_queue: 0
                                     views_for_assign: [0, 1]
                                     wandb_sweep: 0
                                     warmup_epochs: 10
                                     wd: 1e-06
                                     weighted_batch: 0
                                     workers: 1
                                     world_size: 1
INFO - 09/05/25 14:01:31 - 0:00:00 - The experiment will be stored in /home/icb/fatemehs.hashemig/models//pancreas/corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs_128


INFO - 09/05/25 14:01:31 - 0:00:00 - initalizing prototypes using kmeans

Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

100%|██████████| 103/103 [00:01<00:00, 71.98it/s]
INFO - 09/05/25 14:01:33 - 0:00:02 - Building model done. with prot init kmeans
INFO - 09/05/25 14:01:34 - 0:00:03 - Building data done with 3230 samples loaded.
INFO - 09/05/25 14:01:34 - 0:00:03 - Building optimizer done.
INFO - 09/05/25 14:01:34 - 0:00:03 - no mixed precision

In [100]:
model = t.load_model()
z = t.encode_adata(adata, model)
adata.obsm[t.get_model_name()] = z.detach().cpu().numpy()

Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

100%|██████████| 128/128 [00:00<00:00, 299.71it/s]

In [101]:
save_metrics(adata, [t.get_model_name()], ds, bk, lk)

... storing 'conditions_combined' as categorical

Skipped cell type t_cell, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Computing neighbors: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 14:01:48 - 0:00:17 - isolated labels: no more than 4 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:05,  1.70it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:00<00:05,  1.70it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:09,  1.14s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:09,  1.14s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:02<00:06,  1.12it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:02<00:06,  1.12it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:02<00:05,  1.12it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:02<00:02,  2.27it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:02<00:02,  2.27it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:02<00:01,  2.27it/s, Batch correction: kbet_per_label]

INFO     t_cell consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:09<00:04,  1.62s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:09<00:04,  1.62s/it, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 1/1 [00:09<00:00,  9.15s/it]atch correction: pcr_comparison]

(                                                   Isolated labels KMeans NMI  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...        0.466922   0.728244
 X_scvi                                                    0.747434   0.755029
 seacell_pca                                                    0.5   0.625279
 seacell_pca_harmoney                                           0.5   0.749384
 X_pca                                                     0.662941    0.68413
 X_pca_harmoney                                            0.607937   0.831354

                                                    KMeans ARI  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...   0.470065
 X_scvi                                               0.495347
 seacell_pca                                          0.383839
 seacell_pca_harmoney                                 0.569488
 X_pca                                                0.473834
 X_pca_harmoney                                       0.831072

                                                    Silhouette label     cLISI  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.688101       1.0
 X_scvi                                                     0.629888       1.0
 seacell_pca                                                  0.5833  0.933285
 seacell_pca_harmoney                                       0.630511   0.96952
 X_pca                                                       0.54067       1.0
 X_pca_harmoney                                             0.608349       1.0

                                                    Silhouette batch     iLISI  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.824205  0.075737
 X_scvi                                                     0.859884   0.17507
 seacell_pca                                                0.701281   0.17771
 seacell_pca_harmoney                                       0.818407  0.376212
 X_pca                                                      0.831701   0.00043
 X_pca_harmoney                                              0.90136  0.233896

                                                         KBET  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...  0.204384
 X_scvi                                              0.318916
 seacell_pca                                         0.575758
 seacell_pca_harmoney                                0.852755
 X_pca                                               0.160427
 X_pca_harmoney                                       0.52573

                                                    Graph connectivity  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...           0.830931
 X_scvi                                                       0.931973
 seacell_pca                                                   0.77553
 seacell_pca_harmoney                                         0.827615
 X_pca                                                        0.719823
 X_pca_harmoney                                               0.882766

                                                    PCR comparison  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...       0.814429
 X_scvi                                                   0.670423
 seacell_pca                                                   0.0
 seacell_pca_harmoney                                     0.537683
 X_pca                                                         0.0
 X_pca_harmoney                                           0.859589

                                                    Batch correction  \
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.549937
 X_scvi                                                     0.591253
 seacell_pca                                                0.446056
 seacell_pca_harmoney                                       0.682534
 X_pca                                                      0.342476
 X_pca_harmoney                                             0.680668

                                                    Bio conservation     Total
 Embedding
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.670666  0.622375
 X_scvi                                                      0.72554  0.671825
 seacell_pca                                                0.605141  0.541507
 seacell_pca_harmoney                                        0.68378  0.683282
 X_pca                                                      0.672315   0.54038
 X_pca_harmoney                                             0.775742  0.737713  ,
                                                     Rank-PCA  Corr-PCA  \
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...  0.669484  0.803664
 X_scvi                                              0.532967  0.743138
 seacell_pca                                         0.943878  0.989190
 seacell_pca_harmoney                                0.913265  0.987165
 X_pca                                               0.915046  0.961659
 X_pca_harmoney                                      0.916314  0.970931

                                                     Corr-Weighted
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...       0.640737
 X_scvi                                                   0.469317
 seacell_pca                                              0.959352
 seacell_pca_harmoney                                     0.959283
 X_pca                                                    0.920961
 X_pca_harmoney                                           0.932270  )

# scpoli

In [102]:
from interpretable_ssl.trainers.scpoli_original import *

In [103]:
params = {
    "dataset_id": "pancreas",
    'experiment_name': 'scpoli-new'
}

t = OriginalTrainer(**params)

dataset is None, loading pancreas
loading pancreas data

INFO - 09/05/25 14:01:57 - 0:00:26 - Starting '__init__' of class 'get train test'
INFO - 09/05/25 14:01:57 - 0:00:26 - Finished '__init__' of class 'get train test' in 0.0054 seconds

done
tech
input data size:  13093
Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

In [104]:
model = t.load_model()

Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

In [105]:
t.condition_key = 'tech'

In [106]:
adata.obsm['X_scpoli'] = t.encode_adata(adata, model).detach().cpu().numpy()

Embedding dictionary:
 	Num conditions: [7]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

100%|██████████| 16/16 [00:00<00:00, 61.90it/s]

In [107]:
save_metrics(adata, ['X_scpoli'], ds, bk, lk)

... storing 'conditions_combined' as categorical

Skipped cell type t_cell, due to < 10 cells
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Computing neighbors: 100%|██████████| 1/1 [00:06<00:00,  6.95s/it]
Embeddings:   0%|          | 0/1 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s]
Metrics:   0%|          | 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels]INFO - 09/05/25 14:02:12 - 0:00:41 - isolated labels: no more than 4 batches per label

Metrics:  10%|█         | 1/10 [00:00<00:05,  1.76it/s, Bio conservation: isolated_labels]
Metrics:  10%|█         | 1/10 [00:00<00:05,  1.76it/s, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:09,  1.16s/it, Bio conservation: nmi_ari_cluster_labels_kmeans]
Metrics:  20%|██        | 2/10 [00:02<00:09,  1.16s/it, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:02<00:06,  1.12it/s, Bio conservation: silhouette_label]
Metrics:  30%|███       | 3/10 [00:02<00:06,  1.12it/s, Bio conservation: clisi_knn]
Metrics:  40%|████      | 4/10 [00:02<00:05,  1.12it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:02<00:02,  2.30it/s, Batch correction: silhouette_batch]
Metrics:  50%|█████     | 5/10 [00:02<00:02,  2.30it/s, Batch correction: ilisi_knn]
Metrics:  60%|██████    | 6/10 [00:02<00:01,  2.30it/s, Batch correction: kbet_per_label]

INFO     t_cell consists of a single batch or is too small. Skip.

Metrics:  70%|███████   | 7/10 [00:09<00:05,  1.67s/it, Batch correction: kbet_per_label]
Metrics:  70%|███████   | 7/10 [00:09<00:05,  1.67s/it, Batch correction: graph_connectivity]
Embeddings: 100%|██████████| 1/1 [00:09<00:00,  9.39s/it]atch correction: pcr_comparison]

(                                                   Isolated labels KMeans NMI  \
 Embedding
 X_scpoli                                                  0.648738   0.752577
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...        0.466922   0.728244
 X_scvi                                                    0.747434   0.755029
 seacell_pca                                                    0.5   0.625279
 seacell_pca_harmoney                                           0.5   0.749384
 X_pca                                                     0.662941    0.68413
 X_pca_harmoney                                            0.607937   0.831354

                                                    KMeans ARI  \
 Embedding
 X_scpoli                                              0.48712
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...   0.470065
 X_scvi                                               0.495347
 seacell_pca                                          0.383839
 seacell_pca_harmoney                                 0.569488
 X_pca                                                0.473834
 X_pca_harmoney                                       0.831072

                                                    Silhouette label     cLISI  \
 Embedding
 X_scpoli                                                   0.637264       1.0
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.688101       1.0
 X_scvi                                                     0.629888       1.0
 seacell_pca                                                  0.5833  0.933285
 seacell_pca_harmoney                                       0.630511   0.96952
 X_pca                                                       0.54067       1.0
 X_pca_harmoney                                             0.608349       1.0

                                                    Silhouette batch     iLISI  \
 Embedding
 X_scpoli                                                   0.857502   0.16696
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.824205  0.075737
 X_scvi                                                     0.859884   0.17507
 seacell_pca                                                0.701281   0.17771
 seacell_pca_harmoney                                       0.818407  0.376212
 X_pca                                                      0.831701   0.00043
 X_pca_harmoney                                              0.90136  0.233896

                                                         KBET  \
 Embedding
 X_scpoli                                            0.317765
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...  0.204384
 X_scvi                                              0.318916
 seacell_pca                                         0.575758
 seacell_pca_harmoney                                0.852755
 X_pca                                               0.160427
 X_pca_harmoney                                       0.52573

                                                    Graph connectivity  \
 Embedding
 X_scpoli                                                     0.948536
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...           0.830931
 X_scvi                                                       0.931973
 seacell_pca                                                   0.77553
 seacell_pca_harmoney                                         0.827615
 X_pca                                                        0.719823
 X_pca_harmoney                                               0.882766

                                                    PCR comparison  \
 Embedding
 X_scpoli                                                 0.744381
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...       0.814429
 X_scvi                                                   0.670423
 seacell_pca                                                   0.0
 seacell_pca_harmoney                                     0.537683
 X_pca                                                         0.0
 X_pca_harmoney                                           0.859589

                                                    Batch correction  \
 Embedding
 X_scpoli                                                   0.607029
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.549937
 X_scvi                                                     0.591253
 seacell_pca                                                0.446056
 seacell_pca_harmoney                                       0.682534
 X_pca                                                      0.342476
 X_pca_harmoney                                             0.680668

                                                    Bio conservation     Total
 Embedding
 X_scpoli                                                    0.70514  0.665895
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...         0.670666  0.622375
 X_scvi                                                      0.72554  0.671825
 seacell_pca                                                0.605141  0.541507
 seacell_pca_harmoney                                        0.68378  0.683282
 X_pca                                                      0.672315   0.54038
 X_pca_harmoney                                             0.775742  0.737713  ,
                                                     Rank-PCA  Corr-PCA  \
 X_scpoli                                            0.514793  0.736724
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...  0.669484  0.803664
 X_scvi                                              0.532967  0.743138
 seacell_pca                                         0.943878  0.989190
 seacell_pca_harmoney                                0.913265  0.987165
 X_pca                                               0.915046  0.961659
 X_pca_harmoney                                      0.916314  0.970931

                                                     Corr-Weighted
 X_scpoli                                                 0.461364
 corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_bs...       0.640737
 X_scvi                                                   0.469317
 seacell_pca                                              0.959352
 seacell_pca_harmoney                                     0.959283
 X_pca                                                    0.920961
 X_pca_harmoney                                           0.932270  )

In [108]:
df = pd.read_csv('~/models/pancreas/scib.csv')
df

,Embedding,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
0,X_scpoli,0.648738,0.752577,0.487120,0.637264,1.000000,0.857502,0.166960,0.317765,0.948536,7.443812e-01,0.607029,0.705140,0.665895
1,corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_b...,0.466922,0.728244,0.470065,0.688101,1.000000,0.824205,0.075737,0.204384,0.830931,8.144292e-01,0.549937,0.670666,0.622375
2,X_scvi,0.747434,0.755029,0.495347,0.629888,1.000000,0.859884,0.175070,0.318916,0.931973,6.704225e-01,0.591253,0.725540,0.671825
3,seacell_pca,0.500000,0.625279,0.383839,0.583300,0.933285,0.701281,0.177710,0.575758,0.775530,2.382798e-07,0.446056,0.605141,0.541507
4,seacell_pca_harmoney,0.500000,0.749384,0.569488,0.630511,0.969520,0.818407,0.376212,0.852755,0.827615,5.376830e-01,0.682534,0.683780,0.683282
5,X_pca,0.662941,0.684130,0.473834,0.540670,1.000000,0.831701,0.000430,0.160427,0.719823,0.000000e+00,0.342476,0.672315,0.540380
6,X_pca_harmoney,0.607937,0.831354,0.831072,0.608349,1.000000,0.901360,0.233896,0.525730,0.882766,8.595888e-01,0.680668,0.775742,0.737713

In [109]:
df = pd.read_csv('~/models/pancreas/scgraph.csv')
df

,Unnamed: 0,Rank-PCA,Corr-PCA,Corr-Weighted
0,X_scpoli,0.514793,0.736724,0.461364
1,corrected-ds_ds_panc_NP_220_cvae_0.01_prop_1_b...,0.669484,0.803664,0.640737
2,X_scvi,0.532967,0.743138,0.469317
3,seacell_pca,0.943878,0.989190,0.959352
4,seacell_pca_harmoney,0.913265,0.987165,0.959283
5,X_pca,0.915046,0.961659,0.920961
6,X_pca_harmoney,0.916314,0.970931,0.932270

# same for immune

In [123]:
p = '~/models/pbmc-immune/scgraph.csv'
pd.read_csv(p, index_col=0)

                      Rank-PCA  Corr-PCA  Corr-Weighted
seacell_pca           0.951515  0.987689       0.971995
seacell_pca_harmoney  0.967273  0.989317       0.978554
X_scvi                0.490257  0.660642       0.454720
X_pca                 0.664706  0.498572       0.356963
X_pca_harmoney        0.489522  0.652791       0.442865
scpoli                0.484007  0.662142       0.433064
t1_cvae_0.01_prop_1   0.556066  0.751401       0.533528

In [125]:
p = '~/models/pbmc-immune/scib.csv'
pd.read_csv(p, index_col=0)

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
X_scvi,0.603341,0.630693,0.396484,0.576507,0.994001,0.738550,1.173860e-02,0.210403,0.855577,0.559455,0.475145,0.640205,0.574181
X_pca,0.599962,0.587749,0.387142,0.536031,0.996539,0.728243,5.960464e-08,0.216919,0.640025,0.000000,0.317037,0.621485,0.499706
X_pca_harmoney,0.575475,0.688179,0.535855,0.568512,0.995544,0.825176,1.981992e-01,0.267034,0.630237,0.879787,0.560087,0.672713,0.627662
scpoli,0.586489,0.534954,0.352088,0.525205,0.978042,0.877507,3.834963e-01,0.458728,0.874263,0.953695,0.709538,0.595355,0.641028
t1_cvae_0.01_prop_1,0.598919,0.633081,0.343383,0.561711,0.994110,0.809191,2.313032e-01,0.253728,0.887752,0.930498,0.622494,0.626241,0.624742

## calculate scib for immune seacells, also re-calc scGraph