## Status (created 2026-08-04) -- READ BEFORE RUNNING

**This one trains.** GPU runtime required. Budget ~4 arms x 3 seeds = 12 Stage-2 runs on
pancreas.

Reviewer nG29 (round 3): *"variance in the ablations is reported across batches rather
than seeds, which makes deriving conclusions from these results difficult. [...]
Reporting variance over seeds and for all datasets would make these results clearer."*

**What a seed run answers that a batch run cannot.** Per-batch spread says how much
batches differ from each other. It cannot say whether an effect would survive a
different random initialisation. Those are different questions, and only re-training
answers the second one. (The first is answered without re-training by
`ablation_paired_significance.ipynb` -- run that one too; the two are complements, not
alternatives.)

**The arm that matters most is the one the reviewer did not ask for.** He named
`- nassoc` and `stop-gradient`. This notebook also runs `- community loss`, and that is
the point of the whole exercise: it is the largest effect in the ablation
(pancreas modularity .615 -> .449). Once seed spread is known, every arm gets a scale --
*"the community-loss drop is N times the seed noise"*. Without a large-effect arm in the
same run there is no yardstick and the seed numbers say nothing.

### Two deliberate choices

**Stage 1 is shared across seeds; only Stage 2 is re-seeded.** `seed` is not in
`PRETRAIN_PARAM_KEYS` (`adaptive_trainer.py:65`), so every arm resolves to the same
Stage-1 checkpoint. That is the correct scope here -- the ablation is about Stage-2
components, and every arm in the original ablation also shared one Stage-1. It is also
much faster.

**`cvae_epochs` stays at 50 -- do NOT lower it.** It is part of the Stage-1 checkpoint
name, so lowering it forces a *fresh Stage-1 pretrain for every run*, making the notebook
slower, not faster, and breaking comparability with the reported table. Only
`train_epochs` (Stage 2) is reduced.

**These numbers will not match the paper's table**, because Stage 2 is shortened. That is
fine and it is the point: every arm here runs at the *same* reduced setting, so
`full - ablated` and the seed spread are measured on the same footing and can be compared
to each other. Report this as a stability check, labelled as such -- not as a replacement
for the main ablation table.

Every finished (seed, arm) is written to `OUT_DIR` immediately, so a Colab disconnect
costs at most one run.

## Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install -q scarches faiss-gpu-cu12 scib-metrics
!pip install git+https://github.com/dpeerlab/SEACells.git --quiet --no-deps
!pip install numpy scipy --upgrade -q
!pip install -q palantir harmonypy
!pip install -q "numpy==1.26.4" "scipy==1.13.1"
!pip install --upgrade --force-reinstall numpy cupy-cuda12x
!pip install "numpy<2.3"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 57.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.5/187.5 kB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 139.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 118.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 133.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 158.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 112.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.2/711.2 kB 62.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 111.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/137.4 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 848.6/848.6 kB 61.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.9/155.9 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 69.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 37.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 61.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 158.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 68.9 MB/s eta 0:00:00
  Building wheel for docrep (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
ibis-framework 9.5.0 requires toolz<1,>=0.11, but you have toolz 1.1.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
  Preparing metadata (setup.py) ... done
  Building wheel for SEACells (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 117.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 83.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires palantir, which is not installed.
seacells 0.3.3 requires pyranges, which is not installed.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 116.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.4/172.4 kB 18.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 131.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 73.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
scanpy 1.12.3 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
fast-array-utils 1.5 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
zarr 3.3.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
faiss-gpu-cu12 1.14.1.post1 requires numpy<3,>=2, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires numpy>=2.1, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Collecting numpy
  Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting cupy-cuda12x
  Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (2.8 kB)
Collecting cuda-pathfinder==1.*,>=1.3.4 (from cupy-cuda12x)
  Downloading cuda_pathfinder-1.6.0-py3-none-any.whl.metadata (1.9 kB)
Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl (133.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 MB 20.1 MB/s eta 0:00:00
Downloading cuda_pathfinder-1.6.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 6.3 MB/s eta 0:00:00
Installing collected packages: numpy, cuda-pathfinder, cupy-cuda12x
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: cuda-pathfinder
    Found existing installation: cuda-pathfinder 1.5.6
    Uninstalling cuda-pathfinder-1.5.6:
      Successfully uninstalled cuda-pathfinder-1.5.6
  Attempting uninstall: cupy-cuda12x
    Found existing installation: cupy-cuda12x 14.0.1
    Uninstalling cupy-cuda12x-14.0.1:
      Successfully uninstalled cupy-cuda12x-14.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.5.1 which is incompatible.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed cuda-pathfinder-1.6.0 cupy-cuda12x-14.1.1 numpy-2.5.1

Collecting numpy<2.3
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.5 MB/s eta 0:00:00
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 131.7 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.1
    Uninstalling numpy-2.5.1:
      Successfully uninstalled numpy-2.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed numpy-2.2.6

In [ ]:
# Restart the runtime after the install cell above before running anything below --
# numpy/scipy/anndata are C-extension linked and an in-process upgrade won't take
# effect on already-imported modules.

In [1]:
_checks = {
    'numpy': 'numpy', 'scipy': 'scipy', 'anndata': 'anndata', 'scanpy': 'scanpy',
    'scarches': 'scarches', 'scvi-tools': 'scvi', 'torch': 'torch',
}
_failed = []
for pkg, imp in _checks.items():
    try:
        m = __import__(imp)
        print(f'  OK   {pkg:14s} {getattr(m, "__version__", "?")}')
    except Exception as e:
        _failed.append(pkg)
        print(f'  FAIL {pkg:14s} {type(e).__name__}: {e}')
print('\nall good' if not _failed else f'\nfailed: {_failed}')

import torch
print('cuda available:', torch.cuda.is_available(),
      '|', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU only')

  OK   numpy          2.2.6
  OK   scipy          1.13.1

/tmp/ipykernel_2064/654138299.py:9: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(f'  OK   {pkg:14s} {getattr(m, "__version__", "?")}')

  OK   anndata        0.13.2

/tmp/ipykernel_2064/654138299.py:9: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print(f'  OK   {pkg:14s} {getattr(m, "__version__", "?")}')

  OK   scanpy         1.12.3

WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).

  FAIL scarches       ImportError: cannot import name 'read' from 'anndata' (/usr/local/lib/python3.12/dist-packages/anndata/__init__.py)
  OK   scvi-tools     1.5.0.post1
  OK   torch          2.11.0+cu128

failed: ['scarches']
cuda available: True | NVIDIA A100-SXM4-40GB

In [2]:
%run /content/drive/MyDrive/codes/interpretable-prototype/notebooks/nb_setup.py

nb_setup done. Available: get_trainer, run_mc_task, fig_*, LAMBDA_PROTO_UMAP, LAMBDA_PROTO_UMAP_PRECON, LAMBDA_PARAM_UMAP, LAMBDA_RECON_ONLY, train_sure, eval_sure_task1/2/3
Configs: {'LAMBDA_PROTO_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'proto'}, 'LAMBDA_PARAM_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'embedding'}, 'LAMBDA_RECON_ONLY': {'lambda_umap': 0, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 1, 'lambda_proto_recon': 0.0}}

In [3]:
import os, json, time, traceback
import numpy as np
import pandas as pd

from interpretable_ssl.experiments.tasks import (
    run_ablation_variant, LAMBDA_PROTO_UMAP_PRECON,
)
from interpretable_ssl.configs.paths import get_dataset_model_dir

print('ready')

ready

## Config

The overrides below are read off `LAMBDA_PROTO_UMAP_PRECON` (`tasks.py:35`), the exact
Stage-2 objective the paper's runs use:

| arm | override | what it removes |
|---|---|---|
| `full` | -- | nothing (reference) |
| `no_community` | `lambda_umap=0` | the affinity/community loss -- **the yardstick arm** |
| `no_nassoc` | `lambda_nassoc=0` | nassoc (reviewer named this one) |
| `stopgrad_off` | `proto_recon_stopgrad=0` | the stop-gradient (reviewer named this one) |

`proto_recon_stopgrad` is read via `getattr(self, 'proto_recon_stopgrad', True)`
(`scproto.py:1460`) and reaches the trainer because `run_mc_task` forwards every
`lambda_config` key to `get_trainer` (`tasks.py:249`).

Seed 31 is first on purpose: it is the codebase default (`configs/defaults.py:47`), so
that arm is the closest thing to a re-run of the original ablation and acts as a sanity
check on the whole setup.

In [4]:
DS = 'pancreas'          # one dataset first -- extend below only if time allows
SEEDS = [31, 1, 2]       # 31 = codebase default, so it doubles as a sanity check

ARMS = {
    'full':         {},
    'no_community': {'lambda_umap': 0},
    'no_nassoc':    {'lambda_nassoc': 0},
    'stopgrad_off': {'proto_recon_stopgrad': 0},
}
ARM_DISPLAY = {
    'full':         'Full model',
    'no_community': '- community loss',
    'no_nassoc':    '- nassoc',
    'stopgrad_off': 'Stop-grad off',
}

# cvae_epochs MUST stay 50 -- it names the shared Stage-1 checkpoint (see intro).
# train_epochs is the only thing reduced.
COMMON = dict(
    cvae_epochs=50,
    train_epochs=20,
    eval_freq=1,
    patience=5,
    batch_size=1024,
)

OUT_DIR = '/content/drive/MyDrive/rebuttal_results/ablation_seeds/'
os.makedirs(OUT_DIR, exist_ok=True)

SKIP_IF_DONE = True   # a (ds, seed, arm) whose record already exists is not re-run

print(f'{len(SEEDS)} seeds x {len(ARMS)} arms = {len(SEEDS) * len(ARMS)} runs on {DS}')
print('OUT_DIR:', OUT_DIR)

3 seeds x 4 arms = 12 runs on pancreas
OUT_DIR: /content/drive/MyDrive/rebuttal_results/ablation_seeds/

## Runner

Two layers of resume, because a Colab session dying mid-sweep is the normal case:

1. **Record level** -- if `OUT_DIR/{ds}__s{seed}__{arm}.json` exists, the run is skipped
   entirely (no reload, no re-eval).
2. **Checkpoint level** -- `run_ablation_variant(load_umap=None)` auto-detects a saved
   Stage-2 checkpoint for that exact `experiment_name` and reloads instead of retraining
   (`tasks.py:434`). So even a record deleted by hand costs only re-evaluation.

`experiment_prefix=f'seedabl_s{seed}'` is what keeps the seeds apart on disk. It has to
be the prefix, because `seed` does not appear anywhere in the model-name builder -- two
seeds run under the same prefix would resolve to the same folder and silently overwrite
each other.

The per-batch modularity vector is copied into the record as well as the scalar mean, so
the paired-test notebook can be pointed at these runs too without re-reading the model
dir.

In [5]:
def record_path(ds, seed, arm):
    return os.path.join(OUT_DIR, f'{ds}__s{seed}__{arm}.json')


def _per_batch_modularity(ds, seed, arm):
    """Copy modularity_per_batch.csv out of this run's folder into the record."""
    base = get_dataset_model_dir(ds)
    prefix = f'seedabl_s{seed}_{arm}_'
    cands = [e for e in sorted(os.listdir(base)) if e.startswith(prefix)] if os.path.isdir(base) else []
    for e in reversed(cands):
        p = os.path.join(base, e, 'modularity_per_batch.csv')
        if os.path.exists(p):
            df = pd.read_csv(p, index_col=0)
            num = df.select_dtypes(include=[np.number])
            if num.shape[1]:
                s = num.iloc[:, 0].astype(float)
                return {'batches': [str(i) for i in s.index], 'values': [float(v) for v in s.values]}
    return None


def run_one(ds, seed, arm, force=False):
    path = record_path(ds, seed, arm)
    if SKIP_IF_DONE and not force and os.path.exists(path):
        print(f'  [{ds} s{seed} {arm}] record exists -- skipped')
        with open(path) as f:
            return json.load(f)

    overrides = dict(ARMS[arm])
    overrides['seed'] = seed      # -> get_trainer -> fix_random_seeds(self.seed)

    t0 = time.time()
    try:
        _, res, _ = run_ablation_variant(
            ds, arm, overrides,
            base_lambda_config=LAMBDA_PROTO_UMAP_PRECON,
            common_kwargs=COMMON,
            variant_display_names=ARM_DISPLAY,
            load_umap=None,                       # auto: reload checkpoint if present
            experiment_prefix=f'seedabl_s{seed}',  # keeps seeds in separate folders
        )
    except Exception:
        print(f'  [{ds} s{seed} {arm}] FAILED after {time.time() - t0:.0f}s')
        traceback.print_exc()
        return None

    rec = {'dataset': ds, 'seed': seed, 'arm': arm,
           'elapsed_s': round(time.time() - t0, 1),
           'metrics': {k: v for k, v in res.items() if isinstance(v, (int, float, type(None)))},
           'modularity_per_batch': _per_batch_modularity(ds, seed, arm)}

    with open(path, 'w') as f:
        json.dump(rec, f, indent=2)
    print(f'  [{ds} s{seed} {arm}] done in {rec["elapsed_s"]}s -> {path}')
    return rec

print('runner ready')

runner ready

## Run: Pancreas

Arm-major, not seed-major: all seeds of `full` finish before `no_community` starts. If
the session dies halfway you have complete seed spread for the arms that ran, instead of
one incomplete seed of everything.

In [6]:
records = []
for arm in ARMS:
    for seed in SEEDS:
        r = run_one(DS, seed, arm)
        if r:
            records.append(r)

print(f'\n{len(records)}/{len(ARMS) * len(SEEDS)} runs available')

=== [pancreas] ablation variant: full (Full model) ===  [training fresh]

WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2677.41proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=82.4  top5_share=13.1%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3397 unreachable (max E[q_pos]=0.3249), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0497 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3297

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3297, coverage=1.0000 (14/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 1/~20 | loss=26.7569 | q+=0.475 | q-=0.056 | margin=0.419 | effk=1.8 | unused_proto=0 | bentropy=1.341 | proto_recon=2386.0534 | nassoc=0.7446 [diag=0.176 offdiag=0.005] | proto_usage=7.8937

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6896

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 217/220 used (98.6%)  effective_n=27.4  top5_share=31.6%  community-preservation(mean neighbor agreement)=0.719
  [Early stop] modularity improved to 0.6896 (+0.3599), coverage=1.0000 (14/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.10it/s]

>>> Epoch 2/~20 | loss=26.1628 | q+=0.531 | q-=0.053 | margin=0.479 | effk=1.6 | unused_proto=0 | bentropy=1.062 | proto_recon=2363.3249 | nassoc=0.7087 [diag=0.209 offdiag=0.004] | proto_usage=6.0937

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6860

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 217/220 used (98.6%)  effective_n=31.3  top5_share=28.9%  community-preservation(mean neighbor agreement)=0.712
  [Early stop] No improvement (0.6860 vs best 0.6896, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.26it/s]

>>> Epoch 3/~20 | loss=25.9928 | q+=0.539 | q-=0.050 | margin=0.489 | effk=1.5 | unused_proto=0 | bentropy=0.986 | proto_recon=2357.9381 | nassoc=0.6919 [diag=0.222 offdiag=0.004] | proto_usage=5.4167

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6839

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=33.2  top5_share=27.9%  community-preservation(mean neighbor agreement)=0.709
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6839 vs best 0.6896, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.22it/s]

>>> Epoch 4/~20 | loss=25.8908 | q+=0.538 | q-=0.049 | margin=0.489 | effk=1.5 | unused_proto=0 | bentropy=0.943 | proto_recon=2354.3419 | nassoc=0.6779 [diag=0.232 offdiag=0.004] | proto_usage=4.9825

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6773

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=35.1  top5_share=27.5%  community-preservation(mean neighbor agreement)=0.701
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6773 vs best 0.6896, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.26it/s]

>>> Epoch 5/~20 | loss=25.8254 | q+=0.539 | q-=0.048 | margin=0.491 | effk=1.5 | unused_proto=0 | bentropy=0.901 | proto_recon=2353.2866 | nassoc=0.6634 [diag=0.243 offdiag=0.004] | proto_usage=4.6671

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6801

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=36.5  top5_share=26.7%  community-preservation(mean neighbor agreement)=0.703
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6801 vs best 0.6896, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.25it/s]

>>> Epoch 6/~20 | loss=25.7739 | q+=0.540 | q-=0.047 | margin=0.493 | effk=1.5 | unused_proto=0 | bentropy=0.874 | proto_recon=2351.5959 | nassoc=0.6552 [diag=0.249 offdiag=0.004] | proto_usage=4.4786

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6762

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=36.3  top5_share=27.2%  community-preservation(mean neighbor agreement)=0.699
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6762 vs best 0.6896, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 6.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 3/220 (1.36%)
[proto] mean cell-type purity: 0.9113  (size-weighted: 0.9711 ± 0.0847)
[proto] mean batch entropy: 0.4345  (size-weighted: 1.0559 ± 0.5650)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6896
[proto] per-batch modularity: mean=0.6159, std=0.0756

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_7462a98d.h5ad
[task2] coverage: 1.0000
[task2] dge_rbo_avg: 0.1797
[task2] dge_kendall_avg: 0.1927
[task2] dge_jaccard_avg: 0.2285
[task2] scgraph_corr_avg: 0.9182
[task2] scgraph_corr_std: 0.0459
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.3524 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s31 full] done in 599.9s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s31__full.json

=== [pancreas] ablation variant: full (Full model) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2606.64proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=80.9  top5_share=14.0%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3399 unreachable (max E[q_pos]=0.3196), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0498 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3217

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3217, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.96it/s]

>>> Epoch 1/~20 | loss=26.7073 | q+=0.453 | q-=0.056 | margin=0.397 | effk=2.0 | unused_proto=0 | bentropy=1.372 | proto_recon=2384.7501 | nassoc=0.7267 [diag=0.186 offdiag=0.005] | proto_usage=7.4151

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7011

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 216/220 used (98.2%)  effective_n=33.2  top5_share=27.1%  community-preservation(mean neighbor agreement)=0.723
  [Early stop] modularity improved to 0.7011 (+0.3793), coverage=1.0000 (14/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.97it/s]

>>> Epoch 2/~20 | loss=26.0810 | q+=0.524 | q-=0.054 | margin=0.469 | effk=1.6 | unused_proto=0 | bentropy=1.126 | proto_recon=2362.5922 | nassoc=0.6853 [diag=0.224 offdiag=0.005] | proto_usage=5.4689

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6798

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=37.8  top5_share=24.9%  community-preservation(mean neighbor agreement)=0.701
  [Early stop] No improvement (0.6798 vs best 0.7011, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.90it/s]

>>> Epoch 3/~20 | loss=25.9105 | q+=0.529 | q-=0.051 | margin=0.478 | effk=1.6 | unused_proto=0 | bentropy=1.038 | proto_recon=2357.6721 | nassoc=0.6626 [diag=0.241 offdiag=0.004] | proto_usage=4.8038

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6768

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=41.0  top5_share=22.6%  community-preservation(mean neighbor agreement)=0.695
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6768 vs best 0.7011, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.14it/s]

>>> Epoch 4/~20 | loss=25.8222 | q+=0.535 | q-=0.049 | margin=0.485 | effk=1.5 | unused_proto=0 | bentropy=0.994 | proto_recon=2354.7928 | nassoc=0.6516 [diag=0.249 offdiag=0.004] | proto_usage=4.4672

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6737

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=41.9  top5_share=22.6%  community-preservation(mean neighbor agreement)=0.693
  [Early stop] No improvement (0.6737 vs best 0.7011, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.03it/s]

>>> Epoch 5/~20 | loss=25.7596 | q+=0.535 | q-=0.048 | margin=0.487 | effk=1.5 | unused_proto=0 | bentropy=0.967 | proto_recon=2351.9389 | nassoc=0.6442 [diag=0.254 offdiag=0.004] | proto_usage=4.2801

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6691

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=42.1  top5_share=23.0%  community-preservation(mean neighbor agreement)=0.688
  [Early stop] No improvement (0.6691 vs best 0.7011, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.09it/s]

>>> Epoch 6/~20 | loss=25.7107 | q+=0.534 | q-=0.047 | margin=0.487 | effk=1.5 | unused_proto=0 | bentropy=0.946 | proto_recon=2350.2434 | nassoc=0.6369 [diag=0.259 offdiag=0.004] | proto_usage=4.0842

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6685

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=43.7  top5_share=22.5%  community-preservation(mean neighbor agreement)=0.687
  [Early stop] No improvement (0.6685 vs best 0.7011, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 6.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 4/220 (1.82%)
[proto] mean cell-type purity: 0.9224  (size-weighted: 0.9805 ± 0.0503)
[proto] mean batch entropy: 0.4456  (size-weighted: 0.9311 ± 0.5075)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7011
[proto] per-batch modularity: mean=0.6138, std=0.0777

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_761bcaf1.h5ad
[task2] coverage: 1.0000
[task2] dge_rbo_avg: 0.1934
[task2] dge_kendall_avg: 0.2045
[task2] dge_jaccard_avg: 0.2354
[task2] scgraph_corr_avg: 0.9011
[task2] scgraph_corr_std: 0.0299
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.4501 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s1 full] done in 545.7s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s1__full.json

=== [pancreas] ablation variant: full (Full model) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2628.27proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=76.6  top5_share=16.0%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3378 unreachable (max E[q_pos]=0.3223), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0508 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3266

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3266, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.04it/s]

>>> Epoch 1/~20 | loss=26.6814 | q+=0.462 | q-=0.055 | margin=0.407 | effk=1.9 | unused_proto=0 | bentropy=1.249 | proto_recon=2383.2264 | nassoc=0.7305 [diag=0.184 offdiag=0.005] | proto_usage=7.4842

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6979

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 218/220 used (99.1%)  effective_n=33.4  top5_share=26.7%  community-preservation(mean neighbor agreement)=0.720
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6979 (+0.3713), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.09it/s]

>>> Epoch 2/~20 | loss=26.0881 | q+=0.530 | q-=0.053 | margin=0.477 | effk=1.6 | unused_proto=0 | bentropy=0.977 | proto_recon=2362.1300 | nassoc=0.6950 [diag=0.218 offdiag=0.004] | proto_usage=5.7086

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6895

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=35.8  top5_share=25.5%  community-preservation(mean neighbor agreement)=0.711
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6895 vs best 0.6979, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.08it/s]

>>> Epoch 3/~20 | loss=25.9146 | q+=0.535 | q-=0.050 | margin=0.485 | effk=1.5 | unused_proto=0 | bentropy=0.893 | proto_recon=2357.1304 | nassoc=0.6731 [diag=0.235 offdiag=0.004] | proto_usage=4.9628

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6768

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=37.9  top5_share=25.3%  community-preservation(mean neighbor agreement)=0.697
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6768 vs best 0.6979, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.05it/s]

>>> Epoch 4/~20 | loss=25.8107 | q+=0.537 | q-=0.049 | margin=0.488 | effk=1.5 | unused_proto=0 | bentropy=0.839 | proto_recon=2353.6141 | nassoc=0.6571 [diag=0.247 offdiag=0.004] | proto_usage=4.5618

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6743

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=39.6  top5_share=24.4%  community-preservation(mean neighbor agreement)=0.694
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6743 vs best 0.6979, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.05it/s]

>>> Epoch 5/~20 | loss=25.7555 | q+=0.538 | q-=0.048 | margin=0.490 | effk=1.5 | unused_proto=0 | bentropy=0.806 | proto_recon=2352.3152 | nassoc=0.6479 [diag=0.254 offdiag=0.004] | proto_usage=4.2947

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6722

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=39.9  top5_share=24.4%  community-preservation(mean neighbor agreement)=0.692
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6722 vs best 0.6979, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.03it/s]

>>> Epoch 6/~20 | loss=25.7086 | q+=0.538 | q-=0.047 | margin=0.491 | effk=1.5 | unused_proto=0 | bentropy=0.780 | proto_recon=2350.9545 | nassoc=0.6392 [diag=0.260 offdiag=0.004] | proto_usage=4.0931

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6702

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=39.6  top5_share=25.3%  community-preservation(mean neighbor agreement)=0.690
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6702 vs best 0.6979, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 6.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 2/220 (0.91%)
[proto] mean cell-type purity: 0.9146  (size-weighted: 0.9781 ± 0.0577)
[proto] mean batch entropy: 0.3768  (size-weighted: 0.9809 ± 0.5685)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6979
[proto] per-batch modularity: mean=0.6215, std=0.0759

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_187c40b8.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.1801
[task2] dge_kendall_avg: 0.2028
[task2] dge_jaccard_avg: 0.2389
[task2] scgraph_corr_avg: 0.9026
[task2] scgraph_corr_std: 0.0622
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.5359 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_full_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s2 full] done in 545.4s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s2__full.json

=== [pancreas] ablation variant: no_community (- community loss) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2619.38proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=90.4  top5_share=13.4%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3397 unreachable (max E[q_pos]=0.3143), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0485 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3104

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3104, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.05it/s]

>>> Epoch 1/~20 | loss=24.4816 | q+=0.220 | q-=0.015 | margin=0.205 | effk=2.6 | unused_proto=0 | bentropy=1.349 | proto_recon=2373.5407 | nassoc=0.5309 [diag=0.297 offdiag=0.011] | proto_usage=2.1532

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3954

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=180.1  top5_share=5.8%  community-preservation(mean neighbor agreement)=0.402
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.3954 (+0.0850), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.97it/s]

>>> Epoch 2/~20 | loss=23.9920 | q+=0.312 | q-=0.017 | margin=0.295 | effk=1.7 | unused_proto=0 | bentropy=1.043 | proto_recon=2349.7667 | nassoc=0.4089 [diag=0.399 offdiag=0.010] | proto_usage=0.8543

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4344

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=184.9  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.443
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4344 (+0.0390), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.04it/s]

>>> Epoch 3/~20 | loss=23.9232 | q+=0.352 | q-=0.017 | margin=0.335 | effk=1.4 | unused_proto=0 | bentropy=0.932 | proto_recon=2349.0965 | nassoc=0.3683 [diag=0.438 offdiag=0.009] | proto_usage=0.6397

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4525

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=185.5  top5_share=5.7%  community-preservation(mean neighbor agreement)=0.462
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4525 (+0.0181), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.02it/s]

>>> Epoch 4/~20 | loss=23.8984 | q+=0.373 | q-=0.018 | margin=0.356 | effk=1.3 | unused_proto=0 | bentropy=0.871 | proto_recon=2349.2837 | nassoc=0.3497 [diag=0.457 offdiag=0.009] | proto_usage=0.5594

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4620

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=185.4  top5_share=5.7%  community-preservation(mean neighbor agreement)=0.472
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4620 (+0.0095), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 4)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.99it/s]

>>> Epoch 5/~20 | loss=23.8901 | q+=0.389 | q-=0.018 | margin=0.371 | effk=1.3 | unused_proto=0 | bentropy=0.832 | proto_recon=2350.0992 | nassoc=0.3382 [diag=0.469 offdiag=0.008] | proto_usage=0.5099

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4690

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=185.9  top5_share=5.7%  community-preservation(mean neighbor agreement)=0.480
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4690 (+0.0071), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 5)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.98it/s]

>>> Epoch 6/~20 | loss=23.8740 | q+=0.398 | q-=0.018 | margin=0.380 | effk=1.2 | unused_proto=0 | bentropy=0.807 | proto_recon=2349.7919 | nassoc=0.3283 [diag=0.480 offdiag=0.008] | proto_usage=0.4776

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4727

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=186.5  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.484
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4727 vs best 0.4690, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:12<00:00, 13.86it/s]

>>> Epoch 7/~20 | loss=23.8703 | q+=0.405 | q-=0.018 | margin=0.387 | effk=1.2 | unused_proto=0 | bentropy=0.787 | proto_recon=2350.0322 | nassoc=0.3246 [diag=0.484 offdiag=0.008] | proto_usage=0.4543

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4758

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=186.4  top5_share=5.7%  community-preservation(mean neighbor agreement)=0.487
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4758 (+0.0068), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 7)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.07it/s]

>>> Epoch 8/~20 | loss=23.8693 | q+=0.411 | q-=0.018 | margin=0.393 | effk=1.2 | unused_proto=0 | bentropy=0.771 | proto_recon=2350.6278 | nassoc=0.3194 [diag=0.490 offdiag=0.008] | proto_usage=0.4362

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4768

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=186.7  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.488
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4768 vs best 0.4758, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.01it/s]

>>> Epoch 9/~20 | loss=23.8560 | q+=0.414 | q-=0.018 | margin=0.397 | effk=1.2 | unused_proto=0 | bentropy=0.763 | proto_recon=2349.7834 | nassoc=0.3161 [diag=0.493 offdiag=0.008] | proto_usage=0.4214

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4790

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.1  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.491
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4790 vs best 0.4758, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.01it/s]

>>> Epoch 10/~20 | loss=23.8490 | q+=0.418 | q-=0.018 | margin=0.400 | effk=1.2 | unused_proto=0 | bentropy=0.753 | proto_recon=2349.5816 | nassoc=0.3124 [diag=0.498 offdiag=0.008] | proto_usage=0.4087

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4809

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.3  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.493
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4809 (+0.0051), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 10)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.01it/s]

>>> Epoch 11/~20 | loss=23.8444 | q+=0.421 | q-=0.018 | margin=0.403 | effk=1.2 | unused_proto=0 | bentropy=0.745 | proto_recon=2349.2425 | nassoc=0.3120 [diag=0.498 offdiag=0.008] | proto_usage=0.3998

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4812

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.4  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.493
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4812 vs best 0.4809, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 12/~20 | loss=23.8387 | q+=0.424 | q-=0.018 | margin=0.406 | effk=1.2 | unused_proto=0 | bentropy=0.738 | proto_recon=2349.0595 | nassoc=0.3089 [diag=0.502 offdiag=0.008] | proto_usage=0.3915

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4833

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.5  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.495
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4833 vs best 0.4809, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.10it/s]

>>> Epoch 13/~20 | loss=23.8470 | q+=0.426 | q-=0.018 | margin=0.407 | effk=1.2 | unused_proto=0 | bentropy=0.732 | proto_recon=2350.0617 | nassoc=0.3080 [diag=0.503 offdiag=0.008] | proto_usage=0.3844

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4839

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.7  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.496
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4839 vs best 0.4809, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 14/~20 | loss=23.8253 | q+=0.427 | q-=0.018 | margin=0.409 | effk=1.2 | unused_proto=0 | bentropy=0.727 | proto_recon=2348.0495 | nassoc=0.3069 [diag=0.504 offdiag=0.008] | proto_usage=0.3787

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4839

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.7  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.496
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4839 vs best 0.4809, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.07it/s]

>>> Epoch 15/~20 | loss=23.8286 | q+=0.429 | q-=0.018 | margin=0.411 | effk=1.2 | unused_proto=0 | bentropy=0.721 | proto_recon=2348.5699 | nassoc=0.3057 [diag=0.506 offdiag=0.008] | proto_usage=0.3721

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4859

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.6  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.498
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4859 (+0.0050), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 15)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.99it/s]

>>> Epoch 16/~20 | loss=23.8247 | q+=0.431 | q-=0.018 | margin=0.413 | effk=1.1 | unused_proto=0 | bentropy=0.715 | proto_recon=2348.4114 | nassoc=0.3038 [diag=0.508 offdiag=0.008] | proto_usage=0.3672

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4862

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.8  top5_share=5.5%  community-preservation(mean neighbor agreement)=0.498
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4862 vs best 0.4859, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.08it/s]

>>> Epoch 17/~20 | loss=23.8251 | q+=0.432 | q-=0.018 | margin=0.414 | effk=1.1 | unused_proto=0 | bentropy=0.712 | proto_recon=2348.4963 | nassoc=0.3036 [diag=0.508 offdiag=0.008] | proto_usage=0.3647

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4865

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.8  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.499
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4865 vs best 0.4859, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:10<00:00, 14.11it/s]

>>> Epoch 18/~20 | loss=23.8178 | q+=0.434 | q-=0.018 | margin=0.415 | effk=1.1 | unused_proto=0 | bentropy=0.707 | proto_recon=2347.9639 | nassoc=0.3022 [diag=0.509 offdiag=0.008] | proto_usage=0.3598

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4877

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.8  top5_share=5.5%  community-preservation(mean neighbor agreement)=0.500
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4877 vs best 0.4859, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.08it/s]

>>> Epoch 19/~20 | loss=23.8236 | q+=0.434 | q-=0.018 | margin=0.416 | effk=1.1 | unused_proto=0 | bentropy=0.703 | proto_recon=2348.6498 | nassoc=0.3012 [diag=0.510 offdiag=0.007] | proto_usage=0.3594

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4886

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=187.8  top5_share=5.6%  community-preservation(mean neighbor agreement)=0.501
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4886 vs best 0.4859, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 20/~20 | loss=23.8150 | q+=0.437 | q-=0.018 | margin=0.418 | effk=1.1 | unused_proto=0 | bentropy=0.700 | proto_recon=2347.9776 | nassoc=0.2997 [diag=0.512 offdiag=0.007] | proto_usage=0.3549
[Early stop] Reached max_epochs=20. Saving checkpoint.
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 20)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 20)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9549  (size-weighted: 0.9649 ± 0.0899)
[proto] mean batch entropy: 0.4784  (size-weighted: 0.4417 ± 0.4723)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4889
[proto] per-batch modularity: mean=0.4446, std=0.0473

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_67eb8559.h5ad
[task2] coverage: 0.8571
[task2] dge_rbo_avg: 0.1822
[task2] dge_kendall_avg: 0.1567
[task2] dge_jaccard_avg: 0.2201
[task2] scgraph_corr_avg: 0.9351
[task2] scgraph_corr_std: 0.0315
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.2165 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s31 no_community] done in 1643.6s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s31__no_community.json

=== [pancreas] ablation variant: no_community (- community loss) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2647.61proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=68.5  top5_share=18.0%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3399 unreachable (max E[q_pos]=0.3325), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0497 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3370

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3370, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.07it/s]

>>> Epoch 1/~20 | loss=24.4811 | q+=0.231 | q-=0.019 | margin=0.213 | effk=2.6 | unused_proto=0 | bentropy=1.362 | proto_recon=2369.1620 | nassoc=0.5403 [diag=0.290 offdiag=0.011] | proto_usage=2.4914

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4215

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=147.2  top5_share=8.2%  community-preservation(mean neighbor agreement)=0.426
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4215 (+0.0845), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 2/~20 | loss=24.0132 | q+=0.329 | q-=0.022 | margin=0.306 | effk=1.7 | unused_proto=0 | bentropy=1.039 | proto_recon=2348.5602 | nassoc=0.4190 [diag=0.391 offdiag=0.009] | proto_usage=1.0860

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4605

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=149.8  top5_share=8.2%  community-preservation(mean neighbor agreement)=0.467
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4605 (+0.0389), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.00it/s]

>>> Epoch 3/~20 | loss=23.9462 | q+=0.371 | q-=0.024 | margin=0.347 | effk=1.5 | unused_proto=0 | bentropy=0.919 | proto_recon=2348.2762 | nassoc=0.3828 [diag=0.427 offdiag=0.009] | proto_usage=0.8061

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4784

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=150.7  top5_share=8.2%  community-preservation(mean neighbor agreement)=0.486
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4784 (+0.0179), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.07it/s]

>>> Epoch 4/~20 | loss=23.9212 | q+=0.395 | q-=0.024 | margin=0.370 | effk=1.4 | unused_proto=0 | bentropy=0.852 | proto_recon=2348.9086 | nassoc=0.3631 [diag=0.446 offdiag=0.008] | proto_usage=0.6900

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4910

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=152.0  top5_share=8.1%  community-preservation(mean neighbor agreement)=0.499
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4910 (+0.0126), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 4)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 5/~20 | loss=23.8989 | q+=0.410 | q-=0.025 | margin=0.386 | effk=1.3 | unused_proto=0 | bentropy=0.816 | proto_recon=2348.3958 | nassoc=0.3518 [diag=0.458 offdiag=0.008] | proto_usage=0.6311

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4968

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=153.1  top5_share=8.0%  community-preservation(mean neighbor agreement)=0.505
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4968 (+0.0058), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 5)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.04it/s]

>>> Epoch 6/~20 | loss=23.8873 | q+=0.421 | q-=0.025 | margin=0.396 | effk=1.3 | unused_proto=0 | bentropy=0.792 | proto_recon=2348.3188 | nassoc=0.3448 [diag=0.466 offdiag=0.008] | proto_usage=0.5928

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4999

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=153.6  top5_share=8.0%  community-preservation(mean neighbor agreement)=0.508
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.4999 vs best 0.4968, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.94it/s]

>>> Epoch 7/~20 | loss=23.8798 | q+=0.428 | q-=0.025 | margin=0.403 | effk=1.2 | unused_proto=0 | bentropy=0.772 | proto_recon=2348.3904 | nassoc=0.3393 [diag=0.472 offdiag=0.008] | proto_usage=0.5665

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5032

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=153.9  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.512
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.5032 (+0.0064), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 7)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.00it/s]

>>> Epoch 8/~20 | loss=23.8774 | q+=0.433 | q-=0.025 | margin=0.408 | effk=1.2 | unused_proto=0 | bentropy=0.759 | proto_recon=2348.5880 | nassoc=0.3366 [diag=0.475 offdiag=0.008] | proto_usage=0.5489

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5061

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=154.3  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.515
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.5061 vs best 0.5032, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.08it/s]

>>> Epoch 9/~20 | loss=23.8667 | q+=0.438 | q-=0.025 | margin=0.412 | effk=1.2 | unused_proto=0 | bentropy=0.748 | proto_recon=2348.0866 | nassoc=0.3327 [diag=0.479 offdiag=0.008] | proto_usage=0.5316

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5069

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=154.2  top5_share=8.0%  community-preservation(mean neighbor agreement)=0.516
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.5069 vs best 0.5032, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 10/~20 | loss=23.8661 | q+=0.442 | q-=0.025 | margin=0.416 | effk=1.2 | unused_proto=0 | bentropy=0.737 | proto_recon=2348.4548 | nassoc=0.3302 [diag=0.482 offdiag=0.008] | proto_usage=0.5139

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5094

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=154.4  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.518
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.5094 (+0.0063), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 10)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.03it/s]

>>> Epoch 11/~20 | loss=23.8744 | q+=0.445 | q-=0.025 | margin=0.419 | effk=1.2 | unused_proto=0 | bentropy=0.728 | proto_recon=2349.6273 | nassoc=0.3281 [diag=0.484 offdiag=0.008] | proto_usage=0.5006

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5101

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=154.8  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.519
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.5101 vs best 0.5094, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.06it/s]

>>> Epoch 12/~20 | loss=23.8558 | q+=0.446 | q-=0.025 | margin=0.421 | effk=1.2 | unused_proto=0 | bentropy=0.721 | proto_recon=2348.0440 | nassoc=0.3263 [diag=0.486 offdiag=0.007] | proto_usage=0.4903

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5114

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=155.1  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.521
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5114 vs best 0.5094, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.59it/s]

>>> Epoch 13/~20 | loss=23.8565 | q+=0.449 | q-=0.026 | margin=0.423 | effk=1.2 | unused_proto=0 | bentropy=0.715 | proto_recon=2348.3669 | nassoc=0.3247 [diag=0.488 offdiag=0.007] | proto_usage=0.4808

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5121

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=155.3  top5_share=7.8%  community-preservation(mean neighbor agreement)=0.521
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5121 vs best 0.5094, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.69it/s]

>>> Epoch 14/~20 | loss=23.8526 | q+=0.451 | q-=0.025 | margin=0.425 | effk=1.2 | unused_proto=0 | bentropy=0.708 | proto_recon=2348.2072 | nassoc=0.3236 [diag=0.489 offdiag=0.007] | proto_usage=0.4702

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5127

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=155.6  top5_share=7.8%  community-preservation(mean neighbor agreement)=0.522
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.5127 vs best 0.5094, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.61it/s]

>>> Epoch 15/~20 | loss=23.8423 | q+=0.452 | q-=0.025 | margin=0.426 | effk=1.2 | unused_proto=0 | bentropy=0.704 | proto_recon=2347.3955 | nassoc=0.3218 [diag=0.491 offdiag=0.007] | proto_usage=0.4655

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5136

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=155.5  top5_share=7.9%  community-preservation(mean neighbor agreement)=0.523
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5136 vs best 0.5094, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 15.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 10)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9560  (size-weighted: 0.9694 ± 0.0660)
[proto] mean batch entropy: 0.4685  (size-weighted: 0.4485 ± 0.4378)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5094
[proto] per-batch modularity: mean=0.4578, std=0.0418

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_55d0af8d.h5ad
[task2] coverage: 0.7857
[task2] dge_rbo_avg: 0.2151
[task2] dge_kendall_avg: 0.1979
[task2] dge_jaccard_avg: 0.2163
[task2] scgraph_corr_avg: 0.9456
[task2] scgraph_corr_std: 0.0256
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.2220 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s1 no_community] done in 1263.7s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s1__no_community.json

=== [pancreas] ablation variant: no_community (- community loss) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2595.64proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=89.4  top5_share=11.7%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3378 unreachable (max E[q_pos]=0.2975), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0486 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3075

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3075, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.50it/s]

>>> Epoch 1/~20 | loss=24.4999 | q+=0.234 | q-=0.018 | margin=0.216 | effk=2.6 | unused_proto=0 | bentropy=1.338 | proto_recon=2370.7762 | nassoc=0.5414 [diag=0.290 offdiag=0.011] | proto_usage=2.5076

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4059

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=153.4  top5_share=8.1%  community-preservation(mean neighbor agreement)=0.412
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.4059 (+0.0983), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.62it/s]

>>> Epoch 2/~20 | loss=24.0356 | q+=0.321 | q-=0.021 | margin=0.301 | effk=1.7 | unused_proto=0 | bentropy=1.031 | proto_recon=2350.0469 | nassoc=0.4238 [diag=0.387 offdiag=0.009] | proto_usage=1.1129

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4418

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=162.9  top5_share=7.1%  community-preservation(mean neighbor agreement)=0.450
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.4418 (+0.0359), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.57it/s]

>>> Epoch 3/~20 | loss=23.9752 | q+=0.359 | q-=0.021 | margin=0.338 | effk=1.5 | unused_proto=0 | bentropy=0.912 | proto_recon=2350.5447 | nassoc=0.3852 [diag=0.423 offdiag=0.009] | proto_usage=0.8460

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4591

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=166.0  top5_share=6.6%  community-preservation(mean neighbor agreement)=0.468
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.4591 (+0.0174), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.67it/s]

>>> Epoch 4/~20 | loss=23.9432 | q+=0.383 | q-=0.021 | margin=0.361 | effk=1.3 | unused_proto=0 | bentropy=0.850 | proto_recon=2350.4328 | nassoc=0.3652 [diag=0.442 offdiag=0.008] | proto_usage=0.7372

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4703

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=166.9  top5_share=6.5%  community-preservation(mean neighbor agreement)=0.480
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4703 (+0.0112), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 4)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.62it/s]

>>> Epoch 5/~20 | loss=23.9348 | q+=0.398 | q-=0.022 | margin=0.376 | effk=1.3 | unused_proto=0 | bentropy=0.814 | proto_recon=2351.4116 | nassoc=0.3531 [diag=0.455 offdiag=0.008] | proto_usage=0.6766

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4766

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=167.7  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.487
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.4766 (+0.0063), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 5)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.59it/s]

>>> Epoch 6/~20 | loss=23.9236 | q+=0.408 | q-=0.022 | margin=0.386 | effk=1.2 | unused_proto=0 | bentropy=0.787 | proto_recon=2351.5644 | nassoc=0.3443 [diag=0.464 offdiag=0.008] | proto_usage=0.6365

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4815

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=168.4  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.492
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.4815 vs best 0.4766, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:12<00:00, 13.73it/s]

>>> Epoch 7/~20 | loss=23.9052 | q+=0.416 | q-=0.022 | margin=0.394 | effk=1.2 | unused_proto=0 | bentropy=0.768 | proto_recon=2350.6909 | nassoc=0.3378 [diag=0.471 offdiag=0.008] | proto_usage=0.6050

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4868

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=168.3  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.497
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4868 (+0.0101), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 7)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.51it/s]

>>> Epoch 8/~20 | loss=23.9100 | q+=0.421 | q-=0.022 | margin=0.399 | effk=1.2 | unused_proto=0 | bentropy=0.752 | proto_recon=2351.6043 | nassoc=0.3355 [diag=0.474 offdiag=0.008] | proto_usage=0.5838

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4876

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=169.1  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.498
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4876 vs best 0.4868, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.55it/s]

>>> Epoch 9/~20 | loss=23.9031 | q+=0.426 | q-=0.022 | margin=0.404 | effk=1.2 | unused_proto=0 | bentropy=0.740 | proto_recon=2351.5324 | nassoc=0.3310 [diag=0.478 offdiag=0.008] | proto_usage=0.5669

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4909

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=169.1  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.501
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] No improvement (0.4909 vs best 0.4868, min_delta=0.005), coverage=0.7857 (11/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.66it/s]

>>> Epoch 10/~20 | loss=23.8968 | q+=0.430 | q-=0.022 | margin=0.408 | effk=1.2 | unused_proto=0 | bentropy=0.731 | proto_recon=2351.4319 | nassoc=0.3274 [diag=0.482 offdiag=0.008] | proto_usage=0.5499

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4924

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=169.4  top5_share=6.1%  community-preservation(mean neighbor agreement)=0.503
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] modularity improved to 0.4924 (+0.0057), coverage=0.8571 (12/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 10)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.48it/s]

>>> Epoch 11/~20 | loss=23.9016 | q+=0.434 | q-=0.022 | margin=0.412 | effk=1.2 | unused_proto=0 | bentropy=0.724 | proto_recon=2352.1945 | nassoc=0.3260 [diag=0.484 offdiag=0.007] | proto_usage=0.5358

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4940

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=169.6  top5_share=6.2%  community-preservation(mean neighbor agreement)=0.505
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4940 vs best 0.4924, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.47it/s]

>>> Epoch 12/~20 | loss=23.8851 | q+=0.435 | q-=0.022 | margin=0.413 | effk=1.2 | unused_proto=0 | bentropy=0.718 | proto_recon=2350.8699 | nassoc=0.3243 [diag=0.486 offdiag=0.007] | proto_usage=0.5208

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4956

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.0  top5_share=6.1%  community-preservation(mean neighbor agreement)=0.506
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4956 vs best 0.4924, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.56it/s]

>>> Epoch 13/~20 | loss=23.8865 | q+=0.439 | q-=0.022 | margin=0.417 | effk=1.2 | unused_proto=0 | bentropy=0.711 | proto_recon=2351.3653 | nassoc=0.3221 [diag=0.489 offdiag=0.007] | proto_usage=0.5070

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4977

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.1  top5_share=6.1%  community-preservation(mean neighbor agreement)=0.508
  [coverage] missing (no prototype's majority label): ['epsilon', 'schwann', 't_cell']
  [Early stop] modularity improved to 0.4977 (+0.0053), coverage=0.7857 (11/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 13)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.55it/s]

>>> Epoch 14/~20 | loss=23.8751 | q+=0.441 | q-=0.022 | margin=0.419 | effk=1.2 | unused_proto=0 | bentropy=0.707 | proto_recon=2350.4478 | nassoc=0.3209 [diag=0.490 offdiag=0.007] | proto_usage=0.4970

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4983

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.3  top5_share=6.1%  community-preservation(mean neighbor agreement)=0.509
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4983 vs best 0.4977, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.64it/s]

>>> Epoch 15/~20 | loss=23.8865 | q+=0.443 | q-=0.022 | margin=0.420 | effk=1.2 | unused_proto=0 | bentropy=0.702 | proto_recon=2351.8058 | nassoc=0.3194 [diag=0.492 offdiag=0.007] | proto_usage=0.4907

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4996

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.6  top5_share=6.0%  community-preservation(mean neighbor agreement)=0.510
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.4996 vs best 0.4977, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 13.94it/s]

>>> Epoch 16/~20 | loss=23.8713 | q+=0.445 | q-=0.022 | margin=0.423 | effk=1.1 | unused_proto=0 | bentropy=0.697 | proto_recon=2350.5645 | nassoc=0.3175 [diag=0.494 offdiag=0.007] | proto_usage=0.4824

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5001

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.7  top5_share=6.0%  community-preservation(mean neighbor agreement)=0.511
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5001 vs best 0.4977, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.02it/s]

>>> Epoch 17/~20 | loss=23.8649 | q+=0.446 | q-=0.022 | margin=0.424 | effk=1.1 | unused_proto=0 | bentropy=0.693 | proto_recon=2350.0096 | nassoc=0.3173 [diag=0.494 offdiag=0.007] | proto_usage=0.4750

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5012

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.6  top5_share=6.0%  community-preservation(mean neighbor agreement)=0.512
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5012 vs best 0.4977, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:11<00:00, 14.00it/s]

>>> Epoch 18/~20 | loss=23.8697 | q+=0.448 | q-=0.022 | margin=0.425 | effk=1.1 | unused_proto=0 | bentropy=0.691 | proto_recon=2350.7243 | nassoc=0.3156 [diag=0.496 offdiag=0.007] | proto_usage=0.4684

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.5009

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=170.7  top5_share=6.0%  community-preservation(mean neighbor agreement)=0.512
  [coverage] missing (no prototype's majority label): ['epsilon', 't_cell']
  [Early stop] No improvement (0.5009 vs best 0.4977, min_delta=0.005), coverage=0.8571 (12/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 18.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=0, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 13)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9566  (size-weighted: 0.9693 ± 0.0847)
[proto] mean batch entropy: 0.4863  (size-weighted: 0.4491 ± 0.4436)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.4977
[proto] per-batch modularity: mean=0.4490, std=0.0501

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_cf04ad52.h5ad
[task2] coverage: 0.7857
[task2] dge_rbo_avg: 0.2099
[task2] dge_kendall_avg: 0.1615
[task2] dge_jaccard_avg: 0.2249
[task2] scgraph_corr_avg: 0.9319
[task2] scgraph_corr_std: 0.0362
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.2216 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_community_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_lumap0_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s2 no_community] done in 1531.7s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s2__no_community.json

=== [pancreas] ablation variant: no_nassoc (- nassoc) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2515.35proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=83.9  top5_share=13.0%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3397 unreachable (max E[q_pos]=0.3025), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0510 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3115

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3115, coverage=1.0000 (14/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:52<00:00, 19.12it/s]

>>> Epoch 1/~20 | loss=26.3031 | q+=0.504 | q-=0.063 | margin=0.441 | effk=1.8 | unused_proto=0 | bentropy=1.525 | proto_recon=2400.0525 | proto_usage=9.7620

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6990

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 216/220 used (98.2%)  effective_n=17.1  top5_share=42.0%  community-preservation(mean neighbor agreement)=0.753
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6990 (+0.3875), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.31it/s]

>>> Epoch 2/~20 | loss=25.7599 | q+=0.578 | q-=0.063 | margin=0.515 | effk=1.5 | unused_proto=0 | bentropy=1.317 | proto_recon=2378.2322 | proto_usage=7.9636

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7040

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=17.4  top5_share=41.8%  community-preservation(mean neighbor agreement)=0.756
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.7040 (+0.0050), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.39it/s]

>>> Epoch 3/~20 | loss=25.6069 | q+=0.585 | q-=0.061 | margin=0.524 | effk=1.5 | unused_proto=0 | bentropy=1.258 | proto_recon=2372.4186 | proto_usage=7.2699

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7008

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=17.7  top5_share=41.0%  community-preservation(mean neighbor agreement)=0.754
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.7008 vs best 0.7040, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.34it/s]

>>> Epoch 4/~20 | loss=25.5248 | q+=0.588 | q-=0.060 | margin=0.528 | effk=1.5 | unused_proto=0 | bentropy=1.217 | proto_recon=2369.0276 | proto_usage=6.9517

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7006

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=18.4  top5_share=40.0%  community-preservation(mean neighbor agreement)=0.751
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.7006 vs best 0.7040, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.35it/s]

>>> Epoch 5/~20 | loss=25.4831 | q+=0.589 | q-=0.059 | margin=0.530 | effk=1.5 | unused_proto=0 | bentropy=1.198 | proto_recon=2367.3097 | proto_usage=6.7835

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6996

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=19.2  top5_share=39.0%  community-preservation(mean neighbor agreement)=0.748
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6996 vs best 0.7040, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.42it/s]

>>> Epoch 6/~20 | loss=25.4393 | q+=0.590 | q-=0.059 | margin=0.532 | effk=1.4 | unused_proto=0 | bentropy=1.183 | proto_recon=2365.3197 | proto_usage=6.6212

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6999

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=18.9  top5_share=39.7%  community-preservation(mean neighbor agreement)=0.749
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6999 vs best 0.7040, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.43it/s]

>>> Epoch 7/~20 | loss=25.4110 | q+=0.591 | q-=0.058 | margin=0.533 | effk=1.4 | unused_proto=0 | bentropy=1.167 | proto_recon=2364.1070 | proto_usage=6.5039

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6978

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=19.6  top5_share=39.1%  community-preservation(mean neighbor agreement)=0.745
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6978 vs best 0.7040, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 7.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 1/220 (0.45%)
[proto] mean cell-type purity: 0.8721  (size-weighted: 0.9709 ± 0.0670)
[proto] mean batch entropy: 0.5020  (size-weighted: 1.5481 ± 0.5886)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7040
[proto] per-batch modularity: mean=0.6465, std=0.0955

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_5dbf9cac.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.1442
[task2] dge_kendall_avg: 0.1906
[task2] dge_jaccard_avg: 0.1759
[task2] scgraph_corr_avg: 0.8752
[task2] scgraph_corr_std: 0.0642
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.2962 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
  [pancreas s31 no_nassoc] done in 486.0s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s31__no_nassoc.json

=== [pancreas] ablation variant: no_nassoc (- nassoc) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2286.17proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=67.3  top5_share=18.4%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3399 unreachable (max E[q_pos]=0.3250), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0510 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3361

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3361, coverage=1.0000 (14/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:52<00:00, 19.08it/s]

>>> Epoch 1/~20 | loss=26.5210 | q+=0.520 | q-=0.067 | margin=0.454 | effk=1.7 | unused_proto=0 | bentropy=1.391 | proto_recon=2406.9065 | proto_usage=11.4494

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6995

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 214/220 used (97.3%)  effective_n=14.9  top5_share=48.9%  community-preservation(mean neighbor agreement)=0.763
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6995 (+0.3635), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:52<00:00, 19.21it/s]

>>> Epoch 2/~20 | loss=25.8717 | q+=0.580 | q-=0.064 | margin=0.516 | effk=1.5 | unused_proto=0 | bentropy=1.166 | proto_recon=2379.4122 | proto_usage=9.0484

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7035

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 218/220 used (99.1%)  effective_n=15.8  top5_share=47.7%  community-preservation(mean neighbor agreement)=0.764
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.7035 vs best 0.6995, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [00:53<00:00, 18.65it/s]

>>> Epoch 3/~20 | loss=25.6949 | q+=0.587 | q-=0.062 | margin=0.525 | effk=1.5 | unused_proto=0 | bentropy=1.132 | proto_recon=2373.6009 | proto_usage=8.1195

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6968

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=16.2  top5_share=46.5%  community-preservation(mean neighbor agreement)=0.755
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6968 vs best 0.6995, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [00:52<00:00, 19.12it/s]

>>> Epoch 4/~20 | loss=25.6025 | q+=0.588 | q-=0.061 | margin=0.527 | effk=1.5 | unused_proto=0 | bentropy=1.105 | proto_recon=2370.9801 | proto_usage=7.5983

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6977

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=16.6  top5_share=46.0%  community-preservation(mean neighbor agreement)=0.754
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6977 vs best 0.6995, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [00:52<00:00, 19.02it/s]

>>> Epoch 5/~20 | loss=25.5346 | q+=0.590 | q-=0.060 | margin=0.529 | effk=1.4 | unused_proto=0 | bentropy=1.082 | proto_recon=2368.1061 | proto_usage=7.3020

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6986

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=16.2  top5_share=47.2%  community-preservation(mean neighbor agreement)=0.757
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6986 vs best 0.6995, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.35it/s]

>>> Epoch 6/~20 | loss=25.4822 | q+=0.591 | q-=0.059 | margin=0.531 | effk=1.4 | unused_proto=0 | bentropy=1.068 | proto_recon=2366.5834 | proto_usage=7.0036

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6970

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=17.2  top5_share=45.0%  community-preservation(mean neighbor agreement)=0.752
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6970 vs best 0.6995, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 6.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 6/220 (2.73%)
[proto] mean cell-type purity: 0.9068  (size-weighted: 0.9682 ± 0.0820)
[proto] mean batch entropy: 0.3787  (size-weighted: 1.6126 ± 0.6091)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6995
[proto] per-batch modularity: mean=0.6518, std=0.0831

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_a27e0fe0.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.1255
[task2] dge_kendall_avg: 0.1823
[task2] dge_jaccard_avg: 0.1584
[task2] scgraph_corr_avg: 0.9145
[task2] scgraph_corr_std: 0.0435
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.2413 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
  [pancreas s1 no_nassoc] done in 432.0s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s1__no_nassoc.json

=== [pancreas] ablation variant: no_nassoc (- nassoc) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2568.72proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=77.3  top5_share=14.4%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3378 unreachable (max E[q_pos]=0.3006), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0506 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3155

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3155, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.47it/s]

>>> Epoch 1/~20 | loss=26.3506 | q+=0.497 | q-=0.061 | margin=0.436 | effk=1.8 | unused_proto=0 | bentropy=1.446 | proto_recon=2396.0209 | proto_usage=10.6840

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6907

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 212/220 used (96.4%)  effective_n=19.0  top5_share=40.2%  community-preservation(mean neighbor agreement)=0.739
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6907 (+0.3752), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.42it/s]

>>> Epoch 2/~20 | loss=25.7553 | q+=0.561 | q-=0.059 | margin=0.502 | effk=1.5 | unused_proto=0 | bentropy=1.230 | proto_recon=2372.6849 | proto_usage=8.4849

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6935

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 216/220 used (98.2%)  effective_n=21.2  top5_share=36.8%  community-preservation(mean neighbor agreement)=0.738
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6935 vs best 0.6907, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.37it/s]

>>> Epoch 3/~20 | loss=25.6055 | q+=0.570 | q-=0.057 | margin=0.513 | effk=1.5 | unused_proto=0 | bentropy=1.171 | proto_recon=2368.7261 | proto_usage=7.6858

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6937

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 218/220 used (99.1%)  effective_n=21.7  top5_share=36.1%  community-preservation(mean neighbor agreement)=0.737
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6937 vs best 0.6907, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.43it/s]

>>> Epoch 4/~20 | loss=25.5126 | q+=0.575 | q-=0.056 | margin=0.519 | effk=1.5 | unused_proto=0 | bentropy=1.137 | proto_recon=2365.5897 | proto_usage=7.2414

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6948

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 218/220 used (99.1%)  effective_n=22.1  top5_share=35.1%  community-preservation(mean neighbor agreement)=0.737
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6948 vs best 0.6907, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.44it/s]

>>> Epoch 5/~20 | loss=25.4642 | q+=0.578 | q-=0.056 | margin=0.522 | effk=1.5 | unused_proto=0 | bentropy=1.115 | proto_recon=2364.5725 | proto_usage=6.9437

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6943

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=22.9  top5_share=34.1%  community-preservation(mean neighbor agreement)=0.735
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6943 vs best 0.6907, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [00:51<00:00, 19.46it/s]

>>> Epoch 6/~20 | loss=25.4349 | q+=0.580 | q-=0.056 | margin=0.524 | effk=1.5 | unused_proto=0 | bentropy=1.097 | proto_recon=2363.8684 | proto_usage=6.7858

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6930

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=22.7  top5_share=34.7%  community-preservation(mean neighbor agreement)=0.734
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6930 vs best 0.6907, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 6.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 8/220 (3.64%)
[proto] mean cell-type purity: 0.9213  (size-weighted: 0.9709 ± 0.0757)
[proto] mean batch entropy: 0.3799  (size-weighted: 1.4696 ± 0.5164)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6907
[proto] per-batch modularity: mean=0.6306, std=0.0878

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_7bf620de.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.1637
[task2] dge_kendall_avg: 0.1477
[task2] dge_jaccard_avg: 0.1652
[task2] scgraph_corr_avg: 0.8367
[task2] scgraph_corr_std: 0.0740
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.4593 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_no_nassoc_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_nagg-max_upm-dotp_v31
  [pancreas s2 no_nassoc] done in 428.7s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s2__no_nassoc.json

=== [pancreas] ablation variant: stopgrad_off (Stop-grad off) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2485.08proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=80.5  top5_share=15.6%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3397 unreachable (max E[q_pos]=0.3278), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0499 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3173

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3173, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:15<00:00, 13.32it/s]

>>> Epoch 1/~20 | loss=26.3441 | q+=0.351 | q-=0.040 | margin=0.311 | effk=2.4 | unused_proto=0 | bentropy=1.431 | proto_recon=2357.0249 | nassoc=0.6868 [diag=0.200 offdiag=0.007] | proto_usage=5.4912

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6183

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 219/220 used (99.5%)  effective_n=40.1  top5_share=25.0%  community-preservation(mean neighbor agreement)=0.633
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6183 (+0.3009), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.45it/s]

>>> Epoch 2/~20 | loss=25.7354 | q+=0.413 | q-=0.040 | margin=0.372 | effk=2.1 | unused_proto=0 | bentropy=1.232 | proto_recon=2332.8833 | nassoc=0.6392 [diag=0.240 offdiag=0.006] | proto_usage=4.1398

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6245

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=43.0  top5_share=23.9%  community-preservation(mean neighbor agreement)=0.638
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6245 (+0.0063), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.46it/s]

>>> Epoch 3/~20 | loss=25.5693 | q+=0.419 | q-=0.039 | margin=0.380 | effk=2.0 | unused_proto=0 | bentropy=1.160 | proto_recon=2326.6957 | nassoc=0.6168 [diag=0.256 offdiag=0.006] | proto_usage=3.5993

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6230

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=45.4  top5_share=23.0%  community-preservation(mean neighbor agreement)=0.636
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6230 vs best 0.6245, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.48it/s]

>>> Epoch 4/~20 | loss=25.4751 | q+=0.422 | q-=0.038 | margin=0.383 | effk=2.0 | unused_proto=0 | bentropy=1.119 | proto_recon=2322.7064 | nassoc=0.6031 [diag=0.265 offdiag=0.006] | proto_usage=3.3310

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6262

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=46.0  top5_share=23.0%  community-preservation(mean neighbor agreement)=0.639
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6262 vs best 0.6245, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.44it/s]

>>> Epoch 5/~20 | loss=25.4116 | q+=0.424 | q-=0.038 | margin=0.386 | effk=2.0 | unused_proto=0 | bentropy=1.088 | proto_recon=2320.7841 | nassoc=0.5913 [diag=0.273 offdiag=0.006] | proto_usage=3.1062

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6237

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=48.1  top5_share=22.3%  community-preservation(mean neighbor agreement)=0.635
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6237 vs best 0.6245, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.47it/s]

>>> Epoch 6/~20 | loss=25.3602 | q+=0.424 | q-=0.038 | margin=0.387 | effk=2.0 | unused_proto=0 | bentropy=1.066 | proto_recon=2318.6140 | nassoc=0.5814 [diag=0.280 offdiag=0.006] | proto_usage=2.9598

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6252

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=47.8  top5_share=22.8%  community-preservation(mean neighbor agreement)=0.637
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6252 vs best 0.6245, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.45it/s]

>>> Epoch 7/~20 | loss=25.3270 | q+=0.425 | q-=0.037 | margin=0.387 | effk=2.0 | unused_proto=0 | bentropy=1.046 | proto_recon=2317.3226 | nassoc=0.5752 [diag=0.284 offdiag=0.006] | proto_usage=2.8518

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6231

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=49.7  top5_share=21.8%  community-preservation(mean neighbor agreement)=0.634
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6231 vs best 0.6245, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 7.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9037  (size-weighted: 0.9786 ± 0.0611)
[proto] mean batch entropy: 0.5922  (size-weighted: 0.9380 ± 0.5535)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6245
[proto] per-batch modularity: mean=0.5553, std=0.0689

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_273af140.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.2050
[task2] dge_kendall_avg: 0.2120
[task2] dge_jaccard_avg: 0.2346
[task2] scgraph_corr_avg: 0.9387
[task2] scgraph_corr_std: 0.0318
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.4054 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s31_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s31 stopgrad_off] done in 647.4s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s31__stopgrad_off.json

=== [pancreas] ablation variant: stopgrad_off (Stop-grad off) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2280.32proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=93.7  top5_share=11.7%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3399 unreachable (max E[q_pos]=0.2799), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0460 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.2927

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.2927, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.50it/s]

>>> Epoch 1/~20 | loss=26.3719 | q+=0.358 | q-=0.039 | margin=0.319 | effk=2.4 | unused_proto=0 | bentropy=1.352 | proto_recon=2360.7020 | nassoc=0.6882 [diag=0.204 offdiag=0.006] | proto_usage=5.3558

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6129

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=41.2  top5_share=25.6%  community-preservation(mean neighbor agreement)=0.627
  [Early stop] modularity improved to 0.6129 (+0.3202), coverage=1.0000 (14/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.44it/s]

>>> Epoch 2/~20 | loss=25.7561 | q+=0.417 | q-=0.040 | margin=0.377 | effk=2.0 | unused_proto=0 | bentropy=1.169 | proto_recon=2334.6469 | nassoc=0.6449 [diag=0.240 offdiag=0.006] | proto_usage=4.1968

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6204

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=42.7  top5_share=25.6%  community-preservation(mean neighbor agreement)=0.635
  [Early stop] modularity improved to 0.6204 (+0.0075), coverage=1.0000 (14/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.46it/s]

>>> Epoch 3/~20 | loss=25.5895 | q+=0.424 | q-=0.039 | margin=0.385 | effk=2.0 | unused_proto=0 | bentropy=1.108 | proto_recon=2328.4052 | nassoc=0.6226 [diag=0.256 offdiag=0.006] | proto_usage=3.6741

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6264

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=43.2  top5_share=25.4%  community-preservation(mean neighbor agreement)=0.641
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6264 (+0.0060), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.44it/s]

>>> Epoch 4/~20 | loss=25.4931 | q+=0.428 | q-=0.039 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=1.067 | proto_recon=2325.0083 | nassoc=0.6084 [diag=0.266 offdiag=0.006] | proto_usage=3.3352

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6245

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=44.2  top5_share=25.4%  community-preservation(mean neighbor agreement)=0.639
  [Early stop] No improvement (0.6245 vs best 0.6264, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.47it/s]

>>> Epoch 5/~20 | loss=25.4236 | q+=0.428 | q-=0.038 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=1.040 | proto_recon=2321.9232 | nassoc=0.5980 [diag=0.272 offdiag=0.006] | proto_usage=3.0952

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6244

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=44.2  top5_share=25.4%  community-preservation(mean neighbor agreement)=0.639
  [Early stop] No improvement (0.6244 vs best 0.6264, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.41it/s]

>>> Epoch 6/~20 | loss=25.3690 | q+=0.427 | q-=0.037 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=1.015 | proto_recon=2319.6593 | nassoc=0.5880 [diag=0.278 offdiag=0.006] | proto_usage=2.9176

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6194

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=45.2  top5_share=24.9%  community-preservation(mean neighbor agreement)=0.633
  [Early stop] No improvement (0.6194 vs best 0.6264, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.46it/s]

>>> Epoch 7/~20 | loss=25.3333 | q+=0.426 | q-=0.037 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=0.994 | proto_recon=2318.4395 | nassoc=0.5811 [diag=0.282 offdiag=0.006] | proto_usage=2.7790

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6176

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=45.9  top5_share=24.7%  community-preservation(mean neighbor agreement)=0.631
  [Early stop] No improvement (0.6176 vs best 0.6264, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.46it/s]

>>> Epoch 8/~20 | loss=25.3064 | q+=0.426 | q-=0.036 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=0.979 | proto_recon=2317.4984 | nassoc=0.5756 [diag=0.286 offdiag=0.006] | proto_usage=2.6842

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6156

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=47.1  top5_share=24.3%  community-preservation(mean neighbor agreement)=0.629
  [Early stop] No improvement (0.6156 vs best 0.6264, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 8.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9022  (size-weighted: 0.9734 ± 0.0684)
[proto] mean batch entropy: 0.5534  (size-weighted: 0.9360 ± 0.6369)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6264
[proto] per-batch modularity: mean=0.5645, std=0.0575

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_c1d3f493.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.2024
[task2] dge_kendall_avg: 0.1956
[task2] dge_jaccard_avg: 0.2248
[task2] scgraph_corr_avg: 0.9082
[task2] scgraph_corr_std: 0.0349
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.5569 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s1_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s1 stopgrad_off] done in 728.3s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s1__stopgrad_off.json

=== [pancreas] ablation variant: stopgrad_off (Stop-grad off) ===  [training fresh]
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
[waypoint init] N=16382  K=220  n_eigs=10  nnz=1155146  nnz/row=70.5  w[min/mean/max]=3.203e-02/3.392e-01/9.688e-01  deg[min/mean/max]=5.45/23.92/92.20
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2595.83proto/s]

[waypoint init] selected 220 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 220/220 prototypes used (100.0%)  effective_n=74.0  top5_share=16.2%

  0%|          | 0/16 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3378 unreachable (max E[q_pos]=0.3311), falling back to effk=5.0

  0%|          | 0/16 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0492 (mean_effk=5.00)
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 1 epochs, patience=5, max_epochs=20

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3286

  0%|          | 0/16 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3286, coverage=0.9286 (13/14 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.48it/s]

>>> Epoch 1/~20 | loss=26.4210 | q+=0.359 | q-=0.040 | margin=0.319 | effk=2.4 | unused_proto=0 | bentropy=1.411 | proto_recon=2358.3255 | nassoc=0.7089 [diag=0.189 offdiag=0.006] | proto_usage=6.1802

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6184

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=40.9  top5_share=24.0%  community-preservation(mean neighbor agreement)=0.633
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6184 (+0.2898), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 1)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.46it/s]

>>> Epoch 2/~20 | loss=25.8058 | q+=0.417 | q-=0.040 | margin=0.378 | effk=2.0 | unused_proto=0 | bentropy=1.244 | proto_recon=2333.0761 | nassoc=0.6662 [diag=0.224 offdiag=0.006] | proto_usage=4.7464

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6283

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=40.7  top5_share=24.5%  community-preservation(mean neighbor agreement)=0.643
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] modularity improved to 0.6283 (+0.0099), coverage=0.9286 (13/14) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.47it/s]

>>> Epoch 3/~20 | loss=25.6479 | q+=0.426 | q-=0.039 | margin=0.387 | effk=2.0 | unused_proto=0 | bentropy=1.178 | proto_recon=2327.5631 | nassoc=0.6491 [diag=0.236 offdiag=0.006] | proto_usage=4.1735

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6269

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=43.5  top5_share=23.9%  community-preservation(mean neighbor agreement)=0.641
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6269 vs best 0.6283, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 1/5

edges: 100%|██████████| 1000/1000 [01:13<00:00, 13.51it/s]

>>> Epoch 4/~20 | loss=25.5399 | q+=0.428 | q-=0.038 | margin=0.390 | effk=2.0 | unused_proto=0 | bentropy=1.137 | proto_recon=2323.2996 | nassoc=0.6335 [diag=0.246 offdiag=0.006] | proto_usage=3.8161

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6283

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=44.5  top5_share=23.5%  community-preservation(mean neighbor agreement)=0.642
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6283 vs best 0.6283, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 2/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.44it/s]

>>> Epoch 5/~20 | loss=25.4813 | q+=0.428 | q-=0.038 | margin=0.390 | effk=2.0 | unused_proto=0 | bentropy=1.107 | proto_recon=2321.4930 | nassoc=0.6222 [diag=0.254 offdiag=0.006] | proto_usage=3.5605

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6242

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=46.4  top5_share=22.6%  community-preservation(mean neighbor agreement)=0.637
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6242 vs best 0.6283, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 3/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.51it/s]

>>> Epoch 6/~20 | loss=25.4313 | q+=0.427 | q-=0.037 | margin=0.390 | effk=2.0 | unused_proto=0 | bentropy=1.082 | proto_recon=2319.7233 | nassoc=0.6118 [diag=0.260 offdiag=0.006] | proto_usage=3.3752

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6228

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=46.3  top5_share=23.5%  community-preservation(mean neighbor agreement)=0.636
  [coverage] missing (no prototype's majority label): ['t_cell']
  [Early stop] No improvement (0.6228 vs best 0.6283, min_delta=0.005), coverage=0.9286 (13/14), no-improve streak: 4/5

edges: 100%|██████████| 1000/1000 [01:14<00:00, 13.43it/s]

>>> Epoch 7/~20 | loss=25.3881 | q+=0.426 | q-=0.037 | margin=0.389 | effk=2.0 | unused_proto=0 | bentropy=1.061 | proto_recon=2317.4385 | nassoc=0.6046 [diag=0.265 offdiag=0.006] | proto_usage=3.2570

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6240

  0%|          | 0/16 [00:00<?, ?it/s]

  [proto usage] 220/220 used (100.0%)  effective_n=47.1  top5_share=23.0%  community-preservation(mean neighbor agreement)=0.637
  [Early stop] No improvement (0.6240 vs best 0.6283, min_delta=0.005), coverage=1.0000 (14/14), no-improve streak: 5/5
[Early stop] Patience exhausted. Stopping at epoch 7.

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=1000 → 1024000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 2)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9113  (size-weighted: 0.9777 ± 0.0582)
[proto] mean batch entropy: 0.5896  (size-weighted: 1.0233 ± 0.5690)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6283
[proto] per-batch modularity: mean=0.5663, std=0.0679

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_433a5428.h5ad
[task2] coverage: 0.9286
[task2] dge_rbo_avg: 0.1912
[task2] dge_kendall_avg: 0.2363
[task2] dge_jaccard_avg: 0.1844
[task2] scgraph_corr_avg: 0.8942
[task2] scgraph_corr_std: 0.0460
[task3] no niche_key defined, skipped

  0%|          | 0/16 [00:00<?, ?it/s]

[aff_dc_compactness] mean=0.4104 | saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/aff_dc_compactness.csv
Dominant batch: [[6]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/seedabl_s2_stopgrad_off_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
  [pancreas s2 stopgrad_off] done in 644.8s -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas__s2__stopgrad_off.json

12/12 runs available

## Analysis 1 -- spread across seeds, per arm

This is the table nG29 asked for: `mean +- std` where the `+-` is **over seeds**.

In [7]:
def load_records(ds):
    out = []
    for f in sorted(os.listdir(OUT_DIR)):
        if f.startswith(f'{ds}__') and f.endswith('.json'):
            with open(os.path.join(OUT_DIR, f)) as fh:
                out.append(json.load(fh))
    return out


METRICS = ['modularity', 'purity', 'batch_entropy', 'coverage',
           'batch_rare_homogeneity_mean', 'batch_rare_coverage_mean',
           'batch_rare_f1_macro_mean', 'active_prototype_count']

recs = load_records(DS)
rows = []
for r in recs:
    row = {'arm': r['arm'], 'seed': r['seed']}
    row.update({m: r['metrics'].get(m) for m in METRICS})
    rows.append(row)

df_raw = pd.DataFrame(rows).sort_values(['arm', 'seed'])
present = [m for m in METRICS if m in df_raw.columns and df_raw[m].notna().any()]
missing = [m for m in METRICS if m not in present]
if missing:
    print(f'not produced by this run (name differs or metric skipped): {missing}')

print(f'\nraw per-seed values ({len(df_raw)} runs)')
display(df_raw[['arm', 'seed'] + present])

df_seed = df_raw.groupby('arm')[present].agg(['mean', 'std', 'count'])
print('\nmean +- std ACROSS SEEDS')
display(df_seed)

df_raw.to_csv(os.path.join(OUT_DIR, f'{DS}_per_seed_raw.csv'), index=False)
df_seed.to_csv(os.path.join(OUT_DIR, f'{DS}_per_seed_summary.csv'))
print('saved ->', OUT_DIR)

not produced by this run (name differs or metric skipped): ['batch_rare_homogeneity_mean', 'batch_rare_coverage_mean', 'batch_rare_f1_macro_mean', 'active_prototype_count']

raw per-seed values (12 runs)

             arm  seed  modularity    purity  batch_entropy  coverage
0           full     1    0.701069  0.922393       0.445614  1.000000
4           full     2    0.697862  0.914601       0.376770  0.928571
8           full    31    0.689617  0.911317       0.434529  1.000000
1   no_community     1    0.509445  0.955964       0.468540  0.785714
5   no_community     2    0.497727  0.956642       0.486260  0.785714
9   no_community    31    0.488888  0.954927       0.478449  0.857143
2      no_nassoc     1    0.699537  0.906820       0.378727  0.928571
6      no_nassoc     2    0.690684  0.921303       0.379863  0.928571
10     no_nassoc    31    0.704029  0.872092       0.502007  0.928571
3   stopgrad_off     1    0.626371  0.902231       0.553437  0.928571
7   stopgrad_off     2    0.628309  0.911280       0.589551  0.928571
11  stopgrad_off    31    0.624505  0.903705       0.592197  0.928571

mean +- std ACROSS SEEDS

             modularity                    purity                  \
                   mean       std count      mean       std count
arm
full           0.696183  0.005908     3  0.916104  0.005689     3
no_community   0.498687  0.010312     3  0.955844  0.000863     3
no_nassoc      0.698084  0.006790     3  0.900072  0.025290     3
stopgrad_off   0.626395  0.001902     3  0.905739  0.004855     3

             batch_entropy                  coverage
                      mean       std count      mean       std count
arm
full              0.418971  0.036965     3  0.976190  0.041239     3
no_community      0.477750  0.008881     3  0.809524  0.041239     3
no_nassoc         0.420199  0.070850     3  0.928571  0.000000     3
stopgrad_off      0.578395  0.021654     3  0.928571  0.000000     3

saved -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/

## Analysis 2 -- effect size against seed noise

The number to quote. For each arm and metric:

```
effect      = mean_over_seeds(full) - mean_over_seeds(arm)
seed_noise  = std_over_seeds(full)
ratio       = |effect| / seed_noise
```

`ratio` says how many seed-standard-deviations the ablation moved the metric. A ratio
near 1 means the arm is indistinguishable from re-running the same model with a different
initialisation -- and if that is what `stopgrad_off` shows, the honest move is to drop the
empirical claim and justify the stop-gradient by design instead.

`- community loss` is in here as the calibration point: whatever ratio it earns is the
scale against which every other arm should be read.

In [8]:
def effect_vs_seed_noise(df_raw, metrics, ref_arm='full'):
    if ref_arm not in set(df_raw['arm']):
        print(f'no {ref_arm!r} arm -- cannot compute effects')
        return pd.DataFrame()
    g = df_raw.groupby('arm')
    rows = []
    for m in metrics:
        if m not in df_raw.columns:
            continue
        ref_mean, ref_std = g[m].mean().get(ref_arm), g[m].std().get(ref_arm)
        n_ref = int(g[m].count().get(ref_arm, 0))
        for arm in df_raw['arm'].unique():
            if arm == ref_arm:
                continue
            am, asd = g[m].mean().get(arm), g[m].std().get(arm)
            if pd.isna(ref_mean) or pd.isna(am):
                continue
            eff = ref_mean - am
            pooled = np.sqrt(np.nanmean([ref_std ** 2, asd ** 2])) if pd.notna(ref_std) and pd.notna(asd) else np.nan
            rows.append({
                'metric': m, 'arm': arm,
                'full_mean': ref_mean, 'full_seed_std': ref_std,
                'arm_mean': am, 'arm_seed_std': asd,
                'effect': eff,
                'ratio_vs_full_std': abs(eff) / ref_std if pd.notna(ref_std) and ref_std > 0 else np.nan,
                'ratio_vs_pooled_std': abs(eff) / pooled if pd.notna(pooled) and pooled > 0 else np.nan,
                'n_seeds': min(n_ref, int(g[m].count().get(arm, 0))),
            })
    return pd.DataFrame(rows)


df_eff = effect_vs_seed_noise(df_raw, present)
if not df_eff.empty:
    df_eff = df_eff.sort_values(['metric', 'ratio_vs_full_std'], ascending=[True, False])
    display(df_eff.round(4))
    df_eff.to_csv(os.path.join(OUT_DIR, f'{DS}_effect_vs_seed_noise.csv'), index=False)
    print('saved ->', os.path.join(OUT_DIR, f'{DS}_effect_vs_seed_noise.csv'))

,metric,arm,full_mean,full_seed_std,arm_mean,arm_seed_std,effect,ratio_vs_full_std,ratio_vs_pooled_std,n_seeds
8,batch_entropy,stopgrad_off,0.4190,0.0370,0.5784,0.0217,-0.1594,4.3128,5.2627,3
6,batch_entropy,no_community,0.4190,0.0370,0.4777,0.0089,-0.0588,1.5901,2.1865,3
7,batch_entropy,no_nassoc,0.4190,0.0370,0.4202,0.0709,-0.0012,0.0332,0.0217,3
9,coverage,no_community,0.9762,0.0412,0.8095,0.0412,0.1667,4.0415,4.0415,3
10,coverage,no_nassoc,0.9762,0.0412,0.9286,0.0000,0.0476,1.1547,1.6330,3
11,coverage,stopgrad_off,0.9762,0.0412,0.9286,0.0000,0.0476,1.1547,1.6330,3
0,modularity,no_community,0.6962,0.0059,0.4987,0.0103,0.1975,33.4301,23.5021,3
2,modularity,stopgrad_off,0.6962,0.0059,0.6264,0.0019,0.0698,11.8129,15.9019,3
1,modularity,no_nassoc,0.6962,0.0059,0.6981,0.0068,-0.0019,0.3217,0.2986,3
3,purity,no_community,0.9161,0.0057,0.9558,0.0009,-0.0397,6.9856,9.7673,3
4,purity,no_nassoc,0.9161,0.0057,0.9001,0.0253,0.0160,2.8182,0.8747,3
5,purity,stopgrad_off,0.9161,0.0057,0.9057,0.0049,0.0104,1.8220,1.9600,3

saved -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas_effect_vs_seed_noise.csv

In [9]:
# Headline sentence, ready to paste.
if not df_eff.empty and 'modularity' in set(df_eff['metric']):
    d = df_eff[df_eff['metric'] == 'modularity'].set_index('arm')
    noise = d['full_seed_std'].iloc[0]
    print(f'Modularity, {DS}, across {int(d["n_seeds"].max())} seeds')
    print(f'  seed-to-seed std of the full model: {noise:.4f}\n')
    for arm in d.index:
        r = d.loc[arm]
        print(f'  {ARM_DISPLAY.get(arm, arm):18s} effect {r["effect"]:+.4f}  '
              f'= {r["ratio_vs_full_std"]:.1f}x the seed noise')
    print('\nRead as: an arm whose ratio is around 1 is not separable from re-running '
          'the same model with a different seed.')

Modularity, pancreas, across 3 seeds
  seed-to-seed std of the full model: 0.0059

  - community loss   effect +0.1975  = 33.4x the seed noise
  Stop-grad off      effect +0.0698  = 11.8x the seed noise
  - nassoc           effect -0.0019  = 0.3x the seed noise

Read as: an arm whose ratio is around 1 is not separable from re-running the same model with a different seed.

## Analysis 3 -- pooling seeds into the paired batch test

Seeds and batches are not competing evidence -- they stack. Pooling every (seed, batch)
pair for an arm against the same pairs for the full model gives `n_seeds x n_batches`
paired observations instead of `n_batches`, which is the strongest version of the
argument: the difference holds within each batch, *and* it holds across initialisations.

Pairing is on `(seed, batch)`, so a batch is only ever compared against itself under the
same seed.

In [10]:
from scipy.stats import wilcoxon

def pooled_paired_modularity(ds, ref_arm='full'):
    recs = load_records(ds)
    by = {}
    for r in recs:
        pb = r.get('modularity_per_batch')
        if pb:
            by[(r['arm'], r['seed'])] = pd.Series(pb['values'], index=pb['batches'], dtype=float)
    if not by:
        print('no per-batch modularity stored in the records yet')
        return pd.DataFrame()

    arms = sorted({a for a, _ in by})
    seeds = sorted({s for _, s in by})
    rows = []
    for arm in arms:
        if arm == ref_arm:
            continue
        ref_v, arm_v, keys = [], [], []
        for s in seeds:
            a, b = by.get((ref_arm, s)), by.get((arm, s))
            if a is None or b is None:
                continue
            a2, b2 = a.align(b, join='inner')
            ref_v += list(a2.values); arm_v += list(b2.values)
            keys += [(s, i) for i in a2.index]
        if not ref_v:
            continue
        ref_v, arm_v = np.array(ref_v), np.array(arm_v)
        diff = ref_v - arm_v
        row = {'arm': arm, 'n_pairs': len(diff), 'n_seeds': len({k[0] for k in keys}),
               'full_mean': ref_v.mean(), 'arm_mean': arm_v.mean(),
               'mean_diff': diff.mean(), 'n_drop': int((diff > 0).sum())}
        if np.any(diff != 0):
            row['p_two_sided'] = float(wilcoxon(ref_v, arm_v, alternative='two-sided')[1])
        rows.append(row)
    return pd.DataFrame(rows)


df_pooled = pooled_paired_modularity(DS)
if not df_pooled.empty:
    _show = df_pooled.round(4)
    if 'p_two_sided' in _show:   # can go far below 1e-4 once seeds are pooled --
        _show['p_two_sided'] = df_pooled['p_two_sided'].map('{:.3g}'.format)  # never print "0.0"
    display(_show)
    df_pooled.to_csv(os.path.join(OUT_DIR, f'{DS}_pooled_paired_modularity.csv'), index=False)
    print('saved ->', os.path.join(OUT_DIR, f'{DS}_pooled_paired_modularity.csv'))

,arm,n_pairs,n_seeds,full_mean,arm_mean,mean_diff,n_drop,p_two_sided
0,no_community,27,3,0.6171,0.4505,0.1666,26,4.47e-08
1,no_nassoc,27,3,0.6171,0.6429,-0.0259,4,8.37e-05
2,stopgrad_off,27,3,0.6171,0.5620,0.0550,26,2.98e-08

saved -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas_pooled_paired_modularity.csv

## Extend to Lung / Immune -- only if pancreas is finished and time allows

Run these one at a time and check the pancreas result first. If the session runs out,
having pancreas complete is worth more than three datasets half-done -- pancreas is the
dataset the reviewer quoted.

In [11]:
# DS = 'lung'
# records = [run_one(DS, s, a) for a in ARMS for s in SEEDS]
# -- then re-run the Analysis cells above with DS='lung'

In [12]:
# DS = 'pbmc-immune'
# records = [run_one(DS, s, a) for a in ARMS for s in SEEDS]
# -- then re-run the Analysis cells above with DS='pbmc-immune'

## Export

Writes a markdown block with seed-level `mean +- std` and the effect/noise ratios,
formatted to drop straight into `experiment-results/` or a reviewer reply.

In [13]:
lines = [f'# Seed-variance check -- {DS}', '',
         f'{len(SEEDS)} seeds ({SEEDS}), Stage-1 shared across seeds, '
         f'Stage-2 shortened to train_epochs={COMMON["train_epochs"]}.',
         'Every arm runs at the same reduced setting, so effects and seed spread are',
         'measured on the same footing. Not comparable to the main table by absolute value.', '']

if not df_seed.empty:
    lines += ['## Mean +- std across seeds', '']
    metric_cols = [m for m in present]
    lines.append('| Arm | ' + ' | '.join(metric_cols) + ' |')
    lines.append('|---' * (len(metric_cols) + 1) + '|')
    for arm in df_seed.index:
        cells = []
        for m in metric_cols:
            mu, sd = df_seed.loc[arm, (m, 'mean')], df_seed.loc[arm, (m, 'std')]
            cells.append(f'{mu:.3f}+-{sd:.3f}' if pd.notna(mu) and pd.notna(sd)
                         else (f'{mu:.3f}' if pd.notna(mu) else '-'))
        lines.append(f'| {ARM_DISPLAY.get(arm, arm)} | ' + ' | '.join(cells) + ' |')
    lines.append('')

if not df_eff.empty:
    lines += ['## Effect size vs seed noise', '',
              '| Metric | Arm | full | arm | effect | x seed std |', '|---|---|---|---|---|---|']
    for _, r in df_eff.iterrows():
        ratio = f'{r["ratio_vs_full_std"]:.1f}x' if pd.notna(r['ratio_vs_full_std']) else '-'
        lines.append(f'| {r["metric"]} | {ARM_DISPLAY.get(r["arm"], r["arm"])} | '
                     f'{r["full_mean"]:.3f} | {r["arm_mean"]:.3f} | {r["effect"]:+.3f} | {ratio} |')
    lines.append('')

md = '\n'.join(lines)
with open(os.path.join(OUT_DIR, f'{DS}_seed_variance_summary.md'), 'w') as f:
    f.write(md)
print('saved ->', os.path.join(OUT_DIR, f'{DS}_seed_variance_summary.md'))
print()
print(md)

saved -> /content/drive/MyDrive/rebuttal_results/ablation_seeds/pancreas_seed_variance_summary.md

# Seed-variance check -- pancreas

3 seeds ([31, 1, 2]), Stage-1 shared across seeds, Stage-2 shortened to train_epochs=20.
Every arm runs at the same reduced setting, so effects and seed spread are
measured on the same footing. Not comparable to the main table by absolute value.

## Mean +- std across seeds

| Arm | modularity | purity | batch_entropy | coverage |
|---|---|---|---|---|
| Full model | 0.696+-0.006 | 0.916+-0.006 | 0.419+-0.037 | 0.976+-0.041 |
| - community loss | 0.499+-0.010 | 0.956+-0.001 | 0.478+-0.009 | 0.810+-0.041 |
| - nassoc | 0.698+-0.007 | 0.900+-0.025 | 0.420+-0.071 | 0.929+-0.000 |
| Stop-grad off | 0.626+-0.002 | 0.906+-0.005 | 0.578+-0.022 | 0.929+-0.000 |

## Effect size vs seed noise

| Metric | Arm | full | arm | effect | x seed std |
|---|---|---|---|---|---|
| batch_entropy | Stop-grad off | 0.419 | 0.578 | -0.159 | 4.3x |
| batch_entropy | - community loss | 0.419 | 0.478 | -0.059 | 1.6x |
| batch_entropy | - nassoc | 0.419 | 0.420 | -0.001 | 0.0x |
| coverage | - community loss | 0.976 | 0.810 | +0.167 | 4.0x |
| coverage | - nassoc | 0.976 | 0.929 | +0.048 | 1.2x |
| coverage | Stop-grad off | 0.976 | 0.929 | +0.048 | 1.2x |
| modularity | - community loss | 0.696 | 0.499 | +0.197 | 33.4x |
| modularity | Stop-grad off | 0.696 | 0.626 | +0.070 | 11.8x |
| modularity | - nassoc | 0.696 | 0.698 | -0.002 | 0.3x |
| purity | - community loss | 0.916 | 0.956 | -0.040 | 7.0x |
| purity | - nassoc | 0.916 | 0.900 | +0.016 | 2.8x |
| purity | Stop-grad off | 0.916 | 0.906 | +0.010 | 1.8x |