## Status (updated 2026-07-31) -- READ BEFORE RUNNING

Fixed since the original version: (1) modularity is now always scored against one canonical
ARBF-on-PCA graph, not whatever graph happened to be sitting on `ad.obsp['connectivities']`
last; (2) the `AnnData.__init__` dtype monkeypatch is guarded against re-run recursion.
Helper functions now live in `interpretable_ssl/evaluation/batch_correct_baselines.py`
(imported by the "Helper functions" cell below) instead of being defined inline here.

**Current run scope (set in the Config cell):** `CORRECTION_METHODS = ['harmony',
'scvi_gauss']`, `RUN_SEACELLS = True` -- scProto vs. {Harmony, scVI (Gaussian)} x
{SEACells, Leiden}. Plain ZINB `scvi` is deliberately left OUT of the display as of
2026-07-31 (having both scVI variants in every table at once was more confusing than
useful) -- its results are untouched on disk (`seacell_X_scvi` / `leiden_X_scvi_K{K}`)
and can be brought back any time by adding `'scvi'` back to `CORRECTION_METHODS`.
`harmony` already has a complete cached run on disk for all 3 RNA-seq datasets (verified
2026-07-30) -- with `SKIP_IF_EXISTS = True` it's a cheap metrics.json/cache reload, no
retraining. **`scvi_gauss` is the one thing this run actually computes** -- real scVI
model training with `gene_likelihood='normal'` instead of the ZINB default. `stage1z`
and `bbknn` are left out of `CORRECTION_METHODS` for now (stage1z's own results are
already available separately; bbknn's install is still unreliable, see pipInstall01) --
widen `CORRECTION_METHODS` to bring any of these back.

**Why `scvi_gauss` exists (2026-07-31):** scProto's Stage-1 pretrain uses `recon_loss='mse'`
on log-normalized expression (`defaults.py`), while plain scVI reconstructs raw counts under
a ZINB likelihood -- two different noise-model families, not just two different
architectures, which confounds "is scVI's batch-correction mechanism better" with "is ZINB
just a better-suited loss for scRNA-seq counts than MSE." `scvi_gauss` swaps in
`gene_likelihood='normal'` (Gaussian NLL, learned per-gene variance -- reduces to weighted
MSE) -- still scVI's real, unmodified architecture (same encoder, same
library-size-scaled/softmax decoder mean, same batch conditioning, same n_latent=8, same
epoch budget), just without the NB/zero-inflation shape. This is NOT a perfect match to
scProto's plain MSE-on-lognorm -- the decoder mean is still `library_size * softmax(...)`,
not an unconstrained prediction directly against log-normalized targets (stock scVI has no
supported way to bypass its library-size machinery) -- but it removes the single biggest
source of mismatch. Report it as "scVI (Gaussian)", not "scVI (MSE)". `stage1z`
(scProto's own actual MSE-on-lognorm Stage-1 encoder) remains the more literal MSE control
and needs no new training -- see its own results elsewhere in this notebook / the paper's
existing runs.

Data preprocessing for scVI (both variants): trains on `adata.layers['counts']` (verified
2026-07-31 to be genuine pre-normalization raw counts for all 3 datasets, not a copy of the
log-normalized `.X` -- see `add_scvi_emb`'s docstring), NOT `ad.X` (which is
log-normalized at the point this notebook's `ad` reaches `run_correction_method` --
`get_stage1_latent`/`get_preprocessed_adata` both load with `use_counts=False`). scVI's own
internal library-size normalization is what it uses raw counts for; feeding it
already-normalized data would double-normalize and break that machinery, hence the
raw-counts layer swap inside `add_scvi_emb` regardless of `gene_likelihood`.

Folder/cache naming: `scvi_gauss` never collides with plain `scvi` -- distinct tag
(`X_scvi_gauss` vs `X_scvi`), distinct cache files (`_cache_X_scvi_gauss_*` vs
`_cache_X_scvi_*`), distinct result folders (`seacell_X_scvi_gauss` /
`leiden_X_scvi_gauss_K{K}` vs `seacell_X_scvi` / `leiden_X_scvi_K{K}`). Both are 8-dim
(`n_latent=8`, matching scProto's own `latent_dims`), and both go through the exact same
downstream SEACells/Leiden pipeline (same K-matching, same canonical-modularity recompute,
same result tables below) as every other correction method here -- nothing method-specific
needed beyond `run_correction_method`'s new `scvi_gauss` branch.

If you already have this notebook open in another Colab tab, close it (or File > Revert)
first -- Colab autosaving from a stale tab can silently overwrite this file. Also note:
`rare_affinity_purity_{ds}.json` (the embedding-only rare-cell diagnostic a few cells down)
is a file SHARED with sibling baseline notebooks (e.g. `combat_then_cluster_baselines.ipynb`)
-- each overwrites it wholesale with whatever it computed, so if another such notebook runs
after this one, `scvi_gauss`'s row there can disappear even though its actual SEACells/Leiden
results (which live in their own per-method folders, never shared) are unaffected.

# Rebuttal experiment E1: batch-correct-then-cluster baselines -- {scPoli, Harmony, scVI, BBKNN} latent -> {SEACells, Leiden}

**Current default run scope:** the Config cell below currently sets `CORRECTION_METHODS = ['harmony', 'scvi', 'scvi_gauss']` and `RUN_SEACELLS = True` -- scProto vs. {Harmony, scVI (ZINB), scVI (Gaussian)} x {SEACells, Leiden}. `stage1z` and `bbknn` are left out for now (see Status cell above) -- widen `CORRECTION_METHODS` to bring them back.

**This is the single, merged notebook for E1.** It used to be split into two
notebooks (`e1_two_step_baseline_1_scpoli.ipynb` handling scPoli alone, `e1_two_step_baseline_2_harmony_scvi_bbknn.ipynb`
handling the other three) purely because scVI/Harmony/BBKNN need heavier installs -- that split caused real
maintenance risk (every helper function was duplicated near-verbatim across both files, so a bugfix in one could
silently not make it into the other -- this is exactly what happened with the Leiden resolution-search bug). Both
old notebooks are kept on disk for now as an execution-history archive but are superseded by this one; delete them
once this notebook's outputs are trusted.

**Purpose.** Reviewer F5RB (Q1): *"Please compare scProto with stronger two-step baselines, such as scPoli latent + SEACells, scVI
latent + SEACells, Harmony latent + SEACells, and BBKNN graph + SEACells."* e9Ho: *"K-means handicaps the baselines ... the
community-structure win is confounded with the clusterer, not the embedding."* This notebook runs exactly that: for each of
**4 batch-correction methods** (scPoli Stage-1, Harmony, scVI, BBKNN), get the corrected embedding/graph, then run
**2 graph-aware clustering methods** (SEACells, Leiden) on it -- replacing the paper's current weak `scPoli + K-means` baseline
with proper two-step baselines. In other words: does "correct the batch effect first, then find metacells" (the reviewers'
suggested alternative) work as well as scProto's joint approach?

**Per RNA-seq dataset (pancreas, lung, pbmc-immune), per correction method:**
- **scPoli Stage-1**: load the *existing* pretrain checkpoint (no retraining), encode cells -> latent `X_stage1z`.
- **Harmony**: PCA + `harmonypy.run_harmony` directly (pinned harmonypy==0.0.9; not routed through `scanpy.external.pp.harmony_integrate`, which hardcodes an output shape that silently breaks under newer harmonypy versions) -> `X_harmony`.
- **scVI**: trains a fresh scVI model (via this codebase's `embedding_metrics.add_scvi_emb`) -> `X_scvi`. Slower than the other methods -- it's actual model training, not a lookup. Two variants: plain `scvi` (scvi-tools' default ZINB reconstruction likelihood) and `scvi_gauss` (`gene_likelihood='normal'`, a Gaussian/MSE-like reconstruction on the same raw-count target, loss-matched closer to scProto's own `recon_loss='mse'` Stage-1 pretrain -- see the Status cell above for the full rationale/caveats). Both are 8-dim, matching scProto's latent.
- **BBKNN**: `scanpy.external.pp.bbknn` -> a batch-balanced kNN graph directly (no embedding step -- this graph itself is the affinity fed to SEACells/Leiden below).

For the embedding-based methods, **one** adaptive-RBF affinity graph is built per embedding (same construction SEACells/scProto
use by default -- see `method.tex` / `results.tex`: *"adaptive Gaussian kernel on PCA embeddings"*, here pointed at the corrected
embedding instead of PCA) and fed to **both** SEACells and Leiden, so any SEACells-vs-Leiden gap is purely the clustering algorithm,
never confounded with a different graph construction (directly answers e9Ho's "confounded with clusterer, not embedding").

**Leiden hits target K exactly.** `leiden_resolution_search` over-segments (pushes resolution up until the partition has
more communities than target K -- always achievable) then greedily merges whichever pair of clusters loses the LEAST
modularity, until exactly K clusters remain (same principle Louvain/Leiden's own multilevel algorithm uses internally to
build its hierarchy). An earlier version used plain resolution bisection with a fixed upper bound and silently landed at
~70-90 clusters when the target was 220-300 -- invalidating any modularity comparison, since modularity is not
resolution-invariant (fewer/larger clusters score higher on a fixed graph almost by construction). Do not reintroduce that
bug; always verify `n_clusters` in the saved metrics.json matches `target_k` before trusting a Leiden modularity number.

**Metrics: only what the paper already reports** -- no new diagnostics, except DGE consistency is turned off
(`compute_dge=False` everywhere) since it is not needed for this hypothesis test and was failing on non-lognormalized
data. `compute_task1_metrics` / `calc_task2_metrics` (same functions the paper's existing numbers come from -- see
`method.tex`'s community/nassoc/usage/recon losses section) give Modularity / Batch Entropy / Purity (Table 1) and
Coverage / scGraph (Table 2); `rare_celltype_purity_table` gives the per-batch rare-cell Coverage / Homogeneity
(`results.tex` Table 2, tab:rare_cells).

**On the modularity number specifically (e9Ho's point on this):** modularity here is scored against the
adaptive-RBF-on-PCA graph, which is the same graph scProto's `L_community` is trained to match every step. None of the
two-step baselines in this notebook get that training-time guidance -- they cluster a graph built from a *different*
embedding (scPoli/Harmony/scVI latent) that only gets scored against the PCA graph after the fact. That is not a
causally fair comparison to scProto, and should not be presented as one. Treat this modularity number as a plausibility
sanity check only (if a baseline that never sees the PCA graph can match or beat scProto's modularity against it, that
would already be surprising and worth flagging) -- not as the load-bearing evidence. The actual evidence for "does
batch-correct-then-cluster work as well as scProto" has to come from metrics no method gets a training-time advantage
on: cell-type purity, batch entropy, and especially the rare-cell coverage/homogeneity table, all computed identically,
post-hoc, for every method regardless of what it optimized during training.

**Before running:** assumes Stage-1 pretrain checkpoints already exist for pancreas / lung / pbmc-immune (`cvae_epochs=50`,
`batch_size=1024`, see `train_scproto.ipynb`) -- this notebook does not retrain Stage 1, only loads it.

**Outputs, per dataset, per method:**
- `MODEL_DIR/{ds}/seacell_X_{method}/` -- SEACells-on-{method} (metrics.json, umap_cells.csv, umap_protos.csv, ...)
- `MODEL_DIR/{ds}/leiden_X_{method}_K{K}/` -- Leiden-on-{method} (same file set)

## Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install -q scarches faiss-gpu-cu12 scib-metrics
!pip install git+https://github.com/dpeerlab/SEACells.git --quiet --no-deps
!pip install numpy scipy --upgrade -q
!pip install -q palantir harmonypy
!pip install -q "numpy==1.26.4" "scipy==1.13.1"
!pip install --upgrade --force-reinstall numpy cupy-cuda12x
!pip install "numpy<2.3"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 55.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.5/187.5 kB 30.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 118.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 90.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 119.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 116.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 185.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.2/711.2 kB 88.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 101.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 29.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/137.4 kB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 848.6/848.6 kB 103.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.9/155.9 kB 25.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 103.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 54.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 90.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 125.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 28.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 95.9 MB/s eta 0:00:00
  Building wheel for docrep (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
ibis-framework 9.5.0 requires toolz<1,>=0.11, but you have toolz 1.1.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
  Preparing metadata (setup.py) ... done
  Building wheel for SEACells (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 116.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 73.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires palantir, which is not installed.
seacells 0.3.3 requires pyranges, which is not installed.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.4/172.4 kB 29.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 111.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 68.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
scanpy 1.12.3 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
fast-array-utils 1.5 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
zarr 3.3.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
faiss-gpu-cu12 1.14.1.post1 requires numpy<3,>=2, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires numpy>=2.1, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Collecting numpy
  Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting cupy-cuda12x
  Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (2.8 kB)
Collecting cuda-pathfinder==1.*,>=1.3.4 (from cupy-cuda12x)
  Downloading cuda_pathfinder-1.6.0-py3-none-any.whl.metadata (1.9 kB)
Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl (133.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 MB 11.4 MB/s eta 0:00:00
Downloading cuda_pathfinder-1.6.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 7.0 MB/s eta 0:00:00
Installing collected packages: numpy, cuda-pathfinder, cupy-cuda12x
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: cuda-pathfinder
    Found existing installation: cuda-pathfinder 1.5.6
    Uninstalling cuda-pathfinder-1.5.6:
      Successfully uninstalled cuda-pathfinder-1.5.6
  Attempting uninstall: cupy-cuda12x
    Found existing installation: cupy-cuda12x 14.0.1
    Uninstalling cupy-cuda12x-14.0.1:
      Successfully uninstalled cupy-cuda12x-14.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.5.1 which is incompatible.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed cuda-pathfinder-1.6.0 cupy-cuda12x-14.1.1 numpy-2.5.1

Collecting numpy<2.3
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.9 MB/s eta 0:00:00
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 111.1 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.1
    Uninstalling numpy-2.5.1:
      Successfully uninstalled numpy-2.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed numpy-2.2.6

In [1]:
# IMPORTANT: restart the runtime after this cell before running the cells below --
# numpy/scipy/anndata are C-extension linked, an in-process upgrade alone won't
# reliably take effect on already-imported modules.

In [2]:
# Ground truth for "did the install cell above actually work" -- pip's own log is
# noisy (resolver backtracking prints "Getting requirements to build wheel" errors
# for discarded candidate versions even on a fully successful install), so eyeballing
# it is unreliable. Actually importing every package we just installed is the real
# test. No anndata.io/anndata.abc bridge needed anymore (removed -- that only
# existed to patch an old, explicitly-pinned anndata==0.10.6; the current install
# lets anndata resolve naturally to whatever scvi-tools/scarches need, which already
# has both natively). bbknn excluded here -- temporarily removed, see pipInstall01.
_checks = {
    'numpy': 'numpy', 'scipy': 'scipy', 'anndata': 'anndata', 'scanpy': 'scanpy',
    'scarches': 'scarches', 'scvi-tools': 'scvi', 'seacells': 'SEACells',
    'palantir': 'palantir', 'scib-metrics': 'scib_metrics', 'leidenalg': 'leidenalg',
    'python-igraph': 'igraph', 'umap-learn': 'umap', 'harmonypy': 'harmonypy',
    'faiss-cpu': 'faiss',
}
_failed = []
for pkg_name, import_name in _checks.items():
    try:
        mod = __import__(import_name)
        ver = getattr(mod, '__version__', '?')
        print(f"  OK   {pkg_name:16s} (import {import_name}, version {ver})")
    except Exception as e:
        _failed.append(pkg_name)
        print(f"  FAIL {pkg_name:16s} (import {import_name}): {type(e).__name__}: {e}")

if _failed:
    print(f"\n{len(_failed)} package(s) failed to import: {_failed} -- re-run that "
          f"package's specific pip install line above and check its full error "
          f"output before proceeding.")
else:
    print(f"\nAll {len(_checks)} packages import cleanly -- safe to continue.")

  OK   numpy            (import numpy, version 2.2.6)
  OK   scipy            (import scipy, version 1.13.1)

/tmp/ipykernel_1839/2506724420.py:20: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  ver = getattr(mod, '__version__', '?')
/tmp/ipykernel_1839/2506724420.py:20: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  ver = getattr(mod, '__version__', '?')

  OK   anndata          (import anndata, version 0.13.2)
  OK   scanpy           (import scanpy, version 1.12.3)

WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).

  FAIL scarches         (import scarches): ImportError: cannot import name 'read' from 'anndata' (/usr/local/lib/python3.12/dist-packages/anndata/__init__.py)
  OK   scvi-tools       (import scvi, version 1.5.0.post1)
  OK   seacells         (import SEACells, version 0.3.3)
  OK   palantir         (import palantir, version 1.4.5)
  OK   scib-metrics     (import scib_metrics, version 0.6.0)
  OK   leidenalg        (import leidenalg, version 0.12.0)
  OK   python-igraph    (import igraph, version 1.0.0)
  OK   umap-learn       (import umap, version 0.5.12)
  OK   harmonypy        (import harmonypy, version 2.0.0)
  OK   faiss-cpu        (import faiss, version 1.14.1)

1 package(s) failed to import: ['scarches'] -- re-run that package's specific pip install line above and check its full error output before proceeding.

In [3]:
%run /content/drive/MyDrive/codes/interpretable-prototype/notebooks/nb_setup.py

nb_setup done. Available: get_trainer, run_mc_task, fig_*, LAMBDA_PROTO_UMAP, LAMBDA_PROTO_UMAP_PRECON, LAMBDA_PARAM_UMAP, LAMBDA_RECON_ONLY, train_sure, eval_sure_task1/2/3
Configs: {'LAMBDA_PROTO_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'proto'}, 'LAMBDA_PARAM_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'embedding'}, 'LAMBDA_RECON_ONLY': {'lambda_umap': 0, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 1, 'lambda_proto_recon': 0.0}}

In [4]:
# Extra imports not already covered by nb_setup.py (which already pulls in
# run_mc_task, eval_seacell_task1/2/3, load_task1_multi, show_table, clean_run_names,
# rare_celltype_purity_table, TASK1_METRICS, TASK2_METRICS via
# `from interpretable_ssl.evaluation.paper_figures import *` and
# `from interpretable_ssl.evaluation.metric_helpers.result_tables import *`).
from interpretable_ssl.datasets.dataset_configs import DATASETS
from interpretable_ssl.configs.paths import get_dataset_model_dir

print("extra imports ready")

extra imports ready

## Config

Same hyperparameters `train_scproto.ipynb` used to produce the existing Stage-1 checkpoints for these three datasets
(`cvae_epochs=50`, `batch_size=1024`) -- must match, or `load_pretrain_checkpoint()` looks in the wrong folder. `K` (n_SEACells /
target Leiden cluster count) defaults to each dataset's `num_prototypes` from `DATASETS`, matching `results.tex`:
*"All baselines are configured to produce the same number of metacells K as scProto."*

In [5]:
RNA_SEQ_DATASETS = ['pancreas', 'lung', 'pbmc-immune']

SKIP_IF_EXISTS = True  # skip a baseline entirely (embedding + SEACells + Leiden) if its
                        # metrics.json already exists on disk -- re-running the dataset
                        # cell after a crash/interrupt never redoes already-saved work
                        # (matters most for scVI, the slow one: real model training).

# 'bbknn' TEMPORARILY REMOVED -- see pipInstall01's comment (suspected stale numpy/
# scipy pin in the bbknn package itself). Re-add once installable again.
# 'scvi' (plain ZINB) REMOVED FROM DISPLAY 2026-07-31 -- its results are still fully
# intact on disk (seacell_X_scvi / leiden_X_scvi_K{K}, untouched by this change) and
# can be brought back into the tables any time by adding 'scvi' below again; it's just
# not shown alongside 'scvi_gauss' right now since having both scVI variants in every
# table at once was more confusing than useful. 'scvi_gauss' (Gaussian likelihood,
# loss-matched closer to scProto's own MSE Stage-1 -- see Status cell) is the one
# scVI variant actually being compared against going forward.
# Full sweep -- restore this to also rerun stage1z / bring ZINB scVI back:
# CORRECTION_METHODS = ['stage1z', 'harmony', 'scvi', 'scvi_gauss']
CORRECTION_METHODS = ['harmony', 'scvi_gauss']
# -- 'harmony' already has a complete cached seacell_X_harmony_d8 / leiden_X_harmony_d8_K{K}
#    run on disk for all 3 RNA-seq datasets (verified 2026-07-30) -- with
#    SKIP_IF_EXISTS=True below, re-running it is just a metrics.json / cached-embedding
#    reload, NOT retraining. Nothing to do for it, it's here only so the result tables
#    below include it.
# -- 'scvi_gauss' is the one real compute here: scVI trained with gene_likelihood='normal'
#    (Gaussian reconstruction) instead of the ZINB default -- loss-matched closer to
#    scProto's own recon_loss='mse' Stage-1 pretrain (see the Status cell at the top of
#    this notebook for the full rationale/caveats: it removes the NB/zero-inflation
#    likelihood shape but is still library-size/softmax-coupled, so it's "scVI
#    (Gaussian)", not a literal MSE-on-lognorm match -- stage1z remains the more literal
#    MSE control). Same n_latent=8, same epoch budget, same reference/query split as the
#    ZINB run -- only gene_likelihood differs. Saved under its own tag (X_scvi_gauss),
#    never collides with the still-intact-on-disk plain-scvi (ZINB) cache/results.
METHOD_DISPLAY_NAMES = {
    'stage1z': 'scPoli (Stage-1)',
    'harmony': 'Harmony',
    'scvi': 'scVI',
    'scvi_gauss': 'scVI (Gaussian)',
    'bbknn': 'BBKNN',
}

RUN_SEACELLS = True  # also compute/load SEACells-on-{method}, not just Leiden.

## Helper functions

Moved to `interpretable_ssl/evaluation/batch_correct_baselines.py` (imported below) --
this notebook now only holds config + the per-dataset run/results cells. The module also
carries the two environment patches (SEACells' stray `dtype=` kwarg, Arrow-backed string
columns breaking the h5ad writer) that used to be separate cells here; they're applied
automatically on import.

In [6]:
from interpretable_ssl.evaluation.batch_correct_baselines import run_all_baselines_for_dataset

print("baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)")

baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)

## Run: Pancreas

In [7]:
pancreas_results = run_all_baselines_for_dataset(
    'pancreas', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS,
)

loading pancreas data
✅ Already subsetted to HVGs (4000 genes).

WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/16 [00:00<?, ?it/s]

=== [pancreas] batch-correction method: harmony ===
[pancreas] harmony_d8_k100: reusing cached embedding at /content/drive/MyDrive/models/pancreas/_cache_X_harmony_d8_k100_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] seacell_X_harmony_d8 already computed -- skipping (metrics.json found)
[pancreas] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl (nnz=1171528) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pancreas/seacell_X_harmony_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.18880866024666138 +/- 0.04495189131312506 (was 0.18880866024666138), K_target=220
[pancreas] leiden_X_harmony_d8 already computed -- skipping (found /content/drive/MyDrive/models/pancreas/leiden_X_harmony_d8_K220)
[/content/drive/MyDrive/models/pancreas/leiden_X_harmony_d8_K220] modularity recomputed against canonical graph: mean_modularity_batch=0.26263194765071124 +/- 0.05794787478703293 (was 0.26263194765071124), K_target=220

=== [pancreas] batch-correction method: scvi_gauss ===
adata.X max: 1453667.0
training scvi (gene_likelihood=normal) with ds size: 11783 and 25, 0

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: You are using a CUDA device ('NVIDIA RTX PRO 6000 Blackwell Server Edition') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:lightning.pytorch.utilities.rank_zero:You are using a CUDA device ('NVIDIA RTX PRO 6000 Blackwell Server Edition') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training:   0%|          | 0/25 [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=25` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=25` reached.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: `Trainer.fit` stopped: `max_epochs=0` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=0` reached.

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=16382  k=220  n_eigs=10  nnz=1082686  nnz/row=66.1
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 5411.08archetype/s]

[waypoint init] selected 220 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.35678
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 11 iterations.

100%|██████████| 220/220 [00:00<00:00, 726.40it/s]

saving to:  /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 3 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss ...
[seacell] unused protos: 0/220 (0.00%)
[seacell] mean cell-type purity: 0.9201  (size-weighted: 0.9327 ± 0.1334)
[seacell] mean batch entropy: 0.8007  (size-weighted: 0.8983 ± 0.4588)
[seacell] coverage: 0.6429
[seacell] modularity: 0.7345
[seacell] per-batch modularity: mean=0.7017, std=0.0328
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.8577 | saved to /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss
SEACell UMAP data saved to /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss
[/content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss] modularity recomputed against canonical graph: mean_modularity_batch=0.18940896671023708 +/- 0.021488448866820806 (was 0.7016787870932317), K_target=220
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_scvi_gauss ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_68ae59e7.h5ad
[seacell task2] coverage: 0.6429
[seacell task2] scgraph_corr_avg: 0.9351
[seacell task2] scgraph_corr_std: 0.0280
  [leiden oversegment] resolution=1.0000 -> 21 clusters (need >= 220)
  [leiden oversegment] resolution=2.0000 -> 33 clusters (need >= 220)
  [leiden oversegment] resolution=4.0000 -> 48 clusters (need >= 220)
  [leiden oversegment] resolution=8.0000 -> 81 clusters (need >= 220)
  [leiden oversegment] resolution=16.0000 -> 138 clusters (need >= 220)
  [leiden oversegment] resolution=32.0000 -> 219 clusters (need >= 220)
  [leiden oversegment] resolution=64.0000 -> 383 clusters (need >= 220)
  [leiden merge] -> 380 clusters (target 220)
  [leiden merge] -> 370 clusters (target 220)
  [leiden merge] -> 360 clusters (target 220)
  [leiden merge] -> 350 clusters (target 220)
  [leiden merge] -> 340 clusters (target 220)
  [leiden merge] -> 330 clusters (target 220)
  [leiden merge] -> 320 clusters (target 220)
  [leiden merge] -> 310 clusters (target 220)
  [leiden merge] -> 300 clusters (target 220)
  [leiden merge] -> 290 clusters (target 220)
  [leiden merge] -> 280 clusters (target 220)
  [leiden merge] -> 270 clusters (target 220)
  [leiden merge] -> 260 clusters (target 220)
  [leiden merge] -> 250 clusters (target 220)
  [leiden merge] -> 240 clusters (target 220)
  [leiden merge] -> 230 clusters (target 220)
  [leiden merge] -> 225 clusters (target 220)
  [leiden merge] -> 224 clusters (target 220)
  [leiden merge] -> 223 clusters (target 220)
  [leiden merge] -> 222 clusters (target 220)
  [leiden merge] -> 221 clusters (target 220)
  [leiden merge] -> 220 clusters (target 220)
[leiden merge-down] final: 220 clusters (target 220)
[leiden_X_scvi_gauss_K220] unused protos: 0/220 (0.00%)
[leiden_X_scvi_gauss_K220] mean cell-type purity: 0.9114  (size-weighted: 0.9434 ± 0.1180)
[leiden_X_scvi_gauss_K220] mean batch entropy: 0.9112  (size-weighted: 0.9448 ± 0.4457)
[leiden_X_scvi_gauss_K220] coverage: 0.7143
[leiden_X_scvi_gauss_K220] modularity: 0.4285
[leiden_X_scvi_gauss_K220] per-batch modularity: mean=0.3777, std=0.0873
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.8313 | saved to /content/drive/MyDrive/models/pancreas/leiden_X_scvi_gauss_K220/aff_dc_compactness.csv
[leiden_X_scvi_gauss_K220] saved metrics to /content/drive/MyDrive/models/pancreas/leiden_X_scvi_gauss_K220
[/content/drive/MyDrive/models/pancreas/leiden_X_scvi_gauss_K220] modularity recomputed against canonical graph: mean_modularity_batch=0.37772920746939637 +/- 0.08731469074563511 (was 0.37772920746939637), K_target=220

100%|██████████| 220/220 [00:00<00:00, 919.30it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_scvi_gauss: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_scvi_gauss] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pancreas/leiden_X_scvi_gauss_K220
[pancreas] leiden-on-X_scvi_gauss saved to /content/drive/MyDrive/models/pancreas/leiden_X_scvi_gauss_K220

[pancreas] rare-type kNN purity by method: {'raw_pca': 0.499, 'harmony': 0.24, 'scvi_gauss': 0.142}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] Raw PCA (uncorrected) (d=50): 0.385 +/- 0.164 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] scVI (Gaussian) (d=8): 0.246 +/- 0.276 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] Harmony (d=8): 0.297 +/- 0.129 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] scProto (d=8): 0.454 +/- 0.184 (n=8 batches)
[pancreas] affinity purity saved to /content/drive/MyDrive/models/pancreas/rare_affinity_purity_pancreas.json (merged with any existing entries from other runs/notebooks)

## Run: Lung

In [8]:
lung_results = run_all_baselines_for_dataset(
    'lung', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS,
)

loading lung data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading lung
loading lung data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [16]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.255/24.467/119.300, effk_med=63.8, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/lung/pretrain/pretrain_ds-lung_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'lung', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'batch'}
📊 EdgeDataset: 2447924 edges
   Weight range: [0.0137, 0.9491]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2447924 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//lung/proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/32 [00:00<?, ?it/s]

=== [lung] batch-correction method: harmony ===
[lung] harmony_d8_k100: reusing cached embedding at /content/drive/MyDrive/models/lung/_cache_X_harmony_d8_k100_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] seacell_X_harmony_d8 already computed -- skipping (metrics.json found)
[lung] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl (nnz=2480396) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/lung/seacell_X_harmony_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.20235484769869405 +/- 0.037729396486311934 (was 0.20235484769869405), K_target=300
[lung] leiden_X_harmony_d8 already computed -- skipping (found /content/drive/MyDrive/models/lung/leiden_X_harmony_d8_K300)
[/content/drive/MyDrive/models/lung/leiden_X_harmony_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.41932156109416646 +/- 0.15162658784094546 (was 0.41932156109416646), K_target=300

=== [lung] batch-correction method: scvi_gauss ===
adata.X max: 1873.0

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

training scvi (gene_likelihood=normal) with ds size: 29224 and 25, 0

Training:   0%|          | 0/25 [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=25` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=25` reached.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: `Trainer.fit` stopped: `max_epochs=0` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=0` reached.

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=32472  k=300  n_eigs=10  nnz=2154238  nnz/row=66.3
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 5108.46archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.51666
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 10 iterations.

100%|██████████| 300/300 [00:00<00:00, 337.21it/s]

saving to:  /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 1 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8193  (size-weighted: 0.7661 ± 0.2298)
[seacell] mean batch entropy: 1.1051  (size-weighted: 1.1900 ± 0.4484)
[seacell] coverage: 0.8824
[seacell] modularity: 0.7311
[seacell] per-batch modularity: mean=0.7091, std=0.0161
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=12.0718 | saved to /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss
SEACell UMAP data saved to /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss
[/content/drive/MyDrive/models/lung/seacell_X_scvi_gauss] modularity recomputed against canonical graph: mean_modularity_batch=0.13849869064077758 +/- 0.024122436819468632 (was 0.7091062193579882), K_target=300
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_scvi_gauss ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

Deleted: tmp_77448a7a.h5ad
[seacell task2] coverage: 0.8824
[seacell task2] scgraph_corr_avg: 0.8813
[seacell task2] scgraph_corr_std: 0.0839
  [leiden oversegment] resolution=1.0000 -> 24 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 37 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 55 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 89 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 148 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 259 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 459 clusters (need >= 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_scvi_gauss_K300] unused protos: 0/300 (0.00%)
[leiden_X_scvi_gauss_K300] mean cell-type purity: 0.7669  (size-weighted: 0.7803 ± 0.2132)
[leiden_X_scvi_gauss_K300] mean batch entropy: 1.1033  (size-weighted: 1.1857 ± 0.4552)
[leiden_X_scvi_gauss_K300] coverage: 0.8824
[leiden_X_scvi_gauss_K300] modularity: 0.3250
[leiden_X_scvi_gauss_K300] per-batch modularity: mean=0.2763, std=0.0909
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=9.0876 | saved to /content/drive/MyDrive/models/lung/leiden_X_scvi_gauss_K300/aff_dc_compactness.csv
[leiden_X_scvi_gauss_K300] saved metrics to /content/drive/MyDrive/models/lung/leiden_X_scvi_gauss_K300
[/content/drive/MyDrive/models/lung/leiden_X_scvi_gauss_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.2763320714053522 +/- 0.09085789524077226 (was 0.2763320714053522), K_target=300

100%|██████████| 300/300 [00:00<00:00, 451.52it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_scvi_gauss: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_scvi_gauss] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/lung/leiden_X_scvi_gauss_K300
[lung] leiden-on-X_scvi_gauss saved to /content/drive/MyDrive/models/lung/leiden_X_scvi_gauss_K300

[lung] rare-type kNN purity by method: {'raw_pca': 0.912, 'harmony': 0.414, 'scvi_gauss': 0.457}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] Raw PCA (uncorrected) (d=50): 0.559 +/- 0.194 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] scVI (Gaussian) (d=8): 0.424 +/- 0.138 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] Harmony (d=8): 0.423 +/- 0.095 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] scProto (d=8): 0.586 +/- 0.208 (n=15 batches)
[lung] affinity purity saved to /content/drive/MyDrive/models/lung/rare_affinity_purity_lung.json (merged with any existing entries from other runs/notebooks)

## Run: PBMC (Immune)

In [9]:
immune_results = run_all_baselines_for_dataset(
    'pbmc-immune', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS,
)

loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading pbmc-immune
loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [5]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=1.667/25.923/299.545, effk_med=62.9, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pbmc-immune/pretrain/pretrain_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pbmc-immune', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'study'}
📊 EdgeDataset: 2590828 edges
   Weight range: [0.0050, 0.9224]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2590828 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pbmc-immune/proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/33 [00:00<?, ?it/s]

=== [pbmc-immune] batch-correction method: harmony ===
[pbmc-immune] harmony_d8_k100: reusing cached embedding at /content/drive/MyDrive/models/pbmc-immune/_cache_X_harmony_d8_k100_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] seacell_X_harmony_d8 already computed -- skipping (metrics.json found)
[pbmc-immune] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl (nnz=2624382) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pbmc-immune/seacell_X_harmony_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.1829990712532604 +/- 0.02714317050553936 (was 0.1829990712532604), K_target=300
[pbmc-immune] leiden_X_harmony_d8 already computed -- skipping (found /content/drive/MyDrive/models/pbmc-immune/leiden_X_harmony_d8_K300)
[/content/drive/MyDrive/models/pbmc-immune/leiden_X_harmony_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.29666126687112104 +/- 0.1221249465662934 (was 0.29666126687112104), K_target=300

=== [pbmc-immune] batch-correction method: scvi_gauss ===
adata.X max: 73869.078125

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

training scvi (gene_likelihood=normal) with ds size: 26223 and 25, 0

Training:   0%|          | 0/25 [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=25` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=25` reached.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: `Trainer.fit` stopped: `max_epochs=0` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=0` reached.

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=33506  k=300  n_eigs=10  nnz=2244522  nnz/row=67.0
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 4926.02archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!
Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.53511
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 12 iterations.

100%|██████████| 300/300 [00:00<00:00, 349.33it/s]

saving to:  /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 3 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8328  (size-weighted: 0.7815 ± 0.1787)
[seacell] mean batch entropy: 0.4968  (size-weighted: 0.7386 ± 0.4274)
[seacell] coverage: 1.0000
[seacell] modularity: 0.6752
[seacell] per-batch modularity: mean=0.6535, std=0.0275
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=4.5813 | saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss
SEACell UMAP data saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss
[/content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss] modularity recomputed against canonical graph: mean_modularity_batch=0.11044877923216696 +/- 0.04346901417933053 (was 0.6534546594068267), K_target=300
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvi_gauss ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_5bc33906.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.8475
[seacell task2] scgraph_corr_std: 0.0392
  [leiden oversegment] resolution=1.0000 -> 19 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 31 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 56 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 93 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 162 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 292 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 535 clusters (need >= 300)
  [leiden merge] -> 530 clusters (target 300)
  [leiden merge] -> 520 clusters (target 300)
  [leiden merge] -> 510 clusters (target 300)
  [leiden merge] -> 500 clusters (target 300)
  [leiden merge] -> 490 clusters (target 300)
  [leiden merge] -> 480 clusters (target 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_scvi_gauss_K300] unused protos: 0/300 (0.00%)
[leiden_X_scvi_gauss_K300] mean cell-type purity: 0.7653  (size-weighted: 0.7799 ± 0.1684)
[leiden_X_scvi_gauss_K300] mean batch entropy: 0.7104  (size-weighted: 0.7256 ± 0.4342)
[leiden_X_scvi_gauss_K300] coverage: 1.0000
[leiden_X_scvi_gauss_K300] modularity: 0.3646
[leiden_X_scvi_gauss_K300] per-batch modularity: mean=0.3588, std=0.1527
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=2.4109 | saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvi_gauss_K300/aff_dc_compactness.csv
[leiden_X_scvi_gauss_K300] saved metrics to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvi_gauss_K300
[/content/drive/MyDrive/models/pbmc-immune/leiden_X_scvi_gauss_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.35879640128307877 +/- 0.15271107005374587 (was 0.35879640128307877), K_target=300

100%|██████████| 300/300 [00:00<00:00, 486.36it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_scvi_gauss: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_scvi_gauss] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvi_gauss_K300
[pbmc-immune] leiden-on-X_scvi_gauss saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvi_gauss_K300

[pbmc-immune] rare-type kNN purity by method: {'raw_pca': 0.776, 'stage1z': 0.698, 'harmony': 0.564, 'scvi_gauss': 0.434}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] Raw PCA (uncorrected) (d=50): 0.827 +/- 0.050 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] scVI (Gaussian) (d=8): 0.613 +/- 0.106 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] Harmony (d=8): 0.712 +/- 0.116 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] scProto (d=8): 0.849 +/- 0.085 (n=5 batches)
[pbmc-immune] affinity purity saved to /content/drive/MyDrive/models/pbmc-immune/rare_affinity_purity_pbmc-immune.json (merged with any existing entries from other runs/notebooks)

## Results comparison

Pulls in **every** existing run under `MODEL_DIR/{ds}/*` (scProto, SEACells(PCA), MetaQ, scPoli-cVAE, UMAP, ...) alongside the
8 new baselines computed above (4 correction methods x {SEACells, Leiden}) -- `load_task1_multi` / `rare_celltype_purity_table`
just scan folders + `metrics.json` / `umap_cells.csv`, they don't need to know these runs are new.

Keyword note: SEACells folders are `seacell_X_{method}`, Leiden folders are `leiden_X_{method}_K{n}` -- the full
`seacell_X_{method}` / `leiden_X_{method}` strings are used as match keywords below (not just `X_{method}`) so a SEACells run
can never accidentally substring-match its sibling Leiden run's folder name, or vice versa.

**Reminder (see intro cell):** the modularity column below is scored against the arbf-on-PCA graph that only scProto is
trained to match -- treat it as a plausibility check, not the primary evidence. Purity, batch entropy, and especially the
rare-cell coverage/homogeneity table (two cells down) are the fair, post-hoc comparison.

### Harmony + Leiden -- realized cluster count vs. scProto's target K

`leiden_resolution_search` targets scProto's own `num_prototypes` for this dataset exactly
(see intro cell) -- this checks it actually landed there for the Harmony run, and would
surface a mismatch if the resolution search's `max_res` cap were ever hit instead (see
`leiden_resolution_search`'s docstring in `batch_correct_baselines.py`). Reads directly
from each run's saved `metrics.json` (`n_clusters` / `resolution` fields written by
`run_leiden_on_latent`), so this works whether the run above was fresh or a
`skip_if_exists` cache hit -- and simply shows nothing for a dataset that hasn't been run yet.

In [10]:
target_k = {ds: DATASETS[ds]['num_prototypes'] for ds in RNA_SEQ_DATASETS}

df_harmony_k = load_task1_multi(RNA_SEQ_DATASETS, metrics=['n_clusters', 'resolution'])
if df_harmony_k.empty:
    print("No runs found yet under MODEL_DIR for RNA_SEQ_DATASETS -- run the 'Run: ...' "
          "cells above first.")
else:
    is_harmony_leiden = df_harmony_k.index.get_level_values('run').str.startswith('leiden_X_harmony')
    df_harmony_k = df_harmony_k[is_harmony_leiden].copy()
    if df_harmony_k.empty:
        print("No leiden_X_harmony run found yet for any dataset in RNA_SEQ_DATASETS -- "
              "run the 'Run: ...' cells above first (with 'harmony' in CORRECTION_METHODS).")
    else:
        df_harmony_k['target_k'] = [target_k[ds] for ds, _run in df_harmony_k.index]
        df_harmony_k['matches_target'] = df_harmony_k['n_clusters'] == df_harmony_k['target_k']
        display(df_harmony_k)

                                     n_clusters resolution  target_k  \
dataset     run
pancreas    leiden_X_harmony_K220         220.0       32.0       220
            leiden_X_harmony_d8_K220      220.0       32.0       220
lung        leiden_X_harmony_K300         300.0       64.0       300
            leiden_X_harmony_d8_K300      300.0       64.0       300
pbmc-immune leiden_X_harmony_K119         119.0   7.992236       300
            leiden_X_harmony_K300         300.0       16.0       300
            leiden_X_harmony_d8_K300      300.0       32.0       300

                                      matches_target
dataset     run
pancreas    leiden_X_harmony_K220               True
            leiden_X_harmony_d8_K220            True
lung        leiden_X_harmony_K300               True
            leiden_X_harmony_d8_K300            True
pbmc-immune leiden_X_harmony_K119              False
            leiden_X_harmony_K300               True
            leiden_X_harmony_d8_K300            True

### SEACells -- realized metacell count vs. scProto's target K (read-only, no recompute)

SEACells folders don't encode K in their name the way Leiden's do (`seacell_X_harmony`,
not `seacell_X_harmony_K300`), so a stale run from an old `num_prototypes` value can't be
spotted from the folder listing alone, and `metrics.json`'s own `K_target` field gets
silently overwritten to the current target on every `skip_if_exists` cache hit even for a
stale run -- see `get_realized_seacell_count`'s docstring in `batch_correct_baselines.py`.
This reads the actual realized count from each run's saved `cell_assignments.csv`
directly -- no archetypal analysis is re-run, this is purely a check of what's already on
disk. `RUN_SEACELLS` above only controls whether new SEACells runs execute; this cell
works regardless of that setting, checking whatever the last SEACells run for each
(dataset, method) actually produced.

In [11]:
from interpretable_ssl.evaluation.batch_correct_baselines import get_realized_seacell_count

seacell_k_rows = []
for ds_id in RNA_SEQ_DATASETS:
    for method in CORRECTION_METHODS:
        n_actual = get_realized_seacell_count(ds_id, f'X_{method}')
        k = target_k[ds_id]
        seacell_k_rows.append({
            'dataset': ds_id, 'method': method,
            'n_actual': n_actual, 'target_k': k,
            'matches_target': (n_actual is not None and abs(n_actual - k) <= 0.05 * k),
        })

df_seacell_k = pd.DataFrame(seacell_k_rows).set_index(['dataset', 'method'])
if df_seacell_k['n_actual'].isna().all():
    print("No seacell_X_{method} runs found on disk yet for RNA_SEQ_DATASETS/CORRECTION_METHODS.")
else:
    display(df_seacell_k)

                        n_actual  target_k  matches_target
dataset     method
pancreas    harmony          220       220            True
            scvi_gauss       220       220            True
lung        harmony          300       300            True
            scvi_gauss       300       300            True
pbmc-immune harmony          300       300            True
            scvi_gauss       300       300            True

In [12]:
dataset_display_names = {'pancreas': 'Pancreas', 'lung': 'Lung', 'pbmc-immune': 'Immune'}

# scProto runs verified against the paper's published numbers via generate_tables.ipynb
# (the actual notebook used to build the paper's tables -- it dumps every candidate run
# for manual reading, no auto-selection) and cross-checked against appendix/training.tex's
# described loss weights/hyperparameters -- these are NOT just "close", they're
# bit-identical to the published numbers on multiple metrics simultaneously per dataset.
SCPROTO_CANONICAL_RUNS = {
    'proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
    'proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
    'proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
}

# BUG FIX 2026-07-30: load_task1_df already runs every folder name through
# extract_model_key() (strips _ds-panc/_NP220/_cvae_e50/_v31 etc. so the SAME
# experiment aligns as one row across datasets) BEFORE this notebook ever sees the
# `run` index -- so matching against the raw folder names above (as this used to do)
# never matched anything, and scProto silently never appeared in Table 1/2. All three
# raw names normalize to one shared stripped key (that's the point of
# extract_model_key) -- computed here instead of re-hardcoded, and asserted so a
# future change to extract_model_key's patterns fails loudly instead of silently
# reintroducing this bug.
SCPROTO_KEY = extract_model_key(next(iter(SCPROTO_CANONICAL_RUNS)))
assert all(extract_model_key(r) == SCPROTO_KEY for r in SCPROTO_CANONICAL_RUNS), (
    "SCPROTO_CANONICAL_RUNS entries no longer normalize to one shared key -- "
    "extract_model_key's stripping patterns changed; update the scProto matching logic."
)

# One shared {run_prefix: display_name} map for scProto + SEACells(PCA) + one
# {SEACells, Leiden} entry per method currently in CORRECTION_METHODS -- built once
# here, reused by Table 1, Table 2, and the rare-cell-type table below (previously
# duplicated in each of those cells separately).
MODEL_KEYWORDS = {SCPROTO_KEY: 'scProto'}
MODEL_KEYWORDS['seacell'] = 'SEACells (PCA)'

# 'harmony' excluded from this generic loop on purpose: run_correction_method now
# corrects Harmony at scProto's own latent dimension instead of the usual 50 (see
# its harmony_n_comps docstring), so its folders are 'seacell_X_harmony_d{n}' /
# 'leiden_X_harmony_d{n}_K{K}', not the plain 'seacell_X_harmony' /
# 'leiden_X_harmony_K{K}' this loop would generate. One Harmony baseline, added
# explicitly below with its real (dimension-qualified) folder name -- not two.
for _method in CORRECTION_METHODS:
    if _method == 'harmony':
        continue
    _disp = METHOD_DISPLAY_NAMES[_method]
    MODEL_KEYWORDS[f'seacell_X_{_method}'] = f'SEACells ({_disp})'
    MODEL_KEYWORDS[f'leiden_X_{_method}']  = f'Leiden ({_disp})'

# HARMONY_DIM must match scProto's actual latent_dims (currently 8 for all three
# datasets here, per the Stage-1 pretrain params printed in the 'Run:' cells above)
# -- update this if that ever changes, since MODEL_KEYWORDS below is a literal
# string match, not computed dynamically like the .py code is.
HARMONY_DIM = 8
if 'harmony' in CORRECTION_METHODS:
    MODEL_KEYWORDS[f'seacell_X_harmony_d{HARMONY_DIM}'] = 'SEACells (Harmony)'
    MODEL_KEYWORDS[f'leiden_X_harmony_d{HARMONY_DIM}']  = 'Leiden (Harmony)'

def _keep_and_rename_runs(df, model_keywords=MODEL_KEYWORDS):
    """Filter load_task1_multi's output down to just the runs in model_keywords, and
    collapse each method's per-dataset '_K{n}' folder-name suffix (e.g.
    'leiden_X_harmony_K300' for one dataset vs '..._K220' for another, since target K
    is scProto's num_prototypes and differs by dataset) into ONE shared display row per
    method -- otherwise Table 1/2 fragment into a separate row per distinct K value
    instead of one compact row per method spanning all datasets.

    If more than one on-disk run for the same dataset maps to the same display name
    (e.g. a stale leiden_X_harmony_K* folder left over from an earlier num_prototypes
    value, alongside the current one), the extra row is dropped with a WARNING rather
    than silently picked or crashing show_table's unstack() on the duplicate index --
    investigate and clean up the stale run directory if you see that warning.
    """
    runs = df.index.get_level_values('run')
    datasets = df.index.get_level_values('dataset')
    stripped = runs.str.replace(r'_K\d+$', '', regex=True)
    keep_mask = stripped.isin(model_keywords)

    kept_runs, kept_datasets = runs[keep_mask], datasets[keep_mask]
    kept_display = stripped[keep_mask].map(model_keywords)

    out = df[keep_mask].copy()
    out.index = pd.MultiIndex.from_arrays([kept_datasets, kept_display], names=['dataset', 'run'])

    dupe_mask = out.index.duplicated(keep='first')
    if dupe_mask.any():
        stale = list(zip(kept_datasets[dupe_mask], kept_runs[dupe_mask], kept_display[dupe_mask]))
        print(f"WARNING: dropped {dupe_mask.sum()} duplicate (dataset, method) row(s) -- "
              f"likely a stale run at an old K value still on disk. "
              f"(dataset, on-disk folder, display name): {stale}")
        out = out[~dupe_mask]
    return out

# --- Table 1 (community structure / batch integration): modularity, batch entropy, purity ---
df_task1 = load_task1_multi(RNA_SEQ_DATASETS, metrics=TASK1_METRICS)
df_task1 = _keep_and_rename_runs(df_task1)
show_table(df_task1, metrics=TASK1_METRICS, dataset_display_names=dataset_display_names)

In [13]:
# --- Table 2 (metacell representation quality): coverage, scGraph (DGE consistency turned off, see intro) ---
# Filtered/renamed the same way as Table 1 -- see _keep_and_rename_runs (defined in the Table 1 cell above).
df_task2 = load_task1_multi(RNA_SEQ_DATASETS, metrics=TASK2_METRICS)
df_task2 = _keep_and_rename_runs(df_task2)
show_table(df_task2, metrics=TASK2_METRICS, dataset_display_names=dataset_display_names)

In [14]:
CORRECTION_METHODS

['harmony', 'scvi_gauss']

In [15]:
# --- Rare-cell-type table (the key hypothesis test): coverage + homogeneity + F1, same
# per-batch-rare-cell definition results.tex uses for Table 2 (tab:rare_cells) ---
#
# scProto keyword: three dataset-specific exact folder names, all mapped to
# display name 'scProto'. Verified:
# the computed numbers now match the paper's published Table 2 exactly (pancreas
# 0.66/0.54, lung 0.72/0.60, pbmc 1.00/0.86 -- coverage/homogeneity, bit-identical).
#
# batch_rare_f1_macro_mean added -- per-rare-type F1 (precision = purity of that type's
# dedicated metacell(s), recall = fraction of that type's cells that landed in one),
# macro-averaged across rare types, then mean+-std across batches. Can't be gamed by
# over-segmenting (hurts precision) or under-segmenting (hurts recall) the way coverage
# alone can -- see chat history for the full reasoning.
#
# batch_rare_cross_batch_homog_mean added -- same formula/denominator as homogeneity
# (fraction of a rare cell's metacell that shares its label), but the numerator only
# counts same-label metacell-mates from a DIFFERENT batch. Coverage/homogeneity/F1
# can all be satisfied by a method giving each batch's rare cells their own small
# same-batch-only cluster -- exactly the "no co-clustering" failure mode
# harmony_notes.md describes. This metric can't be gamed that way: same-batch
# same-label mates never count toward it, so it directly tests whether rare types
# are actually grouped WITH their cross-batch counterparts, not just clustered.
#
# df_rare.index deduplicated below as a defensive guard -- extract_model_key() strips
# dataset-specific tokens (ds-panc/NP220/cvae_e50/v31/...) before substring-matching,
# which risks >1 of the 3 scProto keywords independently resolving for the same
# dataset and producing duplicate (dataset, 'scProto') rows -- pandas' unstack() then
# raises ValueError on the duplicate MultiIndex. Deduplicating (keep='first') is a
# no-op if it turns out not to be needed, and prevents the crash either way.
# model_keywords: reuses MODEL_KEYWORDS built once in the Table 1 cell above (same
# scProto canonical runs + SEACells(PCA) + one {SEACells, Leiden} entry per method in
# CORRECTION_METHODS) -- no longer duplicated here.
df_rare = rare_celltype_purity_table(RNA_SEQ_DATASETS, model_keywords=MODEL_KEYWORDS, verbose=True)

_dupe_mask = df_rare.index.duplicated(keep='first')
if _dupe_mask.any():
    print(f"WARNING: dropped {_dupe_mask.sum()} duplicate row(s) from df_rare: "
          f"{df_rare.index[_dupe_mask].tolist()}")
    df_rare = df_rare[~_dupe_mask]

show_table(
    df_rare,
    metrics=[
        'batch_rare_coverage_mean', 'batch_rare_recall_macro_mean',
        'batch_rare_precision_macro_mean', 'batch_rare_homogeneity_mean',
        'batch_rare_cross_batch_homog_mean', 'batch_rare_f1_macro_mean',
    ],
    dataset_display_names=dataset_display_names,
)

  [scProto|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] resolving run dir ...
  [SEACells (scVI (Gaussian))|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] run dir resolved (0.0s)
  [Leiden (scVI (Gaussian))|pancreas] resolving run dir ...
  [SEACells (Harmony)|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] reading umap_cells.csv ...
  [Leiden (Harmony)|pancreas] resolving run dir ...  [scProto|lung] resolving run dir ...

  [SEACells (PCA)|lung] resolving run dir ...
  [SEACells (PCA)|lung] run dir resolved (0.0s)
  [SEACells (PCA)|lung] reading umap_cells.csv ...
  [scProto|lung] run dir resolved (0.0s)
  [scProto|lung] reading umap_cells.csv ...
  [SEACells (scVI (Gaussian))|pancreas] run dir resolved (0.0s)
  [Leiden (scVI (Gaussian))|pancreas] run dir resolved (0.0s)  [scProto|pancreas] run dir resolved (0.0s)
  [SEACells (Harmony)|pancreas] run dir resolved (0.0s)

  [SEACells (scVI (Gaussian))|pancreas] reading umap_cells.csv ...
  [Leiden (Harmony)|pancreas] run dir resolved (0.0s)
  [SEACells (Harmony)|pancreas] reading umap_cells.csv ...  [scProto|pancreas] reading umap_cells.csv ...

  [Leiden (scVI (Gaussian))|pancreas] reading umap_cells.csv ...
  [Leiden (Harmony)|pancreas] reading umap_cells.csv ...
  [SEACells (PCA)|pancreas] umap_cells.csv loaded (16382 rows, 0.2s)
  [SEACells (PCA)|pancreas] reading umap_protos.csv ...
  [SEACells (PCA)|lung] umap_cells.csv loaded (32472 rows, 0.3s)
  [SEACells (PCA)|lung] reading umap_protos.csv ...
  [SEACells (scVI (Gaussian))|pancreas] umap_cells.csv loaded (16382 rows, 0.3s)
  [SEACells (scVI (Gaussian))|pancreas] reading umap_protos.csv ...
  [scProto|pancreas] umap_cells.csv loaded (16382 rows, 0.3s)
  [scProto|pancreas] reading umap_protos.csv ...
  [scProto|lung] umap_cells.csv loaded (32472 rows, 0.3s)
  [scProto|lung] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 0.3s)
  [SEACells (Harmony)|pancreas] reading umap_protos.csv ...
  [Leiden (scVI (Gaussian))|pancreas] umap_cells.csv loaded (16382 rows, 0.4s)
  [Leiden (scVI (Gaussian))|pancreas] reading umap_protos.csv ...
  [Leiden (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 0.4s)
  [Leiden (Harmony)|pancreas] reading umap_protos.csv ...
  [SEACells (scVI (Gaussian))|pancreas] umap_protos.csv loaded (0.2s)
  [SEACells (scVI (Gaussian))|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (scVI (Gaussian))|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (scVI (Gaussian))|pancreas] label fractions done (0.0s)
  [SEACells (PCA)|lung] umap_protos.csv loaded (0.2s)
  [SEACells (PCA)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (PCA)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (scVI (Gaussian))|pancreas] done
  [SEACells (scVI (Gaussian))|lung] resolving run dir ...
  [SEACells (scVI (Gaussian))] ds=pancreas: coverage=0.25±0.31  repr macro=0.19±0.30  micro=0.19±0.30  homogeneity=0.19±0.30  cross_batch_homog=0.12±0.21  purity=0.52±0.29  recall=0.21±0.31  precision=0.28±0.29  F1=0.18±0.31
  [SEACells (scVI (Gaussian))|lung] run dir resolved (0.0s)
  [SEACells (scVI (Gaussian))|lung] reading umap_cells.csv ...
  [SEACells (PCA)|lung] label fractions done (0.0s)
  [SEACells (PCA)|pancreas] umap_protos.csv loaded (0.3s)
  [SEACells (PCA)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (PCA)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [scProto|lung] umap_protos.csv loaded (0.2s)
  [SEACells (PCA)|pancreas] label fractions done (0.0s)
  [scProto|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto|pancreas] umap_protos.csv loaded (0.3s)
  [scProto|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [scProto|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [scProto|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (PCA)|lung] done
  [Leiden (scVI (Gaussian))|lung] resolving run dir ...
  [SEACells (PCA)] ds=lung: coverage=0.52±0.23  repr macro=0.43±0.19  micro=0.47±0.24  homogeneity=0.47±0.24  cross_batch_homog=0.39±0.20  purity=0.90±0.03  recall=0.41±0.23  precision=0.90±0.04  F1=0.42±0.22
  [Leiden (scVI (Gaussian))|lung] run dir resolved (0.0s)
  [Leiden (scVI (Gaussian))|lung] reading umap_cells.csv ...
  [scProto|pancreas] label fractions done (0.0s)
  [scProto|lung] label fractions done (0.0s)
  [Leiden (scVI (Gaussian))|lung] umap_cells.csv loaded (32472 rows, 0.0s)
  [SEACells (Harmony)|pancreas] umap_protos.csv loaded (0.3s)
  [Leiden (scVI (Gaussian))|lung] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (PCA)|pancreas] done
  [SEACells (Harmony)|lung] resolving run dir ...
  [Leiden (scVI (Gaussian))|lung] umap_protos.csv loaded (0.0s)
  [SEACells (Harmony)|lung] run dir resolved (0.0s)
  [SEACells (PCA)] ds=pancreas: coverage=0.43±0.27  repr macro=0.39±0.20  micro=0.42±0.20  homogeneity=0.42±0.20  cross_batch_homog=0.22±0.10  purity=0.82±0.13  recall=0.41±0.24  precision=0.54±0.22  F1=0.37±0.25
  [Leiden (scVI (Gaussian))|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (Harmony)|lung] reading umap_cells.csv ...
  [Leiden (scVI (Gaussian))|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (Harmony)|pancreas] label fractions done (0.0s)
  [scProto|pancreas] done
  [Leiden (Harmony)|lung] resolving run dir ...
  [scProto] ds=pancreas: coverage=0.64±0.24  repr macro=0.53±0.17  micro=0.56±0.16  homogeneity=0.56±0.16  cross_batch_homog=0.32±0.18  purity=0.88±0.08  recall=0.54±0.20  precision=0.77±0.13  F1=0.54±0.21
  [Leiden (scVI (Gaussian))|lung] label fractions done (0.0s)
  [Leiden (Harmony)|lung] run dir resolved (0.0s)
  [Leiden (Harmony)|lung] reading umap_cells.csv ...
  [Leiden (Harmony)|pancreas] umap_protos.csv loaded (0.3s)
  [Leiden (scVI (Gaussian))|pancreas] umap_protos.csv loaded (0.3s)
  [Leiden (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (scVI (Gaussian))|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (scVI (Gaussian))|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [scProto|lung] done
  [scProto|pbmc-immune] resolving run dir ...
  [scProto] ds=lung: coverage=0.79±0.18  repr macro=0.56±0.20  micro=0.58±0.22  homogeneity=0.58±0.22  cross_batch_homog=0.51±0.20  purity=0.85±0.04  recall=0.60±0.23  precision=0.70±0.14  F1=0.60±0.18
  [Leiden (scVI (Gaussian))|pancreas] label fractions done (0.0s)  [Leiden (Harmony)|pancreas] label fractions done (0.0s)

  [SEACells (Harmony)|pancreas] done
  [SEACells (PCA)|pbmc-immune] resolving run dir ...
  [SEACells (Harmony)] ds=pancreas: coverage=0.56±0.28  repr macro=0.27±0.12  micro=0.29±0.12  homogeneity=0.29±0.12  cross_batch_homog=0.23±0.10  purity=0.56±0.16  recall=0.35±0.14  precision=0.36±0.18  F1=0.32±0.16
  [SEACells (PCA)|pbmc-immune] run dir resolved (0.0s)
  [SEACells (PCA)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (scVI (Gaussian))|lung] umap_cells.csv loaded (32472 rows, 0.3s)
  [SEACells (scVI (Gaussian))|lung] reading umap_protos.csv ...
  [Leiden (scVI (Gaussian))|lung] done
  [SEACells (scVI (Gaussian))|pbmc-immune] resolving run dir ...
  [Leiden (scVI (Gaussian))] ds=lung: coverage=0.58±0.28  repr macro=0.35±0.17  micro=0.38±0.20  homogeneity=0.38±0.20  cross_batch_homog=0.36±0.20  purity=0.75±0.07  recall=0.36±0.22  precision=0.57±0.12  F1=0.34±0.16
  [scProto|pbmc-immune] run dir resolved (0.1s)
  [Leiden (Harmony)|pancreas] done
  [scProto|pbmc-immune] reading umap_cells.csv ...
  [Leiden (scVI (Gaussian))|pbmc-immune] resolving run dir ...
  [Leiden (Harmony)] ds=pancreas: coverage=0.40±0.24  repr macro=0.21±0.09  micro=0.22±0.09  homogeneity=0.22±0.09  cross_batch_homog=0.19±0.08  purity=0.52±0.20  recall=0.28±0.19  precision=0.24±0.18  F1=0.22±0.17
  [Leiden (scVI (Gaussian))|pbmc-immune] run dir resolved (0.0s)
  [Leiden (scVI (Gaussian))|pbmc-immune] reading umap_cells.csv ...
  [Leiden (scVI (Gaussian))|pancreas] done
  [SEACells (Harmony)|pbmc-immune] resolving run dir ...
  [Leiden (scVI (Gaussian))] ds=pancreas: coverage=0.16±0.33  repr macro=0.21±0.29  micro=0.21±0.28  homogeneity=0.21±0.28  cross_batch_homog=0.14±0.20  purity=0.60±0.19  recall=0.14±0.32  precision=0.27±0.23  F1=0.14±0.30
  [SEACells (Harmony)|pbmc-immune] run dir resolved (0.0s)
  [SEACells (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (scVI (Gaussian))|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.0s)
  [Leiden (scVI (Gaussian))|pbmc-immune] reading umap_protos.csv ...
  [Leiden (scVI (Gaussian))|pbmc-immune] umap_protos.csv loaded (0.0s)
  [Leiden (scVI (Gaussian))|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (scVI (Gaussian))|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (scVI (Gaussian))|pbmc-immune] run dir resolved (0.1s)
  [SEACells (scVI (Gaussian))|pbmc-immune] reading umap_cells.csv ...
  [Leiden (scVI (Gaussian))|pbmc-immune] label fractions done (0.0s)
  [SEACells (scVI (Gaussian))|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.0s)
  [SEACells (scVI (Gaussian))|pbmc-immune] reading umap_protos.csv ...
  [SEACells (scVI (Gaussian))|pbmc-immune] umap_protos.csv loaded (0.0s)
  [SEACells (scVI (Gaussian))|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (scVI (Gaussian))|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (Harmony)|lung] umap_cells.csv loaded (32472 rows, 0.4s)
  [SEACells (Harmony)|lung] reading umap_protos.csv ...
  [Leiden (scVI (Gaussian))|pbmc-immune] done  [SEACells (scVI (Gaussian))|pbmc-immune] label fractions done (0.0s)

  [Leiden (Harmony)|pbmc-immune] resolving run dir ...
  [Leiden (scVI (Gaussian))] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.51±0.12  micro=0.52±0.12  homogeneity=0.52±0.12  cross_batch_homog=0.28±0.15  purity=0.73±0.20  recall=0.65±0.07  precision=0.72±0.09  F1=0.65±0.10
  [Leiden (Harmony)|pbmc-immune] run dir resolved (0.0s)
  [Leiden (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (scVI (Gaussian))|pbmc-immune] done
  [SEACells (scVI (Gaussian))] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.55±0.14  micro=0.57±0.13  homogeneity=0.57±0.13  cross_batch_homog=0.27±0.15  purity=0.74±0.16  recall=0.61±0.14  precision=0.75±0.12  F1=0.62±0.18
  [Leiden (Harmony)|lung] umap_cells.csv loaded (32472 rows, 0.4s)
  [Leiden (Harmony)|lung] reading umap_protos.csv ...
  [SEACells (PCA)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.3s)
  [SEACells (PCA)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (scVI (Gaussian))|lung] umap_protos.csv loaded (0.3s)
  [SEACells (scVI (Gaussian))|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (scVI (Gaussian))|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (scVI (Gaussian))|lung] label fractions done (0.0s)
  [SEACells (scVI (Gaussian))|lung] done
  [SEACells (scVI (Gaussian))] ds=lung: coverage=0.53±0.31  repr macro=0.36±0.18  micro=0.39±0.20  homogeneity=0.39±0.20  cross_batch_homog=0.37±0.20  purity=0.73±0.07  recall=0.35±0.23  precision=0.63±0.14  F1=0.35±0.20
  [scProto|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.3s)
  [scProto|pbmc-immune] reading umap_protos.csv ...
  [SEACells (PCA)|pbmc-immune] umap_protos.csv loaded (0.2s)
  [SEACells (PCA)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (PCA)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (PCA)|pbmc-immune] label fractions done (0.0s)
  [Leiden (Harmony)|lung] umap_protos.csv loaded (0.3s)
  [SEACells (PCA)|pbmc-immune] done  [Leiden (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']

  [Leiden (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (PCA)] ds=pbmc-immune: coverage=1.00±0.00  repr macro=0.84±0.08  micro=0.85±0.07  homogeneity=0.85±0.07  cross_batch_homog=0.12±0.17  purity=0.93±0.03  recall=0.87±0.09  precision=0.94±0.01  F1=0.88±0.08
  [Leiden (Harmony)|lung] label fractions done (0.0s)
  [SEACells (Harmony)|lung] umap_protos.csv loaded (0.4s)
  [SEACells (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.5s)
  [SEACells (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (Harmony)|lung] label fractions done (0.0s)
  [Leiden (Harmony)|lung] done
  [Leiden (Harmony)] ds=lung: coverage=0.43±0.26  repr macro=0.33±0.10  micro=0.34±0.08  homogeneity=0.34±0.08  cross_batch_homog=0.33±0.09  purity=0.69±0.09  recall=0.31±0.17  precision=0.49±0.13  F1=0.28±0.14
  [Leiden (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.4s)
  [Leiden (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [scProto|pbmc-immune] umap_protos.csv loaded (0.2s)
  [scProto|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [scProto|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (Harmony)|lung] done
  [SEACells (Harmony)] ds=lung: coverage=0.54±0.19  repr macro=0.36±0.10  micro=0.40±0.12  homogeneity=0.40±0.12  cross_batch_homog=0.37±0.12  purity=0.73±0.07  recall=0.38±0.17  precision=0.62±0.11  F1=0.36±0.14
  [scProto|pbmc-immune] label fractions done (0.0s)
  [scProto|pbmc-immune] done
  [scProto] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.81±0.11  micro=0.83±0.10  homogeneity=0.83±0.10  cross_batch_homog=0.35±0.20  purity=0.92±0.08  recall=0.88±0.12  precision=0.90±0.03  F1=0.85±0.14
  [SEACells (Harmony)|pbmc-immune] umap_protos.csv loaded (0.3s)
  [SEACells (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (Harmony)|pbmc-immune] label fractions done (0.0s)
  [SEACells (Harmony)|pbmc-immune] done
  [SEACells (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.65±0.17  micro=0.68±0.19  homogeneity=0.68±0.19  cross_batch_homog=0.25±0.15  purity=0.82±0.10  recall=0.77±0.15  precision=0.81±0.08  F1=0.75±0.16
  [Leiden (Harmony)|pbmc-immune] umap_protos.csv loaded (0.3s)
  [Leiden (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [Leiden (Harmony)|pbmc-immune] label fractions done (0.0s)
  [Leiden (Harmony)|pbmc-immune] done
  [Leiden (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.61±0.11  micro=0.64±0.13  homogeneity=0.64±0.13  cross_batch_homog=0.30±0.18  purity=0.79±0.14  recall=0.80±0.12  precision=0.75±0.15  F1=0.75±0.17

In [16]:
# --- Significance test on the rare-cell F1/homogeneity table above ---
# Paired one-sided Mann-Whitney U (H1: scProto > other), Bonferroni-corrected across
# the non-ref methods compared within each (dataset, metric) group -- same convention
# already used for the spatial Fig. 3 significance test elsewhere in this codebase.
# Needs df_rare's raw '_batch_rare_f1_macro_per_batch' / '_batch_rare_homogeneity_per_batch'
# list columns (kept by default, not the display-filtered show_table view above) --
# uses the same df_rare computed in rareTableCell01, so run that cell first.
from interpretable_ssl.evaluation.paper_figures import rare_metric_significance

df_sig = rare_metric_significance(
    df_rare,
    ref_name='scProto',
    metrics=(
        '_batch_rare_f1_macro_per_batch',
        '_batch_rare_homogeneity_per_batch',
        '_batch_rare_cross_batch_homog_per_batch',
    ),
    dataset_display_names=dataset_display_names,
)
df_sig

,dataset,metric,method,k,n,median,mean,std,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,scProto,219,8,0.437680,0.535403,0.207961,NaN,NaN,NaN
1,Pancreas,batch_rare_f1_macro,SEACells (PCA),220,8,0.372628,0.370589,0.250869,0.032643,0.163214,ns
2,Pancreas,batch_rare_f1_macro,SEACells (scVI (Gaussian)),220,8,0.080208,0.177817,0.305975,0.006657,0.033283,*
3,Pancreas,batch_rare_f1_macro,Leiden (scVI (Gaussian)),220,8,0.000000,0.136982,0.296791,0.004122,0.020610,*
4,Pancreas,batch_rare_f1_macro,SEACells (Harmony),220,8,0.295521,0.316501,0.159421,0.014064,0.070319,ns
5,Pancreas,batch_rare_f1_macro,Leiden (Harmony),220,8,0.133361,0.223580,0.171156,0.002331,0.011655,*
6,Pancreas,batch_rare_homogeneity,scProto,219,8,0.522129,0.564854,0.155263,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,SEACells (PCA),220,8,0.369265,0.420592,0.195138,0.010334,0.051671,ns
8,Pancreas,batch_rare_homogeneity,SEACells (scVI (Gaussian)),220,8,0.073982,0.188286,0.298413,0.005206,0.026030,*
9,Pancreas,batch_rare_homogeneity,Leiden (scVI (Gaussian)),220,8,0.118845,0.214499,0.284644,0.005206,0.026030,*
10,Pancreas,batch_rare_homogeneity,SEACells (Harmony),220,8,0.269034,0.285358,0.115015,0.000932,0.004662,**
11,Pancreas,batch_rare_homogeneity,Leiden (Harmony),220,8,0.220189,0.218359,0.085397,0.000155,0.000777,***
12,Pancreas,batch_rare_cross_batch_homog,scProto,219,8,0.259411,0.322859,0.179414,NaN,NaN,NaN
13,Pancreas,batch_rare_cross_batch_homog,SEACells (PCA),220,8,0.212005,0.221772,0.100594,0.139316,0.696581,ns
14,Pancreas,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),220,8,0.041038,0.124562,0.213338,0.005206,0.026030,*
15,Pancreas,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),220,8,0.063618,0.141228,0.203271,0.007382,0.036908,*
16,Pancreas,batch_rare_cross_batch_homog,SEACells (Harmony),220,8,0.210341,0.227762,0.098150,0.097436,0.487179,ns
17,Pancreas,batch_rare_cross_batch_homog,Leiden (Harmony),220,8,0.183894,0.188323,0.084876,0.052448,0.262238,ns
18,Lung,batch_rare_f1_macro,scProto,298,15,0.610777,0.599348,0.175935,NaN,NaN,NaN
19,Lung,batch_rare_f1_macro,SEACells (PCA),300,15,0.498294,0.420330,0.217382,0.040680,0.203398,ns
20,Lung,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,15,0.342397,0.351520,0.195825,0.001069,0.005344,**
21,Lung,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,15,0.298562,0.343621,0.164360,0.000389,0.001945,**
22,Lung,batch_rare_f1_macro,SEACells (Harmony),300,15,0.348333,0.357564,0.144189,0.000606,0.003030,**
23,Lung,batch_rare_f1_macro,Leiden (Harmony),300,15,0.282094,0.280384,0.141206,0.000034,0.000170,***
24,Lung,batch_rare_homogeneity,scProto,298,15,0.586120,0.577994,0.220956,NaN,NaN,NaN
25,Lung,batch_rare_homogeneity,SEACells (PCA),300,15,0.495372,0.472356,0.242324,0.140421,0.702105,ns
26,Lung,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,15,0.385405,0.386730,0.202635,0.015508,0.077542,ns
27,Lung,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,15,0.326560,0.380982,0.195458,0.012551,0.062757,ns
28,Lung,batch_rare_homogeneity,SEACells (Harmony),300,15,0.408222,0.402522,0.115704,0.009033,0.045167,*
29,Lung,batch_rare_homogeneity,Leiden (Harmony),300,15,0.344610,0.344719,0.084300,0.000933,0.004664,**
30,Lung,batch_rare_cross_batch_homog,scProto,298,15,0.509701,0.508327,0.196956,NaN,NaN,NaN
31,Lung,batch_rare_cross_batch_homog,SEACells (PCA),300,15,0.415586,0.393655,0.201346,0.073288,0.366440,ns
32,Lung,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,15,0.376639,0.365457,0.199952,0.040747,0.203737,ns
33,Lung,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,15,0.318222,0.359455,0.200846,0.028196,0.140981,ns
34,Lung,batch_rare_cross_batch_homog,SEACells (Harmony),300,15,0.398968,0.371869,0.121918,0.013963,0.069813,ns
35,Lung,batch_rare_cross_batch_homog,Leiden (Harmony),300,15,0.341005,0.328868,0.089351,0.001845,0.009226,**
36,Immune,batch_rare_f1_macro,scProto,294,5,0.896681,0.854140,0.138252,NaN,NaN,NaN
37,Immune,batch_rare_f1_macro,SEACells (PCA),300,5,0.922877,0.879883,0.082663,0.579365,1.000000,ns
38,Immune,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,5,0.651993,0.623414,0.177152,0.047619,0.238095,ns
39,Immune,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,5,0.675523,0.650881,0.099053,0.047619,0.238095,ns
40,Immune,batch_rare_f1_macro,SEACells (Harmony),300,5,0.812234,0.750774,0.162481,0.154762,0.773810,ns
41,Immune,batch_rare_f1_macro,Leiden (Harmony),300,5,0.765805,0.751472,0.166212,0.210317,1.000000,ns
42,Immune,batch_rare_homogeneity,scProto,294,5,0.855792,0.827192,0.101982,NaN,NaN,NaN
43,Immune,batch_rare_homogeneity,SEACells (PCA),300,5,0.815416,0.854752,0.073552,0.726190,1.000000,ns
44,Immune,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,5,0.581696,0.567966,0.131954,0.007937,0.039683,*
45,Immune,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,5,0.538280,0.520888,0.119735,0.007937,0.039683,*
46,Immune,batch_rare_homogeneity,SEACells (Harmony),300,5,0.804136,0.676898,0.185473,0.111111,0.555556,ns
47,Immune,batch_rare_homogeneity,Leiden (Harmony),300,5,0.706627,0.635473,0.125110,0.027778,0.138889,ns
48,Immune,batch_rare_cross_batch_homog,scProto,294,5,0.406766,0.349204,0.197947,NaN,NaN,NaN
49,Immune,batch_rare_cross_batch_homog,SEACells (PCA),300,5,0.028607,0.120662,0.166976,0.172871,0.864355,ns
50,Immune,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,5,0.347206,0.273950,0.149657,0.231672,1.000000,ns
51,Immune,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,5,0.344439,0.275207,0.152992,0.231672,1.000000,ns
52,Immune,batch_rare_cross_batch_homog,SEACells (Harmony),300,5,0.304594,0.245410,0.153361,0.273810,1.000000,ns
53,Immune,batch_rare_cross_batch_homog,Leiden (Harmony),300,5,0.372796,0.304595,0.181786,0.458281,1.000000,ns

In [17]:
# --- PAIRED version of the test above (recommended) ---
# The test above (rare_metric_significance) is UNPAIRED Mann-Whitney U, despite its
# own docstring calling it "paired". Since scProto and each baseline are scored on
# the exact same batches, a genuinely PAIRED test (Wilcoxon signed-rank on the
# per-batch differences) removes shared batch-to-batch variance from the comparison
# and has more power on this exact same data -- no new runs needed. See
# rare_metric_significance_paired's docstring in paper_figures.py for the full
# reasoning. Also adds n_wins: how many of the n batches scProto's value beats the
# baseline's outright -- easy to read even when p_adj stays 'ns'.
from interpretable_ssl.evaluation.paper_figures import rare_metric_significance_paired

df_sig_paired = rare_metric_significance_paired(
    df_rare,
    ref_name='scProto',
    metrics=(
        '_batch_rare_f1_macro_per_batch',
        '_batch_rare_homogeneity_per_batch',
        '_batch_rare_cross_batch_homog_per_batch',
    ),
    dataset_display_names=dataset_display_names,
)
df_sig_paired

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,scProto,219,8,0.437680,0.535403,0.207961,NaN,NaN,NaN,NaN
1,Pancreas,batch_rare_f1_macro,SEACells (PCA),220,8,0.372628,0.370589,0.250869,6.0,0.039062,0.195312,ns
2,Pancreas,batch_rare_f1_macro,SEACells (scVI (Gaussian)),220,8,0.080208,0.177817,0.305975,7.0,0.007812,0.039062,*
3,Pancreas,batch_rare_f1_macro,Leiden (scVI (Gaussian)),220,8,0.000000,0.136982,0.296791,8.0,0.003906,0.019531,*
4,Pancreas,batch_rare_f1_macro,SEACells (Harmony),220,8,0.295521,0.316501,0.159421,7.0,0.011719,0.058594,ns
5,Pancreas,batch_rare_f1_macro,Leiden (Harmony),220,8,0.133361,0.223580,0.171156,8.0,0.003906,0.019531,*
6,Pancreas,batch_rare_homogeneity,scProto,219,8,0.522129,0.564854,0.155263,NaN,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,SEACells (PCA),220,8,0.369265,0.420592,0.195138,8.0,0.003906,0.019531,*
8,Pancreas,batch_rare_homogeneity,SEACells (scVI (Gaussian)),220,8,0.073982,0.188286,0.298413,7.0,0.007812,0.039062,*
9,Pancreas,batch_rare_homogeneity,Leiden (scVI (Gaussian)),220,8,0.118845,0.214499,0.284644,7.0,0.007812,0.039062,*
10,Pancreas,batch_rare_homogeneity,SEACells (Harmony),220,8,0.269034,0.285358,0.115015,8.0,0.003906,0.019531,*
11,Pancreas,batch_rare_homogeneity,Leiden (Harmony),220,8,0.220189,0.218359,0.085397,8.0,0.003906,0.019531,*
12,Pancreas,batch_rare_cross_batch_homog,scProto,219,8,0.259411,0.322859,0.179414,NaN,NaN,NaN,NaN
13,Pancreas,batch_rare_cross_batch_homog,SEACells (PCA),220,8,0.212005,0.221772,0.100594,5.0,0.125000,0.625000,ns
14,Pancreas,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),220,8,0.041038,0.124562,0.213338,8.0,0.003906,0.019531,*
15,Pancreas,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),220,8,0.063618,0.141228,0.203271,8.0,0.003906,0.019531,*
16,Pancreas,batch_rare_cross_batch_homog,SEACells (Harmony),220,8,0.210341,0.227762,0.098150,6.0,0.074219,0.371094,ns
17,Pancreas,batch_rare_cross_batch_homog,Leiden (Harmony),220,8,0.183894,0.188323,0.084876,6.0,0.039062,0.195312,ns
18,Lung,batch_rare_f1_macro,scProto,298,15,0.610777,0.599348,0.175935,NaN,NaN,NaN,NaN
19,Lung,batch_rare_f1_macro,SEACells (PCA),300,15,0.498294,0.420330,0.217382,11.0,0.001678,0.008392,**
20,Lung,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,15,0.342397,0.351520,0.195825,15.0,0.000031,0.000153,***
21,Lung,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,15,0.298562,0.343621,0.164360,15.0,0.000031,0.000153,***
22,Lung,batch_rare_f1_macro,SEACells (Harmony),300,15,0.348333,0.357564,0.144189,13.0,0.000763,0.003815,**
23,Lung,batch_rare_f1_macro,Leiden (Harmony),300,15,0.282094,0.280384,0.141206,13.0,0.000305,0.001526,**
24,Lung,batch_rare_homogeneity,scProto,298,15,0.586120,0.577994,0.220956,NaN,NaN,NaN,NaN
25,Lung,batch_rare_homogeneity,SEACells (PCA),300,15,0.495372,0.472356,0.242324,13.0,0.002686,0.013428,*
26,Lung,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,15,0.385405,0.386730,0.202635,14.0,0.000092,0.000458,***
27,Lung,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,15,0.326560,0.380982,0.195458,15.0,0.000031,0.000153,***
28,Lung,batch_rare_homogeneity,SEACells (Harmony),300,15,0.408222,0.402522,0.115704,14.0,0.002136,0.010681,*
29,Lung,batch_rare_homogeneity,Leiden (Harmony),300,15,0.344610,0.344719,0.084300,13.0,0.000763,0.003815,**
30,Lung,batch_rare_cross_batch_homog,scProto,298,15,0.509701,0.508327,0.196956,NaN,NaN,NaN,NaN
31,Lung,batch_rare_cross_batch_homog,SEACells (PCA),300,15,0.415586,0.393655,0.201346,12.0,0.001678,0.008392,**
32,Lung,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,15,0.376639,0.365457,0.199952,13.0,0.000153,0.000763,***
33,Lung,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,15,0.318222,0.359455,0.200846,14.0,0.000061,0.000305,***
34,Lung,batch_rare_cross_batch_homog,SEACells (Harmony),300,15,0.398968,0.371869,0.121918,14.0,0.003357,0.016785,*
35,Lung,batch_rare_cross_batch_homog,Leiden (Harmony),300,15,0.341005,0.328868,0.089351,13.0,0.003357,0.016785,*
36,Immune,batch_rare_f1_macro,scProto,294,5,0.896681,0.854140,0.138252,NaN,NaN,NaN,NaN
37,Immune,batch_rare_f1_macro,SEACells (PCA),300,5,0.922877,0.879883,0.082663,2.0,0.687500,1.000000,ns
38,Immune,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,5,0.651993,0.623414,0.177152,5.0,0.031250,0.156250,ns
39,Immune,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,5,0.675523,0.650881,0.099053,5.0,0.031250,0.156250,ns
40,Immune,batch_rare_f1_macro,SEACells (Harmony),300,5,0.812234,0.750774,0.162481,4.0,0.062500,0.312500,ns
41,Immune,batch_rare_f1_macro,Leiden (Harmony),300,5,0.765805,0.751472,0.166212,4.0,0.062500,0.312500,ns
42,Immune,batch_rare_homogeneity,scProto,294,5,0.855792,0.827192,0.101982,NaN,NaN,NaN,NaN
43,Immune,batch_rare_homogeneity,SEACells (PCA),300,5,0.815416,0.854752,0.073552,3.0,0.687500,1.000000,ns
44,Immune,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,5,0.581696,0.567966,0.131954,5.0,0.031250,0.156250,ns
45,Immune,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,5,0.538280,0.520888,0.119735,5.0,0.031250,0.156250,ns
46,Immune,batch_rare_homogeneity,SEACells (Harmony),300,5,0.804136,0.676898,0.185473,5.0,0.031250,0.156250,ns
47,Immune,batch_rare_homogeneity,Leiden (Harmony),300,5,0.706627,0.635473,0.125110,5.0,0.031250,0.156250,ns
48,Immune,batch_rare_cross_batch_homog,scProto,294,5,0.406766,0.349204,0.197947,NaN,NaN,NaN,NaN
49,Immune,batch_rare_cross_batch_homog,SEACells (PCA),300,5,0.028607,0.120662,0.166976,3.0,0.072064,0.360318,ns
50,Immune,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,5,0.347206,0.273950,0.149657,4.0,0.033945,0.169723,ns
51,Immune,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,5,0.344439,0.275207,0.152992,4.0,0.033945,0.169723,ns
52,Immune,batch_rare_cross_batch_homog,SEACells (Harmony),300,5,0.304594,0.245410,0.153361,3.0,0.156250,0.781250,ns
53,Immune,batch_rare_cross_batch_homog,Leiden (Harmony),300,5,0.372796,0.304595,0.181786,2.0,0.232604,1.000000,ns

In [18]:
# --- Embedding-level rare-cell kNN purity: was structure already lost before any
# clustering ran? (no clustering involved in this check) ---
rows = []
for ds_id in RNA_SEQ_DATASETS:
    path = os.path.join(get_dataset_model_dir(ds_id), f'rare_knn_purity_{ds_id}.json')
    if not os.path.exists(path):
        continue
    d = json.load(open(path))
    rows.append({'dataset': ds_id, **{m: v['mean_purity'] for m, v in d.items()}})

pd.DataFrame(rows).set_index('dataset')

              raw_pca   harmony  scvi_gauss   stage1z     scvi
dataset
pancreas     0.499371  0.239623    0.147170  0.579874  0.45283
lung         0.912445  0.414134    0.456534  0.696960      NaN
pbmc-immune  0.776144  0.564410    0.433785  0.697679      NaN

## Embedding-only rare-cell affinity purity (no downstream clustering)

F1/homogeneity in the rare-cell table above is a *pipeline*-level metric -- it bundles
embedding quality with whichever downstream clustering algorithm ran on top (SEACells'
archetypal search vs. Leiden's modularity optimization vs. scProto's own trained,
joint assignment -- three different mechanisms, each with independent rare-state
handling behavior, sitting on top of one shared metric). This section isolates the
embedding: for each method's raw embedding, build one ARBF affinity graph directly on
it (no SEACells/Leiden/prototype-assignment step involved), then for each
locally-rare-type cell score what fraction of its total affinity MASS goes to
same-type cells. Also includes a dimensionality-MATCHED Harmony/PCA control at
scProto's own latent dimension, since scProto's latent (d=8) vs. Harmony's usual
embedding (d=50) isn't an apples-to-apples comparison on its own.

**No separate step to run here** -- `compute_and_save_embedding_affinity_purity`
(`interpretable_ssl/evaluation/batch_correct_baselines.py`) now runs automatically at
the end of `run_all_baselines_for_dataset`, so it already ran as part of the
`Run: Pancreas` / `Run: Lung` / `Run: PBMC (Immune)` cells above and saved its results
to `rare_affinity_purity_{ds_id}.json` per dataset. The cell below just loads and
displays those files -- rerun the `Run:` cells above if you need fresh numbers.

In [19]:
from interpretable_ssl.evaluation.batch_correct_baselines import load_and_compare_affinity_purity

df_affinity_purity = load_and_compare_affinity_purity(
    RNA_SEQ_DATASETS, dataset_display_names=dataset_display_names,
)
df_affinity_purity

,dataset,method,dim,n,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,Raw PCA (uncorrected),50,8,0.385,0.164,7.0,0.0742,0.3711,ns
1,Pancreas,scProto,8,8,0.454,0.184,NaN,NaN,NaN,NaN
2,Pancreas,scVI (Gaussian),8,8,0.261,0.267,7.0,0.0078,0.0391,*
3,Pancreas,Harmony,8,8,0.297,0.129,7.0,0.0195,0.0977,ns
4,Pancreas,scPoli (Stage-1),8,8,0.512,0.162,3.0,0.8750,1.0000,ns
5,Pancreas,scVI,8,8,0.365,0.175,8.0,0.0039,0.0195,*
6,Lung,Raw PCA (uncorrected),50,15,0.559,0.194,11.0,0.0240,0.0958,ns
7,Lung,scProto,8,15,0.586,0.208,NaN,NaN,NaN,NaN
8,Lung,scVI (Gaussian),8,15,0.424,0.138,14.0,0.0002,0.0006,***
9,Lung,Harmony,8,15,0.423,0.095,13.0,0.0062,0.0249,*
10,Lung,scPoli (Stage-1),8,15,0.550,0.149,11.0,0.0473,0.1892,ns
11,Immune,Raw PCA (uncorrected),50,5,0.827,0.050,4.0,0.3125,0.9375,ns
12,Immune,scProto,8,5,0.849,0.085,NaN,NaN,NaN,NaN
13,Immune,scVI (Gaussian),8,5,0.613,0.106,5.0,0.0312,0.0938,ns
14,Immune,Harmony,8,5,0.712,0.116,5.0,0.0312,0.0938,ns

## scIB integration metrics (e9Ho Q3)

> "Report the standard scIB metrics. Will you add standard metrics like ARI, NMI, ASW,
> kBET, iLISI, and graph-connectivity on the datasets?"

`get_scib()` and `get_all_embeddings_for_scib()`
(`interpretable_ssl/evaluation/metric_helpers/embedding_metrics.py`) wrap
`scib_metrics.benchmark.Benchmarker`, which computes the full standard
bio-conservation + batch-correction battery (isolated-label ASW/F1, NMI, ARI,
silhouette batch, iLISI, kBET, graph connectivity) directly from a set of `obsm`
embeddings -- this was already implemented elsewhere in the codebase but never run on
these three datasets/methods together until now.

`get_all_embeddings_for_scib()` reuses embeddings already computed above (Harmony/scVI
caches from `run_all_baselines_for_dataset`, run earlier in this notebook) plus
scProto's own Stage-2 latent, reloaded from its existing trained checkpoint (no
retraining). Run the `Run: Pancreas` / `Run: Lung` / `Run: PBMC (Immune)` cells above at
least once first so the Harmony/scVI caches exist on disk.

In [20]:
# from interpretable_ssl.evaluation.metric_helpers.embedding_metrics import (
#     get_scib, get_all_embeddings_for_scib,
# )

# EMBEDDING_KEYS_FOR_SCIB = ['X_pca', 'X_stage1z', 'X_harmony', 'X_scvi', 'X_scproto']
# EMBEDDING_DISPLAY_NAMES = {
#     'X_pca': 'Raw PCA (uncorrected)',
#     'X_stage1z': 'scPoli (Stage-1)',
#     'X_harmony': 'Harmony',
#     'X_scvi': 'scVI',
#     'X_scproto': 'scProto',
# }

# # This can take a while per dataset -- kBET/iLISI neighbor graphs are not cheap on
# # 16-30k cells x up to 5 embeddings at once. Expect several minutes per dataset.
# scib_results = {}
# for ds_id in RNA_SEQ_DATASETS:
#     print(f"\n=== [{ds_id}] computing scIB metrics ===")
#     lk = DATASETS[ds_id]['label_key']
#     bk = DATASETS[ds_id].get('batch_key')

#     ad_scib = get_all_embeddings_for_scib(ds_id)
#     keys_present = [k for k in EMBEDDING_KEYS_FOR_SCIB if k in ad_scib.obsm]
#     missing_keys = [k for k in EMBEDDING_KEYS_FOR_SCIB if k not in ad_scib.obsm]
#     if missing_keys:
#         print(f"[{ds_id}] proceeding without: {missing_keys}")

#     scib_df = get_scib(ad_scib, keys_present, bk, lk)
#     if scib_df is None:
#         print(f"[{ds_id}] get_scib returned None (single batch?) -- skipping.")
#         continue

#     scib_df = scib_df.rename(index=EMBEDDING_DISPLAY_NAMES)
#     save_path = os.path.join(get_dataset_model_dir(ds_id), 'scib_metrics.csv')
#     scib_df.to_csv(save_path)
#     print(f"[{ds_id}] scIB metrics saved to {save_path}")
#     scib_results[ds_id] = scib_df

# scib_results

In [21]:
# for ds_id, df in scib_results.items():
#     print(f"\n=== {dataset_display_names.get(ds_id, ds_id)} ===")
#     display(df)

# significant tests

In [22]:
# --- Significance test for the rare-cell metrics above (F1, homogeneity) ---
#
# Reviewer e9Ho (Weakness 7): "Tables 1-2 report no significance test ... some
# 'wins' overlap in std." This is a PAIRED one-sided Wilcoxon signed-rank test
# (ref > other) -- scProto and each baseline are scored on the exact same batches
# for a given dataset, so pairing removes shared batch-to-batch variance (e.g.
# "batch 3 is just noisier for everyone") and isolates just the
# scProto-vs-baseline difference (see rare_metric_significance_paired's docstring
# in paper_figures.py for the full reasoning). An earlier UNPAIRED Mann-Whitney U
# version of this same test sits right after the rare-cell table above -- kept
# there for comparison, this cell is the recommended one to cite.
#
# Bonferroni-corrected across the non-ref methods compared within each dataset.
# Runs directly on the per-batch F1/homogeneity arrays underlying df_rare above --
# no retraining needed.
#
# Only same-K comparisons are made: a baseline whose total metacell count K
# differs from scProto's for that dataset is dropped before testing (not
# compared at all), per the paper's own protocol ("All baselines are
# configured to produce the same number of metacells K as scProto") --
# printed below as 'Skipped (K mismatch ...)' if any run doesn't match.
#
# scProto is the reference (alternative='greater'): p_adj small => scProto's
# median is significantly higher than that baseline's, not just numerically
# ahead. 'ns' means the two are not significantly separated at alpha=0.05 after
# correction -- an honest result to report, not a bug. n_wins: out of n batches,
# how many scProto's value beats the baseline's outright -- easy to read
# regardless of p_adj, and stays informative even when 'ns'.

from interpretable_ssl.evaluation.paper_figures import rare_metric_significance_paired

sig_df = rare_metric_significance_paired(
    df_rare,
    ref_name='scProto',
    metrics=(
        '_batch_rare_f1_macro_per_batch',
        '_batch_rare_homogeneity_per_batch',
        '_batch_rare_cross_batch_homog_per_batch',
    ),
    dataset_display_names=dataset_display_names,
)

for metric_name in sig_df['metric'].unique():
    print(f"=== {metric_name}: scProto vs. each same-K baseline, PAIRED one-sided "
          f"Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===")
    sub = sig_df[sig_df['metric'] == metric_name].copy()
    sub['cell'] = sub.apply(
        lambda r: f"{r['median']:.3f} (K={r['k']}, n={r['n']}) [ref]" if r['method'] == 'scProto'
        else f"{r['median']:.3f} (K={r['k']}, n={r['n']}, wins={r.get('n_wins', '?')}/{r['n']})  "
             f"{r.get('sig', '?')}  p_adj={r.get('p_adj', float('nan')):.3g}",
        axis=1,
    )
    display(sub.pivot(index='method', columns='dataset', values='cell'))

sig_df

=== batch_rare_f1_macro: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.766 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.282 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.133 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
Leiden (scVI (Gaussian)),"0.676 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.299 (K=300, n=15, wins=15.0/15) *** p_adj=...","0.000 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (Harmony),"0.812 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.348 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.296 (K=220, n=8, wins=7.0/8) ns p_adj=0.0586"
SEACells (PCA),"0.923 (K=300, n=5, wins=2.0/5) ns p_adj=1","0.498 (K=300, n=15, wins=11.0/15) ** p_adj=0...","0.373 (K=220, n=8, wins=6.0/8) ns p_adj=0.195"
SEACells (scVI (Gaussian)),"0.652 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.342 (K=300, n=15, wins=15.0/15) *** p_adj=...","0.080 (K=220, n=8, wins=7.0/8) * p_adj=0.0391"
scProto,"0.897 (K=294, n=5) [ref]","0.611 (K=298, n=15) [ref]","0.438 (K=219, n=8) [ref]"

=== batch_rare_homogeneity: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.707 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.345 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.220 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
Leiden (scVI (Gaussian)),"0.538 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.327 (K=300, n=15, wins=15.0/15) *** p_adj=...","0.119 (K=220, n=8, wins=7.0/8) * p_adj=0.0391"
SEACells (Harmony),"0.804 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.408 (K=300, n=15, wins=14.0/15) * p_adj=0....","0.269 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (PCA),"0.815 (K=300, n=5, wins=3.0/5) ns p_adj=1","0.495 (K=300, n=15, wins=13.0/15) * p_adj=0....","0.369 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (scVI (Gaussian)),"0.582 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.385 (K=300, n=15, wins=14.0/15) *** p_adj=...","0.074 (K=220, n=8, wins=7.0/8) * p_adj=0.0391"
scProto,"0.856 (K=294, n=5) [ref]","0.586 (K=298, n=15) [ref]","0.522 (K=219, n=8) [ref]"

=== batch_rare_cross_batch_homog: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.373 (K=300, n=5, wins=2.0/5) ns p_adj=1","0.341 (K=300, n=15, wins=13.0/15) * p_adj=0....","0.184 (K=220, n=8, wins=6.0/8) ns p_adj=0.195"
Leiden (scVI (Gaussian)),"0.344 (K=300, n=5, wins=4.0/5) ns p_adj=0.17","0.318 (K=300, n=15, wins=14.0/15) *** p_adj=...","0.064 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (Harmony),"0.305 (K=300, n=5, wins=3.0/5) ns p_adj=0.781","0.399 (K=300, n=15, wins=14.0/15) * p_adj=0....","0.210 (K=220, n=8, wins=6.0/8) ns p_adj=0.371"
SEACells (PCA),"0.029 (K=300, n=5, wins=3.0/5) ns p_adj=0.36","0.416 (K=300, n=15, wins=12.0/15) ** p_adj=0...","0.212 (K=220, n=8, wins=5.0/8) ns p_adj=0.625"
SEACells (scVI (Gaussian)),"0.347 (K=300, n=5, wins=4.0/5) ns p_adj=0.17","0.377 (K=300, n=15, wins=13.0/15) *** p_adj=...","0.041 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
scProto,"0.407 (K=294, n=5) [ref]","0.510 (K=298, n=15) [ref]","0.259 (K=219, n=8) [ref]"

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,scProto,219,8,0.437680,0.535403,0.207961,NaN,NaN,NaN,NaN
1,Pancreas,batch_rare_f1_macro,SEACells (PCA),220,8,0.372628,0.370589,0.250869,6.0,0.039062,0.195312,ns
2,Pancreas,batch_rare_f1_macro,SEACells (scVI (Gaussian)),220,8,0.080208,0.177817,0.305975,7.0,0.007812,0.039062,*
3,Pancreas,batch_rare_f1_macro,Leiden (scVI (Gaussian)),220,8,0.000000,0.136982,0.296791,8.0,0.003906,0.019531,*
4,Pancreas,batch_rare_f1_macro,SEACells (Harmony),220,8,0.295521,0.316501,0.159421,7.0,0.011719,0.058594,ns
5,Pancreas,batch_rare_f1_macro,Leiden (Harmony),220,8,0.133361,0.223580,0.171156,8.0,0.003906,0.019531,*
6,Pancreas,batch_rare_homogeneity,scProto,219,8,0.522129,0.564854,0.155263,NaN,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,SEACells (PCA),220,8,0.369265,0.420592,0.195138,8.0,0.003906,0.019531,*
8,Pancreas,batch_rare_homogeneity,SEACells (scVI (Gaussian)),220,8,0.073982,0.188286,0.298413,7.0,0.007812,0.039062,*
9,Pancreas,batch_rare_homogeneity,Leiden (scVI (Gaussian)),220,8,0.118845,0.214499,0.284644,7.0,0.007812,0.039062,*
10,Pancreas,batch_rare_homogeneity,SEACells (Harmony),220,8,0.269034,0.285358,0.115015,8.0,0.003906,0.019531,*
11,Pancreas,batch_rare_homogeneity,Leiden (Harmony),220,8,0.220189,0.218359,0.085397,8.0,0.003906,0.019531,*
12,Pancreas,batch_rare_cross_batch_homog,scProto,219,8,0.259411,0.322859,0.179414,NaN,NaN,NaN,NaN
13,Pancreas,batch_rare_cross_batch_homog,SEACells (PCA),220,8,0.212005,0.221772,0.100594,5.0,0.125000,0.625000,ns
14,Pancreas,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),220,8,0.041038,0.124562,0.213338,8.0,0.003906,0.019531,*
15,Pancreas,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),220,8,0.063618,0.141228,0.203271,8.0,0.003906,0.019531,*
16,Pancreas,batch_rare_cross_batch_homog,SEACells (Harmony),220,8,0.210341,0.227762,0.098150,6.0,0.074219,0.371094,ns
17,Pancreas,batch_rare_cross_batch_homog,Leiden (Harmony),220,8,0.183894,0.188323,0.084876,6.0,0.039062,0.195312,ns
18,Lung,batch_rare_f1_macro,scProto,298,15,0.610777,0.599348,0.175935,NaN,NaN,NaN,NaN
19,Lung,batch_rare_f1_macro,SEACells (PCA),300,15,0.498294,0.420330,0.217382,11.0,0.001678,0.008392,**
20,Lung,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,15,0.342397,0.351520,0.195825,15.0,0.000031,0.000153,***
21,Lung,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,15,0.298562,0.343621,0.164360,15.0,0.000031,0.000153,***
22,Lung,batch_rare_f1_macro,SEACells (Harmony),300,15,0.348333,0.357564,0.144189,13.0,0.000763,0.003815,**
23,Lung,batch_rare_f1_macro,Leiden (Harmony),300,15,0.282094,0.280384,0.141206,13.0,0.000305,0.001526,**
24,Lung,batch_rare_homogeneity,scProto,298,15,0.586120,0.577994,0.220956,NaN,NaN,NaN,NaN
25,Lung,batch_rare_homogeneity,SEACells (PCA),300,15,0.495372,0.472356,0.242324,13.0,0.002686,0.013428,*
26,Lung,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,15,0.385405,0.386730,0.202635,14.0,0.000092,0.000458,***
27,Lung,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,15,0.326560,0.380982,0.195458,15.0,0.000031,0.000153,***
28,Lung,batch_rare_homogeneity,SEACells (Harmony),300,15,0.408222,0.402522,0.115704,14.0,0.002136,0.010681,*
29,Lung,batch_rare_homogeneity,Leiden (Harmony),300,15,0.344610,0.344719,0.084300,13.0,0.000763,0.003815,**
30,Lung,batch_rare_cross_batch_homog,scProto,298,15,0.509701,0.508327,0.196956,NaN,NaN,NaN,NaN
31,Lung,batch_rare_cross_batch_homog,SEACells (PCA),300,15,0.415586,0.393655,0.201346,12.0,0.001678,0.008392,**
32,Lung,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,15,0.376639,0.365457,0.199952,13.0,0.000153,0.000763,***
33,Lung,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,15,0.318222,0.359455,0.200846,14.0,0.000061,0.000305,***
34,Lung,batch_rare_cross_batch_homog,SEACells (Harmony),300,15,0.398968,0.371869,0.121918,14.0,0.003357,0.016785,*
35,Lung,batch_rare_cross_batch_homog,Leiden (Harmony),300,15,0.341005,0.328868,0.089351,13.0,0.003357,0.016785,*
36,Immune,batch_rare_f1_macro,scProto,294,5,0.896681,0.854140,0.138252,NaN,NaN,NaN,NaN
37,Immune,batch_rare_f1_macro,SEACells (PCA),300,5,0.922877,0.879883,0.082663,2.0,0.687500,1.000000,ns
38,Immune,batch_rare_f1_macro,SEACells (scVI (Gaussian)),300,5,0.651993,0.623414,0.177152,5.0,0.031250,0.156250,ns
39,Immune,batch_rare_f1_macro,Leiden (scVI (Gaussian)),300,5,0.675523,0.650881,0.099053,5.0,0.031250,0.156250,ns
40,Immune,batch_rare_f1_macro,SEACells (Harmony),300,5,0.812234,0.750774,0.162481,4.0,0.062500,0.312500,ns
41,Immune,batch_rare_f1_macro,Leiden (Harmony),300,5,0.765805,0.751472,0.166212,4.0,0.062500,0.312500,ns
42,Immune,batch_rare_homogeneity,scProto,294,5,0.855792,0.827192,0.101982,NaN,NaN,NaN,NaN
43,Immune,batch_rare_homogeneity,SEACells (PCA),300,5,0.815416,0.854752,0.073552,3.0,0.687500,1.000000,ns
44,Immune,batch_rare_homogeneity,SEACells (scVI (Gaussian)),300,5,0.581696,0.567966,0.131954,5.0,0.031250,0.156250,ns
45,Immune,batch_rare_homogeneity,Leiden (scVI (Gaussian)),300,5,0.538280,0.520888,0.119735,5.0,0.031250,0.156250,ns
46,Immune,batch_rare_homogeneity,SEACells (Harmony),300,5,0.804136,0.676898,0.185473,5.0,0.031250,0.156250,ns
47,Immune,batch_rare_homogeneity,Leiden (Harmony),300,5,0.706627,0.635473,0.125110,5.0,0.031250,0.156250,ns
48,Immune,batch_rare_cross_batch_homog,scProto,294,5,0.406766,0.349204,0.197947,NaN,NaN,NaN,NaN
49,Immune,batch_rare_cross_batch_homog,SEACells (PCA),300,5,0.028607,0.120662,0.166976,3.0,0.072064,0.360318,ns
50,Immune,batch_rare_cross_batch_homog,SEACells (scVI (Gaussian)),300,5,0.347206,0.273950,0.149657,4.0,0.033945,0.169723,ns
51,Immune,batch_rare_cross_batch_homog,Leiden (scVI (Gaussian)),300,5,0.344439,0.275207,0.152992,4.0,0.033945,0.169723,ns
52,Immune,batch_rare_cross_batch_homog,SEACells (Harmony),300,5,0.304594,0.245410,0.153361,3.0,0.156250,0.781250,ns
53,Immune,batch_rare_cross_batch_homog,Leiden (Harmony),300,5,0.372796,0.304595,0.181786,2.0,0.232604,1.000000,ns

In [23]:
# --- Significance test for Table 1 (modularity, batch entropy, purity) ---
#
# Reviewer e9Ho (Weakness 7): "Tables 1-2 report no significance test." The cell
# above covers Table 2 (F1, homogeneity); this is the Table 1 counterpart --
# same one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected across
# baselines per dataset, same K-matching (realized metacell count within 5%
# tolerance, since a few empty prototypes/archetypes are normal even at
# identical configured K -- see rareSignificanceCell01 above for why exact
# equality is the wrong bar).
#
# Reads modularity_per_batch.csv / purity_per_mc.csv / batch_entropy_per_mc.csv
# directly from each run's saved directory (the same files load_task1_multi
# already reduces to the mean/std shown in Table 1 above) -- no retraining
# needed. Reuses the shared MODEL_KEYWORDS dict built in the Table 1 cell above,
# so method names/canonical runs are identical across every table and test.

from interpretable_ssl.evaluation.paper_figures import graph_batch_significance

sig_df_table1 = graph_batch_significance(
    RNA_SEQ_DATASETS,
    MODEL_KEYWORDS,
    ref_name='scProto',
    dataset_display_names=dataset_display_names,
)

for metric_name in sig_df_table1['metric'].unique():
    print(f"=== {metric_name}: scProto vs. each same-K baseline, one-sided "
          f"Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===")
    sub = sig_df_table1[sig_df_table1['metric'] == metric_name].copy()
    sub['cell'] = sub.apply(
        lambda r: f"{r['median']:.3f} (K={r['k']}, n={r['n']}) [ref]" if r['method'] == 'scProto'
        else f"{r['median']:.3f} (K={r['k']}, n={r['n']})  {r.get('sig', '?')}  p_adj={r.get('p_adj', float('nan')):.3g}",
        axis=1,
    )
    display(sub.pivot(index='method', columns='dataset', values='cell'))

sig_df_table1

=== modularity_per_batch: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.250 (K=300, n=5) * p_adj=0.0198","0.403 (K=300, n=16) *** p_adj=4.66e-06","0.614 (K=220, n=9) ns p_adj=1"
Leiden (scVI (Gaussian)),"0.344 (K=300, n=5) ns p_adj=0.0794","0.300 (K=300, n=16) *** p_adj=3.86e-06","0.340 (K=220, n=9) ** p_adj=0.00272"
SEACells (Harmony),"0.551 (K=300, n=5) ns p_adj=0.0794","0.625 (K=300, n=16) *** p_adj=0.000798","0.566 (K=220, n=9) ns p_adj=0.159"
SEACells (PCA),"0.569 (K=300, n=5) ns p_adj=0.139","0.671 (K=300, n=16) ns p_adj=1","0.658 (K=220, n=9) ns p_adj=1"
SEACells (scVI (Gaussian)),"0.657 (K=300, n=5) ns p_adj=1","0.141 (K=300, n=16) *** p_adj=3.86e-06","0.720 (K=220, n=9) ns p_adj=1"
scProto,"0.620 (K=294, n=5) [ref]","0.669 (K=298, n=16) [ref]","0.621 (K=219, n=9) [ref]"

=== purity_per_mc: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.855 (K=300, n=300) *** p_adj=2.58e-17","0.841 (K=300, n=300) *** p_adj=1.16e-12","1.000 (K=220, n=220) ns p_adj=1"
Leiden (scVI (Gaussian)),"0.799 (K=300, n=300) *** p_adj=8.93e-35","0.831 (K=300, n=300) *** p_adj=6.64e-12","1.000 (K=220, n=220) ns p_adj=1"
SEACells (Harmony),"0.883 (K=300, n=300) *** p_adj=4.41e-15","0.832 (K=300, n=300) *** p_adj=8.01e-12","0.967 (K=220, n=220) *** p_adj=0.000186"
SEACells (PCA),"0.965 (K=300, n=300) *** p_adj=8.99e-06","0.977 (K=300, n=300) ns p_adj=1","0.993 (K=220, n=220) ns p_adj=1"
SEACells (scVI (Gaussian)),"0.906 (K=300, n=300) *** p_adj=4.33e-15","0.944 (K=300, n=300) *** p_adj=0.000159","0.981 (K=220, n=220) ns p_adj=0.0654"
scProto,"1.000 (K=294, n=294) [ref]","0.996 (K=298, n=298) [ref]","1.000 (K=219, n=219) [ref]"

=== batch_entropy_per_mc: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"1.071 (K=300, n=300) ns p_adj=1","1.350 (K=300, n=300) ns p_adj=1","1.327 (K=220, n=220) ns p_adj=1"
Leiden (scVI (Gaussian)),"0.769 (K=300, n=300) ns p_adj=1","1.122 (K=300, n=300) ns p_adj=1","0.805 (K=220, n=220) ns p_adj=1"
SEACells (Harmony),"0.726 (K=300, n=300) ns p_adj=1","1.526 (K=300, n=300) ns p_adj=1","1.339 (K=220, n=220) ns p_adj=1"
SEACells (PCA),"-0.000 (K=300, n=300) ns p_adj=1","0.218 (K=300, n=300) ns p_adj=1","-0.000 (K=220, n=220) *** p_adj=7.98e-06"
SEACells (scVI (Gaussian)),"0.434 (K=300, n=300) ns p_adj=1","1.116 (K=300, n=300) ns p_adj=1","0.882 (K=220, n=220) ns p_adj=1"
scProto,"-0.000 (K=294, n=294) [ref]","0.500 (K=298, n=298) [ref]","0.214 (K=219, n=219) [ref]"

,dataset,metric,method,k,n,median,mean,std,p_vs_ref,p_adj,sig
0,Pancreas,modularity_per_batch,scProto,219,9,6.214564e-01,0.601234,0.083385,NaN,NaN,NaN
1,Pancreas,modularity_per_batch,SEACells (PCA),220,9,6.578915e-01,0.673906,0.050910,9.739706e-01,1.000000e+00,ns
2,Pancreas,modularity_per_batch,SEACells (scVI (Gaussian)),220,9,7.202421e-01,0.725213,0.038824,9.994569e-01,1.000000e+00,ns
3,Pancreas,modularity_per_batch,Leiden (scVI (Gaussian)),220,9,3.404861e-01,0.352439,0.100534,5.431233e-04,2.715617e-03,**
4,Pancreas,modularity_per_batch,SEACells (Harmony),220,9,5.663669e-01,0.567150,0.017709,3.184489e-02,1.592244e-01,ns
5,Pancreas,modularity_per_batch,Leiden (Harmony),220,9,6.143183e-01,0.612469,0.021231,3.619660e-01,1.000000e+00,ns
6,Pancreas,purity_per_mc,scProto,219,219,1.000000e+00,0.912529,0.160439,NaN,NaN,NaN
7,Pancreas,purity_per_mc,SEACells (PCA),220,220,9.931271e-01,0.956404,0.090829,4.277007e-01,1.000000e+00,ns
8,Pancreas,purity_per_mc,SEACells (scVI (Gaussian)),220,220,9.813068e-01,0.930490,0.128800,1.307339e-02,6.536697e-02,ns
9,Pancreas,purity_per_mc,Leiden (scVI (Gaussian)),220,220,1.000000e+00,0.919241,0.163201,5.001637e-01,1.000000e+00,ns
10,Pancreas,purity_per_mc,SEACells (Harmony),220,220,9.666502e-01,0.883981,0.162928,3.716617e-05,1.858308e-04,***
11,Pancreas,purity_per_mc,Leiden (Harmony),220,220,1.000000e+00,0.923363,0.150398,4.039544e-01,1.000000e+00,ns
12,Pancreas,batch_entropy_per_mc,scProto,219,219,2.136999e-01,0.399301,0.459746,NaN,NaN,NaN
13,Pancreas,batch_entropy_per_mc,SEACells (PCA),220,220,-1.000000e-10,0.179207,0.308164,1.595315e-06,7.976573e-06,***
14,Pancreas,batch_entropy_per_mc,SEACells (scVI (Gaussian)),220,220,8.823510e-01,0.867831,0.493654,1.000000e+00,1.000000e+00,ns
15,Pancreas,batch_entropy_per_mc,Leiden (scVI (Gaussian)),220,220,8.051659e-01,0.814297,0.482490,1.000000e+00,1.000000e+00,ns
16,Pancreas,batch_entropy_per_mc,SEACells (Harmony),220,220,1.339383e+00,1.305290,0.340185,1.000000e+00,1.000000e+00,ns
17,Pancreas,batch_entropy_per_mc,Leiden (Harmony),220,220,1.326997e+00,1.293224,0.320674,1.000000e+00,1.000000e+00,ns
18,Lung,modularity_per_batch,scProto,298,16,6.693902e-01,0.664444,0.022871,NaN,NaN,NaN
19,Lung,modularity_per_batch,SEACells (PCA),300,16,6.713397e-01,0.673784,0.037789,6.538492e-01,1.000000e+00,ns
20,Lung,modularity_per_batch,SEACells (scVI (Gaussian)),300,16,1.408502e-01,0.140271,0.023944,7.724551e-07,3.862275e-06,***
21,Lung,modularity_per_batch,Leiden (scVI (Gaussian)),300,16,3.004420e-01,0.276332,0.087973,7.724551e-07,3.862275e-06,***
22,Lung,modularity_per_batch,SEACells (Harmony),300,16,6.248080e-01,0.606050,0.044595,1.595426e-04,7.977128e-04,***
23,Lung,modularity_per_batch,Leiden (Harmony),300,16,4.034519e-01,0.419322,0.146812,9.319447e-07,4.659724e-06,***
24,Lung,purity_per_mc,scProto,298,298,9.961818e-01,0.858799,0.195540,NaN,NaN,NaN
25,Lung,purity_per_mc,SEACells (PCA),300,300,9.770757e-01,0.904696,0.147952,4.719455e-01,1.000000e+00,ns
26,Lung,purity_per_mc,SEACells (scVI (Gaussian)),300,300,9.436508e-01,0.828244,0.208866,3.178298e-05,1.589149e-04,***
27,Lung,purity_per_mc,Leiden (scVI (Gaussian)),300,300,8.309524e-01,0.766878,0.218298,1.327907e-12,6.639533e-12,***
28,Lung,purity_per_mc,SEACells (Harmony),300,300,8.317610e-01,0.778053,0.201215,1.602045e-12,8.010225e-12,***
29,Lung,purity_per_mc,Leiden (Harmony),300,300,8.412654e-01,0.773991,0.204636,2.319003e-13,1.159502e-12,***
30,Lung,batch_entropy_per_mc,scProto,298,298,5.004024e-01,0.537913,0.566815,NaN,NaN,NaN
31,Lung,batch_entropy_per_mc,SEACells (PCA),300,300,2.177791e-01,0.443425,0.486565,4.477125e-01,1.000000e+00,ns
32,Lung,batch_entropy_per_mc,SEACells (scVI (Gaussian)),300,300,1.115838e+00,1.089087,0.454362,1.000000e+00,1.000000e+00,ns
33,Lung,batch_entropy_per_mc,Leiden (scVI (Gaussian)),300,300,1.121563e+00,1.103339,0.429002,1.000000e+00,1.000000e+00,ns
34,Lung,batch_entropy_per_mc,SEACells (Harmony),300,300,1.526025e+00,1.519974,0.269127,1.000000e+00,1.000000e+00,ns
35,Lung,batch_entropy_per_mc,Leiden (Harmony),300,300,1.349972e+00,1.339778,0.305790,1.000000e+00,1.000000e+00,ns
36,Immune,modularity_per_batch,scProto,294,5,6.195963e-01,0.628591,0.051655,NaN,NaN,NaN
37,Immune,modularity_per_batch,SEACells (PCA),300,5,5.687329e-01,0.553930,0.031290,2.777778e-02,1.388889e-01,ns
38,Immune,modularity_per_batch,SEACells (scVI (Gaussian)),300,5,6.568617e-01,0.653455,0.024633,7.261905e-01,1.000000e+00,ns
39,Immune,modularity_per_batch,Leiden (scVI (Gaussian)),300,5,3.438221e-01,0.358796,0.136589,1.587302e-02,7.936508e-02,ns
40,Immune,modularity_per_batch,SEACells (Harmony),300,5,5.511271e-01,0.548892,0.012923,1.587302e-02,7.936508e-02,ns
41,Immune,modularity_per_batch,Leiden (Harmony),300,5,2.500208e-01,0.296661,0.109232,3.968254e-03,1.984127e-02,*
42,Immune,purity_per_mc,scProto,294,294,1.000000e+00,0.901103,0.171917,NaN,NaN,NaN
43,Immune,purity_per_mc,SEACells (PCA),300,300,9.649015e-01,0.893854,0.139833,1.797436e-06,8.987179e-06,***
44,Immune,purity_per_mc,SEACells (scVI (Gaussian)),300,300,9.058693e-01,0.832763,0.186797,8.657465e-16,4.328733e-15,***
45,Immune,purity_per_mc,Leiden (scVI (Gaussian)),300,300,7.986486e-01,0.765300,0.149341,1.786369e-35,8.931845e-35,***
46,Immune,purity_per_mc,SEACells (Harmony),300,300,8.834890e-01,0.843477,0.165027,8.812823e-16,4.406412e-15,***
47,Immune,purity_per_mc,Leiden (Harmony),300,300,8.546196e-01,0.849236,0.132604,5.167299e-18,2.583649e-17,***
48,Immune,batch_entropy_per_mc,scProto,294,294,-1.000000e-10,0.229215,0.371121,NaN,NaN,NaN
49,Immune,batch_entropy_per_mc,SEACells (PCA),300,300,-1.000000e-10,0.135273,0.224257,3.877261e-01,1.000000e+00,ns
50,Immune,batch_entropy_per_mc,SEACells (scVI (Gaussian)),300,300,4.343067e-01,0.496806,0.475820,1.000000e+00,1.000000e+00,ns
51,Immune,batch_entropy_per_mc,Leiden (scVI (Gaussian)),300,300,7.693858e-01,0.710373,0.406745,1.000000e+00,1.000000e+00,ns
52,Immune,batch_entropy_per_mc,SEACells (Harmony),300,300,7.259650e-01,0.640662,0.511225,1.000000e+00,1.000000e+00,ns
53,Immune,batch_entropy_per_mc,Leiden (Harmony),300,300,1.071138e+00,0.947120,0.382718,1.000000e+00,1.000000e+00,ns

In [24]:
# --- PAIRED significance test for Table 1's modularity (recommended for this metric) ---
# Only modularity_per_batch is pairable here -- batch is a shared, method-independent
# unit (see graph_batch_significance_paired's docstring in paper_figures.py).
# purity_per_mc and batch_entropy_per_mc stay unpaired (Mann-Whitney U, the cell
# above) -- a metacell is a method-specific output (different clustering methods
# produce different numbers of metacells with different compositions), so there is
# no natural cross-method correspondence to pair on. That's the statistically
# correct test for those two, not a limitation to fix.

from interpretable_ssl.evaluation.paper_figures import graph_batch_significance_paired

sig_df_table1_paired = graph_batch_significance_paired(
    RNA_SEQ_DATASETS,
    MODEL_KEYWORDS,
    ref_name='scProto',
    dataset_display_names=dataset_display_names,
)

sub = sig_df_table1_paired.copy()
sub['cell'] = sub.apply(
    lambda r: f"{r['median']:.3f} (K={r['k']}, n={r['n']}) [ref]" if r['method'] == 'scProto'
    else f"{r['median']:.3f} (K={r['k']}, n={r['n']}, wins={r.get('n_wins', '?')}/{r['n']})  "
         f"{r.get('sig', '?')}  p_adj={r.get('p_adj', float('nan')):.3g}",
    axis=1,
)
display(sub.pivot(index='method', columns='dataset', values='cell'))

sig_df_table1_paired

dataset,Immune,Lung,Pancreas
method,,,
Leiden (Harmony),"0.250 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.403 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.614 (K=220, n=9, wins=6.0/9) ns p_adj=1"
Leiden (scVI (Gaussian)),"0.344 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.300 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.340 (K=220, n=9, wins=8.0/9) * p_adj=0.0195"
SEACells (Harmony),"0.551 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.625 (K=300, n=16, wins=14.0/16) ** p_adj=0...","0.566 (K=220, n=9, wins=7.0/9) ns p_adj=0.625"
SEACells (PCA),"0.569 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.671 (K=300, n=16, wins=9.0/16) ns p_adj=1","0.658 (K=220, n=9, wins=0.0/9) ns p_adj=1"
SEACells (scVI (Gaussian)),"0.657 (K=300, n=5, wins=1.0/5) ns p_adj=1","0.141 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.720 (K=220, n=9, wins=0.0/9) ns p_adj=1"
scProto,"0.620 (K=294, n=5) [ref]","0.669 (K=298, n=16) [ref]","0.621 (K=219, n=9) [ref]"

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,modularity_per_batch,scProto,219,9,0.621456,0.601234,0.083385,NaN,NaN,NaN,NaN
1,Pancreas,modularity_per_batch,SEACells (PCA),220,9,0.657892,0.673906,0.050910,0.0,1.000000,1.000000,ns
2,Pancreas,modularity_per_batch,SEACells (scVI (Gaussian)),220,9,0.720242,0.725213,0.038824,0.0,1.000000,1.000000,ns
3,Pancreas,modularity_per_batch,Leiden (scVI (Gaussian)),220,9,0.340486,0.352439,0.100534,8.0,0.003906,0.019531,*
4,Pancreas,modularity_per_batch,SEACells (Harmony),220,9,0.566367,0.567150,0.017709,7.0,0.125000,0.625000,ns
5,Pancreas,modularity_per_batch,Leiden (Harmony),220,9,0.614318,0.612469,0.021231,6.0,0.544922,1.000000,ns
6,Lung,modularity_per_batch,scProto,298,16,0.669390,0.664444,0.022871,NaN,NaN,NaN,NaN
7,Lung,modularity_per_batch,SEACells (PCA),300,16,0.671340,0.673784,0.037789,9.0,0.628220,1.000000,ns
8,Lung,modularity_per_batch,SEACells (scVI (Gaussian)),300,16,0.140850,0.140271,0.023944,16.0,0.000015,0.000076,***
9,Lung,modularity_per_batch,Leiden (scVI (Gaussian)),300,16,0.300442,0.276332,0.087973,16.0,0.000015,0.000076,***
10,Lung,modularity_per_batch,SEACells (Harmony),300,16,0.624808,0.606050,0.044595,14.0,0.000214,0.001068,**
11,Lung,modularity_per_batch,Leiden (Harmony),300,16,0.403452,0.419322,0.146812,16.0,0.000015,0.000076,***
12,Immune,modularity_per_batch,scProto,294,5,0.619596,0.628591,0.051655,NaN,NaN,NaN,NaN
13,Immune,modularity_per_batch,SEACells (PCA),300,5,0.568733,0.553930,0.031290,5.0,0.031250,0.156250,ns
14,Immune,modularity_per_batch,SEACells (scVI (Gaussian)),300,5,0.656862,0.653455,0.024633,1.0,0.843750,1.000000,ns
15,Immune,modularity_per_batch,Leiden (scVI (Gaussian)),300,5,0.343822,0.358796,0.136589,4.0,0.062500,0.312500,ns
16,Immune,modularity_per_batch,SEACells (Harmony),300,5,0.551127,0.548892,0.012923,5.0,0.031250,0.156250,ns
17,Immune,modularity_per_batch,Leiden (Harmony),300,5,0.250021,0.296661,0.109232,5.0,0.031250,0.156250,ns