## Status (created 2026-07-30) -- READ BEFORE RUNNING

**Standalone BBKNN baseline notebook.** Deliberately a SEPARATE notebook from
`batch_correct_then_cluster_baselines.ipynb` (Harmony) and `combat_then_cluster_baselines.ipynb`
(ComBat) -- same underlying helper module
(`interpretable_ssl/evaluation/batch_correct_baselines.py`) and same shared results
section (`interpretable_ssl/evaluation/rebuttal_report.py`), just a different
`CORRECTION_METHODS` value (`['bbknn']` here).

BBKNN support already existed in `batch_correct_baselines.py` (`get_bbknn_graph`, the
`'bbknn'` branch in `run_correction_method`) from the original 4-method design, but was
excluded from every notebook's `CORRECTION_METHODS` due to a suspected stale numpy/scipy
pin inside the `bbknn` PyPI package itself conflicting with the numpy/scipy pins scVI/
scArches need. This notebook installs `bbknn` with `--no-deps` (see the install cell)
so its own requirements file never gets a chance to downgrade numpy/scipy -- if that
turns out not to be enough, the import-check cell below will fail loudly and name
exactly which package is missing.

Results land in the exact same on-disk run folders/metrics.json format the other two
notebooks use (`seacell_X_bbknn`, `leiden_X_bbknn_K{n}`), so the comparison tables below
can pull in Harmony/ComBat results too, if those have already been run -- no need to
re-run anything from the other notebooks to see them side by side here.

If you already have this notebook open in another Colab tab, close it (or File >
Revert) first -- Colab autosaving from a stale tab can silently overwrite this file.

# Rebuttal experiment: BBKNN batch-correction-then-cluster baseline -- BBKNN graph -> {SEACells, Leiden}

**Purpose.** Reviewer F5RB (Question 1): *"Please compare scProto with stronger
two-step baselines, such as scPoli latent + SEACells, scVI latent + SEACells, Harmony
latent + SEACells, and BBKNN graph + SEACells."* The scPoli/Harmony/scVI arms are
already covered by the Harmony notebook; this notebook runs the BBKNN arm.

**Why BBKNN is a structurally different comparison than Harmony/ComBat/scVI:** those
three all correct expression or a PCA embedding FIRST, then a separate step (RBF kernel
+ SEACells/Leiden) builds a graph on top of the corrected result. BBKNN instead builds
its batch-balanced kNN graph directly -- for each cell, it finds its k nearest
neighbors WITHIN EACH BATCH SEPARATELY (not a global neighbor search), then merges those
per-batch neighbor sets into one graph. There is no intermediate corrected embedding at
all: the graph IS the batch correction. That graph is fed directly to SEACells/Leiden
below -- no separate RBF-on-embedding construction step, unlike every other method in
these notebooks.

This also means the "embedding-only rare-cell affinity purity" diagnostic (used in the
Harmony/ComBat notebooks to check whether a correction method already destroys rare-type
separability before any clustering algorithm runs) does not apply to BBKNN -- there is
no embedding to build that diagnostic's own ARBF graph on top of. The rare-cell
coverage/homogeneity/F1 table further down (computed on BBKNN's own graph directly) is
the fair comparison for this method instead.

## Setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!pip install -q scarches faiss-cpu scib-metrics
!pip install git+https://github.com/dpeerlab/SEACells.git --quiet --no-deps
!pip install numpy scipy --upgrade -q
!pip install -q palantir harmonypy
!pip install -q "numpy==1.26.4" "scipy==1.13.1"
!pip install --upgrade --force-reinstall numpy cupy-cuda12x
!pip install "numpy<2.3"
# bbknn --no-deps: installed LAST, after the numpy/scipy pins above are already in
# place -- bbknn's own requirements file is suspected to carry a stale numpy/scipy
# pin (see the Status cell), and --no-deps stops pip from acting on it and
# downgrading what scVI/scArches need. bbknn's actual runtime code does not appear to
# need anything beyond what's already installed above (umap-learn, scikit-learn) --
# if that turns out wrong, the import-check cell below will fail loudly and name the
# missing package explicitly.
!pip install bbknn --no-deps -q
# annoy: bbknn/matrix.py does `from annoy import AnnoyIndex` unconditionally at
# import time -- a real (if small) dependency, not something --no-deps could skip
# safely. Confirmed missing via ModuleNotFoundError on first run; installed
# separately here since it has no numpy/scipy pin of its own to worry about.
!pip install annoy -q

In [ ]:
# IMPORTANT: restart the runtime after this cell before running the cells below --
# numpy/scipy/anndata are C-extension linked, an in-process upgrade alone won't
# reliably take effect on already-imported modules.
#
# Note: scarches/scvi-tools/harmonypy are installed above even though THIS notebook
# only runs BBKNN -- run_all_baselines_for_dataset always calls get_stage1_latent()
# first to build `ad` from the existing scPoli Stage-1 checkpoint, and that path needs
# scarches/scvi importable regardless of which correction method is requested
# afterward.

In [ ]:
# Ground truth for "did the install cell above actually work" -- pip's own log is
# noisy (resolver backtracking prints "Getting requirements to build wheel" errors
# for discarded candidate versions even on a fully successful install), so eyeballing
# it is unreliable. Actually importing every package we just installed is the real
# test.
_checks = {
    'numpy': 'numpy', 'scipy': 'scipy', 'anndata': 'anndata', 'scanpy': 'scanpy',
    'scarches': 'scarches', 'scvi-tools': 'scvi', 'seacells': 'SEACells',
    'palantir': 'palantir', 'scib-metrics': 'scib_metrics', 'leidenalg': 'leidenalg',
    'python-igraph': 'igraph', 'umap-learn': 'umap', 'harmonypy': 'harmonypy',
    'faiss-cpu': 'faiss', 'bbknn': 'bbknn', 'annoy': 'annoy',
}
_failed = []
for pkg_name, import_name in _checks.items():
    try:
        mod = __import__(import_name)
        ver = getattr(mod, '__version__', '?')
        print(f"  OK   {pkg_name:16s} (import {import_name}, version {ver})")
    except Exception as e:
        _failed.append(pkg_name)
        print(f"  FAIL {pkg_name:16s} (import {import_name}): {type(e).__name__}: {e}")

if _failed:
    print(f"\n{len(_failed)} package(s) failed to import: {_failed} -- re-run that "
          f"package's specific pip install line above and check its full error "
          f"output before proceeding.")
else:
    print(f"\nAll {len(_checks)} packages import cleanly -- safe to continue.")

In [1]:
%run /content/drive/MyDrive/codes/interpretable-prototype/notebooks/nb_setup.py

nb_setup done. Available: get_trainer, run_mc_task, fig_*, LAMBDA_PROTO_UMAP, LAMBDA_PROTO_UMAP_PRECON, LAMBDA_PARAM_UMAP, LAMBDA_RECON_ONLY, train_sure, eval_sure_task1/2/3
Configs: {'LAMBDA_PROTO_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'proto'}, 'LAMBDA_PARAM_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'embedding'}, 'LAMBDA_RECON_ONLY': {'lambda_umap': 0, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 1, 'lambda_proto_recon': 0.0}}

In [2]:
# Extra imports not already covered by nb_setup.py (which already pulls in
# run_mc_task, eval_seacell_task1/2/3, load_task1_multi, show_table, clean_run_names,
# rare_celltype_purity_table, TASK1_METRICS, TASK2_METRICS, extract_model_key via
# `from interpretable_ssl.evaluation.paper_figures import *` and
# `from interpretable_ssl.evaluation.metric_helpers.result_tables import *`).
from interpretable_ssl.datasets.dataset_configs import DATASETS
from interpretable_ssl.configs.paths import get_dataset_model_dir

print("extra imports ready")

extra imports ready

## Config

Same hyperparameters `train_scproto.ipynb` used to produce the existing Stage-1
checkpoints for these three datasets (`cvae_epochs=50`, `batch_size=1024`) -- must
match, or `load_pretrain_checkpoint()` looks in the wrong folder. `K` (n_SEACells /
target Leiden cluster count) defaults to each dataset's `num_prototypes` from
`DATASETS`, matching `results.tex`: *"All baselines are configured to produce the same
number of metacells K as scProto."*

In [3]:
RNA_SEQ_DATASETS = ['pancreas', 'lung', 'pbmc-immune']

SKIP_IF_EXISTS = True  # skip a baseline entirely (embedding + SEACells + Leiden) if its
                        # metrics.json already exists on disk -- re-running the dataset
                        # cell after a crash/interrupt never redoes already-saved work.

CORRECTION_METHODS = ['bbknn']  # this notebook: BBKNN only (see intro cell)
METHOD_DISPLAY_NAMES = {
    'bbknn': 'BBKNN',
}

RUN_SEACELLS = True  # both SEACells AND Leiden on BBKNN's own graph -- reviewer F5RB's
                      # Q1 explicitly named "BBKNN graph + SEACells" as a requested arm.
RUN_LEIDEN = True

## Helper functions

Shared with the Harmony and ComBat notebooks -- lives in
`interpretable_ssl/evaluation/batch_correct_baselines.py` (imported below), not
redefined here. BBKNN support (`get_bbknn_graph`, and the `'bbknn'` branch in
`run_correction_method`) already existed in that module from the original 4-method
design -- this notebook just turns it back on via `CORRECTION_METHODS`, it required no
new helper-module code.

In [4]:
from interpretable_ssl.evaluation.batch_correct_baselines import run_all_baselines_for_dataset

print("baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)")

baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)

## Run: Pancreas

In [5]:
pancreas_results = run_all_baselines_for_dataset(
    'pancreas', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading pancreas data
✅ Already subsetted to HVGs (4000 genes).

WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).
WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/16 [00:00<?, ?it/s]

=== [pancreas] batch-correction method: bbknn ===
WARNING: consider updating your call to make use of `computation`
[pancreas] bbknn_d8: cached graph to /content/drive/MyDrive/models/pancreas/_cache_X_bbknn_d8_aff.npz
[waypoint init] N=16382  k=220  n_eigs=10  nnz=535440  nnz/row=32.7
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 2233.18archetype/s]

[waypoint init] selected 220 archetype seed cells
[SEACells backend] No GPU → use_sparse=True (sparse CPU, avoids dense K)
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.26623
Starting iteration 1.
Completed iteration 1.
Converged after 7 iterations.
Converged after 9 iterations.
Starting iteration 10.
Completed iteration 10.
Converged after 10 iterations.

100%|██████████| 220/220 [00:01<00:00, 150.23it/s]

saving to:  /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 2 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8 ...
[seacell] unused protos: 0/220 (0.00%)
[seacell] mean cell-type purity: 0.8806  (size-weighted: 0.9040 ± 0.1683)
[seacell] mean batch entropy: 0.8800  (size-weighted: 0.7905 ± 0.4543)
[seacell] coverage: 0.7857
[seacell] modularity: 0.4398
[seacell] per-batch modularity: mean=0.4005, std=0.0965
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.4942 | saved to /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8
[pancreas] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl (nnz=1171528) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.30619923725947046 +/- 0.09640259593196528 (was 0.4005075959221043), K_target=220
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_bbknn_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_8df418a9.h5ad
[seacell task2] coverage: 0.7857
[seacell task2] scgraph_corr_avg: 0.8439
[seacell task2] scgraph_corr_std: 0.0823
  [leiden oversegment] resolution=1.0000 -> 13 clusters (need >= 220)
  [leiden oversegment] resolution=2.0000 -> 27 clusters (need >= 220)
  [leiden oversegment] resolution=4.0000 -> 42 clusters (need >= 220)
  [leiden oversegment] resolution=8.0000 -> 74 clusters (need >= 220)
  [leiden oversegment] resolution=16.0000 -> 152 clusters (need >= 220)
  [leiden oversegment] resolution=32.0000 -> 316 clusters (need >= 220)
  [leiden merge] -> 310 clusters (target 220)
  [leiden merge] -> 300 clusters (target 220)
  [leiden merge] -> 290 clusters (target 220)
  [leiden merge] -> 280 clusters (target 220)
  [leiden merge] -> 270 clusters (target 220)
  [leiden merge] -> 260 clusters (target 220)
  [leiden merge] -> 250 clusters (target 220)
  [leiden merge] -> 240 clusters (target 220)
  [leiden merge] -> 230 clusters (target 220)
  [leiden merge] -> 225 clusters (target 220)
  [leiden merge] -> 224 clusters (target 220)
  [leiden merge] -> 223 clusters (target 220)
  [leiden merge] -> 222 clusters (target 220)
  [leiden merge] -> 221 clusters (target 220)
  [leiden merge] -> 220 clusters (target 220)
[leiden merge-down] final: 220 clusters (target 220)
[leiden_X_bbknn_d8_K220] unused protos: 0/220 (0.00%)
[leiden_X_bbknn_d8_K220] mean cell-type purity: 0.8989  (size-weighted: 0.9208 ± 0.1253)
[leiden_X_bbknn_d8_K220] mean batch entropy: 0.8282  (size-weighted: 0.9041 ± 0.4124)
[leiden_X_bbknn_d8_K220] coverage: 0.7857
[leiden_X_bbknn_d8_K220] modularity: 0.4621
[leiden_X_bbknn_d8_K220] per-batch modularity: mean=0.3758, std=0.0676
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.3882 | saved to /content/drive/MyDrive/models/pancreas/leiden_X_bbknn_d8_K220/aff_dc_compactness.csv
[leiden_X_bbknn_d8_K220] saved metrics to /content/drive/MyDrive/models/pancreas/leiden_X_bbknn_d8_K220
[/content/drive/MyDrive/models/pancreas/leiden_X_bbknn_d8_K220] modularity recomputed against canonical graph: mean_modularity_batch=0.3758028830259232 +/- 0.06759127216176526 (was 0.3758028830259232), K_target=220

100%|██████████| 220/220 [00:01<00:00, 167.62it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_bbknn_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_bbknn_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pancreas/leiden_X_bbknn_d8_K220
[pancreas] leiden-on-X_bbknn_d8 saved to /content/drive/MyDrive/models/pancreas/leiden_X_bbknn_d8_K220

[pancreas] rare-type kNN purity by method: {'raw_pca': 0.499}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] Raw PCA (uncorrected) (d=50): 0.385 +/- 0.164 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] scProto (d=8): 0.454 +/- 0.184 (n=8 batches)
[pancreas] affinity purity saved to /content/drive/MyDrive/models/pancreas/rare_affinity_purity_pancreas.json

## Run: Lung

In [6]:
lung_results = run_all_baselines_for_dataset(
    'lung', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading lung data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading lung
loading lung data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [16]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.255/24.467/119.300, effk_med=63.8, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/lung/pretrain/pretrain_ds-lung_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'lung', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'batch'}
📊 EdgeDataset: 2447924 edges
   Weight range: [0.0137, 0.9491]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2447924 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//lung/proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/32 [00:00<?, ?it/s]

=== [lung] batch-correction method: bbknn ===
WARNING: consider updating your call to make use of `computation`
[lung] bbknn_d8: cached graph to /content/drive/MyDrive/models/lung/_cache_X_bbknn_d8_aff.npz
[waypoint init] N=32472  k=300  n_eigs=10  nnz=1474964  nnz/row=45.4
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1085.84archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] No GPU → use_sparse=True (sparse CPU, avoids dense K)
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells!
Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.41957
Starting iteration 1.
Completed iteration 1.
Converged after 7 iterations.
Converged after 8 iterations.
Converged after 9 iterations.
Starting iteration 10.
Completed iteration 10.
Converged after 10 iterations.

100%|██████████| 300/300 [00:04<00:00, 68.13it/s]

saving to:  /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 2 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8 ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8471  (size-weighted: 0.8239 ± 0.2004)
[seacell] mean batch entropy: 1.1679  (size-weighted: 1.0775 ± 0.4650)
[seacell] coverage: 1.0000
[seacell] modularity: 0.4119
[seacell] per-batch modularity: mean=0.3775, std=0.0502
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=12.0289 | saved to /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8
[lung] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl (nnz=2480396) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/lung/seacell_X_bbknn_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.28943811114227114 +/- 0.056276308881835616 (was 0.3774585044813702), K_target=300
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_bbknn_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

Deleted: tmp_979a3cf7.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.8596
[seacell task2] scgraph_corr_std: 0.0792
  [leiden oversegment] resolution=1.0000 -> 19 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 30 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 46 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 84 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 148 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 279 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 592 clusters (need >= 300)
  [leiden merge] -> 590 clusters (target 300)
  [leiden merge] -> 580 clusters (target 300)
  [leiden merge] -> 570 clusters (target 300)
  [leiden merge] -> 560 clusters (target 300)
  [leiden merge] -> 550 clusters (target 300)
  [leiden merge] -> 540 clusters (target 300)
  [leiden merge] -> 530 clusters (target 300)
  [leiden merge] -> 520 clusters (target 300)
  [leiden merge] -> 510 clusters (target 300)
  [leiden merge] -> 500 clusters (target 300)
  [leiden merge] -> 490 clusters (target 300)
  [leiden merge] -> 480 clusters (target 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_bbknn_d8_K300] unused protos: 0/300 (0.00%)
[leiden_X_bbknn_d8_K300] mean cell-type purity: 0.7768  (size-weighted: 0.7934 ± 0.2015)
[leiden_X_bbknn_d8_K300] mean batch entropy: 1.0705  (size-weighted: 1.2600 ± 0.3933)
[leiden_X_bbknn_d8_K300] coverage: 0.8824
[leiden_X_bbknn_d8_K300] modularity: 0.5669
[leiden_X_bbknn_d8_K300] per-batch modularity: mean=0.4720, std=0.0905
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=5.4760 | saved to /content/drive/MyDrive/models/lung/leiden_X_bbknn_d8_K300/aff_dc_compactness.csv
[leiden_X_bbknn_d8_K300] saved metrics to /content/drive/MyDrive/models/lung/leiden_X_bbknn_d8_K300
[/content/drive/MyDrive/models/lung/leiden_X_bbknn_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.4719774588385782 +/- 0.09053421916101763 (was 0.4719774588385782), K_target=300

100%|██████████| 300/300 [00:02<00:00, 103.97it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_bbknn_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_bbknn_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/lung/leiden_X_bbknn_d8_K300
[lung] leiden-on-X_bbknn_d8 saved to /content/drive/MyDrive/models/lung/leiden_X_bbknn_d8_K300

[lung] rare-type kNN purity by method: {'raw_pca': 0.912}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] Raw PCA (uncorrected) (d=50): 0.559 +/- 0.194 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] scProto (d=8): 0.586 +/- 0.208 (n=15 batches)
[lung] affinity purity saved to /content/drive/MyDrive/models/lung/rare_affinity_purity_lung.json

## Run: PBMC (Immune)

In [7]:
immune_results = run_all_baselines_for_dataset(
    'pbmc-immune', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading pbmc-immune
loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [5]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=1.667/25.923/299.545, effk_med=62.9, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pbmc-immune/pretrain/pretrain_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pbmc-immune', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'study'}
📊 EdgeDataset: 2590828 edges
   Weight range: [0.0050, 0.9224]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2590828 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pbmc-immune/proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/33 [00:00<?, ?it/s]

=== [pbmc-immune] batch-correction method: bbknn ===
WARNING: consider updating your call to make use of `computation`
[pbmc-immune] bbknn_d8: cached graph to /content/drive/MyDrive/models/pbmc-immune/_cache_X_bbknn_d8_aff.npz
[waypoint init] N=33506  k=300  n_eigs=10  nnz=355552  nnz/row=10.6
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1215.18archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] No GPU → use_sparse=True (sparse CPU, avoids dense K)
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells!
Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.36422
Starting iteration 1.
Completed iteration 1.
Converged after 9 iterations.
Starting iteration 10.
Completed iteration 10.
Converged after 10 iterations.

100%|██████████| 300/300 [00:05<00:00, 55.58it/s]

saving to:  /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 2 obsm, 0 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8 ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.7804  (size-weighted: 0.7639 ± 0.2068)
[seacell] mean batch entropy: 0.5393  (size-weighted: 0.4977 ± 0.3188)
[seacell] coverage: 1.0000
[seacell] modularity: 0.2623
[seacell] per-batch modularity: mean=0.3077, std=0.1824
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=12.0654 | saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8
[pbmc-immune] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl (nnz=2624382) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.2566299945928785 +/- 0.1999247890255073 (was 0.3076926733233941), K_target=300
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_bbknn_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_8b96d19f.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.7955
[seacell task2] scgraph_corr_std: 0.1354
  [leiden oversegment] resolution=1.0000 -> 18 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 32 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 64 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 127 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 246 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 474 clusters (need >= 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_bbknn_d8_K300] unused protos: 0/300 (0.00%)
[leiden_X_bbknn_d8_K300] mean cell-type purity: 0.8278  (size-weighted: 0.8282 ± 0.1483)
[leiden_X_bbknn_d8_K300] mean batch entropy: 0.2461  (size-weighted: 0.5403 ± 0.4262)
[leiden_X_bbknn_d8_K300] coverage: 1.0000
[leiden_X_bbknn_d8_K300] modularity: 0.4239
[leiden_X_bbknn_d8_K300] per-batch modularity: mean=0.4284, std=0.0895
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.8055 | saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_bbknn_d8_K300/aff_dc_compactness.csv
[leiden_X_bbknn_d8_K300] saved metrics to /content/drive/MyDrive/models/pbmc-immune/leiden_X_bbknn_d8_K300
[/content/drive/MyDrive/models/pbmc-immune/leiden_X_bbknn_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.4284225726332832 +/- 0.08950170893710754 (was 0.4284225726332832), K_target=300

100%|██████████| 300/300 [00:02<00:00, 107.58it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_bbknn_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_bbknn_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_bbknn_d8_K300
[pbmc-immune] leiden-on-X_bbknn_d8 saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_bbknn_d8_K300

[pbmc-immune] rare-type kNN purity by method: {'raw_pca': 0.776}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] Raw PCA (uncorrected) (d=50): 0.827 +/- 0.050 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] scProto (d=8): 0.849 +/- 0.085 (n=5 batches)
[pbmc-immune] affinity purity saved to /content/drive/MyDrive/models/pbmc-immune/rare_affinity_purity_pbmc-immune.json

## Results comparison

Pulls in **every** existing run under `MODEL_DIR/{ds}/*` (scProto, SEACells(PCA), plus
whatever's already been computed by the Harmony/ComBat notebooks, alongside the new
BBKNN baselines here) -- `load_task1_multi` / `rare_celltype_purity_table` just scan
folders + `metrics.json` / `umap_cells.csv`, they don't need to know which notebook
produced them.

Harmony is included in the comparison tables below (via `harmony_read_only_keywords`)
purely as a READ of whatever's already on disk from the Harmony notebook -- it is never
(re)computed here. If that notebook hasn't been run yet, those rows are simply absent,
not an error. (ComBat is not pulled in automatically here -- add
`{"seacell_X_combat": "SEACells (ComBat)", "leiden_X_combat": "Leiden (ComBat)"}` to
`extra_read_only` in the next cell if you want it in this notebook's tables too.)

**Reminder:** the modularity column is scored against the arbf-on-PCA graph that only
scProto is trained to match -- treat it as a plausibility check, not the primary
evidence. Purity, batch entropy, and especially the rare-cell coverage/homogeneity
table (further down) are the fair, post-hoc comparison.

In [8]:
dataset_display_names = {'pancreas': 'Pancreas', 'lung': 'Lung', 'pbmc-immune': 'Immune'}

# Shared across the Harmony/ComBat/BBKNN notebooks -- see
# interpretable_ssl/evaluation/rebuttal_report.py for why this used to be ~10
# near-duplicated cells per notebook (Table 1/2, rare-cell table, 4 significance
# tests) and now is not.
from interpretable_ssl.evaluation.rebuttal_report import (
    build_model_keywords, harmony_read_only_keywords, render_full_comparison_report,
    render_realized_k_check,
)

# Harmony is included READ-ONLY here -- pulled in for side-by-side comparison if the
# Harmony notebook has already produced it. Never (re)computed by this notebook. If
# that notebook hasn't been run yet, these keys simply match nothing on disk yet, not
# an error.
MODEL_KEYWORDS = build_model_keywords(
    CORRECTION_METHODS, METHOD_DISPLAY_NAMES,
    extra_read_only=harmony_read_only_keywords(harmony_dim=8),
)
MODEL_KEYWORDS

{'proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp': 'scProto',
 'seacell': 'SEACells (PCA)',
 'seacell_X_bbknn_d8': 'SEACells (BBKNN)',
 'leiden_X_bbknn_d8': 'Leiden (BBKNN)',
 'seacell_X_harmony_d8': 'SEACells (Harmony)',
 'leiden_X_harmony_d8': 'Leiden (Harmony)'}

In [9]:
report = render_full_comparison_report(
    RNA_SEQ_DATASETS, dataset_display_names, MODEL_KEYWORDS, ref_name='scProto',
)
# report also holds the underlying DataFrames (report['task1'], report['rare'],
# report['rare_sig_paired'], etc.) if you need them beyond what's printed/displayed above.

=== Table 1: community structure / batch integration ===

=== Table 2: metacell representation quality ===

  [scProto|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] run dir resolved (0.0s)
  [SEACells (BBKNN)|pancreas] resolving run dir ...
  [Leiden (BBKNN)|pancreas] resolving run dir ...
  [SEACells (Harmony)|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] reading umap_cells.csv ...  [Leiden (Harmony)|pancreas] resolving run dir ...

  [scProto|lung] resolving run dir ...
  [SEACells (PCA)|lung] resolving run dir ...
  [SEACells (PCA)|lung] run dir resolved (0.0s)
  [SEACells (PCA)|lung] reading umap_cells.csv ...
  [scProto|lung] run dir resolved (0.1s)
  [scProto|lung] reading umap_cells.csv ...
  [SEACells (Harmony)|pancreas] run dir resolved (0.2s)
  [SEACells (BBKNN)|pancreas] run dir resolved (0.2s)
  [Leiden (BBKNN)|pancreas] run dir resolved (0.2s)
  [SEACells (Harmony)|pancreas] reading umap_cells.csv ...
  [scProto|pancreas] run dir resolved (0.2s)
  [SEACells (BBKNN)|pancreas] reading umap_cells.csv ...
  [Leiden (BBKNN)|pancreas] reading umap_cells.csv ...
  [scProto|pancreas] reading umap_cells.csv ...
  [Leiden (Harmony)|pancreas] run dir resolved (0.2s)
  [Leiden (Harmony)|pancreas] reading umap_cells.csv ...
  [SEACells (BBKNN)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [Leiden (BBKNN)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [SEACells (BBKNN)|pancreas] reading umap_protos.csv ...
  [Leiden (BBKNN)|pancreas] reading umap_protos.csv ...
  [SEACells (BBKNN)|pancreas] umap_protos.csv loaded (0.0s)
  [Leiden (BBKNN)|pancreas] umap_protos.csv loaded (0.0s)
  [SEACells (BBKNN)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (BBKNN)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (BBKNN)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (BBKNN)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (BBKNN)|pancreas] label fractions done (0.0s)
  [SEACells (BBKNN)|pancreas] label fractions done (0.0s)
  [SEACells (BBKNN)|pancreas] done
  [SEACells (BBKNN)|lung] resolving run dir ...
  [SEACells (BBKNN)] ds=pancreas: coverage=0.25±0.31  repr macro=0.19±0.07  micro=0.20±0.07  homogeneity=0.20±0.07  cross_batch_homog=0.12±0.06  purity=0.64±0.14  recall=0.20±0.23  precision=0.29±0.20  F1=0.18±0.22
  [SEACells (BBKNN)|lung] run dir resolved (0.0s)  [Leiden (BBKNN)|pancreas] done

  [Leiden (BBKNN)|lung] resolving run dir ...
  [Leiden (BBKNN)] ds=pancreas: coverage=0.17±0.13  repr macro=0.15±0.05  micro=0.16±0.06  homogeneity=0.16±0.06  cross_batch_homog=0.13±0.06  purity=0.61±0.19  recall=0.14±0.12  precision=0.29±0.22  F1=0.10±0.08
  [SEACells (BBKNN)|lung] reading umap_cells.csv ...
  [Leiden (BBKNN)|lung] run dir resolved (0.0s)
  [Leiden (BBKNN)|lung] reading umap_cells.csv ...
  [SEACells (BBKNN)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [SEACells (BBKNN)|lung] reading umap_protos.csv ...
  [SEACells (BBKNN)|lung] umap_protos.csv loaded (0.0s)
  [SEACells (BBKNN)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [Leiden (BBKNN)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [SEACells (BBKNN)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [Leiden (BBKNN)|lung] reading umap_protos.csv ...
  [Leiden (BBKNN)|lung] umap_protos.csv loaded (0.0s)
  [Leiden (BBKNN)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [Leiden (BBKNN)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (BBKNN)|lung] label fractions done (0.0s)
  [Leiden (BBKNN)|lung] label fractions done (0.0s)
  [SEACells (BBKNN)|lung] done
  [SEACells (Harmony)|lung] resolving run dir ...
  [SEACells (BBKNN)] ds=lung: coverage=0.54±0.27  repr macro=0.38±0.16  micro=0.40±0.16  homogeneity=0.40±0.16  cross_batch_homog=0.38±0.17  purity=0.80±0.06  recall=0.42±0.29  precision=0.73±0.06  F1=0.39±0.22
  [SEACells (Harmony)|lung] run dir resolved (0.0s)
  [SEACells (PCA)|pancreas] umap_cells.csv loaded (16382 rows, 1.0s)
  [SEACells (Harmony)|lung] reading umap_cells.csv ...
  [SEACells (PCA)|pancreas] reading umap_protos.csv ...
  [Leiden (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 1.0s)
  [Leiden (Harmony)|pancreas] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 1.1s)  [scProto|pancreas] umap_cells.csv loaded (16382 rows, 1.1s)
  [scProto|lung] umap_cells.csv loaded (32472 rows, 1.2s)

  [scProto|pancreas] reading umap_protos.csv ...
  [scProto|lung] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] reading umap_protos.csv ...
  [Leiden (BBKNN)|lung] done
  [Leiden (Harmony)|lung] resolving run dir ...
  [Leiden (BBKNN)] ds=lung: coverage=0.45±0.24  repr macro=0.34±0.11  micro=0.36±0.11  homogeneity=0.36±0.11  cross_batch_homog=0.33±0.11  purity=0.77±0.10  recall=0.33±0.19  precision=0.63±0.13  F1=0.31±0.17
  [Leiden (Harmony)|lung] run dir resolved (0.0s)
  [Leiden (Harmony)|lung] reading umap_cells.csv ...
  [SEACells (PCA)|pancreas] umap_protos.csv loaded (0.3s)
  [SEACells (PCA)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (PCA)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (PCA)|pancreas] label fractions done (0.0s)
  [SEACells (Harmony)|lung] umap_cells.csv loaded (32472 rows, 0.5s)
  [SEACells (Harmony)|lung] reading umap_protos.csv ...
  [SEACells (PCA)|lung] umap_cells.csv loaded (32472 rows, 1.5s)
  [SEACells (PCA)|lung] reading umap_protos.csv ...
  [scProto|pancreas] umap_protos.csv loaded (0.3s)
  [SEACells (PCA)|pancreas] done
  [scProto|pbmc-immune] resolving run dir ...
  [SEACells (PCA)] ds=pancreas: coverage=0.43±0.27  repr macro=0.39±0.20  micro=0.42±0.20  homogeneity=0.42±0.20  cross_batch_homog=0.22±0.10  purity=0.82±0.13  recall=0.41±0.24  precision=0.54±0.22  F1=0.37±0.25
  [scProto|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [scProto|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] umap_protos.csv loaded (0.4s)
  [scProto|pancreas] label fractions done (0.0s)  [Leiden (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...

  [Leiden (Harmony)|pancreas] label fractions done (0.0s)
  [scProto|lung] umap_protos.csv loaded (0.4s)
  [scProto|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto|pancreas] done  [SEACells (Harmony)|pancreas] umap_protos.csv loaded (0.4s)
  [scProto|lung] label='cell_type', batch='batch' | computing metacell label fractions ...

  [SEACells (PCA)|pbmc-immune] resolving run dir ...
  [scProto] ds=pancreas: coverage=0.64±0.24  repr macro=0.53±0.17  micro=0.56±0.16  homogeneity=0.56±0.16  cross_batch_homog=0.32±0.18  purity=0.88±0.08  recall=0.54±0.20  precision=0.77±0.13  F1=0.54±0.21
  [SEACells (PCA)|pbmc-immune] run dir resolved (0.0s)
  [SEACells (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (PCA)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (PCA)|lung] umap_protos.csv loaded (0.3s)
  [SEACells (Harmony)|lung] umap_protos.csv loaded (0.4s)
  [SEACells (Harmony)|pancreas] label fractions done (0.1s)
  [SEACells (PCA)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (PCA)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] done
  [SEACells (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [scProto|lung] label fractions done (0.2s)
  [SEACells (BBKNN)|pbmc-immune] resolving run dir ...
  [Leiden (Harmony)] ds=pancreas: coverage=0.40±0.24  repr macro=0.21±0.09  micro=0.22±0.09  homogeneity=0.22±0.09  cross_batch_homog=0.19±0.08  purity=0.52±0.20  recall=0.28±0.19  precision=0.24±0.18  F1=0.22±0.17
  [scProto|pbmc-immune] run dir resolved (0.4s)
  [scProto|pbmc-immune] reading umap_cells.csv ...
  [SEACells (PCA)|lung] label fractions done (0.1s)
  [SEACells (Harmony)|lung] label fractions done (0.0s)
  [SEACells (PCA)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.4s)
  [SEACells (PCA)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] done
  [Leiden (BBKNN)|pbmc-immune] resolving run dir ...
  [SEACells (Harmony)] ds=pancreas: coverage=0.56±0.28  repr macro=0.27±0.12  micro=0.29±0.12  homogeneity=0.29±0.12  cross_batch_homog=0.23±0.10  purity=0.56±0.16  recall=0.35±0.14  precision=0.36±0.18  F1=0.32±0.16
  [Leiden (BBKNN)|pbmc-immune] run dir resolved (0.0s)
  [Leiden (BBKNN)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (BBKNN)|pbmc-immune] run dir resolved (0.6s)
  [SEACells (BBKNN)|pbmc-immune] reading umap_cells.csv ...
  [scProto|lung] done
  [SEACells (Harmony)|pbmc-immune] resolving run dir ...
  [scProto] ds=lung: coverage=0.79±0.18  repr macro=0.56±0.20  micro=0.58±0.22  homogeneity=0.58±0.22  cross_batch_homog=0.51±0.20  purity=0.85±0.04  recall=0.60±0.23  precision=0.70±0.14  F1=0.60±0.18
  [SEACells (PCA)|pbmc-immune] umap_protos.csv loaded (0.5s)
  [SEACells (PCA)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (Harmony)|lung] umap_cells.csv loaded (32472 rows, 1.4s)
  [SEACells (Harmony)|pbmc-immune] run dir resolved (0.0s)
  [SEACells (PCA)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (BBKNN)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.5s)  [Leiden (Harmony)|lung] reading umap_protos.csv ...

  [SEACells (PCA)|lung] done
  [Leiden (Harmony)|pbmc-immune] resolving run dir ...
  [Leiden (BBKNN)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (PCA)] ds=lung: coverage=0.52±0.23  repr macro=0.43±0.19  micro=0.47±0.24  homogeneity=0.47±0.24  cross_batch_homog=0.39±0.20  purity=0.90±0.03  recall=0.41±0.23  precision=0.90±0.04  F1=0.42±0.22
  [Leiden (Harmony)|pbmc-immune] run dir resolved (0.0s)
  [Leiden (BBKNN)|pbmc-immune] umap_protos.csv loaded (0.1s)
  [Leiden (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [scProto|pbmc-immune] umap_cells.csv loaded (33506 rows, 1.0s)
  [Leiden (BBKNN)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (BBKNN)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...  [scProto|pbmc-immune] reading umap_protos.csv ...

  [SEACells (BBKNN)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.5s)
  [SEACells (BBKNN)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (Harmony)|lung] done
  [SEACells (Harmony)] ds=lung: coverage=0.54±0.19  repr macro=0.36±0.10  micro=0.40±0.12  homogeneity=0.40±0.12  cross_batch_homog=0.37±0.12  purity=0.73±0.07  recall=0.38±0.17  precision=0.62±0.11  F1=0.36±0.14
  [SEACells (PCA)|pbmc-immune] label fractions done (0.4s)
  [SEACells (BBKNN)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [SEACells (BBKNN)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (BBKNN)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [Leiden (BBKNN)|pbmc-immune] label fractions done (0.1s)
  [Leiden (Harmony)|lung] umap_protos.csv loaded (0.3s)
  [Leiden (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [Leiden (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (BBKNN)|pbmc-immune] label fractions done (0.1s)
  [Leiden (Harmony)|lung] label fractions done (0.1s)
  [SEACells (PCA)|pbmc-immune] done
  [SEACells (PCA)] ds=pbmc-immune: coverage=1.00±0.00  repr macro=0.84±0.08  micro=0.85±0.07  homogeneity=0.85±0.07  cross_batch_homog=0.12±0.17  purity=0.93±0.03  recall=0.87±0.09  precision=0.94±0.01  F1=0.88±0.08
  [scProto|pbmc-immune] umap_protos.csv loaded (0.4s)
  [scProto|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.5s)
  [scProto|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [Leiden (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.7s)
  [SEACells (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (BBKNN)|pbmc-immune] done
  [Leiden (BBKNN)] ds=pbmc-immune: coverage=0.70±0.27  repr macro=0.55±0.23  micro=0.57±0.23  homogeneity=0.57±0.23  cross_batch_homog=0.31±0.19  purity=0.73±0.14  recall=0.60±0.30  precision=0.78±0.13  F1=0.60±0.29
  [scProto|pbmc-immune] label fractions done (0.3s)
  [SEACells (BBKNN)|pbmc-immune] done
  [SEACells (BBKNN)] ds=pbmc-immune: coverage=0.90±0.20  repr macro=0.52±0.19  micro=0.55±0.22  homogeneity=0.55±0.22  cross_batch_homog=0.24±0.12  purity=0.71±0.21  recall=0.64±0.20  precision=0.64±0.19  F1=0.61±0.21
  [SEACells (Harmony)|pbmc-immune] umap_protos.csv loaded (0.4s)
  [Leiden (Harmony)|lung] done
  [Leiden (Harmony)] ds=lung: coverage=0.43±0.26  repr macro=0.33±0.10  micro=0.34±0.08  homogeneity=0.34±0.08  cross_batch_homog=0.33±0.09  purity=0.69±0.09  recall=0.31±0.17  precision=0.49±0.13  F1=0.28±0.14
  [Leiden (Harmony)|pbmc-immune] umap_protos.csv loaded (0.4s)
  [SEACells (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [Leiden (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [Leiden (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (Harmony)|pbmc-immune] label fractions done (0.0s)
  [Leiden (Harmony)|pbmc-immune] label fractions done (0.0s)
  [scProto|pbmc-immune] done
  [scProto] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.81±0.11  micro=0.83±0.10  homogeneity=0.83±0.10  cross_batch_homog=0.35±0.20  purity=0.92±0.08  recall=0.88±0.12  precision=0.90±0.03  F1=0.85±0.14
  [SEACells (Harmony)|pbmc-immune] done
  [SEACells (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.65±0.17  micro=0.68±0.19  homogeneity=0.68±0.19  cross_batch_homog=0.25±0.15  purity=0.82±0.10  recall=0.77±0.15  precision=0.81±0.08  F1=0.75±0.16
  [Leiden (Harmony)|pbmc-immune] done
  [Leiden (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.61±0.11  micro=0.64±0.13  homogeneity=0.64±0.13  cross_batch_homog=0.30±0.18  purity=0.79±0.14  recall=0.80±0.12  precision=0.75±0.15  F1=0.75±0.17

=== Rare-cell-type table (key hypothesis test) ===

=== UNPAIRED rare-cell significance (Mann-Whitney U) ===

,dataset,metric,method,k,n,median,mean,std,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,scProto,219,8,0.437680,0.535403,0.207961,NaN,NaN,NaN
1,Pancreas,batch_rare_f1_macro,SEACells (PCA),220,8,0.372628,0.370589,0.250869,0.032643,0.163214,ns
2,Pancreas,batch_rare_f1_macro,SEACells (BBKNN),220,8,0.155239,0.177425,0.218077,0.003616,0.018081,*
3,Pancreas,batch_rare_f1_macro,Leiden (BBKNN),220,8,0.133314,0.100205,0.083917,0.000453,0.002267,**
4,Pancreas,batch_rare_f1_macro,SEACells (Harmony),220,8,0.295521,0.316501,0.159421,0.014064,0.070319,ns
5,Pancreas,batch_rare_f1_macro,Leiden (Harmony),220,8,0.133361,0.223580,0.171156,0.002331,0.011655,*
6,Pancreas,batch_rare_homogeneity,scProto,219,8,0.522129,0.564854,0.155263,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,SEACells (PCA),220,8,0.369265,0.420592,0.195138,0.010334,0.051671,ns
8,Pancreas,batch_rare_homogeneity,SEACells (BBKNN),220,8,0.190313,0.198640,0.070060,0.000078,0.000389,***
9,Pancreas,batch_rare_homogeneity,Leiden (BBKNN),220,8,0.156982,0.164399,0.059724,0.000078,0.000389,***
10,Pancreas,batch_rare_homogeneity,SEACells (Harmony),220,8,0.269034,0.285358,0.115015,0.000932,0.004662,**
11,Pancreas,batch_rare_homogeneity,Leiden (Harmony),220,8,0.220189,0.218359,0.085397,0.000155,0.000777,***
12,Pancreas,batch_rare_cross_batch_homog,scProto,219,8,0.259411,0.322859,0.179414,NaN,NaN,NaN
13,Pancreas,batch_rare_cross_batch_homog,SEACells (PCA),220,8,0.212005,0.221772,0.100594,0.139316,0.696581,ns
14,Pancreas,batch_rare_cross_batch_homog,SEACells (BBKNN),220,8,0.114371,0.124110,0.056343,0.002331,0.011655,*
15,Pancreas,batch_rare_cross_batch_homog,Leiden (BBKNN),220,8,0.113946,0.126961,0.061576,0.003497,0.017483,*
16,Pancreas,batch_rare_cross_batch_homog,SEACells (Harmony),220,8,0.210341,0.227762,0.098150,0.097436,0.487179,ns
17,Pancreas,batch_rare_cross_batch_homog,Leiden (Harmony),220,8,0.183894,0.188323,0.084876,0.052448,0.262238,ns
18,Lung,batch_rare_f1_macro,scProto,298,15,0.610777,0.599348,0.175935,NaN,NaN,NaN
19,Lung,batch_rare_f1_macro,SEACells (PCA),300,15,0.498294,0.420330,0.217382,0.040680,0.203398,ns
20,Lung,batch_rare_f1_macro,SEACells (BBKNN),300,15,0.355411,0.388414,0.223866,0.005696,0.028480,*
21,Lung,batch_rare_f1_macro,Leiden (BBKNN),300,15,0.281237,0.311806,0.166749,0.000067,0.000337,***
22,Lung,batch_rare_f1_macro,SEACells (Harmony),300,15,0.348333,0.357564,0.144189,0.000606,0.003030,**
23,Lung,batch_rare_f1_macro,Leiden (Harmony),300,15,0.282094,0.280384,0.141206,0.000034,0.000170,***
24,Lung,batch_rare_homogeneity,scProto,298,15,0.586120,0.577994,0.220956,NaN,NaN,NaN
25,Lung,batch_rare_homogeneity,SEACells (PCA),300,15,0.495372,0.472356,0.242324,0.140421,0.702105,ns
26,Lung,batch_rare_homogeneity,SEACells (BBKNN),300,15,0.415064,0.401673,0.156889,0.013963,0.069813,ns
27,Lung,batch_rare_homogeneity,Leiden (BBKNN),300,15,0.359515,0.360325,0.106950,0.001845,0.009226,**
28,Lung,batch_rare_homogeneity,SEACells (Harmony),300,15,0.408222,0.402522,0.115704,0.009033,0.045167,*
29,Lung,batch_rare_homogeneity,Leiden (Harmony),300,15,0.344610,0.344719,0.084300,0.000933,0.004664,**
30,Lung,batch_rare_cross_batch_homog,scProto,298,15,0.509701,0.508327,0.196956,NaN,NaN,NaN
31,Lung,batch_rare_cross_batch_homog,SEACells (PCA),300,15,0.415586,0.393655,0.201346,0.073288,0.366440,ns
32,Lung,batch_rare_cross_batch_homog,SEACells (BBKNN),300,15,0.393091,0.377310,0.166955,0.048546,0.242728,ns
33,Lung,batch_rare_cross_batch_homog,Leiden (BBKNN),300,15,0.339222,0.331898,0.114702,0.003970,0.019851,*
34,Lung,batch_rare_cross_batch_homog,SEACells (Harmony),300,15,0.398968,0.371869,0.121918,0.013963,0.069813,ns
35,Lung,batch_rare_cross_batch_homog,Leiden (Harmony),300,15,0.341005,0.328868,0.089351,0.001845,0.009226,**
36,Immune,batch_rare_f1_macro,scProto,294,5,0.896681,0.854140,0.138252,NaN,NaN,NaN
37,Immune,batch_rare_f1_macro,SEACells (PCA),300,5,0.922877,0.879883,0.082663,0.579365,1.000000,ns
38,Immune,batch_rare_f1_macro,SEACells (BBKNN),300,5,0.628953,0.613644,0.207083,0.154762,0.773810,ns
39,Immune,batch_rare_f1_macro,Leiden (BBKNN),300,5,0.602054,0.602770,0.286204,0.154762,0.773810,ns
40,Immune,batch_rare_f1_macro,SEACells (Harmony),300,5,0.812234,0.750774,0.162481,0.154762,0.773810,ns
41,Immune,batch_rare_f1_macro,Leiden (Harmony),300,5,0.765805,0.751472,0.166212,0.210317,1.000000,ns
42,Immune,batch_rare_homogeneity,scProto,294,5,0.855792,0.827192,0.101982,NaN,NaN,NaN
43,Immune,batch_rare_homogeneity,SEACells (PCA),300,5,0.815416,0.854752,0.073552,0.726190,1.000000,ns
44,Immune,batch_rare_homogeneity,SEACells (BBKNN),300,5,0.654399,0.545034,0.219855,0.027778,0.138889,ns
45,Immune,batch_rare_homogeneity,Leiden (BBKNN),300,5,0.664780,0.565380,0.231909,0.075397,0.376984,ns
46,Immune,batch_rare_homogeneity,SEACells (Harmony),300,5,0.804136,0.676898,0.185473,0.111111,0.555556,ns
47,Immune,batch_rare_homogeneity,Leiden (Harmony),300,5,0.706627,0.635473,0.125110,0.027778,0.138889,ns
48,Immune,batch_rare_cross_batch_homog,scProto,294,5,0.406766,0.349204,0.197947,NaN,NaN,NaN
49,Immune,batch_rare_cross_batch_homog,SEACells (PCA),300,5,0.028607,0.120662,0.166976,0.172871,0.864355,ns
50,Immune,batch_rare_cross_batch_homog,SEACells (BBKNN),300,5,0.269120,0.240877,0.121590,0.154762,0.773810,ns
51,Immune,batch_rare_cross_batch_homog,Leiden (BBKNN),300,5,0.360551,0.308086,0.192517,0.420635,1.000000,ns
52,Immune,batch_rare_cross_batch_homog,SEACells (Harmony),300,5,0.304594,0.245410,0.153361,0.273810,1.000000,ns
53,Immune,batch_rare_cross_batch_homog,Leiden (Harmony),300,5,0.372796,0.304595,0.181786,0.458281,1.000000,ns

=== PAIRED rare-cell significance (Wilcoxon signed-rank, recommended) ===
=== batch_rare_f1_macro: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.602 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.281 (K=300, n=15, wins=14.0/15) ** p_adj=0...","0.133 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
Leiden (Harmony),"0.766 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.282 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.133 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (BBKNN),"0.629 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.355 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.155 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (Harmony),"0.812 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.348 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.296 (K=220, n=8, wins=7.0/8) ns p_adj=0.0586"
SEACells (PCA),"0.923 (K=300, n=5, wins=2.0/5) ns p_adj=1","0.498 (K=300, n=15, wins=11.0/15) ** p_adj=0...","0.373 (K=220, n=8, wins=6.0/8) ns p_adj=0.195"
scProto,"0.897 (K=294, n=5) [ref]","0.611 (K=298, n=15) [ref]","0.438 (K=219, n=8) [ref]"

=== batch_rare_homogeneity: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.665 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.360 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.157 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
Leiden (Harmony),"0.707 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.345 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.220 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (BBKNN),"0.654 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.415 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.190 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (Harmony),"0.804 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.408 (K=300, n=15, wins=14.0/15) * p_adj=0....","0.269 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
SEACells (PCA),"0.815 (K=300, n=5, wins=3.0/5) ns p_adj=1","0.495 (K=300, n=15, wins=13.0/15) * p_adj=0....","0.369 (K=220, n=8, wins=8.0/8) * p_adj=0.0195"
scProto,"0.856 (K=294, n=5) [ref]","0.586 (K=298, n=15) [ref]","0.522 (K=219, n=8) [ref]"

=== batch_rare_cross_batch_homog: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.361 (K=300, n=5, wins=4.0/5) ns p_adj=1","0.339 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.114 (K=220, n=8, wins=7.0/8) * p_adj=0.0391"
Leiden (Harmony),"0.373 (K=300, n=5, wins=2.0/5) ns p_adj=1","0.341 (K=300, n=15, wins=13.0/15) * p_adj=0....","0.184 (K=220, n=8, wins=6.0/8) ns p_adj=0.195"
SEACells (BBKNN),"0.269 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.393 (K=300, n=15, wins=13.0/15) ** p_adj=0...","0.114 (K=220, n=8, wins=7.0/8) * p_adj=0.0391"
SEACells (Harmony),"0.305 (K=300, n=5, wins=3.0/5) ns p_adj=0.781","0.399 (K=300, n=15, wins=14.0/15) * p_adj=0....","0.210 (K=220, n=8, wins=6.0/8) ns p_adj=0.371"
SEACells (PCA),"0.029 (K=300, n=5, wins=3.0/5) ns p_adj=0.36","0.416 (K=300, n=15, wins=12.0/15) ** p_adj=0...","0.212 (K=220, n=8, wins=5.0/8) ns p_adj=0.625"
scProto,"0.407 (K=294, n=5) [ref]","0.510 (K=298, n=15) [ref]","0.259 (K=219, n=8) [ref]"

=== UNPAIRED Table 1 significance (Mann-Whitney U) ===
=== modularity_per_batch: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.399 (K=300, n=5, wins=?/5) * p_adj=0.0397","0.458 (K=300, n=16, wins=?/16) *** p_adj=6.7...","0.390 (K=220, n=9, wins=?/9) ** p_adj=0.00198"
Leiden (Harmony),"0.250 (K=300, n=5, wins=?/5) * p_adj=0.0198","0.403 (K=300, n=16, wins=?/16) *** p_adj=4.6...","0.614 (K=220, n=9, wins=?/9) ns p_adj=1"
SEACells (BBKNN),"0.251 (K=300, n=5, wins=?/5) ns p_adj=0.139","0.361 (K=300, n=16, wins=?/16) *** p_adj=3.8...","0.398 (K=220, n=9, wins=?/9) ** p_adj=0.0067"
SEACells (Harmony),"0.551 (K=300, n=5, wins=?/5) ns p_adj=0.0794","0.625 (K=300, n=16, wins=?/16) *** p_adj=0.0...","0.566 (K=220, n=9, wins=?/9) ns p_adj=0.159"
SEACells (PCA),"0.569 (K=300, n=5, wins=?/5) ns p_adj=0.139","0.671 (K=300, n=16, wins=?/16) ns p_adj=1","0.658 (K=220, n=9, wins=?/9) ns p_adj=1"
scProto,"0.620 (K=294, n=5) [ref]","0.669 (K=298, n=16) [ref]","0.621 (K=219, n=9) [ref]"

=== purity_per_mc: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.856 (K=300, n=300, wins=?/300) *** p_adj=1...","0.833 (K=300, n=300, wins=?/300) *** p_adj=1...","0.999 (K=220, n=220, wins=?/220) ns p_adj=0.526"
Leiden (Harmony),"0.855 (K=300, n=300, wins=?/300) *** p_adj=2...","0.841 (K=300, n=300, wins=?/300) *** p_adj=1...","1.000 (K=220, n=220, wins=?/220) ns p_adj=1"
SEACells (BBKNN),"0.829 (K=300, n=300, wins=?/300) *** p_adj=1...","0.944 (K=300, n=300, wins=?/300) * p_adj=0.0126","0.981 (K=220, n=220, wins=?/220) ** p_adj=0...."
SEACells (Harmony),"0.883 (K=300, n=300, wins=?/300) *** p_adj=4...","0.832 (K=300, n=300, wins=?/300) *** p_adj=8...","0.967 (K=220, n=220, wins=?/220) *** p_adj=0..."
SEACells (PCA),"0.965 (K=300, n=300, wins=?/300) *** p_adj=8...","0.977 (K=300, n=300, wins=?/300) ns p_adj=1","0.993 (K=220, n=220, wins=?/220) ns p_adj=1"
scProto,"1.000 (K=294, n=294) [ref]","0.996 (K=298, n=298) [ref]","1.000 (K=219, n=219) [ref]"

=== batch_entropy_per_mc: scProto vs. each same-K baseline, one-sided Mann-Whitney U (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.143 (K=300, n=300, wins=?/300) ns p_adj=1","1.141 (K=300, n=300, wins=?/300) ns p_adj=1","0.900 (K=220, n=220, wins=?/220) ns p_adj=1"
Leiden (Harmony),"1.071 (K=300, n=300, wins=?/300) ns p_adj=1","1.350 (K=300, n=300, wins=?/300) ns p_adj=1","1.327 (K=220, n=220, wins=?/220) ns p_adj=1"
SEACells (BBKNN),"0.531 (K=300, n=300, wins=?/300) ns p_adj=1","1.162 (K=300, n=300, wins=?/300) ns p_adj=1","0.923 (K=220, n=220, wins=?/220) ns p_adj=1"
SEACells (Harmony),"0.726 (K=300, n=300, wins=?/300) ns p_adj=1","1.526 (K=300, n=300, wins=?/300) ns p_adj=1","1.339 (K=220, n=220, wins=?/220) ns p_adj=1"
SEACells (PCA),"-0.000 (K=300, n=300, wins=?/300) ns p_adj=1","0.218 (K=300, n=300, wins=?/300) ns p_adj=1","-0.000 (K=220, n=220, wins=?/220) *** p_adj=..."
scProto,"-0.000 (K=294, n=294) [ref]","0.500 (K=298, n=298) [ref]","0.214 (K=219, n=219) [ref]"

=== PAIRED Table 1 significance (modularity only, recommended for that metric) ===
=== modularity_per_batch: scProto vs. each same-K baseline, PAIRED one-sided Wilcoxon signed-rank (scProto > other), Bonferroni-corrected per dataset ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (BBKNN),"0.399 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.458 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.390 (K=220, n=9, wins=9.0/9) ** p_adj=0.00977"
Leiden (Harmony),"0.250 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.403 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.614 (K=220, n=9, wins=6.0/9) ns p_adj=1"
SEACells (BBKNN),"0.251 (K=300, n=5, wins=4.0/5) ns p_adj=0.312","0.361 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.398 (K=220, n=9, wins=8.0/9) * p_adj=0.0195"
SEACells (Harmony),"0.551 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.625 (K=300, n=16, wins=14.0/16) ** p_adj=0...","0.566 (K=220, n=9, wins=7.0/9) ns p_adj=0.625"
SEACells (PCA),"0.569 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.671 (K=300, n=16, wins=9.0/16) ns p_adj=1","0.658 (K=220, n=9, wins=0.0/9) ns p_adj=1"
scProto,"0.620 (K=294, n=5) [ref]","0.669 (K=298, n=16) [ref]","0.621 (K=219, n=9) [ref]"

### Realized cluster/metacell count vs. scProto's target K

Sanity check that BBKNN's downstream SEACells/Leiden actually landed at (approximately)
scProto's own `num_prototypes` for each dataset, per the paper's own protocol ("All
baselines are configured to produce the same number of metacells K as scProto"). Reads
directly from each run's saved outputs -- no recompute.

In [10]:
target_k = {ds: DATASETS[ds]['num_prototypes'] for ds in RNA_SEQ_DATASETS}
# 'bbknn_d8' matches the dimension-qualified tag BBKNN now runs under (see
# batch_correct_baselines.DIM_MATCHED_METHODS) -- render_realized_k_check takes the
# literal on-disk suffix, it doesn't know about dimension-matching itself.
_ = render_realized_k_check(RNA_SEQ_DATASETS, DATASETS, method='bbknn_d8')

,,n_clusters,resolution,target_k,matches_target
dataset,run,,,,
pancreas,leiden_X_bbknn_d8_K220,220.0,32.0,220,True
lung,leiden_X_bbknn_d8_K300,300.0,64.0,300,True
pbmc-immune,leiden_X_bbknn_d8_K300,300.0,32.0,300,True

                      n_actual  target_k  matches_target
dataset     method
pancreas    bbknn_d8       220       220            True
lung        bbknn_d8       300       300            True
pbmc-immune bbknn_d8       300       300            True

## Embedding-only rare-cell affinity purity (no downstream clustering)

**Does not apply to BBKNN** -- this diagnostic (used in the Harmony/ComBat notebooks)
needs a corrected EMBEDDING to build its own ARBF affinity graph on top of, so it can
isolate the embedding from whichever clustering algorithm runs on top of it. BBKNN has
no embedding at all -- its batch-balanced kNN graph IS the correction, fed directly to
SEACells/Leiden. The cell below will simply show no BBKNN row (nothing to compute), not
an error -- the rare-cell coverage/homogeneity/F1 table in the Results comparison
section above (scored on BBKNN's own graph directly, post-clustering) is the fair
comparison for this method instead.

In [11]:
from interpretable_ssl.evaluation.batch_correct_baselines import load_and_compare_affinity_purity

df_affinity_purity = load_and_compare_affinity_purity(
    RNA_SEQ_DATASETS, dataset_display_names=dataset_display_names,
)
df_affinity_purity

,dataset,method,dim,n,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,Raw PCA (uncorrected),50,8,0.385,0.164,7.0,0.0742,0.0742,ns
1,Pancreas,scProto,8,8,0.454,0.184,NaN,NaN,NaN,NaN
2,Lung,Raw PCA (uncorrected),50,15,0.559,0.194,11.0,0.0240,0.0240,*
3,Lung,scProto,8,15,0.586,0.208,NaN,NaN,NaN,NaN
4,Immune,Raw PCA (uncorrected),50,5,0.827,0.050,4.0,0.3125,0.3125,ns
5,Immune,scProto,8,5,0.849,0.085,NaN,NaN,NaN,NaN