## Status (created 2026-07-30) -- READ BEFORE RUNNING

**Standalone ComBat baseline notebook.** Deliberately a SEPARATE notebook from
`batch_correct_then_cluster_baselines.ipynb` (not an added arm inside it) so the two can
be run in parallel Colab sessions without one's config/state stomping the other's --
same underlying helper module (`interpretable_ssl/evaluation/batch_correct_baselines.py`),
just a different `CORRECTION_METHODS` value (`['combat']` here vs. `['harmony']` there).

Results land in the exact same on-disk run folders/metrics.json format the other
notebook uses (`seacell_X_combat`, `leiden_X_combat_K{n}`), so the comparison tables
below can pull in Harmony/scPoli/scVI results too, if those have already been run --
no need to re-run anything from the other notebook to see them side by side here.

If you already have this notebook open in another Colab tab, close it (or File >
Revert) first -- Colab autosaving from a stale tab can silently overwrite this file.

# Rebuttal experiment: ComBat batch-correction-then-cluster baseline -- ComBat latent -> {SEACells, Leiden}

**Purpose.** Reviewer nG29 (Question 3): *"How would batch-correction preprocessing
affect the comparison to other baselines? It would be interesting to see how the
performance of scProto would compare to other baselines if batch effects were removed a
priori (for example with Harmony or ComBat)."* The Harmony half of this question is
already answered in `batch_correct_then_cluster_baselines.ipynb`. This notebook runs the
ComBat half: apply original ComBat (Johnson, Li & Rabinovic 2007 -- `scanpy.pp.combat`,
built into scanpy, no extra install) to each dataset's log-normalized expression, PCA the
corrected matrix, then run **both** SEACells and Leiden on the resulting embedding --
replacing the paper's original weak `scPoli + K-means`-only comparison with a proper
two-step baseline, exactly as requested.

**Why ComBat is a meaningfully different comparison than Harmony/scPoli/scVI:** those
three all correct via a learned or iteratively-clustered embedding. ComBat instead fits
one linear (shift, spread) correction per gene per batch directly on gene expression --
no embedding, no clustering step, no neural network. Two structural properties of that
correction are worth watching for in the results (see
`baseline-notes/combat-notes.md` for the full reasoning):

1. ComBat cannot distinguish a genuine batch artifact from a rare cell state that
   happens to be confined to one batch -- both look like "batch i has an unusual mean
   for this gene," and correcting one flattens the other too.
2. ComBat fits a SINGLE shift per gene per batch, applied uniformly to every cell in
   that batch, even though real batch effects are well documented to hit different cell
   types/states by different amounts.

Both point at the same place: the rare-cell coverage/homogeneity/F1 table below is the
sharpest test of whether either limitation actually shows up in these three datasets --
watch that table first, not just the headline modularity/purity numbers.

## Setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install -q scarches faiss-gpu-cu12 scib-metrics
!pip install git+https://github.com/dpeerlab/SEACells.git --quiet --no-deps
!pip install numpy scipy --upgrade -q
!pip install -q palantir harmonypy
!pip install -q "numpy==1.26.4" "scipy==1.13.1"
!pip install --upgrade --force-reinstall numpy cupy-cuda12x
!pip install "numpy<2.3"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 17.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 65.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.5/187.5 kB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 216.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 189.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 215.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 221.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 134.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.2/711.2 kB 86.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 162.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/137.4 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 848.6/848.6 kB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 55.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.9/155.9 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 84.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.6/319.6 kB 36.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 79.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 230.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 72.8 MB/s eta 0:00:00
  Building wheel for docrep (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
ibis-framework 9.5.0 requires toolz<1,>=0.11, but you have toolz 1.1.0 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
  Preparing metadata (setup.py) ... done
  Building wheel for SEACells (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 239.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 105.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires palantir, which is not installed.
seacells 0.3.3 requires pyranges, which is not installed.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 74.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.4/172.4 kB 25.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 189.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 95.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
faiss-gpu-cu12 1.14.1.post1 requires numpy<3,>=2, but you have numpy 1.26.4 which is incompatible.
fast-array-utils 1.5 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
scanpy 1.12.3 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires numpy>=2.1, but you have numpy 1.26.4 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
zarr 3.2.1 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Collecting numpy
  Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting cupy-cuda12x
  Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (2.8 kB)
Collecting cuda-pathfinder==1.*,>=1.3.4 (from cupy-cuda12x)
  Downloading cuda_pathfinder-1.6.0-py3-none-any.whl.metadata (1.9 kB)
Using cached numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Downloading cupy_cuda12x-14.1.1-cp312-cp312-manylinux2014_x86_64.whl (133.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 MB 18.9 MB/s eta 0:00:00
Downloading cuda_pathfinder-1.6.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 8.0 MB/s eta 0:00:00
Installing collected packages: numpy, cuda-pathfinder, cupy-cuda12x
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: cuda-pathfinder
    Found existing installation: cuda-pathfinder 1.5.6
    Uninstalling cuda-pathfinder-1.5.6:
      Successfully uninstalled cuda-pathfinder-1.5.6
  Attempting uninstall: cupy-cuda12x
    Found existing installation: cupy-cuda12x 14.0.1
    Uninstalling cupy-cuda12x-14.0.1:
      Successfully uninstalled cupy-cuda12x-14.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.5.1 which is incompatible.
numba 0.66.0 requires numpy<2.5,>=1.22, but you have numpy 2.5.1 which is incompatible.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed cuda-pathfinder-1.6.0 cupy-cuda12x-14.1.1 numpy-2.5.1

Collecting numpy<2.3
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.5 MB/s eta 0:00:00
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 217.6 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.1
    Uninstalling numpy-2.5.1:
      Successfully uninstalled numpy-2.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seacells 0.3.3 requires pyranges, which is not installed.
anndata 0.13.2 requires scipy!=1.17.0,>=1.14, but you have scipy 1.13.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
pytensor 2.38.3 requires numba<=0.65.1,>=0.58, but you have numba 0.66.0 which is incompatible.
tsfresh 0.21.2 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.66.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed numpy-2.2.6

In [ ]:
# IMPORTANT: restart the runtime after this cell before running the cells below --
# numpy/scipy/anndata are C-extension linked, an in-process upgrade alone won't
# reliably take effect on already-imported modules.
#
# Note: scarches/scvi-tools/harmonypy are installed above even though THIS notebook
# only runs ComBat (which is plain scanpy, sc.pp.combat, no extra package) --
# run_all_baselines_for_dataset always calls get_stage1_latent() first to build `ad`
# from the existing scPoli Stage-1 checkpoint, and that path needs scarches/scvi
# importable regardless of which correction method is requested afterward.

In [ ]:
# Ground truth for "did the install cell above actually work" -- pip's own log is
# noisy (resolver backtracking prints "Getting requirements to build wheel" errors
# for discarded candidate versions even on a fully successful install), so eyeballing
# it is unreliable. Actually importing every package we just installed is the real
# test.
_checks = {
    'numpy': 'numpy', 'scipy': 'scipy', 'anndata': 'anndata', 'scanpy': 'scanpy',
    'scarches': 'scarches', 'scvi-tools': 'scvi', 'seacells': 'SEACells',
    'palantir': 'palantir', 'scib-metrics': 'scib_metrics', 'leidenalg': 'leidenalg',
    'python-igraph': 'igraph', 'umap-learn': 'umap', 'harmonypy': 'harmonypy',
    'faiss-cpu': 'faiss',
}
_failed = []
for pkg_name, import_name in _checks.items():
    try:
        mod = __import__(import_name)
        ver = getattr(mod, '__version__', '?')
        print(f"  OK   {pkg_name:16s} (import {import_name}, version {ver})")
    except Exception as e:
        _failed.append(pkg_name)
        print(f"  FAIL {pkg_name:16s} (import {import_name}): {type(e).__name__}: {e}")

if _failed:
    print(f"\n{len(_failed)} package(s) failed to import: {_failed} -- re-run that "
          f"package's specific pip install line above and check its full error "
          f"output before proceeding.")
else:
    print(f"\nAll {len(_checks)} packages import cleanly -- safe to continue.")

  OK   numpy            (import numpy, version 2.2.6)
  OK   scipy            (import scipy, version 1.13.1)

/tmp/ipykernel_2525/3189155525.py:17: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  ver = getattr(mod, '__version__', '?')
/tmp/ipykernel_2525/3189155525.py:17: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  ver = getattr(mod, '__version__', '?')

  OK   anndata          (import anndata, version 0.13.2)
  OK   scanpy           (import scanpy, version 1.12.3)

WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).

  FAIL scarches         (import scarches): ImportError: cannot import name 'read' from 'anndata' (/usr/local/lib/python3.12/dist-packages/anndata/__init__.py)
  OK   scvi-tools       (import scvi, version 1.5.0.post1)
  OK   seacells         (import SEACells, version 0.3.3)
  OK   palantir         (import palantir, version 1.4.5)
  OK   scib-metrics     (import scib_metrics, version 0.6.0)
  OK   leidenalg        (import leidenalg, version 0.12.0)
  OK   python-igraph    (import igraph, version 1.0.0)
  OK   umap-learn       (import umap, version 0.5.12)
  OK   harmonypy        (import harmonypy, version 2.0.0)
  OK   faiss-cpu        (import faiss, version 1.14.1)

1 package(s) failed to import: ['scarches'] -- re-run that package's specific pip install line above and check its full error output before proceeding.

In [1]:
%run /content/drive/MyDrive/codes/interpretable-prototype/notebooks/nb_setup.py

nb_setup done. Available: get_trainer, run_mc_task, fig_*, LAMBDA_PROTO_UMAP, LAMBDA_PROTO_UMAP_PRECON, LAMBDA_PARAM_UMAP, LAMBDA_RECON_ONLY, train_sure, eval_sure_task1/2/3
Configs: {'LAMBDA_PROTO_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'proto'}, 'LAMBDA_PARAM_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'embedding'}, 'LAMBDA_RECON_ONLY': {'lambda_umap': 0, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 1, 'lambda_proto_recon': 0.0}}

In [2]:
# Extra imports not already covered by nb_setup.py (which already pulls in
# run_mc_task, eval_seacell_task1/2/3, load_task1_multi, show_table, clean_run_names,
# rare_celltype_purity_table, TASK1_METRICS, TASK2_METRICS, extract_model_key via
# `from interpretable_ssl.evaluation.paper_figures import *` and
# `from interpretable_ssl.evaluation.metric_helpers.result_tables import *`).
from interpretable_ssl.datasets.dataset_configs import DATASETS
from interpretable_ssl.configs.paths import get_dataset_model_dir

print("extra imports ready")

extra imports ready

## Config

Same hyperparameters `train_scproto.ipynb` used to produce the existing Stage-1
checkpoints for these three datasets (`cvae_epochs=50`, `batch_size=1024`) -- must
match, or `load_pretrain_checkpoint()` looks in the wrong folder. `K` (n_SEACells /
target Leiden cluster count) defaults to each dataset's `num_prototypes` from
`DATASETS`, matching `results.tex`: *"All baselines are configured to produce the same
number of metacells K as scProto."*

In [3]:
RNA_SEQ_DATASETS = ['pancreas', 'lung', 'pbmc-immune']

SKIP_IF_EXISTS = True  # skip a baseline entirely (embedding + SEACells + Leiden) if its
                        # metrics.json already exists on disk -- re-running the dataset
                        # cell after a crash/interrupt never redoes already-saved work.

CORRECTION_METHODS = ['combat']  # this notebook: ComBat only (see intro cell)
METHOD_DISPLAY_NAMES = {
    'combat': 'ComBat',
}

RUN_SEACELLS = True  # both SEACells AND Leiden on top of ComBat -- reviewer nG29's Q3
                      # asked for the comparison itself, not one clusterer in isolation.
RUN_LEIDEN = True

## Helper functions

Shared with the Harmony notebook -- lives in
`interpretable_ssl/evaluation/batch_correct_baselines.py` (imported below), not
redefined here. ComBat support (`get_combat_corrected_pca`, and the `'combat'` branch
in `run_correction_method`) was added to that same module, so no separate helper file
exists for this notebook -- fixing a bug in the shared pipeline benefits both notebooks
at once, avoiding the exact duplication risk the Harmony notebook's own intro cell
describes from when it used to be split in two.

In [4]:
from interpretable_ssl.evaluation.batch_correct_baselines import run_all_baselines_for_dataset

print("baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)")

baseline helper functions ready (interpretable_ssl.evaluation.batch_correct_baselines)

## Run: Pancreas

In [5]:
pancreas_results = run_all_baselines_for_dataset(
    'pancreas', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading pancreas data

WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).
WARNING:root:In order to use sagenet models, please install pytorch geometric (see https://pytorch-geometric.readthedocs.io) and
 captum (see https://github.com/pytorch/captum).
WARNING:root:mvTCR is not installed. To use mvTCR models, please install it first using "pip install mvtcr"
WARNING:root:multigrate is not installed. To use multigrate models, please install it first using "pip install multigrate".

✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [9]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain/pretrain_ds-pancreas_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/16 [00:00<?, ?it/s]

=== [pancreas] batch-correction method: combat ===
[pancreas] combat_d8: cached embedding to /content/drive/MyDrive/models/pancreas/_cache_X_combat_d8_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=16382  k=220  n_eigs=10  nnz=1141676  nnz/row=69.7
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 219/219 [00:00<00:00, 9570.45archetype/s]

[waypoint init] selected 220 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.35901
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 12 iterations.

100%|██████████| 220/220 [00:00<00:00, 743.71it/s]

saving to:  /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 2 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8 ...
[seacell] unused protos: 0/220 (0.00%)
[seacell] mean cell-type purity: 0.9113  (size-weighted: 0.9416 ± 0.1164)
[seacell] mean batch entropy: 0.9686  (size-weighted: 0.9925 ± 0.4622)
[seacell] coverage: 0.8571
[seacell] modularity: 0.6218
[seacell] per-batch modularity: mean=0.5790, std=0.0288
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.3272 | saved to /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8
[pancreas] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl (nnz=1171528) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pancreas/seacell_X_combat_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.24306335995985362 +/- 0.04109949338544633 (was 0.5789960749693458), K_target=220
Loading SEACell from /content/drive/MyDrive/models/pancreas/seacell_X_combat_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_5ae9787e.h5ad
[seacell task2] coverage: 0.8571
[seacell task2] scgraph_corr_avg: 0.8242
[seacell task2] scgraph_corr_std: 0.0570
  [leiden oversegment] resolution=1.0000 -> 14 clusters (need >= 220)
  [leiden oversegment] resolution=2.0000 -> 25 clusters (need >= 220)
  [leiden oversegment] resolution=4.0000 -> 41 clusters (need >= 220)
  [leiden oversegment] resolution=8.0000 -> 74 clusters (need >= 220)
  [leiden oversegment] resolution=16.0000 -> 131 clusters (need >= 220)
  [leiden oversegment] resolution=32.0000 -> 243 clusters (need >= 220)
  [leiden merge] -> 240 clusters (target 220)
  [leiden merge] -> 230 clusters (target 220)
  [leiden merge] -> 225 clusters (target 220)
  [leiden merge] -> 224 clusters (target 220)
  [leiden merge] -> 223 clusters (target 220)
  [leiden merge] -> 222 clusters (target 220)
  [leiden merge] -> 221 clusters (target 220)
  [leiden merge] -> 220 clusters (target 220)
[leiden merge-down] final: 220 clusters (target 220)
[leiden_X_combat_d8_K220] unused protos: 0/220 (0.00%)
[leiden_X_combat_d8_K220] mean cell-type purity: 0.9439  (size-weighted: 0.9377 ± 0.1186)
[leiden_X_combat_d8_K220] mean batch entropy: 0.9420  (size-weighted: 0.9439 ± 0.4802)
[leiden_X_combat_d8_K220] coverage: 0.7857
[leiden_X_combat_d8_K220] modularity: 0.3383
[leiden_X_combat_d8_K220] per-batch modularity: mean=0.2933, std=0.0711
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.2569 | saved to /content/drive/MyDrive/models/pancreas/leiden_X_combat_d8_K220/aff_dc_compactness.csv
[leiden_X_combat_d8_K220] saved metrics to /content/drive/MyDrive/models/pancreas/leiden_X_combat_d8_K220
[/content/drive/MyDrive/models/pancreas/leiden_X_combat_d8_K220] modularity recomputed against canonical graph: mean_modularity_batch=0.2933051547592376 +/- 0.07106245380628536 (was 0.2933051547592376), K_target=220

100%|██████████| 220/220 [00:00<00:00, 927.11it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_combat_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_combat_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pancreas/leiden_X_combat_d8_K220
[pancreas] leiden-on-X_combat_d8 saved to /content/drive/MyDrive/models/pancreas/leiden_X_combat_d8_K220

[pancreas] rare-type kNN purity by method: {'combat': 0.311, 'raw_pca': 0.499}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] Raw PCA (uncorrected) (d=50): 0.385 +/- 0.164 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] ComBat (d=8): 0.344 +/- 0.155 (n=8 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] scProto (d=8): 0.454 +/- 0.184 (n=8 batches)
[pancreas] affinity purity saved to /content/drive/MyDrive/models/pancreas/rare_affinity_purity_pancreas.json

## Run: Lung

In [6]:
lung_results = run_all_baselines_for_dataset(
    'lung', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading lung data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading lung
loading lung data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [16]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=5.255/24.467/119.300, effk_med=63.8, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/lung/pretrain/pretrain_ds-lung_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'lung', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'batch'}
📊 EdgeDataset: 2447924 edges
   Weight range: [0.0137, 0.9491]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2447924 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//lung/proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/32 [00:00<?, ?it/s]

=== [lung] batch-correction method: combat ===
[lung] combat_d8: cached embedding to /content/drive/MyDrive/models/lung/_cache_X_combat_d8_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=32472  k=300  n_eigs=10  nnz=2292156  nnz/row=70.6
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 5132.21archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.52831
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 14 iterations.

100%|██████████| 300/300 [00:00<00:00, 344.34it/s]

saving to:  /content/drive/MyDrive/models/lung/seacell_X_combat_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 1 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_combat_d8 ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8653  (size-weighted: 0.8370 ± 0.1819)
[seacell] mean batch entropy: 0.7638  (size-weighted: 0.9295 ± 0.5373)
[seacell] coverage: 0.9412
[seacell] modularity: 0.6589
[seacell] per-batch modularity: mean=0.6154, std=0.0260
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=10.6692 | saved to /content/drive/MyDrive/models/lung/seacell_X_combat_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/lung/seacell_X_combat_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/lung/seacell_X_combat_d8
[lung] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl (nnz=2480396) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/lung/seacell_X_combat_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.29439008315243037 +/- 0.04065935036135878 (was 0.6153924007027388), K_target=300
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_combat_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

Deleted: tmp_2f66d969.h5ad
[seacell task2] coverage: 0.9412
[seacell task2] scgraph_corr_avg: 0.8915
[seacell task2] scgraph_corr_std: 0.0700
  [leiden oversegment] resolution=1.0000 -> 25 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 35 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 48 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 80 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 140 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 265 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 520 clusters (need >= 300)
  [leiden merge] -> 510 clusters (target 300)
  [leiden merge] -> 500 clusters (target 300)
  [leiden merge] -> 490 clusters (target 300)
  [leiden merge] -> 480 clusters (target 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_combat_d8_K300] unused protos: 0/300 (0.00%)
[leiden_X_combat_d8_K300] mean cell-type purity: 0.7746  (size-weighted: 0.8173 ± 0.1904)
[leiden_X_combat_d8_K300] mean batch entropy: 0.9631  (size-weighted: 1.0764 ± 0.5636)
[leiden_X_combat_d8_K300] coverage: 1.0000
[leiden_X_combat_d8_K300] modularity: 0.5634
[leiden_X_combat_d8_K300] per-batch modularity: mean=0.4532, std=0.0869
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=4.8220 | saved to /content/drive/MyDrive/models/lung/leiden_X_combat_d8_K300/aff_dc_compactness.csv
[leiden_X_combat_d8_K300] saved metrics to /content/drive/MyDrive/models/lung/leiden_X_combat_d8_K300
[/content/drive/MyDrive/models/lung/leiden_X_combat_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.4532090327346041 +/- 0.08688080012576374 (was 0.4532090327346041), K_target=300

100%|██████████| 300/300 [00:00<00:00, 456.19it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_combat_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_combat_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/lung/leiden_X_combat_d8_K300
[lung] leiden-on-X_combat_d8 saved to /content/drive/MyDrive/models/lung/leiden_X_combat_d8_K300

[lung] rare-type kNN purity by method: {'combat': 0.635, 'raw_pca': 0.912}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] Raw PCA (uncorrected) (d=50): 0.559 +/- 0.194 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] ComBat (d=8): 0.399 +/- 0.171 (n=15 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] scProto (d=8): 0.586 +/- 0.208 (n=15 batches)
[lung] affinity purity saved to /content/drive/MyDrive/models/lung/rare_affinity_purity_lung.json

## Run: PBMC (Immune)

In [7]:
immune_results = run_all_baselines_for_dataset(
    'pbmc-immune', correction_methods=CORRECTION_METHODS, skip_if_exists=SKIP_IF_EXISTS,
    run_seacells=RUN_SEACELLS, run_leiden=RUN_LEIDEN,
)

loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
dataset is None, loading pbmc-immune
loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
Embedding dictionary:
 	Num conditions: [5]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

📊 Affinity: wdeg[min/mean/max]=1.667/25.923/299.545, effk_med=62.9, mutual=100.00%
adam
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pbmc-immune/pretrain/pretrain_cvae_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pbmc-immune', 'cvae_epochs': 50, 'batch_size': 1024, 'latent_dims': 8, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'condition_key': 'study'}
📊 EdgeDataset: 2590828 edges
   Weight range: [0.0050, 0.9224]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2590828 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pbmc-immune/proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/33 [00:00<?, ?it/s]

=== [pbmc-immune] batch-correction method: combat ===
[pbmc-immune] combat_d8: cached embedding to /content/drive/MyDrive/models/pbmc-immune/_cache_X_combat_d8_emb.npy
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[waypoint init] N=33506  k=300  n_eigs=10  nnz=2386114  nnz/row=71.2
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 4790.47archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected → use_gpu=True, use_sparse=False
[SEACells backend] installed SEACells has no `use_sparse` param — dropping it
Welcome to SEACells GPU!

Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 0.53888
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 13 iterations.

100%|██████████| 300/300 [00:00<00:00, 351.38it/s]

saving to:  /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8
  delta kept: X=no (deduped), 1 layer(s), 0 varm, 2 obsm, 2 obsp, obs cols ['SEACell']
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8 ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8752  (size-weighted: 0.8581 ± 0.1488)
[seacell] mean batch entropy: 0.3451  (size-weighted: 0.3996 ± 0.3528)
[seacell] coverage: 1.0000
[seacell] modularity: 0.6158
[seacell] per-batch modularity: mean=0.5898, std=0.0181
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=1.3917 | saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8
SEACell UMAP data saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8
[pbmc-immune] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl (nnz=2624382) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8] modularity recomputed against canonical graph: mean_modularity_batch=0.2775854178726768 +/- 0.03633351060636073 (was 0.5898313678554093), K_target=300
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_combat_d8 ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_8a7c2abc.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.8532
[seacell task2] scgraph_corr_std: 0.0595
  [leiden oversegment] resolution=1.0000 -> 22 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 29 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 44 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 82 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 152 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 297 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 585 clusters (need >= 300)
  [leiden merge] -> 580 clusters (target 300)
  [leiden merge] -> 570 clusters (target 300)
  [leiden merge] -> 560 clusters (target 300)
  [leiden merge] -> 550 clusters (target 300)
  [leiden merge] -> 540 clusters (target 300)
  [leiden merge] -> 530 clusters (target 300)
  [leiden merge] -> 520 clusters (target 300)
  [leiden merge] -> 510 clusters (target 300)
  [leiden merge] -> 500 clusters (target 300)
  [leiden merge] -> 490 clusters (target 300)
  [leiden merge] -> 480 clusters (target 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_combat_d8_K300] unused protos: 0/300 (0.00%)
[leiden_X_combat_d8_K300] mean cell-type purity: 0.8248  (size-weighted: 0.8338 ± 0.1540)
[leiden_X_combat_d8_K300] mean batch entropy: 0.5396  (size-weighted: 0.4620 ± 0.4144)
[leiden_X_combat_d8_K300] coverage: 1.0000
[leiden_X_combat_d8_K300] modularity: 0.5671
[leiden_X_combat_d8_K300] per-batch modularity: mean=0.5100, std=0.1761
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.4453 | saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_combat_d8_K300/aff_dc_compactness.csv
[leiden_X_combat_d8_K300] saved metrics to /content/drive/MyDrive/models/pbmc-immune/leiden_X_combat_d8_K300
[/content/drive/MyDrive/models/pbmc-immune/leiden_X_combat_d8_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.5100419601979406 +/- 0.1761293070418207 (was 0.5100419601979406), K_target=300

100%|██████████| 300/300 [00:00<00:00, 484.66it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_combat_d8: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_combat_d8] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_combat_d8_K300
[pbmc-immune] leiden-on-X_combat_d8 saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_combat_d8_K300

[pbmc-immune] rare-type kNN purity by method: {'combat': 0.692, 'raw_pca': 0.776}
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] Raw PCA (uncorrected) (d=50): 0.827 +/- 0.050 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] ComBat (d=8): 0.806 +/- 0.105 (n=5 batches)
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] scProto (d=8): 0.849 +/- 0.085 (n=5 batches)
[pbmc-immune] affinity purity saved to /content/drive/MyDrive/models/pbmc-immune/rare_affinity_purity_pbmc-immune.json

## Results comparison

Pulls in **every** existing run under `MODEL_DIR/{ds}/*` (scProto, SEACells(PCA), plus
whatever's already been computed by the Harmony notebook, alongside the new ComBat
baselines here) -- `load_task1_multi` / `rare_celltype_purity_table` just scan folders +
`metrics.json` / `umap_cells.csv`, they don't need to know which notebook produced them.

Harmony is included in the comparison tables below (via `HARMONY_DIM`) purely as a
READ of whatever's already on disk from the other notebook -- it is never (re)computed
here. If the Harmony notebook hasn't been run yet, those rows are simply absent, not an
error.

**Reminder:** the modularity column is scored against the arbf-on-PCA graph that only
scProto is trained to match -- treat it as a plausibility check, not the primary
evidence. Purity, batch entropy, and especially the rare-cell coverage/homogeneity
table (further down) are the fair, post-hoc comparison -- see the intro cell's note on
ComBat's two structural limitations for what to look for there specifically.

In [8]:
dataset_display_names = {'pancreas': 'Pancreas', 'lung': 'Lung', 'pbmc-immune': 'Immune'}

# scProto runs verified against the paper's published numbers via generate_tables.ipynb
# (the actual notebook used to build the paper's tables) -- bit-identical to the
# published numbers on multiple metrics simultaneously per dataset. Same three
# canonical run names the Harmony notebook uses (this is the SAME scProto model,
# just compared against a different baseline here).
SCPROTO_CANONICAL_RUNS = {
    'proto_umap_ds-panc_NP220_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
    'proto_umap_ds-lung_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
    'proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_cvae_e50_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31',
}

SCPROTO_KEY = extract_model_key(next(iter(SCPROTO_CANONICAL_RUNS)))
assert all(extract_model_key(r) == SCPROTO_KEY for r in SCPROTO_CANONICAL_RUNS), (
    "SCPROTO_CANONICAL_RUNS entries no longer normalize to one shared key -- "
    "extract_model_key's stripping patterns changed; update the scProto matching logic."
)

MODEL_KEYWORDS = {SCPROTO_KEY: 'scProto'}
MODEL_KEYWORDS['seacell'] = 'SEACells (PCA)'

# MATCHED_DIM must match scProto's actual latent_dims (currently 8 for all three
# datasets, per the Stage-1 pretrain params) -- a literal string match, not computed
# dynamically. ComBat is now ALSO dimension-matched (PCA'd to this dim instead of the
# old default 50) for the same reason Harmony already was: comparing scProto's 8-dim
# latent against a 50-dim-PCA-based baseline isn't apples-to-apples -- see
# batch_correct_baselines.DIM_MATCHED_METHODS / run_correction_method's
# matched_n_comps docstring for the full rationale. Old plain 'seacell_X_combat' /
# 'leiden_X_combat_K*' folders (pre-dimension-matching) are now orphaned leftovers,
# not read by this cell anymore.
MATCHED_DIM = 8
for _method in CORRECTION_METHODS:
    _disp = METHOD_DISPLAY_NAMES[_method]
    MODEL_KEYWORDS[f'seacell_X_{_method}_d{MATCHED_DIM}'] = f'SEACells ({_disp})'
    MODEL_KEYWORDS[f'leiden_X_{_method}_d{MATCHED_DIM}']  = f'Leiden ({_disp})'

# Harmony -- READ ONLY, pulled in for side-by-side comparison if the other notebook has
# already produced it (see 'Results comparison' markdown above).
MODEL_KEYWORDS[f'seacell_X_harmony_d{MATCHED_DIM}'] = 'SEACells (Harmony)'
MODEL_KEYWORDS[f'leiden_X_harmony_d{MATCHED_DIM}']  = 'Leiden (Harmony)'

In [9]:


def _keep_and_rename_runs(df, model_keywords=MODEL_KEYWORDS):
    # Filter load_task1_multi's output down to just the runs in model_keywords, and
    # collapse each method's per-dataset '_K{n}' folder-name suffix into ONE shared
    # display row per method. Identical logic to the Harmony notebook's version of this
    # helper -- kept as a local copy rather than imported, since these notebooks are
    # meant to run independently in parallel sessions.
    runs = df.index.get_level_values('run')
    datasets = df.index.get_level_values('dataset')
    stripped = runs.str.replace(r'_K\d+$', '', regex=True)
    keep_mask = stripped.isin(model_keywords)

    kept_runs, kept_datasets = runs[keep_mask], datasets[keep_mask]
    kept_display = stripped[keep_mask].map(model_keywords)

    out = df[keep_mask].copy()
    out.index = pd.MultiIndex.from_arrays([kept_datasets, kept_display], names=['dataset', 'run'])

    dupe_mask = out.index.duplicated(keep='first')
    if dupe_mask.any():
        stale = list(zip(kept_datasets[dupe_mask], kept_runs[dupe_mask], kept_display[dupe_mask]))
        print(f"WARNING: dropped {dupe_mask.sum()} duplicate (dataset, method) row(s) -- "
              f"likely a stale run at an old K value still on disk. "
              f"(dataset, on-disk folder, display name): {stale}")
        out = out[~dupe_mask]
    return out

# --- Table 1 (community structure / batch integration): modularity, batch entropy, purity ---
df_task1 = load_task1_multi(RNA_SEQ_DATASETS, metrics=TASK1_METRICS)
df_task1 = _keep_and_rename_runs(df_task1)
show_table(df_task1, metrics=TASK1_METRICS, dataset_display_names=dataset_display_names)

In [10]:
# --- Table 2 (metacell representation quality): coverage, scGraph (DGE consistency
# turned off, see intro) ---
df_task2 = load_task1_multi(RNA_SEQ_DATASETS, metrics=TASK2_METRICS)
df_task2 = _keep_and_rename_runs(df_task2)
show_table(df_task2, metrics=TASK2_METRICS, dataset_display_names=dataset_display_names)

In [11]:
# --- Rare-cell-type table (the key hypothesis test for BOTH of ComBat's structural
# limitations discussed in the intro cell): coverage + homogeneity + F1, same
# per-batch-rare-cell definition results.tex uses for Table 2 (tab:rare_cells).
#
# batch_rare_f1_macro_mean -- per-rare-type F1 (precision = purity of that type's
# dedicated metacell(s), recall = fraction of that type's cells that landed in one),
# macro-averaged across rare types, then mean+-std across batches.
#
# batch_rare_cross_batch_homog_mean -- same formula/denominator as homogeneity, but the
# numerator only counts same-label metacell-mates from a DIFFERENT batch -- directly
# tests whether rare types are actually grouped WITH their cross-batch counterparts,
# not just given their own same-batch-only cluster.
df_rare = rare_celltype_purity_table(RNA_SEQ_DATASETS, model_keywords=MODEL_KEYWORDS, verbose=True)

_dupe_mask = df_rare.index.duplicated(keep='first')
if _dupe_mask.any():
    print(f"WARNING: dropped {_dupe_mask.sum()} duplicate row(s) from df_rare: "
          f"{df_rare.index[_dupe_mask].tolist()}")
    df_rare = df_rare[~_dupe_mask]

show_table(
    df_rare,
    metrics=[
        'batch_rare_coverage_mean', 'batch_rare_recall_macro_mean',
        'batch_rare_precision_macro_mean', 'batch_rare_homogeneity_mean',
        'batch_rare_cross_batch_homog_mean', 'batch_rare_f1_macro_mean',
    ],
    dataset_display_names=dataset_display_names,
)

  [scProto|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] resolving run dir ...
  [SEACells (ComBat)|pancreas] resolving run dir ...
  [SEACells (PCA)|pancreas] run dir resolved (0.0s)
  [Leiden (ComBat)|pancreas] resolving run dir ...
  [SEACells (Harmony)|pancreas] resolving run dir ...
  [Leiden (Harmony)|pancreas] resolving run dir ...
  [scProto|lung] resolving run dir ...
  [SEACells (PCA)|pancreas] reading umap_cells.csv ...
  [SEACells (PCA)|lung] resolving run dir ...
  [SEACells (PCA)|lung] run dir resolved (0.0s)
  [SEACells (PCA)|lung] reading umap_cells.csv ...
  [SEACells (PCA)|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)
  [SEACells (PCA)|pancreas] reading umap_protos.csv ...
  [SEACells (PCA)|pancreas] umap_protos.csv loaded (0.0s)
  [SEACells (PCA)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (PCA)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (PCA)|lung] umap_cells.csv loaded (32472 rows, 0.0s)
  [SEACells (PCA)|lung] reading umap_protos.csv ...
  [SEACells (PCA)|pancreas] label fractions done (0.0s)  [SEACells (PCA)|lung] umap_protos.csv loaded (0.0s)

  [SEACells (PCA)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (PCA)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (PCA)|lung] label fractions done (0.0s)
  [scProto|lung] run dir resolved (0.0s)
  [scProto|lung] reading umap_cells.csv ...
  [SEACells (PCA)|pancreas] done
  [SEACells (ComBat)|lung] resolving run dir ...
  [SEACells (PCA)] ds=pancreas: coverage=0.43±0.27  repr macro=0.39±0.20  micro=0.42±0.20  homogeneity=0.42±0.20  cross_batch_homog=0.22±0.10  purity=0.82±0.13  recall=0.41±0.24  precision=0.54±0.22  F1=0.37±0.25
  [SEACells (ComBat)|lung] run dir resolved (0.0s)
  [SEACells (ComBat)|lung] reading umap_cells.csv ...
  [scProto|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [scProto|lung] reading umap_protos.csv ...
  [SEACells (Harmony)|pancreas] run dir resolved (0.1s)
  [SEACells (ComBat)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [SEACells (Harmony)|pancreas] reading umap_cells.csv ...
  [SEACells (ComBat)|lung] reading umap_protos.csv ...
  [Leiden (ComBat)|pancreas] run dir resolved (0.1s)
  [scProto|lung] umap_protos.csv loaded (0.0s)
  [Leiden (Harmony)|pancreas] run dir resolved (0.1s)  [Leiden (ComBat)|pancreas] reading umap_cells.csv ...

  [scProto|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] reading umap_cells.csv ...
  [SEACells (ComBat)|lung] umap_protos.csv loaded (0.0s)
  [SEACells (ComBat)|pancreas] run dir resolved (0.1s)
  [scProto|pancreas] run dir resolved (0.1s)
  [SEACells (ComBat)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (ComBat)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [scProto|pancreas] reading umap_cells.csv ...  [SEACells (ComBat)|pancreas] reading umap_cells.csv ...

  [SEACells (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)
  [SEACells (Harmony)|pancreas] reading umap_protos.csv ...
  [Leiden (Harmony)|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)  [Leiden (ComBat)|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)

  [SEACells (PCA)|lung] done
  [Leiden (Harmony)|pancreas] reading umap_protos.csv ...
  [Leiden (ComBat)|pancreas] reading umap_protos.csv ...
  [SEACells (ComBat)|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)
  [Leiden (ComBat)|lung] resolving run dir ...
  [scProto|lung] label fractions done (0.0s)
  [SEACells (PCA)] ds=lung: coverage=0.52±0.23  repr macro=0.43±0.19  micro=0.47±0.24  homogeneity=0.47±0.24  cross_batch_homog=0.39±0.20  purity=0.90±0.03  recall=0.41±0.23  precision=0.90±0.04  F1=0.42±0.22
  [SEACells (Harmony)|pancreas] umap_protos.csv loaded (0.0s)
  [SEACells (ComBat)|pancreas] reading umap_protos.csv ...
  [scProto|pancreas] umap_cells.csv loaded (16382 rows, 0.0s)
  [Leiden (ComBat)|lung] run dir resolved (0.0s)  [Leiden (Harmony)|pancreas] umap_protos.csv loaded (0.0s)
  [SEACells (ComBat)|lung] label fractions done (0.0s)

  [SEACells (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [scProto|pancreas] reading umap_protos.csv ...
  [Leiden (ComBat)|lung] reading umap_cells.csv ...
  [SEACells (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (Harmony)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (ComBat)|pancreas] umap_protos.csv loaded (0.0s)
  [Leiden (ComBat)|pancreas] umap_protos.csv loaded (0.0s)
  [scProto|pancreas] umap_protos.csv loaded (0.0s)
  [scProto|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']  [Leiden (ComBat)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (ComBat)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...

  [SEACells (ComBat)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [scProto|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (ComBat)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (Harmony)|pancreas] label fractions done (0.0s)
  [SEACells (Harmony)|pancreas] label fractions done (0.0s)
  [SEACells (ComBat)|pancreas] label fractions done (0.0s)
  [Leiden (ComBat)|pancreas] label fractions done (0.0s)
  [Leiden (ComBat)|lung] umap_cells.csv loaded (32472 rows, 0.0s)
  [scProto|pancreas] label fractions done (0.0s)
  [Leiden (ComBat)|lung] reading umap_protos.csv ...
  [Leiden (ComBat)|lung] umap_protos.csv loaded (0.0s)
  [Leiden (ComBat)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [Leiden (ComBat)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (ComBat)|lung] done
  [SEACells (Harmony)|lung] resolving run dir ...  [SEACells (Harmony)|pancreas] done
  [SEACells (ComBat)] ds=lung: coverage=0.46±0.31  repr macro=0.34±0.19  micro=0.40±0.25  homogeneity=0.40±0.25  cross_batch_homog=0.30±0.21  purity=0.82±0.05  recall=0.31±0.21  precision=0.77±0.11  F1=0.33±0.21

  [Leiden (ComBat)|pancreas] done
  [Leiden (ComBat)|lung] label fractions done (0.2s)  [Leiden (Harmony)|lung] resolving run dir ...
  [Leiden (Harmony)|pancreas] done
  [SEACells (Harmony)] ds=pancreas: coverage=0.56±0.28  repr macro=0.27±0.12  micro=0.29±0.12  homogeneity=0.29±0.12  cross_batch_homog=0.23±0.10  purity=0.56±0.16  recall=0.35±0.14  precision=0.36±0.18  F1=0.32±0.16

  [SEACells (Harmony)|lung] run dir resolved (0.0s)
  [scProto|pbmc-immune] resolving run dir ...
  [SEACells (PCA)|pbmc-immune] resolving run dir ...
  [SEACells (Harmony)|lung] reading umap_cells.csv ...
  [Leiden (ComBat)] ds=pancreas: coverage=0.33±0.27  repr macro=0.21±0.11  micro=0.23±0.10  homogeneity=0.23±0.10  cross_batch_homog=0.17±0.06  purity=0.54±0.20  recall=0.20±0.10  precision=0.25±0.25  F1=0.15±0.07
  [Leiden (Harmony)] ds=pancreas: coverage=0.40±0.24  repr macro=0.21±0.09  micro=0.22±0.09  homogeneity=0.22±0.09  cross_batch_homog=0.19±0.08  purity=0.52±0.20  recall=0.28±0.19  precision=0.24±0.18  F1=0.22±0.17
  [SEACells (PCA)|pbmc-immune] run dir resolved (0.0s)
  [Leiden (Harmony)|lung] run dir resolved (0.0s)
  [scProto|lung] done
  [SEACells (PCA)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (Harmony)|lung] reading umap_cells.csv ...
  [SEACells (ComBat)|pbmc-immune] resolving run dir ...
  [scProto] ds=lung: coverage=0.79±0.18  repr macro=0.56±0.20  micro=0.58±0.22  homogeneity=0.58±0.22  cross_batch_homog=0.51±0.20  purity=0.85±0.04  recall=0.60±0.23  precision=0.70±0.14  F1=0.60±0.18
  [SEACells (ComBat)|pancreas] done
  [Leiden (ComBat)|pbmc-immune] resolving run dir ...  [SEACells (ComBat)] ds=pancreas: coverage=0.56±0.28  repr macro=0.28±0.10  micro=0.29±0.08  homogeneity=0.29±0.08  cross_batch_homog=0.21±0.05  purity=0.59±0.18  recall=0.45±0.20  precision=0.38±0.20  F1=0.35±0.21

  [SEACells (PCA)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.0s)
  [scProto|pancreas] done  [SEACells (PCA)|pbmc-immune] reading umap_protos.csv ...

  [SEACells (Harmony)|pbmc-immune] resolving run dir ...
  [scProto] ds=pancreas: coverage=0.64±0.24  repr macro=0.53±0.17  micro=0.56±0.16  homogeneity=0.56±0.16  cross_batch_homog=0.32±0.18  purity=0.88±0.08  recall=0.54±0.20  precision=0.77±0.13  F1=0.54±0.21
  [SEACells (Harmony)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [Leiden (Harmony)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [SEACells (Harmony)|lung] reading umap_protos.csv ...
  [Leiden (Harmony)|lung] reading umap_protos.csv ...
  [SEACells (PCA)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [Leiden (Harmony)|lung] umap_protos.csv loaded (0.0s)
  [SEACells (PCA)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']  [Leiden (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']

  [SEACells (Harmony)|lung] umap_protos.csv loaded (0.0s)
  [SEACells (PCA)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [Leiden (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (Harmony)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (Harmony)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (PCA)|pbmc-immune] label fractions done (0.0s)
  [scProto|pbmc-immune] run dir resolved (0.1s)
  [scProto|pbmc-immune] reading umap_cells.csv ...
  [Leiden (Harmony)|lung] label fractions done (0.1s)
  [SEACells (Harmony)|lung] label fractions done (0.0s)
  [SEACells (ComBat)|pbmc-immune] run dir resolved (0.1s)
  [SEACells (ComBat)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (ComBat)|lung] done
  [Leiden (Harmony)|pbmc-immune] resolving run dir ...
  [Leiden (ComBat)] ds=lung: coverage=0.53±0.26  repr macro=0.36±0.17  micro=0.40±0.21  homogeneity=0.40±0.21  cross_batch_homog=0.34±0.19  purity=0.75±0.09  recall=0.37±0.18  precision=0.74±0.06  F1=0.38±0.19
  [SEACells (Harmony)|pbmc-immune] run dir resolved (0.1s)
  [Leiden (ComBat)|pbmc-immune] run dir resolved (0.1s)
  [Leiden (Harmony)|pbmc-immune] run dir resolved (0.0s)
  [Leiden (ComBat)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (Harmony)|pbmc-immune] reading umap_cells.csv ...
  [scProto|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.0s)
  [scProto|pbmc-immune] reading umap_protos.csv ...
  [SEACells (ComBat)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.0s)  [scProto|pbmc-immune] umap_protos.csv loaded (0.0s)

  [scProto|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [scProto|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (ComBat)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)
  [Leiden (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (ComBat)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)
  [SEACells (Harmony)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)  [Leiden (ComBat)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (ComBat)|pbmc-immune] umap_protos.csv loaded (0.0s)

  [SEACells (ComBat)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (Harmony)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (Harmony)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [SEACells (ComBat)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (PCA)|pbmc-immune] done
  [Leiden (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (PCA)] ds=pbmc-immune: coverage=1.00±0.00  repr macro=0.84±0.08  micro=0.85±0.07  homogeneity=0.85±0.07  cross_batch_homog=0.12±0.17  purity=0.93±0.03  recall=0.87±0.09  precision=0.94±0.01  F1=0.88±0.08  [Leiden (ComBat)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [Leiden (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...

  [Leiden (ComBat)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [scProto|pbmc-immune] label fractions done (0.1s)  [Leiden (ComBat)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...

  [SEACells (Harmony)|pbmc-immune] umap_protos.csv loaded (0.1s)
  [SEACells (Harmony)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (Harmony)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (ComBat)|pbmc-immune] label fractions done (0.1s)
  [Leiden (Harmony)|lung] done
  [Leiden (Harmony)] ds=lung: coverage=0.43±0.26  repr macro=0.33±0.10  micro=0.34±0.08  homogeneity=0.34±0.08  cross_batch_homog=0.33±0.09  purity=0.69±0.09  recall=0.31±0.17  precision=0.49±0.13  F1=0.28±0.14
  [SEACells (Harmony)|lung] done
  [SEACells (Harmony)] ds=lung: coverage=0.54±0.19  repr macro=0.36±0.10  micro=0.40±0.12  homogeneity=0.40±0.12  cross_batch_homog=0.37±0.12  purity=0.73±0.07  recall=0.38±0.17  precision=0.62±0.11  F1=0.36±0.14
  [Leiden (Harmony)|pbmc-immune] label fractions done (0.1s)
  [Leiden (ComBat)|pbmc-immune] label fractions done (0.1s)
  [SEACells (Harmony)|pbmc-immune] label fractions done (0.0s)
  [scProto|pbmc-immune] done
  [scProto] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.81±0.11  micro=0.83±0.10  homogeneity=0.83±0.10  cross_batch_homog=0.35±0.20  purity=0.92±0.08  recall=0.88±0.12  precision=0.90±0.03  F1=0.85±0.14
  [SEACells (ComBat)|pbmc-immune] done
  [SEACells (ComBat)] ds=pbmc-immune: coverage=1.00±0.00  repr macro=0.74±0.13  micro=0.75±0.15  homogeneity=0.75±0.15  cross_batch_homog=0.19±0.10  purity=0.88±0.07  recall=0.88±0.07  precision=0.87±0.06  F1=0.86±0.06
  [Leiden (ComBat)|pbmc-immune] done
  [Leiden (Harmony)|pbmc-immune] done
  [Leiden (ComBat)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.73±0.17  micro=0.75±0.18  homogeneity=0.75±0.18  cross_batch_homog=0.33±0.16  purity=0.81±0.17  recall=0.87±0.12  precision=0.82±0.11  F1=0.80±0.19
  [Leiden (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.61±0.11  micro=0.64±0.13  homogeneity=0.64±0.13  cross_batch_homog=0.30±0.18  purity=0.79±0.14  recall=0.80±0.12  precision=0.75±0.15  F1=0.75±0.17
  [SEACells (Harmony)|pbmc-immune] done
  [SEACells (Harmony)] ds=pbmc-immune: coverage=0.93±0.13  repr macro=0.65±0.17  micro=0.68±0.19  homogeneity=0.68±0.19  cross_batch_homog=0.25±0.15  purity=0.82±0.10  recall=0.77±0.15  precision=0.81±0.08  F1=0.75±0.16

In [12]:
# --- PAIRED significance test for the rare-cell table above (Wilcoxon signed-rank,
# scProto vs. each same-K baseline, Bonferroni-corrected per dataset) -- same
# convention used throughout the Harmony notebook and results.tex.
from interpretable_ssl.evaluation.paper_figures import rare_metric_significance_paired

df_sig_paired = rare_metric_significance_paired(
    df_rare,
    ref_name='scProto',
    metrics=(
        '_batch_rare_f1_macro_per_batch',
        '_batch_rare_homogeneity_per_batch',
        '_batch_rare_cross_batch_homog_per_batch',
    ),
    dataset_display_names=dataset_display_names,
)
df_sig_paired

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,scProto,219,8,0.437680,0.535403,0.207961,NaN,NaN,NaN,NaN
1,Pancreas,batch_rare_f1_macro,SEACells (PCA),220,8,0.372628,0.370589,0.250869,6.0,0.039062,0.195312,ns
2,Pancreas,batch_rare_f1_macro,SEACells (ComBat),220,8,0.320318,0.345186,0.208526,7.0,0.007812,0.039062,*
3,Pancreas,batch_rare_f1_macro,Leiden (ComBat),220,8,0.149533,0.145890,0.066579,8.0,0.003906,0.019531,*
4,Pancreas,batch_rare_f1_macro,SEACells (Harmony),220,8,0.295521,0.316501,0.159421,7.0,0.011719,0.058594,ns
5,Pancreas,batch_rare_f1_macro,Leiden (Harmony),220,8,0.133361,0.223580,0.171156,8.0,0.003906,0.019531,*
6,Pancreas,batch_rare_homogeneity,scProto,219,8,0.522129,0.564854,0.155263,NaN,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,SEACells (PCA),220,8,0.369265,0.420592,0.195138,8.0,0.003906,0.019531,*
8,Pancreas,batch_rare_homogeneity,SEACells (ComBat),220,8,0.272370,0.291237,0.083672,8.0,0.003906,0.019531,*
9,Pancreas,batch_rare_homogeneity,Leiden (ComBat),220,8,0.208180,0.231644,0.101183,8.0,0.003906,0.019531,*
10,Pancreas,batch_rare_homogeneity,SEACells (Harmony),220,8,0.269034,0.285358,0.115015,8.0,0.003906,0.019531,*
11,Pancreas,batch_rare_homogeneity,Leiden (Harmony),220,8,0.220189,0.218359,0.085397,8.0,0.003906,0.019531,*
12,Pancreas,batch_rare_cross_batch_homog,scProto,219,8,0.259411,0.322859,0.179414,NaN,NaN,NaN,NaN
13,Pancreas,batch_rare_cross_batch_homog,SEACells (PCA),220,8,0.212005,0.221772,0.100594,5.0,0.125000,0.625000,ns
14,Pancreas,batch_rare_cross_batch_homog,SEACells (ComBat),220,8,0.231137,0.212543,0.051448,6.0,0.097656,0.488281,ns
15,Pancreas,batch_rare_cross_batch_homog,Leiden (ComBat),220,8,0.167498,0.169997,0.059574,6.0,0.027344,0.136719,ns
16,Pancreas,batch_rare_cross_batch_homog,SEACells (Harmony),220,8,0.210341,0.227762,0.098150,6.0,0.074219,0.371094,ns
17,Pancreas,batch_rare_cross_batch_homog,Leiden (Harmony),220,8,0.183894,0.188323,0.084876,6.0,0.039062,0.195312,ns
18,Lung,batch_rare_f1_macro,scProto,298,15,0.610777,0.599348,0.175935,NaN,NaN,NaN,NaN
19,Lung,batch_rare_f1_macro,SEACells (PCA),300,15,0.498294,0.420330,0.217382,11.0,0.001678,0.008392,**
20,Lung,batch_rare_f1_macro,SEACells (ComBat),300,15,0.309580,0.325291,0.212761,14.0,0.002136,0.010681,*
21,Lung,batch_rare_f1_macro,Leiden (ComBat),300,15,0.359768,0.376468,0.185249,13.0,0.000580,0.002899,**
22,Lung,batch_rare_f1_macro,SEACells (Harmony),300,15,0.348333,0.357564,0.144189,13.0,0.000763,0.003815,**
23,Lung,batch_rare_f1_macro,Leiden (Harmony),300,15,0.282094,0.280384,0.141206,13.0,0.000305,0.001526,**
24,Lung,batch_rare_homogeneity,scProto,298,15,0.586120,0.577994,0.220956,NaN,NaN,NaN,NaN
25,Lung,batch_rare_homogeneity,SEACells (PCA),300,15,0.495372,0.472356,0.242324,13.0,0.002686,0.013428,*
26,Lung,batch_rare_homogeneity,SEACells (ComBat),300,15,0.360115,0.395503,0.253140,14.0,0.003357,0.016785,*
27,Lung,batch_rare_homogeneity,Leiden (ComBat),300,15,0.352481,0.397715,0.209009,14.0,0.002686,0.013428,*
28,Lung,batch_rare_homogeneity,SEACells (Harmony),300,15,0.408222,0.402522,0.115704,14.0,0.002136,0.010681,*
29,Lung,batch_rare_homogeneity,Leiden (Harmony),300,15,0.344610,0.344719,0.084300,13.0,0.000763,0.003815,**
30,Lung,batch_rare_cross_batch_homog,scProto,298,15,0.509701,0.508327,0.196956,NaN,NaN,NaN,NaN
31,Lung,batch_rare_cross_batch_homog,SEACells (PCA),300,15,0.415586,0.393655,0.201346,12.0,0.001678,0.008392,**
32,Lung,batch_rare_cross_batch_homog,SEACells (ComBat),300,15,0.326326,0.299732,0.205254,14.0,0.003357,0.016785,*
33,Lung,batch_rare_cross_batch_homog,Leiden (ComBat),300,15,0.343225,0.338467,0.185430,14.0,0.003357,0.016785,*
34,Lung,batch_rare_cross_batch_homog,SEACells (Harmony),300,15,0.398968,0.371869,0.121918,14.0,0.003357,0.016785,*
35,Lung,batch_rare_cross_batch_homog,Leiden (Harmony),300,15,0.341005,0.328868,0.089351,13.0,0.003357,0.016785,*
36,Immune,batch_rare_f1_macro,scProto,294,5,0.896681,0.854140,0.138252,NaN,NaN,NaN,NaN
37,Immune,batch_rare_f1_macro,SEACells (PCA),300,5,0.922877,0.879883,0.082663,2.0,0.687500,1.000000,ns
38,Immune,batch_rare_f1_macro,SEACells (ComBat),300,5,0.884704,0.859021,0.062687,3.0,0.406250,1.000000,ns
39,Immune,batch_rare_f1_macro,Leiden (ComBat),300,5,0.843666,0.798823,0.188834,4.0,0.062500,0.312500,ns
40,Immune,batch_rare_f1_macro,SEACells (Harmony),300,5,0.812234,0.750774,0.162481,4.0,0.062500,0.312500,ns
41,Immune,batch_rare_f1_macro,Leiden (Harmony),300,5,0.765805,0.751472,0.166212,4.0,0.062500,0.312500,ns
42,Immune,batch_rare_homogeneity,scProto,294,5,0.855792,0.827192,0.101982,NaN,NaN,NaN,NaN
43,Immune,batch_rare_homogeneity,SEACells (PCA),300,5,0.815416,0.854752,0.073552,3.0,0.687500,1.000000,ns
44,Immune,batch_rare_homogeneity,SEACells (ComBat),300,5,0.828196,0.754392,0.145880,4.0,0.093750,0.468750,ns
45,Immune,batch_rare_homogeneity,Leiden (ComBat),300,5,0.843974,0.748406,0.178835,4.0,0.062500,0.312500,ns
46,Immune,batch_rare_homogeneity,SEACells (Harmony),300,5,0.804136,0.676898,0.185473,5.0,0.031250,0.156250,ns
47,Immune,batch_rare_homogeneity,Leiden (Harmony),300,5,0.706627,0.635473,0.125110,5.0,0.031250,0.156250,ns
48,Immune,batch_rare_cross_batch_homog,scProto,294,5,0.406766,0.349204,0.197947,NaN,NaN,NaN,NaN
49,Immune,batch_rare_cross_batch_homog,SEACells (PCA),300,5,0.028607,0.120662,0.166976,3.0,0.072064,0.360318,ns
50,Immune,batch_rare_cross_batch_homog,SEACells (ComBat),300,5,0.113148,0.186625,0.104480,4.0,0.093750,0.468750,ns
51,Immune,batch_rare_cross_batch_homog,Leiden (ComBat),300,5,0.316873,0.329575,0.161361,3.0,0.593750,1.000000,ns
52,Immune,batch_rare_cross_batch_homog,SEACells (Harmony),300,5,0.304594,0.245410,0.153361,3.0,0.156250,0.781250,ns
53,Immune,batch_rare_cross_batch_homog,Leiden (Harmony),300,5,0.372796,0.304595,0.181786,2.0,0.232604,1.000000,ns

In [13]:
# --- PAIRED significance test for Table 1's modularity (scProto vs. each same-K
# baseline). Only modularity_per_batch is pairable (batch is a shared,
# method-independent unit) -- purity_per_mc / batch_entropy_per_mc stay unpaired
# (no natural cross-method correspondence between metacells from different methods).
from interpretable_ssl.evaluation.paper_figures import graph_batch_significance_paired

sig_df_table1_paired = graph_batch_significance_paired(
    RNA_SEQ_DATASETS,
    MODEL_KEYWORDS,
    ref_name='scProto',
    dataset_display_names=dataset_display_names,
)

sub = sig_df_table1_paired.copy()
sub['cell'] = sub.apply(
    lambda r: f"{r['median']:.3f} (K={r['k']}, n={r['n']}) [ref]" if r['method'] == 'scProto'
    else f"{r['median']:.3f} (K={r['k']}, n={r['n']}, wins={r.get('n_wins', '?')}/{r['n']})  "
         f"{r.get('sig', '?')}  p_adj={r.get('p_adj', float('nan')):.3g}",
    axis=1,
)
display(sub.pivot(index='method', columns='dataset', values='cell'))

sig_df_table1_paired

dataset,Immune,Lung,Pancreas
method,,,
Leiden (ComBat),"0.555 (K=300, n=5, wins=4.0/5) ns p_adj=0.781","0.481 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.312 (K=220, n=9, wins=9.0/9) ** p_adj=0.00977"
Leiden (Harmony),"0.250 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.403 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.614 (K=220, n=9, wins=6.0/9) ns p_adj=1"
SEACells (ComBat),"0.588 (K=300, n=5, wins=3.0/5) ns p_adj=0.781","0.615 (K=300, n=16, wins=16.0/16) *** p_adj=...","0.570 (K=220, n=9, wins=7.0/9) ns p_adj=1"
SEACells (Harmony),"0.551 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.625 (K=300, n=16, wins=14.0/16) ** p_adj=0...","0.566 (K=220, n=9, wins=7.0/9) ns p_adj=0.625"
SEACells (PCA),"0.569 (K=300, n=5, wins=5.0/5) ns p_adj=0.156","0.671 (K=300, n=16, wins=9.0/16) ns p_adj=1","0.658 (K=220, n=9, wins=0.0/9) ns p_adj=1"
scProto,"0.620 (K=294, n=5) [ref]","0.669 (K=298, n=16) [ref]","0.621 (K=219, n=9) [ref]"

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,modularity_per_batch,scProto,219,9,0.621456,0.601234,0.083385,NaN,NaN,NaN,NaN
1,Pancreas,modularity_per_batch,SEACells (PCA),220,9,0.657892,0.673906,0.050910,0.0,1.000000,1.000000,ns
2,Pancreas,modularity_per_batch,SEACells (ComBat),220,9,0.569886,0.578996,0.027181,7.0,0.212891,1.000000,ns
3,Pancreas,modularity_per_batch,Leiden (ComBat),220,9,0.311551,0.293305,0.066998,9.0,0.001953,0.009766,**
4,Pancreas,modularity_per_batch,SEACells (Harmony),220,9,0.566367,0.567150,0.017709,7.0,0.125000,0.625000,ns
5,Pancreas,modularity_per_batch,Leiden (Harmony),220,9,0.614318,0.612469,0.021231,6.0,0.544922,1.000000,ns
6,Lung,modularity_per_batch,scProto,298,16,0.669390,0.664444,0.022871,NaN,NaN,NaN,NaN
7,Lung,modularity_per_batch,SEACells (PCA),300,16,0.671340,0.673784,0.037789,9.0,0.628220,1.000000,ns
8,Lung,modularity_per_batch,SEACells (ComBat),300,16,0.615128,0.615392,0.025199,16.0,0.000015,0.000076,***
9,Lung,modularity_per_batch,Leiden (ComBat),300,16,0.480650,0.453209,0.084122,16.0,0.000015,0.000076,***
10,Lung,modularity_per_batch,SEACells (Harmony),300,16,0.624808,0.606050,0.044595,14.0,0.000214,0.001068,**
11,Lung,modularity_per_batch,Leiden (Harmony),300,16,0.403452,0.419322,0.146812,16.0,0.000015,0.000076,***
12,Immune,modularity_per_batch,scProto,294,5,0.619596,0.628591,0.051655,NaN,NaN,NaN,NaN
13,Immune,modularity_per_batch,SEACells (PCA),300,5,0.568733,0.553930,0.031290,5.0,0.031250,0.156250,ns
14,Immune,modularity_per_batch,SEACells (ComBat),300,5,0.588474,0.589831,0.016186,3.0,0.156250,0.781250,ns
15,Immune,modularity_per_batch,Leiden (ComBat),300,5,0.555266,0.510042,0.157535,4.0,0.156250,0.781250,ns
16,Immune,modularity_per_batch,SEACells (Harmony),300,5,0.551127,0.548892,0.012923,5.0,0.031250,0.156250,ns
17,Immune,modularity_per_batch,Leiden (Harmony),300,5,0.250021,0.296661,0.109232,5.0,0.031250,0.156250,ns

### Realized cluster/metacell count vs. scProto's target K

Sanity check that ComBat's downstream SEACells/Leiden actually landed at (approximately)
scProto's own `num_prototypes` for each dataset, per the paper's own protocol ("All
baselines are configured to produce the same number of metacells K as scProto"). Reads
directly from each run's saved outputs -- no recompute.

In [14]:
target_k = {ds: DATASETS[ds]['num_prototypes'] for ds in RNA_SEQ_DATASETS}

# Leiden: reads n_clusters/resolution straight from metrics.json
df_combat_k = load_task1_multi(RNA_SEQ_DATASETS, metrics=['n_clusters', 'resolution'])
if df_combat_k.empty:
    print("No runs found yet under MODEL_DIR for RNA_SEQ_DATASETS -- run the 'Run: ...' "
          "cells above first.")
else:
    is_combat_leiden = df_combat_k.index.get_level_values('run').str.startswith('leiden_X_combat_d8')
    df_combat_k_leiden = df_combat_k[is_combat_leiden].copy()
    if df_combat_k_leiden.empty:
        print("No leiden_X_combat_d8 run found yet for any dataset in RNA_SEQ_DATASETS.")
    else:
        df_combat_k_leiden['target_k'] = [target_k[ds] for ds, _run in df_combat_k_leiden.index]
        df_combat_k_leiden['matches_target'] = df_combat_k_leiden['n_clusters'] == df_combat_k_leiden['target_k']
        display(df_combat_k_leiden)

# SEACells: no K in the folder name -- read realized count from cell_assignments.csv directly
from interpretable_ssl.evaluation.batch_correct_baselines import get_realized_seacell_count

seacell_k_rows = []
for ds_id in RNA_SEQ_DATASETS:
    n_actual = get_realized_seacell_count(ds_id, 'X_combat_d8')
    k = target_k[ds_id]
    seacell_k_rows.append({
        'dataset': ds_id, 'method': 'combat',
        'n_actual': n_actual, 'target_k': k,
        'matches_target': (n_actual is not None and abs(n_actual - k) <= 0.05 * k),
    })

df_seacell_k = pd.DataFrame(seacell_k_rows).set_index(['dataset', 'method'])
if df_seacell_k['n_actual'].isna().all():
    print("No seacell_X_combat_d8 runs found on disk yet for RNA_SEQ_DATASETS.")
else:
    display(df_seacell_k)

,,n_clusters,resolution,target_k,matches_target
dataset,run,,,,
pancreas,leiden_X_combat_d8_K220,220.0,32.0,220,True
lung,leiden_X_combat_d8_K300,300.0,64.0,300,True
pbmc-immune,leiden_X_combat_d8_K300,300.0,64.0,300,True

                    n_actual  target_k  matches_target
dataset     method
pancreas    combat       220       220            True
lung        combat       300       300            True
pbmc-immune combat       300       300            True

## Embedding-only rare-cell affinity purity (no downstream clustering)

Isolates the embedding from whichever clustering algorithm runs on top of it -- for each
method's raw embedding, builds one ARBF affinity graph directly on it, then for each
locally-rare-type cell scores what fraction of its total affinity MASS goes to
same-type cells. This is the most direct empirical check of ComBat's structural
limitation #2 from the intro cell (one shift per gene per batch, not per cell type): if
that blunt correction is distorting rare states, it should show up here even before any
clustering algorithm gets a chance to compensate.

**No separate step to run here** -- this runs automatically at the end of
`run_all_baselines_for_dataset` (via `compute_and_save_embedding_affinity_purity`), so it
already ran as part of the `Run: Pancreas` / `Run: Lung` / `Run: PBMC (Immune)` cells
above. The cell below just loads and displays those saved results.

In [15]:
from interpretable_ssl.evaluation.batch_correct_baselines import load_and_compare_affinity_purity

df_affinity_purity = load_and_compare_affinity_purity(
    RNA_SEQ_DATASETS, dataset_display_names=dataset_display_names,
)
df_affinity_purity

,dataset,method,dim,n,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,Raw PCA (uncorrected),50,8,0.385,0.164,7.0,0.0742,0.1484,ns
1,Pancreas,ComBat,8,8,0.344,0.155,6.0,0.0547,0.1094,ns
2,Pancreas,scProto,8,8,0.454,0.184,NaN,NaN,NaN,NaN
3,Lung,Raw PCA (uncorrected),50,15,0.559,0.194,11.0,0.0240,0.0479,*
4,Lung,ComBat,8,15,0.399,0.171,14.0,0.0034,0.0067,**
5,Lung,scProto,8,15,0.586,0.208,NaN,NaN,NaN,NaN
6,Immune,Raw PCA (uncorrected),50,5,0.827,0.050,4.0,0.3125,0.6250,ns
7,Immune,ComBat,8,5,0.806,0.105,3.0,0.1562,0.3125,ns
8,Immune,scProto,8,5,0.849,0.085,NaN,NaN,NaN,NaN

## Targeted per-cell-type breakdown (combat-notes hypotheses)

The tables above macro-average rare-cell metrics across every locally-rare type
within a batch, then across batches -- which can mask exactly the kind of
per-type unevenness the two `baseline-notes/combat-notes.md` hypotheses predict.
This section checks both directly, targeting specific real cell types identified
empirically from the raw h5ad files (not synthetic/designed cases):

**Hypothesis 1 (ComBat confounds batch artifact with real rare biology confined to
one batch):** sharpest where a rare type lives almost entirely in ONE batch --
**Lung's `Neutrophils_IL1R2`** (472 cells, 6/16 batches, 93% concentrated in a
single batch) is the strongest case across all three datasets; Pancreas has no
comparably sharp case (its rare types spread across 8-9/9 batches).

**Hypothesis 2 (ComBat's one-shift-per-gene-per-batch can't fit every cell type
evenly):** the signature isn't the mean across rare types -- it's the SPREAD
(a method scoring great on one type and terrible on another can still average out
to look identical to a uniformly-mediocre method). Reported per type below, plus
a spread (std/min/max) summary across each dataset's bottom-quartile-frequency
rare types.

Reads already-saved `umap_cells.csv` per run -- no recompute, no retraining.

In [16]:
!ls -la /content/drive/MyDrive/codes/interpretable-prototype/interpretable_ssl/evaluation/ | grep rebuttal

-rw------- 1 root root  20157 Jul 30 14:52 rebuttal_report.py

In [17]:
from interpretable_ssl.evaluation.rebuttal_report import per_celltype_breakdown
import os
# Bottom-quartile-global-frequency rare types per dataset, identified directly from
# the raw h5ad files (obs['celltype']/['cell_type']/['final_annotation'] vs.
# obs['tech']/['batch']) -- see chat history for the per-batch concentration check
# that surfaced Neutrophils_IL1R2 as the sharpest hypothesis-1 case.
RARE_TYPES_BY_DATASET = {
    'pancreas': ['mast', 'epsilon', 'schwann', 't_cell'],
    'lung': ['Neutrophils_IL1R2', 'Type 1', 'Lymphatic', 'Ionocytes'],
    'pbmc-immune': ['Monocyte progenitors', 'Megakaryocyte progenitors', 'CD10+ B cells', 'Plasma cells'],
}

df_celltype_breakdown = pd.concat([
    per_celltype_breakdown(ds_id, MODEL_KEYWORDS, cell_types=cts)
    for ds_id, cts in RARE_TYPES_BY_DATASET.items()
], ignore_index=True)

df_celltype_breakdown

,dataset,method,cell_type,n_cells,homogeneity,precision,recall,f1
0,pancreas,scProto,mast,42,0.695,0.798,0.833,0.815
1,pancreas,scProto,epsilon,32,0.281,0.938,0.281,0.433
2,pancreas,scProto,schwann,25,0.628,0.791,0.720,0.754
3,pancreas,scProto,t_cell,7,0.212,0.000,0.000,0.000
4,pancreas,SEACells (PCA),mast,42,0.660,0.790,0.881,0.833
...,...,...,...,...,...,...,...,...
67,pbmc-immune,SEACells (Harmony),Plasma cells,129,0.489,0.923,0.473,0.625
68,pbmc-immune,Leiden (Harmony),Monocyte progenitors,428,0.314,0.422,0.315,0.361
69,pbmc-immune,Leiden (Harmony),Megakaryocyte progenitors,270,0.305,0.596,0.367,0.454
70,pbmc-immune,Leiden (Harmony),CD10+ B cells,207,0.629,0.736,0.758,0.747
71,pbmc-immune,Leiden (Harmony),Plasma cells,129,0.252,0.440,0.310,0.364

In [18]:
# --- Hypothesis 1, headline case: Lung's Neutrophils_IL1R2 (93% in one batch) ---
# Does ComBat preserve it as a distinct metacell as well as scProto does, or does
# batch-correcting toward the cross-batch typical mean blur this batch-confined
# rare type's identity more than scProto's within-batch-affinity approach does?
df_celltype_breakdown[
    (df_celltype_breakdown['dataset'] == 'lung')
    & (df_celltype_breakdown['cell_type'] == 'Neutrophils_IL1R2')
].sort_values('f1', ascending=False)

,dataset,method,cell_type,n_cells,homogeneity,precision,recall,f1
28,lung,SEACells (PCA),Neutrophils_IL1R2,472,0.736,0.800,0.852,0.825
36,lung,Leiden (ComBat),Neutrophils_IL1R2,472,0.378,0.603,0.449,0.515
32,lung,SEACells (ComBat),Neutrophils_IL1R2,472,0.290,0.490,0.436,0.462
24,lung,scProto,Neutrophils_IL1R2,472,0.168,0.000,0.000,0.000
40,lung,SEACells (Harmony),Neutrophils_IL1R2,472,0.140,0.000,0.000,0.000
44,lung,Leiden (Harmony),Neutrophils_IL1R2,472,0.143,0.000,0.000,0.000

In [19]:
# --- Hypothesis 2: spread (not mean) across each dataset's rare types, per method ---
# High spread (max-min, or std) = uneven across cell types (predicted for ComBat's
# single global per-gene-per-batch shift); low spread = more uniform (predicted
# for scProto, which has no single global correction step).
df_spread = (
    df_celltype_breakdown
    .groupby(['dataset', 'method'])[['homogeneity', 'f1']]
    .agg(['mean', 'std', 'min', 'max'])
)
df_spread['homogeneity_range'] = df_spread[('homogeneity', 'max')] - df_spread[('homogeneity', 'min')]
df_spread['f1_range'] = df_spread[('f1', 'max')] - df_spread[('f1', 'min')]
df_spread

                               homogeneity                               f1  \
                                      mean       std    min    max     mean
dataset     method
lung        Leiden (ComBat)        0.49450  0.095647  0.378  0.609  0.61750
            Leiden (Harmony)       0.16150  0.104825  0.032  0.285  0.18025
            SEACells (ComBat)      0.43325  0.332943  0.041  0.787  0.51525
            SEACells (Harmony)     0.33325  0.134043  0.140  0.450  0.40525
            SEACells (PCA)         0.80700  0.080440  0.736  0.918  0.88125
            scProto                0.48075  0.415953  0.093  0.944  0.45025
pancreas    Leiden (ComBat)        0.12725  0.140215  0.046  0.337  0.13675
            Leiden (Harmony)       0.11775  0.096834  0.027  0.253  0.11375
            SEACells (ComBat)      0.19300  0.144971  0.043  0.343  0.23925
            SEACells (Harmony)     0.16275  0.119970  0.046  0.318  0.22000
            SEACells (PCA)         0.32150  0.268105  0.045  0.660  0.34950
            scProto                0.45400  0.242796  0.212  0.695  0.50050
pbmc-immune Leiden (ComBat)        0.50725  0.262924  0.246  0.743  0.57400
            Leiden (Harmony)       0.37500  0.171528  0.252  0.629  0.48150
            SEACells (ComBat)      0.66275  0.132681  0.519  0.780  0.76050
            SEACells (Harmony)     0.48400  0.100336  0.384  0.620  0.63075
            SEACells (PCA)         0.79450  0.113621  0.682  0.913  0.85900
            scProto                0.64325  0.234574  0.350  0.842  0.76225

                                                       homogeneity_range  \
                                     std    min    max
dataset     method
lung        Leiden (ComBat)     0.098199  0.515  0.718             0.231
            Leiden (Harmony)    0.250855  0.000  0.532             0.253
            SEACells (ComBat)   0.382666  0.000  0.868             0.746
            SEACells (Harmony)  0.271393  0.000  0.576             0.310
            SEACells (PCA)      0.055271  0.825  0.956             0.182
            scProto             0.523081  0.000  0.971             0.851
pancreas    Leiden (ComBat)     0.273500  0.000  0.547             0.291
            Leiden (Harmony)    0.227500  0.000  0.455             0.226
            SEACells (ComBat)   0.278045  0.000  0.517             0.300
            SEACells (Harmony)  0.257832  0.000  0.494             0.272
            SEACells (PCA)      0.418136  0.000  0.833             0.615
            scProto             0.373376  0.000  0.815             0.483
pbmc-immune Leiden (ComBat)     0.311898  0.284  0.859             0.497
            Leiden (Harmony)    0.182184  0.361  0.747             0.377
            SEACells (ComBat)   0.092107  0.679  0.849             0.261
            SEACells (Harmony)  0.070929  0.567  0.731             0.236
            SEACells (PCA)      0.089088  0.766  0.955             0.231
            scProto             0.241559  0.400  0.890             0.492

                               f1_range

dataset     method
lung        Leiden (ComBat)       0.203
            Leiden (Harmony)      0.532
            SEACells (ComBat)     0.868
            SEACells (Harmony)    0.576
            SEACells (PCA)        0.131
            scProto               0.971
pancreas    Leiden (ComBat)       0.547
            Leiden (Harmony)      0.455
            SEACells (ComBat)     0.517
            SEACells (Harmony)    0.494
            SEACells (PCA)        0.833
            scProto               0.815
pbmc-immune Leiden (ComBat)       0.575
            Leiden (Harmony)      0.386
            SEACells (ComBat)     0.170
            SEACells (Harmony)    0.164
            SEACells (PCA)        0.189
            scProto               0.490

In [20]:

RARE_TYPES_BY_DATASET = {
    'pancreas': ['mast', 'epsilon', 'schwann', 't_cell'],
    'lung': ['Neutrophils_IL1R2', 'Type 1', 'Lymphatic', 'Ionocytes'],
    'pbmc-immune': ['Monocyte progenitors', 'Megakaryocyte progenitors', 'CD10+ B cells', 'Plasma cells'],
}

df_celltype_breakdown = pd.concat([
    per_celltype_breakdown(ds_id, MODEL_KEYWORDS, cell_types=cts)
    for ds_id, cts in RARE_TYPES_BY_DATASET.items()
], ignore_index=True)

df_celltype_breakdown

,dataset,method,cell_type,n_cells,homogeneity,precision,recall,f1
0,pancreas,scProto,mast,42,0.695,0.798,0.833,0.815
1,pancreas,scProto,epsilon,32,0.281,0.938,0.281,0.433
2,pancreas,scProto,schwann,25,0.628,0.791,0.720,0.754
3,pancreas,scProto,t_cell,7,0.212,0.000,0.000,0.000
4,pancreas,SEACells (PCA),mast,42,0.660,0.790,0.881,0.833
...,...,...,...,...,...,...,...,...
67,pbmc-immune,SEACells (Harmony),Plasma cells,129,0.489,0.923,0.473,0.625
68,pbmc-immune,Leiden (Harmony),Monocyte progenitors,428,0.314,0.422,0.315,0.361
69,pbmc-immune,Leiden (Harmony),Megakaryocyte progenitors,270,0.305,0.596,0.367,0.454
70,pbmc-immune,Leiden (Harmony),CD10+ B cells,207,0.629,0.736,0.758,0.747
71,pbmc-immune,Leiden (Harmony),Plasma cells,129,0.252,0.440,0.310,0.364

In [21]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df_celltype_breakdown)

save_path = '/content/drive/MyDrive/models/rare_celltype_breakdown_combat.csv'
df_celltype_breakdown.to_csv(save_path, index=False)
print(f"saved to {save_path}")

,dataset,method,cell_type,n_cells,homogeneity,precision,recall,f1
0,pancreas,scProto,mast,42,0.695,0.798,0.833,0.815
1,pancreas,scProto,epsilon,32,0.281,0.938,0.281,0.433
2,pancreas,scProto,schwann,25,0.628,0.791,0.720,0.754
3,pancreas,scProto,t_cell,7,0.212,0.000,0.000,0.000
4,pancreas,SEACells (PCA),mast,42,0.660,0.790,0.881,0.833
5,pancreas,SEACells (PCA),epsilon,32,0.045,0.000,0.000,0.000
6,pancreas,SEACells (PCA),schwann,25,0.397,0.619,0.520,0.565
7,pancreas,SEACells (PCA),t_cell,7,0.184,0.000,0.000,0.000
8,pancreas,SEACells (ComBat),mast,42,0.343,0.385,0.786,0.517
9,pancreas,SEACells (ComBat),epsilon,32,0.043,0.000,0.000,0.000
10,pancreas,SEACells (ComBat),schwann,25,0.288,0.440,0.440,0.440
11,pancreas,SEACells (ComBat),t_cell,7,0.098,0.000,0.000,0.000
12,pancreas,Leiden (ComBat),mast,42,0.337,0.427,0.762,0.547
13,pancreas,Leiden (ComBat),epsilon,32,0.046,0.000,0.000,0.000
14,pancreas,Leiden (ComBat),schwann,25,0.055,0.000,0.000,0.000
15,pancreas,Leiden (ComBat),t_cell,7,0.071,0.000,0.000,0.000
16,pancreas,SEACells (Harmony),mast,42,0.318,0.488,0.500,0.494
17,pancreas,SEACells (Harmony),epsilon,32,0.046,0.000,0.000,0.000
18,pancreas,SEACells (Harmony),schwann,25,0.192,0.344,0.440,0.386
19,pancreas,SEACells (Harmony),t_cell,7,0.095,0.000,0.000,0.000
20,pancreas,Leiden (Harmony),mast,42,0.253,0.333,0.714,0.455
21,pancreas,Leiden (Harmony),epsilon,32,0.027,0.000,0.000,0.000
22,pancreas,Leiden (Harmony),schwann,25,0.113,0.000,0.000,0.000
23,pancreas,Leiden (Harmony),t_cell,7,0.078,0.000,0.000,0.000
24,lung,scProto,Neutrophils_IL1R2,472,0.168,0.000,0.000,0.000
25,lung,scProto,Type 1,424,0.718,0.850,0.811,0.830
26,lung,scProto,Lymphatic,341,0.944,1.000,0.944,0.971
27,lung,scProto,Ionocytes,46,0.093,0.000,0.000,0.000
28,lung,SEACells (PCA),Neutrophils_IL1R2,472,0.736,0.800,0.852,0.825
29,lung,SEACells (PCA),Type 1,424,0.812,0.890,0.875,0.883
30,lung,SEACells (PCA),Lymphatic,341,0.918,0.994,0.921,0.956
31,lung,SEACells (PCA),Ionocytes,46,0.762,0.926,0.804,0.861
32,lung,SEACells (ComBat),Neutrophils_IL1R2,472,0.290,0.490,0.436,0.462
33,lung,SEACells (ComBat),Type 1,424,0.615,0.722,0.741,0.731
34,lung,SEACells (ComBat),Lymphatic,341,0.787,0.892,0.845,0.868
35,lung,SEACells (ComBat),Ionocytes,46,0.041,0.000,0.000,0.000
36,lung,Leiden (ComBat),Neutrophils_IL1R2,472,0.378,0.603,0.449,0.515
37,lung,Leiden (ComBat),Type 1,424,0.609,0.737,0.700,0.718
38,lung,Leiden (ComBat),Lymphatic,341,0.515,0.925,0.396,0.554
39,lung,Leiden (ComBat),Ionocytes,46,0.476,0.778,0.609,0.683
40,lung,SEACells (Harmony),Neutrophils_IL1R2,472,0.140,0.000,0.000,0.000
41,lung,SEACells (Harmony),Type 1,424,0.372,0.551,0.486,0.516
42,lung,SEACells (Harmony),Lymphatic,341,0.450,0.633,0.455,0.529
43,lung,SEACells (Harmony),Ionocytes,46,0.371,0.456,0.783,0.576
44,lung,Leiden (Harmony),Neutrophils_IL1R2,472,0.143,0.000,0.000,0.000
45,lung,Leiden (Harmony),Type 1,424,0.285,0.399,0.795,0.532
46,lung,Leiden (Harmony),Lymphatic,341,0.186,0.549,0.114,0.189
47,lung,Leiden (Harmony),Ionocytes,46,0.032,0.000,0.000,0.000
48,pbmc-immune,scProto,Monocyte progenitors,428,0.558,0.849,0.907,0.877
49,pbmc-immune,scProto,Megakaryocyte progenitors,270,0.350,0.799,0.267,0.400
50,pbmc-immune,scProto,CD10+ B cells,207,0.842,0.905,0.860,0.882
51,pbmc-immune,scProto,Plasma cells,129,0.823,0.993,0.806,0.890
52,pbmc-immune,SEACells (PCA),Monocyte progenitors,428,0.714,0.842,0.769,0.803
53,pbmc-immune,SEACells (PCA),Megakaryocyte progenitors,270,0.682,0.952,0.641,0.766
54,pbmc-immune,SEACells (PCA),CD10+ B cells,207,0.869,0.884,0.942,0.912
55,pbmc-immune,SEACells (PCA),Plasma cells,129,0.913,0.963,0.946,0.955
56,pbmc-immune,SEACells (ComBat),Monocyte progenitors,428,0.519,0.739,0.629,0.679
57,pbmc-immune,SEACells (ComBat),Megakaryocyte progenitors,270,0.581,0.781,0.607,0.683
58,pbmc-immune,SEACells (ComBat),CD10+ B cells,207,0.780,0.956,0.734,0.831
59,pbmc-immune,SEACells (ComBat),Plasma cells,129,0.771,0.776,0.938,0.849
60,pbmc-immune,Leiden (ComBat),Monocyte progenitors,428,0.316,0.560,0.229,0.325
61,pbmc-immune,Leiden (ComBat),Megakaryocyte progenitors,270,0.246,0.610,0.185,0.284
62,pbmc-immune,Leiden (ComBat),CD10+ B cells,207,0.743,0.895,0.826,0.859
63,pbmc-immune,Leiden (ComBat),Plasma cells,129,0.724,0.878,0.783,0.828
64,pbmc-immune,SEACells (Harmony),Monocyte progenitors,428,0.443,0.620,0.582,0.600
65,pbmc-immune,SEACells (Harmony),Megakaryocyte progenitors,270,0.384,0.553,0.581,0.567
66,pbmc-immune,SEACells (Harmony),CD10+ B cells,207,0.620,0.815,0.662,0.731
67,pbmc-immune,SEACells (Harmony),Plasma cells,129,0.489,0.923,0.473,0.625
68,pbmc-immune,Leiden (Harmony),Monocyte progenitors,428,0.314,0.422,0.315,0.361
69,pbmc-immune,Leiden (Harmony),Megakaryocyte progenitors,270,0.305,0.596,0.367,0.454
70,pbmc-immune,Leiden (Harmony),CD10+ B cells,207,0.629,0.736,0.758,0.747
71,pbmc-immune,Leiden (Harmony),Plasma cells,129,0.252,0.440,0.310,0.364

saved to /content/drive/MyDrive/models/rare_celltype_breakdown_combat.csv