# scVI Stage 1, two continuations: Leiden/SEACells vs. scProto Stage 2

**What this answers (reviewer F5RB).**
1. *"The cross-batch alignment seems to come mainly from the Stage-1 scPoli-style pretraining ... the training design does not fully support the mechanism claimed in the paper."*
2. *"The most important baseline is missing: first apply a batch-correction method such as scVI, then run an existing graph-based metacell method on the corrected latent space."*
3. Round 3: *"restricting all methods to d=8 ... replacing scVI's standard count likelihood with a Gaussian likelihood may disadvantage methods under nonstandard settings."*

All three are answered by one controlled experiment. Train **plain scVI at its own default configuration** (n_latent=10, ZINB count likelihood, raw counts), then keep everything downstream identical and change exactly one thing:

| arm | Stage 1 | continuation |
|---|---|---|
| A1 | scVI (default) | **Leiden** on its latent |
| A2 | scVI (default) | **SEACells** on its latent |
| B  | scVI (default) | **scProto Stage 2** keeps training that same encoder |

Same pretrained weights (loaded once, in one process), same adaptive-RBF affinity graph, same K, same evaluation code. No scPoli anywhere. Any difference between A and B is the Stage-2 objective and nothing else.

There is also a fourth, free control: **epoch 0** of arm B — prototypes waypoint-initialised on the *frozen* scVI latent, before a single gradient step — printed by the training cell as `[Epoch 0] initial modularity=...`. It is the "no Stage-2 training at all" reference point.

**Code.** `interpretable_ssl/models/scvi_backbone.py` (scVI-backed scProto model), `interpretable_ssl/trainers/scvi_proto.py` (`ScviProtoTrainer` = `SCProtoTrainer` with Stage 1 replaced), `interpretable_ssl/experiments/scvi_stage2.py` (the runner used below). Stage 2 itself — waypoint init, temperature calibration, community loss, nassoc, usage, prototype reconstruction, early stopping on modularity — is inherited unchanged from the paper's own trainer, and evaluation loads the best checkpoint exactly like `find_metacells` does.

**Resuming.** Every stage writes to Drive and reloads if present (scVI weights → `models/{ds}/scvi_stage1/`, Stage-1 model state → `models/{ds}/pretrain_scvi/`, Stage-2 → `umap_checkpoint.pth` in the run dir, baselines → their own `metrics.json`). A dataset that fails is skipped, not fatal. After a disconnect, re-run the cells top to bottom: finished work reloads in seconds and training continues from the last evaluation.

## Setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Same install cell as batch_correct_then_cluster_baselines.ipynb / headline_significance_test.ipynb.
# Only needed once per fresh runtime. RESTART THE RUNTIME after this cell before running
# anything below -- numpy/scipy/anndata are C-extension linked, an in-process upgrade
# won't reliably take effect on already-imported modules.
!pip install -q scarches faiss-gpu-cu12 scib-metrics
!pip install git+https://github.com/dpeerlab/SEACells.git --quiet --no-deps
!pip install numpy scipy --upgrade -q
!pip install -q palantir harmonypy
!pip install -q "numpy==1.26.4" "scipy==1.13.1"
!pip install --upgrade --force-reinstall numpy cupy-cuda12x
!pip install "numpy<2.3"

In [22]:
# Ground truth for "did the install actually work" -- pip's log is noisy, importing is
# the real test.
_checks = {
    'numpy': 'numpy', 'scipy': 'scipy', 'anndata': 'anndata', 'scanpy': 'scanpy',
    'scarches': 'scarches', 'scvi-tools': 'scvi', 'seacells': 'SEACells',
    'palantir': 'palantir', 'scib-metrics': 'scib_metrics', 'leidenalg': 'leidenalg',
    'python-igraph': 'igraph', 'umap-learn': 'umap', 'faiss-cpu': 'faiss',
}
_failed = []
for pkg_name, import_name in _checks.items():
    try:
        mod = __import__(import_name)
        print(f"  OK   {pkg_name:16s} (import {import_name}, version {getattr(mod, '__version__', '?')})")
    except Exception as e:
        _failed.append(pkg_name)
        print(f"  FAIL {pkg_name:16s} (import {import_name}): {type(e).__name__}: {e}")
print(f"\n{len(_failed)} failed: {_failed}" if _failed else f"\nAll {len(_checks)} packages import cleanly.")

  OK   numpy            (import numpy, version 2.2.6)
  OK   scipy            (import scipy, version 1.13.1)
  OK   anndata          (import anndata, version 0.13.2)
  OK   scanpy           (import scanpy, version 1.12.3)
  OK   scarches         (import scarches, version 0.6.1)
  OK   scvi-tools       (import scvi, version 1.5.0.post1)
  OK   seacells         (import SEACells, version 0.3.3)
  OK   palantir         (import palantir, version 1.4.5)
  OK   scib-metrics     (import scib_metrics, version 0.6.0)
  OK   leidenalg        (import leidenalg, version 0.12.0)
  OK   python-igraph    (import igraph, version 1.0.0)
  OK   umap-learn       (import umap, version 0.5.12)
  OK   faiss-cpu        (import faiss, version 1.14.1)

All 13 packages import cleanly.

In [23]:
%run /content/drive/MyDrive/codes/interpretable-prototype/notebooks/nb_setup.py

nb_setup done. Available: get_trainer, run_mc_task, fig_*, LAMBDA_PROTO_UMAP, LAMBDA_PROTO_UMAP_PRECON, LAMBDA_PARAM_UMAP, LAMBDA_RECON_ONLY, train_sure, eval_sure_task1/2/3
Configs: {'LAMBDA_PROTO_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'proto'}, 'LAMBDA_PARAM_UMAP': {'lambda_umap': 1, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 0, 'lambda_proto_recon': 0.0, 'umap_similarity': 'embedding'}, 'LAMBDA_RECON_ONLY': {'lambda_umap': 0, 'lambda_swav': 0, 'lambda_kl': 0, 'lambda_recon': 1, 'lambda_proto_recon': 0.0}}

In [24]:
import os, json, glob
import numpy as np
import pandas as pd

from interpretable_ssl.experiments.scvi_stage2 import (
    SCVI_DEF_TAG,
    run_all_datasets,
    run_scvi_stage2_experiment,
    get_scvi_proto_trainer,
    run_scvi_clustering_baselines,
    resolve_run_names,
    collect_task1_table,
)
from interpretable_ssl.datasets.dataset_configs import DATASETS
from interpretable_ssl.configs.paths import get_dataset_model_dir
from interpretable_ssl.evaluation.paper_figures import (
    rare_celltype_purity_table, rare_metric_significance_paired,
)

print("scvi_stage2 imports ready")

scvi_stage2 imports ready

## Config

In [25]:
# All three RNA-seq datasets. To (re-)run just one, set this to e.g. ['lung'] --
# every finished stage reloads from disk, so nothing is recomputed.
DATASETS_TO_RUN = ['pancreas', 'lung', 'pbmc-immune']
dataset_display_names = {'pancreas': 'Pancreas', 'lung': 'Lung', 'pbmc-immune': 'Immune'}

# scVI at its OWN defaults -- that is the whole point of this run (round-3 comment:
# d=8 + Gaussian likelihood was a nonstandard setting for scVI). n_latent=10 and
# gene_likelihood='zinb' are scvi-tools' defaults; scProto's Stage 2 adapts to them
# (the prototype layer is built at scVI's latent dimension), not the other way round.
SCVI_N_LATENT        = 10
SCVI_GENE_LIKELIHOOD = 'zinb'
SCVI_EPOCHS          = 50    # Stage 1 budget
STAGE2_MAX_EPOCHS    = 20    # Stage 2 budget (early stopping on modularity may end sooner)
EVAL_FREQ            = 3
PATIENCE             = 6
BATCH_SIZE           = 1024
UMAP_STEPS_PER_EPOCH = 500

for ds in DATASETS_TO_RUN:
    cfg = DATASETS[ds]
    print(f"{ds:<14} K={cfg['num_prototypes']:<5} label_key={cfg['label_key']:<18} batch_key={cfg.get('batch_key')}")

pancreas       K=220   label_key=celltype           batch_key=tech
lung           K=300   label_key=cell_type          batch_key=batch
pbmc-immune    K=300   label_key=final_annotation   batch_key=study

In [26]:
# Preflight: the adaptive-RBF affinity graph should already be on disk for each dataset.
#
# Why check instead of just letting it build: the graph filename is keyed only on
# (dataset, n_cells, n_comps, k, affinity_type) -- not on what adata.X held when it was
# built. This experiment feeds the model log1p(counts) (scVI's own encoder input space),
# so a MISSING graph would be generated from log1p(counts) PCA and would no longer be
# the same graph every other method in the rebuttal was scored on. Present = every arm
# here shares the canonical graph, which is what makes the comparison clean.
for ds in DATASETS_TO_RUN:
    found = sorted(glob.glob(os.path.join('./graphs', f'affinity_{ds}[0-9]*_ncomp50_kneighbors50_arbf.pkl')))
    if found:
        for g in found:
            print(f"  OK   {ds:<14} {os.path.basename(g)}  ({os.path.getsize(g)/1e6:.1f} MB)")
    else:
        print(f"  MISS {ds:<14} no cached ARBF graph -- it will be built from this run's "
              f"adata (log1p counts PCA). Arms stay internally consistent, but modularity "
              f"would not be directly comparable to the other rebuttal tables.")

  OK   pancreas       affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl  (14.1 MB)
  OK   lung           affinity_lung32472_ncomp50_kneighbors50_arbf.pkl  (29.9 MB)
  OK   pbmc-immune    affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl  (31.6 MB)

## Run — Stage 1 + both arms, per dataset

For each dataset: train/reload scVI on raw counts, cluster its latent with Leiden and SEACells, then run scProto Stage 2 on that same encoder and evaluate. A dataset that errors is reported and skipped so the others still finish.

Watch for `[Epoch 0] initial modularity=` in each dataset's Stage-2 output — that is the frozen-encoder control.

In [27]:
RESULTS = run_all_datasets(
    DATASETS_TO_RUN,
    scvi_epochs=SCVI_EPOCHS,
    scvi_n_latent=SCVI_N_LATENT,
    scvi_gene_likelihood=SCVI_GENE_LIKELIHOOD,
    stage2_max_epochs=STAGE2_MAX_EPOCHS,
    eval_freq=EVAL_FREQ,
    patience=PATIENCE,
    batch_size=BATCH_SIZE,
    umap_steps_per_epoch=UMAP_STEPS_PER_EPOCH,
    skip_if_exists=True,
)

======================================================================
=== pancreas ===
======================================================================
dataset is None, loading pancreas
loading pancreas data
✅ Already subsetted to HVGs (4000 genes).
[pancreas] counts check: max=1453667, integer fraction=0.950
[pancreas] NOTE: 5.0% of non-zero entries are not whole numbers. Values are still count-scale (max=1453667), and this is the same matrix the existing scVI baselines used, so the run proceeds.
    celseq          max=      1597.0  integer fraction=0.888
    celseq2         max=      1597.0  integer fraction=0.840
    fluidigmc1      max=   1453667.0  integer fraction=0.851
    smartseq2       max=   1341375.0  integer fraction=1.000
    inDrop1         max=      4318.0  integer fraction=1.000
    inDrop2         max=      3476.0  integer fraction=1.000
    inDrop3         max=      3071.0  integer fraction=1.000
    inDrop4         max=      4234.0  integer fraction=1.000
    smarter         max=    443598.2  integer fraction=0.839
[pancreas] adata.X set to log1p(counts) -- scVI's own encoder input space; raw counts kept in layers['counts'], log-normalised values in layers['lognorm'].
[scvi stage2] run dir: /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
[scvi backbone] latent_dim=10  K=220  n_batches=9  ref_log_library=7.752  recon/kl terms=off
📊 Affinity: wdeg[min/mean/max]=5.446/23.916/92.201, effk_med=62.4, mutual=100.00%
adam

=== [pancreas] Stage 1: scVI ===
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 0, 'batch_size': 1024, 'latent_dims': 10, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'num_prototypes': 220, 'condition_key': 'tech'}

  0%|          | 0/16 [00:00<?, ?it/s]

[pancreas] scVI latent: (16382, 10)

=== [pancreas] arm A: scVI latent -> Leiden / SEACells ===
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] X_scvidef: rare-type kNN purity = {'mean_purity': 0.6012578616352201, 'n_rare_cells': 106}
[pancreas] seacell_X_scvidef already computed -- skipping (metrics.json found)
[pancreas] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pancreas16382_ncomp50_kneighbors50_arbf.pkl (nnz=1171528) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pancreas/seacell_X_scvidef] modularity recomputed against canonical graph: mean_modularity_batch=0.29567328402973025 +/- 0.07786315296931869 (was 0.29567328402973025), K_target=220
[pancreas] leiden_X_scvidef already computed -- skipping (found /content/drive/MyDrive/models/pancreas/leiden_X_scvidef_K220)
[/content/drive/MyDrive/models/pancreas/leiden_X_scvidef_K220] modularity recomputed against canonical graph: mean_modularity_batch=0.37915864734393245 +/- 0.12164557284189471 (was 0.37915864734393245), K_target=220

=== [pancreas] arm B: scProto Stage 2 on the same scVI encoder ===
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 0, 'batch_size': 1024, 'latent_dims': 10, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'num_prototypes': 220, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
[scvi stage2] existing checkpoint found with no stage2_state.json (run predates this bookkeeping) -- reloading it as-is, not training further. Pass force_retrain=True to retrain from scratch.
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pancreas/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pancreas', 'cvae_epochs': 0, 'batch_size': 1024, 'latent_dims': 10, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'num_prototypes': 220, 'condition_key': 'tech'}
📊 EdgeDataset: 1155146 edges
   Weight range: [0.0320, 0.9688]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 1155146 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

Saved clusters (16382 cells, label='proto') and 0 metrics to /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 0/220 (0.00%)
[proto] mean cell-type purity: 0.9136  (size-weighted: 0.9706 ± 0.0901)
[proto] mean batch entropy: 0.3006  (size-weighted: 0.8064 ± 0.6674)

  0%|          | 0/16 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6990
[proto] per-batch modularity: mean=0.6157, std=0.0819

  0%|          | 0/16 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

Deleted: tmp_39803de6.h5ad
[task2] coverage: 1.0000
[task2] dge_rbo_avg: 0.2442
[task2] dge_kendall_avg: 0.2339
[task2] dge_jaccard_avg: 0.2082
[task2] scgraph_corr_avg: 0.7101
[task2] scgraph_corr_std: 0.1514

  0%|          | 0/16 [00:00<?, ?it/s]

[/content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31] modularity recomputed against canonical graph: mean_modularity_batch=0.6156805975346358 +/- 0.08189986843485984 (was 0.6156805975346358), K_target=220
[scvi stage2] metrics saved to /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metrics.json
Dominant batch: [[5]] (3605 cells)

  0%|          | 0/16 [00:00<?, ?it/s]

Saved metacells (220 prototypes) to /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

  0%|          | 0/16 [00:00<?, ?it/s]

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/16382 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/16382 [00:00<?, ?it/s]

Constructing CSR matrix...
[pancreas] embedding-level rare affinity purity saved to /content/drive/MyDrive/models/pancreas/scvi_stage2_affinity_purity_pancreas.json

[pancreas] done. Stage-2 run dir: /content/drive/MyDrive/models//pancreas/scviproto_ds-panc_NP220_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

======================================================================
=== lung ===
======================================================================
dataset is None, loading lung
loading lung data
✅ Already subsetted to HVGs (4000 genes).
[lung] counts check: max=1873, integer fraction=0.123
[lung] NOTE: 87.7% of non-zero entries are not whole numbers. Values are still count-scale (max=1873), and this is the same matrix the existing scVI baselines used, so the run proceeds.
    B1              max=       878.0  integer fraction=1.000
    B2              max=      1351.0  integer fraction=1.000
    B3              max=      1828.0  integer fraction=1.000
    B4              max=      1873.0  integer fraction=1.000
    A6              max=         8.7  integer fraction=0.000
    A1              max=         8.5  integer fraction=0.000
    A5              max=         8.9  integer fraction=0.000
    A3              max=         8.3  integer fraction=0.000
    A4              max=         8.3  integer fraction=0.000
    A2              max=         8.5  integer fraction=0.000
    5               max=         8.5  integer fraction=0.000
    2               max=         8.4  integer fraction=0.000
    4               max=         8.1  integer fraction=0.000
    3               max=         8.2  integer fraction=0.000
    1               max=         8.4  integer fraction=0.000
    6               max=         7.9  integer fraction=0.000
[lung] adata.X set to log1p(counts) -- scVI's own encoder input space; raw counts kept in layers['counts'], log-normalised values in layers['lognorm'].
[scvi stage2] run dir: /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
[scvi backbone] latent_dim=10  K=300  n_batches=16  ref_log_library=6.247  recon/kl terms=off

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

📊 Affinity: wdeg[min/mean/max]=5.255/24.467/119.300, effk_med=63.8, mutual=100.00%
adam

=== [lung] Stage 1: scVI ===
[scvi stage1] training scVI (n_latent=10, gene_likelihood=zinb, max_epochs=50) on 32472 cells

Training:   0%|          | 0/50 [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=50` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=50` reached.

[scvi stage1] saved to /content/drive/MyDrive/models/lung/scvi_stage1/d10_zinb_e50
[scvi stage1] weights loaded into the Stage-2 model
Saved pretrain checkpoint to /content/drive/MyDrive/models/lung/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth

  0%|          | 0/32 [00:00<?, ?it/s]

[lung] scVI latent: (32472, 10)

=== [lung] arm A: scVI latent -> Leiden / SEACells ===
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] X_scvidef: rare-type kNN purity = {'mean_purity': 0.736087295401403, 'n_rare_cells': 1283}
[waypoint init] N=32472  k=300  n_eigs=10  nnz=2311192  nnz/row=71.2
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1426.47archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected but n_cells=32472 > 30000 -- forcing CPU+sparse anyway (GPU path is dense-only and would need a ~32472x32472 dense matrix, likely OOM)
[SEACells backend] using our own optimized sparse-CPU SEACells (never materializes kernel_matrix @ kernel_matrix.T)
Welcome to SEACells!
Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 276.95603
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 11 iterations.

100%|██████████| 300/300 [00:02<00:00, 107.41it/s]

saving to:  /content/drive/MyDrive/models/lung/seacell_X_scvidef
  delta kept: X=yes, 1 layer(s), 0 varm, 1 obsm, 2 obsp, obs cols ['_scvi_batch', '_scvi_labels', 'SEACell']
  saved soft_assignments.npz (32472, 300) to /content/drive/MyDrive/models/lung/seacell_X_scvidef
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_scvidef ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8608  (size-weighted: 0.8671 ± 0.1766)
[seacell] mean batch entropy: 1.1103  (size-weighted: 1.1927 ± 0.5015)
[seacell] coverage: 1.0000
[seacell] modularity: 0.6075
[seacell] per-batch modularity: mean=0.5749, std=0.0325
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=3.5293 | saved to /content/drive/MyDrive/models/lung/seacell_X_scvidef/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/lung/seacell_X_scvidef
SEACell UMAP data saved to /content/drive/MyDrive/models/lung/seacell_X_scvidef
[lung] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl (nnz=2480396) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/lung/seacell_X_scvidef] modularity recomputed against canonical graph: mean_modularity_batch=0.326896246963179 +/- 0.05273701373816794 (was 0.5748868356716059), K_target=300
Loading SEACell from /content/drive/MyDrive/models/lung/seacell_X_scvidef ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

Deleted: tmp_760e0c45.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.8297
[seacell task2] scgraph_corr_std: 0.1010
  [leiden oversegment] resolution=1.0000 -> 19 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 29 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 48 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 80 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 140 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 273 clusters (need >= 300)
  [leiden oversegment] resolution=64.0000 -> 548 clusters (need >= 300)
  [leiden merge] -> 540 clusters (target 300)
  [leiden merge] -> 530 clusters (target 300)
  [leiden merge] -> 520 clusters (target 300)
  [leiden merge] -> 510 clusters (target 300)
  [leiden merge] -> 500 clusters (target 300)
  [leiden merge] -> 490 clusters (target 300)
  [leiden merge] -> 480 clusters (target 300)
  [leiden merge] -> 470 clusters (target 300)
  [leiden merge] -> 460 clusters (target 300)
  [leiden merge] -> 450 clusters (target 300)
  [leiden merge] -> 440 clusters (target 300)
  [leiden merge] -> 430 clusters (target 300)
  [leiden merge] -> 420 clusters (target 300)
  [leiden merge] -> 410 clusters (target 300)
  [leiden merge] -> 400 clusters (target 300)
  [leiden merge] -> 390 clusters (target 300)
  [leiden merge] -> 380 clusters (target 300)
  [leiden merge] -> 370 clusters (target 300)
  [leiden merge] -> 360 clusters (target 300)
  [leiden merge] -> 350 clusters (target 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_scvidef_K300] unused protos: 0/300 (0.00%)
[leiden_X_scvidef_K300] mean cell-type purity: 0.8502  (size-weighted: 0.8387 ± 0.1886)
[leiden_X_scvidef_K300] mean batch entropy: 1.1852  (size-weighted: 1.3897 ± 0.5404)
[leiden_X_scvidef_K300] coverage: 1.0000
[leiden_X_scvidef_K300] modularity: 0.5752
[leiden_X_scvidef_K300] per-batch modularity: mean=0.5224, std=0.0772
[aff_dc_compactness] looking for graph at: ./graphs/affinity_lung32472_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=2.2212 | saved to /content/drive/MyDrive/models/lung/leiden_X_scvidef_K300/aff_dc_compactness.csv
[leiden_X_scvidef_K300] saved metrics to /content/drive/MyDrive/models/lung/leiden_X_scvidef_K300
[/content/drive/MyDrive/models/lung/leiden_X_scvidef_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.52242725589041 +/- 0.07716638806597749 (was 0.52242725589041), K_target=300

100%|██████████| 300/300 [00:02<00:00, 134.48it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_scvidef: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_scvidef] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/lung/leiden_X_scvidef_K300
[lung] leiden-on-X_scvidef saved to /content/drive/MyDrive/models/lung/leiden_X_scvidef_K300

=== [lung] arm B: scProto Stage 2 on the same scVI encoder ===
[waypoint init] N=32472  K=300  n_eigs=10  nnz=2447924  nnz/row=75.4  w[min/mean/max]=1.367e-02/3.246e-01/9.491e-01  deg[min/mean/max]=5.25/24.47/119.30
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1452.72proto/s]

[waypoint init] selected 300 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/32 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 300/300 prototypes used (100.0%)  effective_n=131.1  top5_share=10.8%

  0%|          | 0/32 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3239 → epsilon=0.0042 (effk_mean=1.22 < 3.0), falling back to effk=5.0

  0%|          | 0/32 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0461 (mean_effk=5.00)
📊 EdgeDataset: 2447924 edges
   Weight range: [0.0137, 0.9491]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2447924 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 3 epochs, patience=6, max_epochs=20

  0%|          | 0/32 [00:00<?, ?it/s]

[proto] weighted modularity: 0.3418

  0%|          | 0/32 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.3418, coverage=1.0000 (17/17 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[3]] (3763 cells)

  0%|          | 0/32 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 500/500 [00:49<00:00, 10.05it/s]

>>> Epoch 1/~20 | loss=4.0117 | q+=0.405 | q-=0.047 | margin=0.359 | effk=2.2 | unused_proto=0 | bentropy=1.499 | proto_recon=105.7815 | nassoc=0.6810 [diag=0.214 offdiag=0.005] | proto_usage=7.6952

edges: 100%|██████████| 500/500 [00:49<00:00, 10.12it/s]

>>> Epoch 2/~20 | loss=3.6120 | q+=0.514 | q-=0.052 | margin=0.462 | effk=1.7 | unused_proto=0 | bentropy=1.300 | proto_recon=102.4183 | nassoc=0.6589 [diag=0.248 offdiag=0.004] | proto_usage=6.9208

edges: 100%|██████████| 500/500 [00:49<00:00, 10.12it/s]

>>> Epoch 3/~20 | loss=3.4263 | q+=0.530 | q-=0.050 | margin=0.480 | effk=1.6 | unused_proto=0 | bentropy=1.193 | proto_recon=101.4827 | nassoc=0.6367 [diag=0.268 offdiag=0.004] | proto_usage=5.8797

  0%|          | 0/32 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7274

  0%|          | 0/32 [00:00<?, ?it/s]

  [proto usage] 297/300 used (99.0%)  effective_n=62.9  top5_share=17.8%  community-preservation(mean neighbor agreement)=0.732
  [Early stop] modularity improved to 0.7274 (+0.3856), coverage=1.0000 (17/17) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[3]] (3763 cells)

  0%|          | 0/32 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 500/500 [00:49<00:00, 10.07it/s]

>>> Epoch 4/~20 | loss=3.3146 | q+=0.539 | q-=0.049 | margin=0.489 | effk=1.6 | unused_proto=0 | bentropy=1.114 | proto_recon=100.9740 | nassoc=0.6205 [diag=0.282 offdiag=0.004] | proto_usage=5.2581

edges: 100%|██████████| 500/500 [00:49<00:00, 10.18it/s]

>>> Epoch 5/~20 | loss=3.2408 | q+=0.543 | q-=0.048 | margin=0.494 | effk=1.5 | unused_proto=0 | bentropy=1.052 | proto_recon=100.6985 | nassoc=0.6085 [diag=0.291 offdiag=0.004] | proto_usage=4.8186

edges: 100%|██████████| 500/500 [00:49<00:00, 10.09it/s]

>>> Epoch 6/~20 | loss=3.1878 | q+=0.546 | q-=0.048 | margin=0.498 | effk=1.5 | unused_proto=0 | bentropy=1.014 | proto_recon=100.3010 | nassoc=0.5995 [diag=0.298 offdiag=0.003] | proto_usage=4.5437

  0%|          | 0/32 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7188

  0%|          | 0/32 [00:00<?, ?it/s]

  [proto usage] 300/300 used (100.0%)  effective_n=72.1  top5_share=15.1%  community-preservation(mean neighbor agreement)=0.722
  [Early stop] No improvement (0.7188 vs best 0.7274, min_delta=0.005), coverage=1.0000 (17/17), no-improve streak: 3/6

edges: 100%|██████████| 500/500 [00:48<00:00, 10.29it/s]

>>> Epoch 7/~20 | loss=3.1494 | q+=0.548 | q-=0.047 | margin=0.501 | effk=1.5 | unused_proto=0 | bentropy=0.978 | proto_recon=100.2608 | nassoc=0.5928 [diag=0.304 offdiag=0.003] | proto_usage=4.3202

edges: 100%|██████████| 500/500 [00:49<00:00, 10.08it/s]

>>> Epoch 8/~20 | loss=3.1186 | q+=0.549 | q-=0.047 | margin=0.502 | effk=1.5 | unused_proto=0 | bentropy=0.954 | proto_recon=100.0208 | nassoc=0.5882 [diag=0.307 offdiag=0.003] | proto_usage=4.1351

edges: 100%|██████████| 500/500 [00:49<00:00, 10.07it/s]

>>> Epoch 9/~20 | loss=3.0917 | q+=0.551 | q-=0.046 | margin=0.505 | effk=1.5 | unused_proto=0 | bentropy=0.932 | proto_recon=100.0038 | nassoc=0.5835 [diag=0.311 offdiag=0.003] | proto_usage=3.9859

  0%|          | 0/32 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7101

  0%|          | 0/32 [00:00<?, ?it/s]

  [proto usage] 300/300 used (100.0%)  effective_n=76.1  top5_share=14.5%  community-preservation(mean neighbor agreement)=0.713
  [Early stop] No improvement (0.7101 vs best 0.7274, min_delta=0.005), coverage=1.0000 (17/17), no-improve streak: 6/6
[Early stop] Patience exhausted. Stopping at epoch 9.

  0%|          | 0/32 [00:00<?, ?it/s]

Saved clusters (32472 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/lung/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'lung', 'cvae_epochs': 0, 'batch_size': 1024, 'latent_dims': 10, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'num_prototypes': 300, 'condition_key': 'batch'}
📊 EdgeDataset: 2447924 edges
   Weight range: [0.0137, 0.9491]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2447924 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/32 [00:00<?, ?it/s]

  0%|          | 0/32 [00:00<?, ?it/s]

Saved clusters (32472 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 3/300 (1.00%)
[proto] mean cell-type purity: 0.8722  (size-weighted: 0.9071 ± 0.1315)
[proto] mean batch entropy: 0.5589  (size-weighted: 0.9750 ± 0.6126)

  0%|          | 0/32 [00:00<?, ?it/s]

[proto] weighted modularity: 0.7274
[proto] per-batch modularity: mean=0.6501, std=0.0394

  0%|          | 0/32 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/16 [00:00<?, ?it/s]

Deleted: tmp_8904a8ee.h5ad
[task2] coverage: 1.0000
[task2] dge_rbo_avg: 0.0680
[task2] dge_kendall_avg: 0.1335
[task2] dge_jaccard_avg: 0.1721
[task2] scgraph_corr_avg: 0.8670
[task2] scgraph_corr_std: 0.0769

  0%|          | 0/32 [00:00<?, ?it/s]

[/content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31] modularity recomputed against canonical graph: mean_modularity_batch=0.6500688047317645 +/- 0.03941827865621239 (was 0.6500688047317645), K_target=300
[scvi stage2] metrics saved to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metrics.json
Dominant batch: [[3]] (3763 cells)

  0%|          | 0/32 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/32 [00:00<?, ?it/s]

  0%|          | 0/32 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

  0%|          | 0/32 [00:00<?, ?it/s]

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/32472 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/32472 [00:00<?, ?it/s]

Constructing CSR matrix...
[lung] embedding-level rare affinity purity saved to /content/drive/MyDrive/models/lung/scvi_stage2_affinity_purity_lung.json

[lung] done. Stage-2 run dir: /content/drive/MyDrive/models//lung/scviproto_ds-lung_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

======================================================================
=== pbmc-immune ===
======================================================================
dataset is None, loading pbmc-immune
loading pbmc-immune data
✅ Already subsetted to HVGs (4000 genes).
[pbmc-immune] counts check: max=73869, integer fraction=0.993
[pbmc-immune] adata.X set to log1p(counts) -- scVI's own encoder input space; raw counts kept in layers['counts'], log-normalised values in layers['lognorm'].
[scvi stage2] run dir: /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31
[scvi backbone] latent_dim=10  K=300  n_batches=5  ref_log_library=6.054  recon/kl terms=off

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

📊 Affinity: wdeg[min/mean/max]=1.667/25.923/299.545, effk_med=62.9, mutual=100.00%
adam

=== [pbmc-immune] Stage 1: scVI ===
[scvi stage1] training scVI (n_latent=10, gene_likelihood=zinb, max_epochs=50) on 33506 cells

Training:   0%|          | 0/50 [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=50` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=50` reached.

[scvi stage1] saved to /content/drive/MyDrive/models/pbmc-immune/scvi_stage1/d10_zinb_e50
[scvi stage1] weights loaded into the Stage-2 model
Saved pretrain checkpoint to /content/drive/MyDrive/models/pbmc-immune/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth

  0%|          | 0/33 [00:00<?, ?it/s]

[pbmc-immune] scVI latent: (33506, 10)

=== [pbmc-immune] arm A: scVI latent -> Leiden / SEACells ===
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] X_scvidef: rare-type kNN purity = {'mean_purity': 0.7878143133462284, 'n_rare_cells': 1034}
[waypoint init] N=33506  k=300  n_eigs=10  nnz=2412244  nnz/row=72.0
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1400.82archetype/s]

[waypoint init] selected 300 archetype seed cells
[SEACells backend] GPU detected but n_cells=33506 > 30000 -- forcing CPU+sparse anyway (GPU path is dense-only and would need a ~33506x33506 dense matrix, likely OOM)
[SEACells backend] using our own optimized sparse-CPU SEACells (never materializes kernel_matrix @ kernel_matrix.T)
Welcome to SEACells!
Using provided list of initial archetypes
Randomly initialized A matrix.
Setting convergence threshold at 295.70819
Starting iteration 1.
Completed iteration 1.
Starting iteration 10.
Completed iteration 10.
Converged after 17 iterations.

100%|██████████| 300/300 [00:02<00:00, 113.20it/s]

saving to:  /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef
  delta kept: X=yes, 1 layer(s), 0 varm, 1 obsm, 2 obsp, obs cols ['_scvi_batch', '_scvi_labels', 'SEACell']
  saved soft_assignments.npz (33506, 300) to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef ...
[seacell] unused protos: 0/300 (0.00%)
[seacell] mean cell-type purity: 0.8942  (size-weighted: 0.8924 ± 0.1337)
[seacell] mean batch entropy: 0.5267  (size-weighted: 0.7645 ± 0.4255)
[seacell] coverage: 1.0000
[seacell] modularity: 0.5563
[seacell] per-batch modularity: mean=0.5514, std=0.0596
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.8751 | saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef/aff_dc_compactness.csv
[seacell] saved metrics to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef
SEACell UMAP data saved to /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef
[pbmc-immune] canonical ARBF-on-PCA affinity graph loaded from ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl (nnz=2624382) -- caching for reuse across all methods for this dataset.
[/content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef] modularity recomputed against canonical graph: mean_modularity_batch=0.2404454198736566 +/- 0.12976296815012403 (was 0.5514194905547563), K_target=300
Loading SEACell from /content/drive/MyDrive/models/pbmc-immune/seacell_X_scvidef ...
Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_5e5fadd5.h5ad
[seacell task2] coverage: 1.0000
[seacell task2] scgraph_corr_avg: 0.7781
[seacell task2] scgraph_corr_std: 0.1208
  [leiden oversegment] resolution=1.0000 -> 17 clusters (need >= 300)
  [leiden oversegment] resolution=2.0000 -> 28 clusters (need >= 300)
  [leiden oversegment] resolution=4.0000 -> 45 clusters (need >= 300)
  [leiden oversegment] resolution=8.0000 -> 79 clusters (need >= 300)
  [leiden oversegment] resolution=16.0000 -> 171 clusters (need >= 300)
  [leiden oversegment] resolution=32.0000 -> 342 clusters (need >= 300)
  [leiden merge] -> 340 clusters (target 300)
  [leiden merge] -> 330 clusters (target 300)
  [leiden merge] -> 320 clusters (target 300)
  [leiden merge] -> 310 clusters (target 300)
  [leiden merge] -> 305 clusters (target 300)
  [leiden merge] -> 304 clusters (target 300)
  [leiden merge] -> 303 clusters (target 300)
  [leiden merge] -> 302 clusters (target 300)
  [leiden merge] -> 301 clusters (target 300)
  [leiden merge] -> 300 clusters (target 300)
[leiden merge-down] final: 300 clusters (target 300)
[leiden_X_scvidef_K300] unused protos: 0/300 (0.00%)
[leiden_X_scvidef_K300] mean cell-type purity: 0.8677  (size-weighted: 0.8925 ± 0.1333)
[leiden_X_scvidef_K300] mean batch entropy: 0.8061  (size-weighted: 0.7824 ± 0.4087)
[leiden_X_scvidef_K300] coverage: 1.0000
[leiden_X_scvidef_K300] modularity: 0.3294
[leiden_X_scvidef_K300] per-batch modularity: mean=0.3644, std=0.1829
[aff_dc_compactness] looking for graph at: ./graphs/affinity_pbmc-immune33506_ncomp50_kneighbors50_arbf.pkl
[aff_dc_compactness] mean=0.5665 | saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvidef_K300/aff_dc_compactness.csv
[leiden_X_scvidef_K300] saved metrics to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvidef_K300
[/content/drive/MyDrive/models/pbmc-immune/leiden_X_scvidef_K300] modularity recomputed against canonical graph: mean_modularity_batch=0.3643792462156715 +/- 0.18285786867864307 (was 0.3643792462156715), K_target=300

100%|██████████| 300/300 [00:02<00:00, 141.55it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: task2 failed for leiden_X_scvidef: ValueError: XA must be a 2-dimensional array. -- keeping task1 results, continuing.
[leiden_X_scvidef] umap_cells.csv / umap_protos.csv saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvidef_K300
[pbmc-immune] leiden-on-X_scvidef saved to /content/drive/MyDrive/models/pbmc-immune/leiden_X_scvidef_K300

=== [pbmc-immune] arm B: scProto Stage 2 on the same scVI encoder ===
[waypoint init] N=33506  K=300  n_eigs=10  nnz=2590876  nnz/row=77.3  w[min/mean/max]=1.473e-03/3.352e-01/9.224e-01  deg[min/mean/max]=1.67/25.92/299.54
[waypoint init] computing diffusion map ...
[waypoint init] diffusion map done — 10 eigenvectors

waypoint MaxMin: 100%|██████████| 299/299 [00:00<00:00, 1404.00proto/s]

[waypoint init] selected 300 seed cells

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/33 [00:00<?, ?it/s]

[waypoint init] post-init hard assignment (before any training): 300/300 prototypes used (100.0%)  effective_n=73.3  top5_share=17.1%

  0%|          | 0/33 [00:00<?, ?it/s]

[eps calibration] E[p_pos]=0.3350 unreachable (max E[q_pos]=0.2455), falling back to effk=5.0

  0%|          | 0/33 [00:00<?, ?it/s]

[effk calibration] target_effk=5.0 → epsilon=0.0450 (mean_effk=5.00)
📊 EdgeDataset: 2590828 edges
   Weight range: [0.0050, 0.9224]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2590828 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Early stopping mode: metric=modularity, eval every 3 epochs, patience=6, max_epochs=20

  0%|          | 0/33 [00:00<?, ?it/s]

[proto] weighted modularity: 0.2512

  0%|          | 0/33 [00:00<?, ?it/s]

[Epoch 0] initial modularity=0.2512, coverage=1.0000 (16/16 cell types) → saving as baseline checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 0)
Dominant batch: [[0]] (10727 cells)

  0%|          | 0/33 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 500/500 [00:27<00:00, 18.25it/s]

>>> Epoch 1/~20 | loss=9.0003 | q+=0.421 | q-=0.064 | margin=0.356 | effk=2.1 | unused_proto=0 | bentropy=0.838 | proto_recon=543.8641 | nassoc=0.8306 [diag=0.108 offdiag=0.003] | proto_usage=11.7005

edges: 100%|██████████| 500/500 [00:27<00:00, 18.31it/s]

>>> Epoch 2/~20 | loss=8.6349 | q+=0.507 | q-=0.065 | margin=0.441 | effk=1.7 | unused_proto=0 | bentropy=0.729 | proto_recon=541.0341 | nassoc=0.8295 [diag=0.117 offdiag=0.002] | proto_usage=10.9665

edges: 100%|██████████| 500/500 [00:27<00:00, 18.35it/s]

>>> Epoch 3/~20 | loss=8.4139 | q+=0.524 | q-=0.063 | margin=0.462 | effk=1.6 | unused_proto=0 | bentropy=0.666 | proto_recon=536.6831 | nassoc=0.8231 [diag=0.123 offdiag=0.002] | proto_usage=9.7883

  0%|          | 0/33 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6741

  0%|          | 0/33 [00:00<?, ?it/s]

  [proto usage] 293/300 used (97.7%)  effective_n=19.1  top5_share=39.5%  community-preservation(mean neighbor agreement)=0.722
  [coverage] missing (no prototype's majority label): ['CD8+ T cells']
  [Early stop] modularity improved to 0.6741 (+0.4229), coverage=0.9375 (15/16) → saving checkpoint
Saved UMAP checkpoint to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)
Dominant batch: [[0]] (10727 cells)

  0%|          | 0/33 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

edges: 100%|██████████| 500/500 [00:27<00:00, 18.38it/s]

>>> Epoch 4/~20 | loss=8.2843 | q+=0.532 | q-=0.061 | margin=0.471 | effk=1.6 | unused_proto=0 | bentropy=0.623 | proto_recon=535.0959 | nassoc=0.8186 [diag=0.128 offdiag=0.002] | proto_usage=8.9317

edges: 100%|██████████| 500/500 [00:27<00:00, 18.45it/s]

>>> Epoch 5/~20 | loss=8.1553 | q+=0.537 | q-=0.059 | margin=0.478 | effk=1.6 | unused_proto=0 | bentropy=0.592 | proto_recon=529.3659 | nassoc=0.8140 [diag=0.131 offdiag=0.002] | proto_usage=8.4523

edges: 100%|██████████| 500/500 [00:27<00:00, 18.39it/s]

>>> Epoch 6/~20 | loss=8.1771 | q+=0.541 | q-=0.059 | margin=0.482 | effk=1.6 | unused_proto=0 | bentropy=0.563 | proto_recon=537.3437 | nassoc=0.8112 [diag=0.133 offdiag=0.002] | proto_usage=8.0024

  0%|          | 0/33 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6711

  0%|          | 0/33 [00:00<?, ?it/s]

  [proto usage] 297/300 used (99.0%)  effective_n=20.8  top5_share=36.7%  community-preservation(mean neighbor agreement)=0.716
  [coverage] missing (no prototype's majority label): ['CD8+ T cells']
  [Early stop] No improvement (0.6711 vs best 0.6741, min_delta=0.005), coverage=0.9375 (15/16), no-improve streak: 3/6

edges: 100%|██████████| 500/500 [00:27<00:00, 18.44it/s]

>>> Epoch 7/~20 | loss=8.1436 | q+=0.544 | q-=0.059 | margin=0.486 | effk=1.6 | unused_proto=0 | bentropy=0.541 | proto_recon=538.6767 | nassoc=0.8084 [diag=0.135 offdiag=0.002] | proto_usage=7.6585

edges: 100%|██████████| 500/500 [00:27<00:00, 18.36it/s]

>>> Epoch 8/~20 | loss=8.0214 | q+=0.545 | q-=0.058 | margin=0.487 | effk=1.6 | unused_proto=0 | bentropy=0.527 | proto_recon=529.8248 | nassoc=0.8060 [diag=0.137 offdiag=0.002] | proto_usage=7.3859

edges: 100%|██████████| 500/500 [00:27<00:00, 18.42it/s]

>>> Epoch 9/~20 | loss=8.0494 | q+=0.546 | q-=0.058 | margin=0.488 | effk=1.6 | unused_proto=0 | bentropy=0.511 | proto_recon=535.3818 | nassoc=0.8037 [diag=0.138 offdiag=0.002] | proto_usage=7.1575

  0%|          | 0/33 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6690

  0%|          | 0/33 [00:00<?, ?it/s]

  [proto usage] 300/300 used (100.0%)  effective_n=21.4  top5_share=36.4%  community-preservation(mean neighbor agreement)=0.713
  [coverage] missing (no prototype's majority label): ['CD8+ T cells']
  [Early stop] No improvement (0.6690 vs best 0.6741, min_delta=0.005), coverage=0.9375 (15/16), no-improve streak: 6/6
[Early stop] Patience exhausted. Stopping at epoch 9.

  0%|          | 0/33 [00:00<?, ?it/s]

Saved clusters (33506 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
Loaded pretrain checkpoint from /content/drive/MyDrive/models/pbmc-immune/pretrain_scvi/d10_zinb_e50/pretrain_checkpoint.pth
  pretrain_params: {'dataset_id': 'pbmc-immune', 'cvae_epochs': 0, 'batch_size': 1024, 'latent_dims': 10, 'l2norm': 1, 'model_type': 'gm', 'beta': 0.3, 'num_prototypes': 300, 'condition_key': 'study'}
📊 EdgeDataset: 2590828 edges
   Weight range: [0.0050, 0.9224]
   umap_steps_per_epoch=500 → 512000 edges/epoch (of 2590828 total)
📐 UMAP kernel: min_dist=0.5, spread=1.0 -> a=0.5830, b=1.3342
Starting edge-centric UMAP training (similarity=proto)
   min_dist=0.5, spread=1.0, neg_rate=5
   lambda_umap=1, lambda_recon=0, lambda_kl=0, lambda_proto_recon=0.01, lambda_r1r2=0.0
   nassoc: λ=1, agg=max, diag=ON [(m-1)²], offdiag=[m²]
Loaded UMAP checkpoint from /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/umap_checkpoint.pth (epoch 3)

  0%|          | 0/33 [00:00<?, ?it/s]

  0%|          | 0/33 [00:00<?, ?it/s]

Saved clusters (33506 cells, label='proto') and 2 metrics to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/clusters.npz
[proto] unused protos: 7/300 (2.33%)
[proto] mean cell-type purity: 0.8930  (size-weighted: 0.8724 ± 0.1346)
[proto] mean batch entropy: 0.2231  (size-weighted: 0.8730 ± 0.4807)

  0%|          | 0/33 [00:00<?, ?it/s]

[proto] weighted modularity: 0.6741
[proto] per-batch modularity: mean=0.6181, std=0.0593

  0%|          | 0/33 [00:00<?, ?it/s]

Processing batches, calcualte centroids and pairwise distances

  0%|          | 0/5 [00:00<?, ?it/s]

Deleted: tmp_2332d9df.h5ad
[task2] coverage: 0.9375
[task2] dge_rbo_avg: 0.0978
[task2] dge_kendall_avg: 0.1194
[task2] dge_jaccard_avg: 0.1603
[task2] scgraph_corr_avg: 0.7367
[task2] scgraph_corr_std: 0.1177

  0%|          | 0/33 [00:00<?, ?it/s]

[/content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31] modularity recomputed against canonical graph: mean_modularity_batch=0.6180656389148225 +/- 0.05932137873358251 (was 0.6180656389148225), K_target=300
[scvi stage2] metrics saved to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metrics.json
Dominant batch: [[0]] (10727 cells)

  0%|          | 0/33 [00:00<?, ?it/s]

Saved metacells (300 prototypes) to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31/metacells.h5ad

  0%|          | 0/33 [00:00<?, ?it/s]

  0%|          | 0/33 [00:00<?, ?it/s]

UMAP data saved to /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

  0%|          | 0/33 [00:00<?, ?it/s]

Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
Computing kNN graph using scanpy NN ...
Computing radius for adaptive bandwidth kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Making graph symmetric...
Parameter graph_construction = union being used to build KNN graph...
Computing RBF kernel...

  0%|          | 0/33506 [00:00<?, ?it/s]

Building similarity LIL matrix...

  0%|          | 0/33506 [00:00<?, ?it/s]

Constructing CSR matrix...
[pbmc-immune] embedding-level rare affinity purity saved to /content/drive/MyDrive/models/pbmc-immune/scvi_stage2_affinity_purity_pbmc-immune.json

[pbmc-immune] done. Stage-2 run dir: /content/drive/MyDrive/models//pbmc-immune/scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp_v31

finished: ['pancreas', 'lung', 'pbmc-immune']  failed: []

In [28]:
# OPTIONAL control (off by default -- one extra Leiden run per dataset).
#
# Arm B trains on the unit sphere (l2norm=1, dot-product assignment) because that is
# scProto's own Stage-2 recipe from the paper, while arm A clusters scVI's latent
# as-is, the way anyone using scVI would. Flip this on to also cluster the L2-normalised
# scVI latent, which rules out "the difference is just the normalisation".
# Tag 'X_scvil2' deliberately does not start with 'X_scvidef' -- a prefix-colliding tag
# would make the 'leiden_X_scvidef' keyword ambiguous in the tables below.
RUN_L2NORM_CONTROL = False

if RUN_L2NORM_CONTROL:
    for ds in DATASETS_TO_RUN:
        res = RESULTS.get(ds)
        if res is None:
            continue
        t_ds = res['trainer']
        run_scvi_clustering_baselines(
            t_ds, t_ds.get_latent(l2norm=True), tag='X_scvil2',
            run_seacells=False, run_leiden=True, skip_if_exists=True,
        )

## Results

One keyword set covers all datasets: `extract_model_key` strips the dataset-specific tokens (`_ds-*`, `_NP*`, `_v*`) so each dataset's Stage-2 run maps to the same row, and the Leiden keyword omits `_K{n}` because K differs per dataset.

The canonical scProto runs (scPoli Stage 1, d=8) are included for context only — a different Stage 1 and a different latent dimension, so the controlled comparison is the three scVI rows among themselves.

In [29]:
_first = next((r for r in RESULTS.values() if r is not None), None)
assert _first is not None, "no dataset finished -- nothing to summarise"

MODEL_KEYWORDS = resolve_run_names(_first['run_dir'], include_canonical=True)
MODEL_KEYWORDS

{'seacell_X_scvidef': 'SEACells (scVI)',
 'leiden_X_scvidef': 'Leiden (scVI)',
 'scviproto_LD10_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp': 'scProto Stage 2 (scVI)',
 'proto_umap_prtInit-wayp_aff-arbf_lprec0.01_usim-prot_ecal1_lpu0.1_pum-ema_lna1_nagg-max_upm-dotp': 'scProto (scPoli Stage 1)'}

In [30]:
df_rare = rare_celltype_purity_table(DATASETS_TO_RUN, model_keywords=MODEL_KEYWORDS, verbose=False)

_dupe = df_rare.index.duplicated(keep='first')
if _dupe.any():
    print(f"WARNING: dropped {_dupe.sum()} duplicate row(s): {df_rare.index[_dupe].tolist()}")
    df_rare = df_rare[~_dupe]

show_table(
    df_rare,
    metrics=[
        'batch_rare_coverage_mean', 'batch_rare_recall_macro_mean',
        'batch_rare_precision_macro_mean', 'batch_rare_homogeneity_mean',
        'batch_rare_cross_batch_homog_mean', 'batch_rare_f1_macro_mean',
    ],
    dataset_display_names=dataset_display_names,
)

  [SEACells (scVI)|pancreas] resolving run dir ...
  [Leiden (scVI)|pancreas] resolving run dir ...
  [scProto Stage 2 (scVI)|pancreas] resolving run dir ...
  [scProto (scPoli Stage 1)|pancreas] resolving run dir ...
  [SEACells (scVI)|lung] resolving run dir ...
  [Leiden (scVI)|lung] resolving run dir ...
  [scProto Stage 2 (scVI)|lung] resolving run dir ...
  [scProto (scPoli Stage 1)|lung] resolving run dir ...
  [SEACells (scVI)|lung] run dir resolved (0.1s)
  [Leiden (scVI)|lung] run dir resolved (0.1s)
  [scProto Stage 2 (scVI)|lung] run dir resolved (0.1s)
  [SEACells (scVI)|lung] reading umap_cells.csv ...
  [Leiden (scVI)|lung] reading umap_cells.csv ...
  [scProto Stage 2 (scVI)|lung] reading umap_cells.csv ...
  [SEACells (scVI)|lung] umap_cells.csv loaded (32472 rows, 0.0s)
  [SEACells (scVI)|lung] reading umap_protos.csv ...
  [Leiden (scVI)|lung] umap_cells.csv loaded (32472 rows, 0.1s)
  [Leiden (scVI)|lung] reading umap_protos.csv ...  [scProto Stage 2 (scVI)|lung] umap_cells.csv loaded (32472 rows, 0.1s)

  [SEACells (scVI)|lung] umap_protos.csv loaded (0.0s)
  [scProto Stage 2 (scVI)|lung] reading umap_protos.csv ...
  [SEACells (scVI)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [SEACells (scVI)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (scVI)|pancreas] run dir resolved (0.2s)
  [scProto Stage 2 (scVI)|pancreas] run dir resolved (0.2s)
  [Leiden (scVI)|pancreas] run dir resolved (0.2s)
  [SEACells (scVI)|pancreas] reading umap_cells.csv ...
  [scProto Stage 2 (scVI)|pancreas] reading umap_cells.csv ...
  [Leiden (scVI)|lung] umap_protos.csv loaded (0.0s)
  [scProto (scPoli Stage 1)|pancreas] run dir resolved (0.2s)
  [Leiden (scVI)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto Stage 2 (scVI)|lung] umap_protos.csv loaded (0.0s)
  [scProto (scPoli Stage 1)|pancreas] reading umap_cells.csv ...
  [Leiden (scVI)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [Leiden (scVI)|pancreas] reading umap_cells.csv ...
  [scProto Stage 2 (scVI)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto Stage 2 (scVI)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [SEACells (scVI)|lung] label fractions done (0.0s)
  [Leiden (scVI)|lung] label fractions done (0.0s)
  [scProto Stage 2 (scVI)|lung] label fractions done (0.0s)
  [SEACells (scVI)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [SEACells (scVI)|pancreas] reading umap_protos.csv ...
  [scProto Stage 2 (scVI)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [scProto (scPoli Stage 1)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [scProto Stage 2 (scVI)|pancreas] reading umap_protos.csv ...
  [scProto (scPoli Stage 1)|pancreas] reading umap_protos.csv ...
  [Leiden (scVI)|pancreas] umap_cells.csv loaded (16382 rows, 0.1s)
  [Leiden (scVI)|pancreas] reading umap_protos.csv ...
  [scProto Stage 2 (scVI)|pancreas] umap_protos.csv loaded (0.0s)
  [scProto (scPoli Stage 1)|pancreas] umap_protos.csv loaded (0.0s)
  [scProto Stage 2 (scVI)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [scProto Stage 2 (scVI)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [SEACells (scVI)|pancreas] umap_protos.csv loaded (0.0s)
  [scProto (scPoli Stage 1)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (scVI)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [SEACells (scVI)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [scProto (scPoli Stage 1)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [Leiden (scVI)|pancreas] umap_protos.csv loaded (0.0s)
  [Leiden (scVI)|pancreas] batch='tech' | 9 unique values, e.g. ['celseq', 'celseq2', 'fluidigmc1', 'inDrop1', 'inDrop2']
  [Leiden (scVI)|pancreas] label='celltype', batch='tech' | computing metacell label fractions ...
  [scProto Stage 2 (scVI)|pancreas] label fractions done (0.1s)
  [scProto (scPoli Stage 1)|lung] run dir resolved (0.4s)
  [scProto (scPoli Stage 1)|lung] reading umap_cells.csv ...  [scProto (scPoli Stage 1)|pancreas] label fractions done (0.1s)

  [SEACells (scVI)|pancreas] label fractions done (0.2s)
  [SEACells (scVI)|lung] done
  [SEACells (scVI)|pbmc-immune] resolving run dir ...
  [Leiden (scVI)|pancreas] label fractions done (0.4s)
  [Leiden (scVI)|lung] done
  [Leiden (scVI)|pbmc-immune] resolving run dir ...
  [scProto Stage 2 (scVI)|lung] done
  [scProto Stage 2 (scVI)|pbmc-immune] resolving run dir ...
  [scProto Stage 2 (scVI)|pancreas] done
  [scProto (scPoli Stage 1)|lung] umap_cells.csv loaded (32472 rows, 0.6s)
  [scProto (scPoli Stage 1)|pbmc-immune] resolving run dir ...
  [scProto (scPoli Stage 1)|lung] reading umap_protos.csv ...
  [SEACells (scVI)|pancreas] done
  [scProto (scPoli Stage 1)|pancreas] done
  [Leiden (scVI)|pancreas] done
  [SEACells (scVI)|pbmc-immune] run dir resolved (0.7s)
  [SEACells (scVI)|pbmc-immune] reading umap_cells.csv ...
  [Leiden (scVI)|pbmc-immune] run dir resolved (0.5s)
  [Leiden (scVI)|pbmc-immune] reading umap_cells.csv ...
  [scProto Stage 2 (scVI)|pbmc-immune] run dir resolved (0.4s)
  [scProto Stage 2 (scVI)|pbmc-immune] reading umap_cells.csv ...
  [SEACells (scVI)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)
  [SEACells (scVI)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (scVI)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)
  [SEACells (scVI)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [Leiden (scVI)|pbmc-immune] reading umap_protos.csv ...
  [SEACells (scVI)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [SEACells (scVI)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [scProto Stage 2 (scVI)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.1s)
  [scProto Stage 2 (scVI)|pbmc-immune] reading umap_protos.csv ...
  [Leiden (scVI)|pbmc-immune] umap_protos.csv loaded (0.0s)
  [Leiden (scVI)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']  [scProto Stage 2 (scVI)|pbmc-immune] umap_protos.csv loaded (0.0s)

  [Leiden (scVI)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [scProto Stage 2 (scVI)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [scProto Stage 2 (scVI)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [SEACells (scVI)|pbmc-immune] label fractions done (0.0s)
  [scProto Stage 2 (scVI)|pbmc-immune] label fractions done (0.0s)
  [Leiden (scVI)|pbmc-immune] label fractions done (0.0s)
  [SEACells (scVI)|pbmc-immune] done
  [scProto (scPoli Stage 1)|pbmc-immune] run dir resolved (0.6s)
  [scProto (scPoli Stage 1)|pbmc-immune] reading umap_cells.csv ...
  [scProto Stage 2 (scVI)|pbmc-immune] done
  [Leiden (scVI)|pbmc-immune] done
  [scProto (scPoli Stage 1)|pbmc-immune] umap_cells.csv loaded (33506 rows, 0.3s)
  [scProto (scPoli Stage 1)|lung] umap_protos.csv loaded (0.9s)
  [scProto (scPoli Stage 1)|pbmc-immune] reading umap_protos.csv ...
  [scProto (scPoli Stage 1)|lung] batch='batch' | 16 unique values, e.g. ['1', '2', '3', '4', '5']
  [scProto (scPoli Stage 1)|lung] label='cell_type', batch='batch' | computing metacell label fractions ...
  [scProto (scPoli Stage 1)|lung] label fractions done (0.0s)
  [scProto (scPoli Stage 1)|lung] done
  [scProto (scPoli Stage 1)|pbmc-immune] umap_protos.csv loaded (0.3s)
  [scProto (scPoli Stage 1)|pbmc-immune] batch='study' | 5 unique values, e.g. ['10X', 'Freytag', 'Oetjen', 'Sun', 'Villani']
  [scProto (scPoli Stage 1)|pbmc-immune] label='final_annotation', batch='study' | computing metacell label fractions ...
  [scProto (scPoli Stage 1)|pbmc-immune] label fractions done (0.0s)
  [scProto (scPoli Stage 1)|pbmc-immune] done

In [31]:
# Mean +/- std across batches, per dataset, for the two headline rare metrics.
for metric in ['batch_rare_f1_macro', 'batch_rare_homogeneity']:
    rows = []
    for (ds, run) in df_rare.index:
        vals = np.asarray(df_rare.loc[(ds, run), f'_{metric}_per_batch'], dtype=float)
        rows.append({'dataset': dataset_display_names.get(ds, ds), 'method': run,
                     'n_batches': len(vals),
                     'mean': round(float(vals.mean()), 3),
                     'std': round(float(vals.std()), 3),
                     'median': round(float(np.median(vals)), 3)})
    print(f"=== {metric} (mean +/- std across batches) ===")
    display(pd.DataFrame(rows).pivot(index='method', columns='dataset',
                                     values=['mean', 'std', 'n_batches']))

=== batch_rare_f1_macro (mean +/- std across batches) ===

                           mean                    std                  \
dataset                  Immune   Lung Pancreas Immune   Lung Pancreas
method
Leiden (scVI)             0.855  0.689    0.258  0.108  0.167    0.276
SEACells (scVI)           0.892  0.682    0.639  0.049  0.162    0.196
scProto (scPoli Stage 1)  0.854  0.599    0.535  0.138  0.176    0.208
scProto Stage 2 (scVI)    0.897  0.557    0.614  0.030  0.255    0.218

                         n_batches
dataset                     Immune  Lung Pancreas
method
Leiden (scVI)                  5.0  15.0      8.0
SEACells (scVI)                5.0  15.0      8.0
scProto (scPoli Stage 1)       5.0  15.0      8.0
scProto Stage 2 (scVI)         5.0  15.0      8.0

=== batch_rare_homogeneity (mean +/- std across batches) ===

                           mean                    std                  \
dataset                  Immune   Lung Pancreas Immune   Lung Pancreas
method
Leiden (scVI)             0.729  0.635    0.317  0.158  0.182    0.242
SEACells (scVI)           0.819  0.658    0.588  0.082  0.180    0.180
scProto (scPoli Stage 1)  0.827  0.578    0.565  0.102  0.221    0.155
scProto Stage 2 (scVI)    0.859  0.560    0.601  0.064  0.257    0.173

                         n_batches
dataset                     Immune  Lung Pancreas
method
Leiden (scVI)                  5.0  15.0      8.0
SEACells (scVI)                5.0  15.0      8.0
scProto (scPoli Stage 1)       5.0  15.0      8.0
scProto Stage 2 (scVI)         5.0  15.0      8.0

In [32]:
# Paired one-sided Wilcoxon (scProto Stage 2 > baseline) on the same batches,
# Bonferroni-corrected per dataset.
df_sig = rare_metric_significance_paired(
    df_rare,
    ref_name='scProto Stage 2 (scVI)',
    metrics=(
        '_batch_rare_f1_macro_per_batch',
        '_batch_rare_homogeneity_per_batch',
        '_batch_rare_cross_batch_homog_per_batch',
    ),
    dataset_display_names=dataset_display_names,
)

for metric_name in df_sig['metric'].unique():
    print(f"=== {metric_name}: scProto Stage 2 (scVI) vs. each same-K arm, PAIRED "
          f"one-sided Wilcoxon, Bonferroni-corrected ===")
    sub = df_sig[df_sig['metric'] == metric_name].copy()
    sub['cell'] = sub.apply(
        lambda r: f"{r['mean']:.3f}+/-{r['std']:.3f} (K={r['k']}, n={r['n']}) [ref]"
        if r['method'] == 'scProto Stage 2 (scVI)'
        else f"{r['mean']:.3f}+/-{r['std']:.3f} (K={r['k']}, n={r['n']}, "
             f"wins={r.get('n_wins', '?')}/{r['n']})  {r.get('sig', '?')}  "
             f"p_adj={r.get('p_adj', float('nan')):.3g}",
        axis=1,
    )
    display(sub.pivot(index='method', columns='dataset', values='cell'))

df_sig

=== batch_rare_f1_macro: scProto Stage 2 (scVI) vs. each same-K arm, PAIRED one-sided Wilcoxon, Bonferroni-corrected ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (scVI),"0.855+/-0.108 (K=300, n=5, wins=4.0/5) ns p_...","0.689+/-0.167 (K=300, n=15, wins=4.0/15) ns ...","0.258+/-0.276 (K=220, n=8, wins=8.0/8) * p_a..."
SEACells (scVI),"0.892+/-0.049 (K=300, n=5, wins=3.0/5) ns p_...","0.682+/-0.162 (K=300, n=15, wins=1.0/15) ns ...","0.639+/-0.196 (K=220, n=8, wins=3.0/8) ns p_..."
scProto (scPoli Stage 1),"0.854+/-0.138 (K=294, n=5, wins=2.0/5) ns p_...","0.599+/-0.176 (K=298, n=15, wins=8.0/15) ns ...","0.535+/-0.208 (K=219, n=8, wins=6.0/8) ns p_..."
scProto Stage 2 (scVI),"0.897+/-0.030 (K=293, n=5) [ref]","0.557+/-0.255 (K=297, n=15) [ref]","0.614+/-0.218 (K=220, n=8) [ref]"

=== batch_rare_homogeneity: scProto Stage 2 (scVI) vs. each same-K arm, PAIRED one-sided Wilcoxon, Bonferroni-corrected ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (scVI),"0.729+/-0.158 (K=300, n=5, wins=5.0/5) ns p_...","0.635+/-0.182 (K=300, n=15, wins=4.0/15) ns ...","0.317+/-0.242 (K=220, n=8, wins=8.0/8) * p_a..."
SEACells (scVI),"0.819+/-0.082 (K=300, n=5, wins=4.0/5) ns p_...","0.658+/-0.180 (K=300, n=15, wins=2.0/15) ns ...","0.588+/-0.180 (K=220, n=8, wins=3.0/8) ns p_..."
scProto (scPoli Stage 1),"0.827+/-0.102 (K=294, n=5, wins=4.0/5) ns p_...","0.578+/-0.221 (K=298, n=15, wins=7.0/15) ns ...","0.565+/-0.155 (K=219, n=8, wins=5.0/8) ns p_..."
scProto Stage 2 (scVI),"0.859+/-0.064 (K=293, n=5) [ref]","0.560+/-0.257 (K=297, n=15) [ref]","0.601+/-0.173 (K=220, n=8) [ref]"

=== batch_rare_cross_batch_homog: scProto Stage 2 (scVI) vs. each same-K arm, PAIRED one-sided Wilcoxon, Bonferroni-corrected ===

dataset,Immune,Lung,Pancreas
method,,,
Leiden (scVI),"0.407+/-0.208 (K=300, n=5, wins=2.0/5) ns p_...","0.597+/-0.159 (K=300, n=15, wins=3.0/15) ns ...","0.237+/-0.146 (K=220, n=8, wins=4.0/8) ns p_..."
SEACells (scVI),"0.335+/-0.194 (K=300, n=5, wins=2.0/5) ns p_...","0.598+/-0.154 (K=300, n=15, wins=3.0/15) ns ...","0.411+/-0.123 (K=220, n=8, wins=0.0/8) ns p_..."
scProto (scPoli Stage 1),"0.349+/-0.198 (K=294, n=5, wins=3.0/5) ns p_...","0.508+/-0.197 (K=298, n=15, wins=6.0/15) ns ...","0.323+/-0.179 (K=219, n=8, wins=2.0/8) ns p_..."
scProto Stage 2 (scVI),"0.303+/-0.195 (K=293, n=5) [ref]","0.466+/-0.242 (K=297, n=15) [ref]","0.205+/-0.133 (K=220, n=8) [ref]"

,dataset,metric,method,k,n,median,mean,std,n_wins,p_vs_ref,p_adj,sig
0,Pancreas,batch_rare_f1_macro,SEACells (scVI),220,8,0.682488,0.638570,0.196148,3.0,0.808594,1.000000,ns
1,Pancreas,batch_rare_f1_macro,Leiden (scVI),220,8,0.185185,0.257980,0.276038,8.0,0.003906,0.011719,*
2,Pancreas,batch_rare_f1_macro,scProto Stage 2 (scVI),220,8,0.596716,0.613513,0.217825,NaN,NaN,NaN,NaN
3,Pancreas,batch_rare_f1_macro,scProto (scPoli Stage 1),219,8,0.437680,0.535403,0.207961,6.0,0.156250,0.468750,ns
4,Pancreas,batch_rare_homogeneity,SEACells (scVI),220,8,0.600245,0.588033,0.179627,3.0,0.628906,1.000000,ns
5,Pancreas,batch_rare_homogeneity,Leiden (scVI),220,8,0.248668,0.316738,0.242439,8.0,0.003906,0.011719,*
6,Pancreas,batch_rare_homogeneity,scProto Stage 2 (scVI),220,8,0.604024,0.600766,0.173070,NaN,NaN,NaN,NaN
7,Pancreas,batch_rare_homogeneity,scProto (scPoli Stage 1),219,8,0.522129,0.564854,0.155263,5.0,0.230469,0.691406,ns
8,Pancreas,batch_rare_cross_batch_homog,SEACells (scVI),220,8,0.404908,0.411440,0.122933,0.0,1.000000,1.000000,ns
9,Pancreas,batch_rare_cross_batch_homog,Leiden (scVI),220,8,0.209340,0.236849,0.146107,4.0,0.527344,1.000000,ns
10,Pancreas,batch_rare_cross_batch_homog,scProto Stage 2 (scVI),220,8,0.245973,0.204703,0.133133,NaN,NaN,NaN,NaN
11,Pancreas,batch_rare_cross_batch_homog,scProto (scPoli Stage 1),219,8,0.259411,0.322859,0.179414,2.0,0.945312,1.000000,ns
12,Lung,batch_rare_f1_macro,SEACells (scVI),300,15,0.683658,0.682061,0.161787,1.0,0.999573,1.000000,ns
13,Lung,batch_rare_f1_macro,Leiden (scVI),300,15,0.699703,0.689003,0.167313,4.0,0.994873,1.000000,ns
14,Lung,batch_rare_f1_macro,scProto Stage 2 (scVI),297,15,0.599777,0.557474,0.255121,NaN,NaN,NaN,NaN
15,Lung,batch_rare_f1_macro,scProto (scPoli Stage 1),298,15,0.610777,0.599348,0.175935,8.0,0.719299,1.000000,ns
16,Lung,batch_rare_homogeneity,SEACells (scVI),300,15,0.625275,0.658057,0.179722,2.0,0.999695,1.000000,ns
17,Lung,batch_rare_homogeneity,Leiden (scVI),300,15,0.585769,0.635485,0.181924,4.0,0.989227,1.000000,ns
18,Lung,batch_rare_homogeneity,scProto Stage 2 (scVI),297,15,0.530682,0.560154,0.256962,NaN,NaN,NaN,NaN
19,Lung,batch_rare_homogeneity,scProto (scPoli Stage 1),298,15,0.586120,0.577994,0.220956,7.0,0.737762,1.000000,ns
20,Lung,batch_rare_cross_batch_homog,SEACells (scVI),300,15,0.582804,0.598188,0.153844,3.0,0.999237,1.000000,ns
21,Lung,batch_rare_cross_batch_homog,Leiden (scVI),300,15,0.577642,0.597256,0.158949,3.0,0.998688,1.000000,ns
22,Lung,batch_rare_cross_batch_homog,scProto Stage 2 (scVI),297,15,0.430215,0.466453,0.242446,NaN,NaN,NaN,NaN
23,Lung,batch_rare_cross_batch_homog,scProto (scPoli Stage 1),298,15,0.509701,0.508327,0.196956,6.0,0.932312,1.000000,ns
24,Immune,batch_rare_f1_macro,SEACells (scVI),300,5,0.870241,0.891524,0.048627,3.0,0.406250,1.000000,ns
25,Immune,batch_rare_f1_macro,Leiden (scVI),300,5,0.881720,0.854861,0.107646,4.0,0.218750,0.656250,ns
26,Immune,batch_rare_f1_macro,scProto Stage 2 (scVI),293,5,0.894253,0.897220,0.029541,NaN,NaN,NaN,NaN
27,Immune,batch_rare_f1_macro,scProto (scPoli Stage 1),294,5,0.896681,0.854140,0.138252,2.0,0.687500,1.000000,ns
28,Immune,batch_rare_homogeneity,SEACells (scVI),300,5,0.846697,0.819451,0.081737,4.0,0.062500,0.187500,ns
29,Immune,batch_rare_homogeneity,Leiden (scVI),300,5,0.818150,0.728552,0.158121,5.0,0.031250,0.093750,ns
30,Immune,batch_rare_homogeneity,scProto Stage 2 (scVI),293,5,0.866788,0.859015,0.064490,NaN,NaN,NaN,NaN
31,Immune,batch_rare_homogeneity,scProto (scPoli Stage 1),294,5,0.855792,0.827192,0.101982,4.0,0.062500,0.187500,ns
32,Immune,batch_rare_cross_batch_homog,SEACells (scVI),300,5,0.338899,0.335215,0.193640,2.0,0.781250,1.000000,ns
33,Immune,batch_rare_cross_batch_homog,Leiden (scVI),300,5,0.499560,0.406865,0.207756,2.0,0.843750,1.000000,ns
34,Immune,batch_rare_cross_batch_homog,scProto Stage 2 (scVI),293,5,0.366832,0.302577,0.195402,NaN,NaN,NaN,NaN
35,Immune,batch_rare_cross_batch_homog,scProto (scPoli Stage 1),294,5,0.406766,0.349204,0.197947,3.0,0.687500,1.000000,ns

## Table 1 metrics for every arm and dataset

Purity / batch entropy / modularity / coverage, read from each run's own `metrics.json`. All arms are rescored against the same canonical graph.

In [33]:
df_task1 = collect_task1_table(DATASETS_TO_RUN, MODEL_KEYWORDS, dataset_display_names)
display(df_task1.pivot(index='method', columns='dataset',
                       values=['modularity', 'purity', 'batch_entropy', 'coverage']))
df_task1

                         modularity                        purity            \
dataset                      Immune      Lung  Pancreas    Immune      Lung
method
Leiden (scVI)              0.364379  0.522427  0.379159  0.867663  0.850151
SEACells (scVI)            0.240445  0.326896  0.295673  0.894180  0.860817
scProto (scPoli Stage 1)   0.628591  0.664444  0.601234  0.901103  0.858799
scProto Stage 2 (scVI)     0.618066  0.650069  0.615681  0.892998  0.872173

                                   batch_entropy                     coverage  \
dataset                   Pancreas        Immune      Lung  Pancreas   Immune
method
Leiden (scVI)             0.964776      0.806087  1.185238  0.769753   1.0000
SEACells (scVI)           0.954860      0.526690  1.110295  0.810051   1.0000
scProto (scPoli Stage 1)  0.912529      0.229215  0.537913  0.399301   0.9375
scProto Stage 2 (scVI)    0.913605      0.223084  0.558935  0.300580   0.9375


dataset                       Lung  Pancreas
method
Leiden (scVI)             1.000000  0.785714
SEACells (scVI)           1.000000  1.000000
scProto (scPoli Stage 1)  0.882353  0.928571
scProto Stage 2 (scVI)    1.000000  1.000000

,dataset,method,purity,batch_entropy,modularity,modularity_std,coverage,K
0,Pancreas,SEACells (scVI),0.954860,0.810051,0.295673,0.077863,1.000000,220.0
1,Pancreas,Leiden (scVI),0.964776,0.769753,0.379159,0.121646,0.785714,220.0
2,Pancreas,scProto Stage 2 (scVI),0.913605,0.300580,0.615681,0.081900,1.000000,220.0
3,Pancreas,scProto (scPoli Stage 1),0.912529,0.399301,0.601234,0.088443,0.928571,NaN
4,Lung,SEACells (scVI),0.860817,1.110295,0.326896,0.052737,1.000000,300.0
5,Lung,Leiden (scVI),0.850151,1.185238,0.522427,0.077166,1.000000,300.0
6,Lung,scProto Stage 2 (scVI),0.872173,0.558935,0.650069,0.039418,1.000000,300.0
7,Lung,scProto (scPoli Stage 1),0.858799,0.537913,0.664444,0.023622,0.882353,NaN
8,Immune,SEACells (scVI),0.894180,0.526690,0.240445,0.129763,1.000000,300.0
9,Immune,Leiden (scVI),0.867663,0.806087,0.364379,0.182858,1.000000,300.0
10,Immune,scProto Stage 2 (scVI),0.892998,0.223084,0.618066,0.059321,0.937500,300.0
11,Immune,scProto (scPoli Stage 1),0.901103,0.229215,0.628591,0.057752,0.937500,NaN

## Did the latent itself change?

Clustering-free diagnostic: for every locally-rare-type cell, the fraction of its affinity mass that stays within its own cell type, per batch — computed on the scVI latent before and after Stage 2.

In [34]:
for ds, res in RESULTS.items():
    if res is None:
        continue
    print(f"=== {dataset_display_names.get(ds, ds)} ===")
    display(res['embedding_purity'])

=== Pancreas ===

     embedding  dim  n_batches    mean     std  n_wins  p_vs_ref
0    X_scvidef   10          8  0.5148  0.1696     2.0    0.9453
1  X_scviproto   10          8  0.4727  0.1473     NaN       NaN

=== Lung ===

     embedding  dim  n_batches    mean     std  n_wins  p_vs_ref
0    X_scvidef   10         15  0.6554  0.1467     4.0    0.9681
1  X_scviproto   10         15  0.5944  0.2134     NaN       NaN

=== Immune ===

     embedding  dim  n_batches    mean     std  n_wins  p_vs_ref
0    X_scvidef   10          5  0.8684  0.0472     2.0    0.7812
1  X_scviproto   10          5  0.8634  0.0473     NaN       NaN

## Save a compact summary

In [35]:
summary = {
    'datasets': DATASETS_TO_RUN,
    'scvi': {'n_latent': SCVI_N_LATENT, 'gene_likelihood': SCVI_GENE_LIKELIHOOD,
             'epochs': SCVI_EPOCHS},
    'stage2': {'max_epochs': STAGE2_MAX_EPOCHS, 'eval_freq': EVAL_FREQ, 'patience': PATIENCE},
    'arms': MODEL_KEYWORDS,
    'per_dataset': {
        ds: {
            'K': int(DATASETS[ds]['num_prototypes']),
            'run_dir': res['run_dir'],
            'stage2_metrics': res['stage2_metrics'],
            'embedding_rare_affinity_purity': res['embedding_purity'].to_dict(orient='records'),
        }
        for ds, res in RESULTS.items() if res is not None
    },
    'task1': df_task1.to_dict(orient='records'),
    'rare_significance': df_sig.to_dict(orient='records'),
}

out_dir = '/content/drive/MyDrive/codes/interpretable-prototype/neurips_manuscript/rebuttle/experiment-results'
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'scvi_stage2_summary.json')
with open(out_path, 'w') as f:
    json.dump(summary, f, indent=2, default=str)
print("saved", out_path)

saved /content/drive/MyDrive/codes/interpretable-prototype/neurips_manuscript/rebuttle/experiment-results/scvi_stage2_summary.json